### ISSUE TITLE
The BASELINE_GROUP for Pharo is TravisCI, not default

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#10]
The BASELINE_GROUP for Pharo should be default: https://github.com/hpi-swa/smalltalkCI/blob/master/pharo/run.sh#L46

however since it is already set in the master script it won't be changed https://github.com/hpi-swa/smalltalkCI/blob/master/run.sh#L87

So maybe change the README.md to reflect it, because it is confusing — the values in the readme look like default values.

**Comment by fniephaus** [comment]
Hi @peteruhnak,
Thanks for filing the issue.

I have changed the default for `BASELINE_GROUP` for Pharo to `default`.

Best,
Fabio

**Comment by peteruhnak** [comment]
Thanks!
