### ISSUE TITLE
Is it correct to skip clean if only _builds directory is present?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#101]
I ran into an error while trying to clean the _builds directory (`--clean` option), so only the _cache directory was deleted and then when I ran the --clean (after fixing the error), i got `Nothing to clean up.` message and that's because the [clean test](https://github.com/hpi-swa/smalltalkCI/blob/master/run.sh#L212-L213) is:

```
  if is_dir "${SMALLTALK_CI_CACHE}" || \
      ! is_dir "${SMALLTALK_CI_BUILD_BASE}"; then
```
which reads as `_cache` exists or `_builds` does not exist ... which I think is wrong ... unless it is there on purpose...

**Comment by fniephaus** [comment]
Whoops, I guess this should be:

```bash
  if is_dir "${SMALLTALK_CI_CACHE}" || \
      is_dir "${SMALLTALK_CI_BUILD_BASE}"; then
```

Thanks!

**Comment by dalehenrich** [comment]
I tried that fix in my image and it still seemed to not want to delete 
the _builds directory  --- I think the script silently exited without an 
explanation ... I was guessing that the the `rm -rf` silently failed to 
process the second argument -- so you might want to test it out ... BTW 
the failure seemed to come when the _cache directory was already gone ...

**Comment by fniephaus** [comment]
Thanks. I will need to look into this tomorrow.

**Comment by dalehenrich** [comment]
More nitpicking (that can be ignored) but if you do use `--clean`` without any other args, 1) you are prompted to `Continue` and then if you do continue you get an error:

```
foos:smalltalkCI>./run.sh --clean
cache at '/export/foos1/users/dhenrich/git/smalltalkCI/_cache'.
builds at '/export/foos1/users/dhenrich/git/smalltalkCI/_builds'.
Are you sure you want to clear builds and cache? (y/N): y
Nothing to clean up.
Continue with build progress? (y/N): y
Smalltalk image is not defined.
foos:smalltalkCI>
```

Like I said this is a nitpick and can be ignored...

**Comment by fniephaus** [comment]
I have notice this as well, but thought this might be expected. If you want to continue, you must have provided Smalltalk image and STON. Maybe we should just quit the script after `--clean` is done?

**Comment by dalehenrich** [comment]
Well, it depends upon whether or not additional args have been supplied ... if no additional args exit, otherwise prompt for continue .... or leave the behavior as is and wait to see if anyone else notices/complains :)
