### ISSUE TITLE
cannot interrupt clean prompt? ... if this is standard bash behavior it's acceptable

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#102]
Here's what happens when I hit `CTL-c` at the prompt during clean:

```
foos:smalltalkCI>./run.sh --clean
builds at '/export/foos1/users/dhenrich/git/smalltalkCI/_cache'.
cache at '/export/foos1/users/dhenrich/git/smalltalkCI/_builds'.
Are you sure you want to clear builds and cache? (y/N): ^CsmalltalkCI has been interrupted. Exiting...

Continue with build progress? (y/N): ^CsmalltalkCI has been interrupted. Exiting...
^CsmalltalkCI has been interrupted. Exiting...
^CsmalltalkCI has been interrupted. Exiting...

foos:smalltalkCI>
```

I had to hit a return after `CTL-c` and even then the `CTL-c` did not appear to work ...

Also note that the directories are reversed in the `--clean` prompt:

```
builds at '/export/foos1/users/dhenrich/git/smalltalkCI/_cache'.
cache at '/export/foos1/users/dhenrich/git/smalltalkCI/_builds'.
```

should be:

```
cache at '/export/foos1/users/dhenrich/git/smalltalkCI/_cache'.
builds at '/export/foos1/users/dhenrich/git/smalltalkCI/_builds'.
```
 ... I've got a fix for this in my upcoming PR ...

**Comment by dalehenrich** [comment]
I've fixed the part of this bug that I can fix .. the CTL-C is beyond my bash chops to address, so it's time to close or assign to someone else :)

**Comment by fniephaus** [comment]
Can't you (re)assign issues as a contributor?

**Comment by dalehenrich** [comment]
That must be a new feature as well ... the last time I checked (weeks ago) I couldn't change the assignee, nor could I close issues that I did not create ... and it appears that I can do that now as well ...

**Comment by fniephaus** [comment]
That was why I added you as a contributor in the first place ;) just trying to make our lives as easy as possible

**Comment by dalehenrich** [comment]
Haha, that's great .... now that I know I have different super powers I will try to look for new opportunities to use them :)

BTW, I am thinking that I don't want to overuse the privilege of being able to create a merge branches on the hpi-swa repository ... If I do work in my fork, you don't have to ignore it ... however, if I do work on a branch in hpi-swa, then you can easily contribute changes or test out intermediate results without too much trouble ... so what are your guidelines?
