### ISSUE TITLE
[Update] Push Permissions

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#104]
GitHub has [improved protected branches](https://github.com/blog/2137-protected-branches-improvements), so now @hpi-swa/smalltalkci-contributors can push to all smalltalkCI branches except `master`.
This way @dalehenrich and @estebanlm can now add their feature branches here without having to fork.

Please close once acknowledged :smiley:

**Comment by estebanlm** [comment]
ok :)

**Comment by dalehenrich** [comment]
ok

**Comment by dalehenrich** [comment]
Just a note ... I created an issue_105 branch on hpi-swa and pushed my first set of changes and [one of the builds failed](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/119937794) on osx and when that (randomly) happens I typically restart the job ... al the other builds passed, but apparently I don't have the appropriate access rights on travis to restart the job ... this makes it a bit inconvenient to do development in the hpi-swa repository ... just a nit-pick

**Comment by fniephaus** [comment]
I've restarted the build for you. But yes, this is annoying if builds are flaky and I'd understand why you'd prefer to work on your fork. I will file a bug with Travis I guess...

**Comment by fniephaus** [comment]
> ... users with write/push permissions over a repository should also be able to cancel/restart a given build in that repository.

@dalehenrich: I just synced the repository on Travis, could you try again please?

**Comment by dalehenrich** [comment]
@fniephaus excellent ... just restarted a failed build: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/120625724 ... it will fail again :), but I **was** able to restart THX

**Comment by fniephaus** [comment]
Sweet!
