### ISSUE TITLE
The command "$SMALLTALK_CI_HOME/run.sh" exited with 1.

### ISSUE THREAD

**Issue by SergeStinckwich** [hpi-swa/smalltalkCI#107]
Apparently SmalltalkCI is not working anymore on Mac OS X build:
https://travis-ci.org/UMMISCO/kendrick/jobs/118981955

**Comment by dalehenrich** [comment]
Pretty strange, here's the [bash that is failing](https://github.com/hpi-swa/smalltalkCI/blob/master/run.sh#L34-L37):

```
if [[ ! -f "${SCRIPT_PATH}/run.sh" ]]; then
    echo "smalltalkCI could not be initialized." 1>&2
    exit 1
  fi
```

Not a lot of moving parts at this point.

**Comment by dalehenrich** [comment]
... and last commit was three days ago: https://github.com/hpi-swa/smalltalkCI/commit/b28fec62801910bf3dadeea0d5385b2ee1a499ba

**Comment by SergeStinckwich** [comment]
All my mac os x builds return this error now.

**Comment by dalehenrich** [comment]
this is likely to be either a travis or github problem

**Comment by fniephaus** [comment]
Unfortunately, it is a problem with smalltalkCI that I recently introduced. I know how to fix it and it looks like the hotfix already works. Please restart your builds, @SergeStinckwich :)

**Comment by SergeStinckwich** [comment]
Great ! Thank you Fabio.

**Comment by fniephaus** [comment]
Thanks for letting me know, @SergeStinckwich!
