### ISSUE TITLE
`./run.sh --headfull -s "Pharo-5.0" ./.smalltalk.ston` doesn't quite work as (I) expected

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#109]
I followed the instructions *To reproduce the failed build locally* from [a failed build](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/120459414#L747-L750), and the build failed locally:

```
     Executed 136 tests, with 2 failures and 0 errors in 1.202 seconds.

STON.Tests.STONWriterTests
  ✗ testDoubleQuotedString (0.017 seconds)
  ✗ testString (0.012 seconds)
```

However, the `--headfull` image exited without giving me a chance to debug the problem and the image that was saved in the `_cache` was just a standard Pharo-5.0 image file ... 

So the *to reproduce* message is either incomplete (need instructions for loading the projects and running the tests) or the image needs to not exit after running the tests or the image needs to be saved with all of the trimmings before exiting...

**Comment by dalehenrich** [comment]
Same behavior with `Pharo-3.0`.

It looks like the [eval --save](https://github.com/hpi-swa/smalltalkCI/blob/master/pharo/run.sh#L183-L190) command line:

```
    "${SMALLTALK_CI_VM}" "${SMALLTALK_CI_IMAGE}" eval --save "
      [ Metacello new
          baseline: 'SmalltalkCI';
          repository: 'filetree://${SMALLTALK_CI_HOME}/repository';
          onConflict: [:ex | ex pass];
          load ] on: Warning do: [:w | w resume ].
      (Smalltalk at: #SmalltalkCI) runCIFor: '${project_home}/${config_ston}'
    " || status=$?
```

 is not quite working as expected.

**Comment by dalehenrich** [comment]
Finally found the magic: `_cache/vms/Pharo-5.0/pharo-ui _builds/2016_04_03_11_18_14/TravisCI.image &` ... so it's not that `eval --save` wasn't functioning correctly...

Perhaps the image should not exit when `--headfull` is specified?

**Comment by dalehenrich** [comment]
Also as an aside, it can be a bit of a challenge to figure out how to manually duplicate the set of tests that are run by SmalltalkCI -- if you are interested in re-running the full set of tests while you are sitting in the `--headfull` image.  The new (#105) #testCIFor: helps:

```Smalltalk
SmalltalkCI testCIFor: '/Users/dhenrich/GsDevKit_home/shared/repos/smalltalkCI/.smalltalk.ston'
```

but you still have to know the full path of the `.smalltalk.ston` file and you have to manually look at the xml output to see which tests pass ---- perhaps a #debugTestCIFor: method that brings up a debugger on a test failure and perhaps prints the test results otherwise ...

At the end of the day, I don't quite think that telling the developer to `./run.sh --headfull -s "Pharo-5.0" ./.smalltalk.ston` is quite the complete store...

**Comment by dalehenrich** [comment]
To provide just a tad more info, if you look at the [travis results for this build](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/120459414), you'll see that there are a bunch of `STON` tests being run (and failing two tests), so I was interested in excluding the `STON-Tests` category, since presumably the STON tests are failing in a standard Pharo-5.0 (need to double check that SmalltalkCI isn't causing the failure) --- thus the interest in debugging my .smalltalk.ston changes (excluding the category `STON-Tests`) and not necessarily the tests themselves ...

**Comment by dalehenrich** [comment]
... finally the STON test failures do indeed look like STON test issues and have nothing to do with SmalltalkCI

**Comment by dalehenrich** [comment]
... except that there is also a custom `STON-Tests` package that is being loaded by SmalltalkCI and those tests are actually incorrect for the official version of STON --- which is why the tests are failing ... I discovered this because the STON-Tests failed in the SmalltalkCI image but were passing in the base Pharo-5.0 image ... further illustration of the problems introduced by unconditionally including custom packages instead of using the `official version` ...

**Comment by dalehenrich** [comment]
These last three commits are really at Issue #108, not #109...

**Comment by dalehenrich** [comment]
Despite the issues, it was very satisfying to be able to reproduce the travis environment locally to the extent that I could basically address all of the travis issues (including changes to the `smalltalk.ston` spec) ... 

As a suggestion, when running `--headfull` it may make sense to dump out information about the `_build` directory and the name of the image being used --- perhaps the an `echo` of the command used to launch the image, so that the user can restart the image easily ...

**Comment by fniephaus** [comment]
First, files in `_cache` are not being modified after a download. Otherwise the cache would be inconsistent. Instead, the corresponding image for a build is copied into a corresponding build folder within `_builds` and then the image is being modified.
I'm already working on a fix for the `--headfull` mode for Pharo builds...

**Comment by dalehenrich** [comment]
The image that I was looking for wasn't even in the _cache directory ... when you are running the command locally, it is non-obvious where to look for things ... like I said I think we need a bit more documentation about using ./run.sh locally ... having the image halt and not exit will reduce the priority of better docs :)
