### ISSUE TITLE
missing libssl library

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#11]
I've encountered a problem with ssl and Pharo

My BaselineOf pulls another package from github via 'github://' protocol (which internally uses SSL),
but it fails on missing library.

```
Loading baseline of BaselineOfBormModel...ioLoadModule(/home/travis/smalltalkCI-master/_cache/vms/Pharo-5.0/pharo-vm/libSqueakSSL.so):
  libssl.so.1.0.0: cannot open shared object file: No such file or directory
...RETRY->BaselineOfDynaCASEModel
...RETRY->BaselineOfDynaCASEModel==== Startup Error: ZdcPluginMissing: SSL/TLS plugin initailization failed (VM plugin missing ? OS libraries missing ?)
```

The solution was explicitly adding the following to my `.travis.yml`

```yaml
addons:
    apt:
        packages:
            - libssl1.0.0:i386
```

Maybe it should be part the default container (preinstalled), or alternatively at least having a mention in the README (since other people are likely to eventually encounter this problem too)

**Comment by fniephaus** [comment]
Sorry for the inconvenience.
Will have a chat with the others about adding `libssl1.0.0:i386` to the default container, but it may take a while until available on Travis.
In the meantime, I will add a note to the `README`.

Also, have you tried to run this on OS X (just add `os: osx` to your `.travis.yml`)?

**Comment by peteruhnak** [comment]
I could try that, but since I personally use linux I feel more
confortable with that.

On 11/25, Fabio Niephaus wrote:
> Sorry for the inconvenience.
> Will have a chat with the others about adding `libssl1.0.0:i386` to the default container, but it may take a while until available on Travis.
> In the meantime, I will add a note to the `README`.
> 
> Also, have you tried to run this on OS X (just add `os: osx` to your `.travis.yml`)?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hpi-swa/smalltalkCI/issues/11#issuecomment-159755836

-- 
Peter

**Comment by fniephaus** [comment]
No worries!
The VM that smalltalkCI uses for Squeak builds uses a different SqueakSSL plugin [1] which is why it doesn't need libssl. But it seems that there's something wrong with that version, too.

[1] https://github.com/itsmeront/squeakssl/releases/tag/v0.2.0b

**Comment by Nef10** [comment]
Included in PR travis-ci/travis-build#546

**Comment by estebanlm** [comment]
so not needed anymore?

**Comment by fniephaus** [comment]
Still needed since Travis hasn't merged PR 546 yet.
It'll also take some time to reach production, but in a couple of days it shouldn't be needed anymore.
Will keep you posted.

**Comment by fniephaus** [comment]
@peteruhnak & @estebanlm: can one of you confirm that this is working now without the following:
```
addons:
    apt:
        packages:
            - libssl1.0.0:i386
```

**Comment by peteruhnak** [comment]
I can confirm that libssl is now installed automatically

however my build is failing for some other reason, so I can't confirm that it all goes will

**Comment by peteruhnak** [comment]
ok my build is running again, so I can confirm that it's working correctly, thanks!

**Comment by fniephaus** [comment]
Perfect, sorry again for the inconvenience.
