### ISSUE TITLE
Error running: ` ./run.sh --headfull -s "Squeak-5.0" ./.smalltalk.ston` on osx

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#110]
I was just testing my fixes for #109 with Squeak for completeness and hit the following (running on OSX):

```
nehalem:smalltalkCI $ ./run.sh --headfull -s "Squeak-5.0" ./.smalltalk.ston
Preparing folders...
Starting Squeak build...
Downloading Squeak-5.0 testing image...
 > Time to run: 18.000s 
Extracting image...
Downloading virtual machine...
 > Time to run: 5.000s 
Extracting virtual machine...
Cog VM Information
5.0 5.0.3427 Mac OS X built on Aug 22 2015 04:44:22 UTC Compiler: 4.2.1 (Apple Inc. build 5666) (dot 3) [Production Spur VM]
CoInterpreter VMMaker.oscog-eem.1441 uuid: c41d605b-7d2e-4ecc-95e1-b295119106a7 Aug 22 2015
StackToRegisterMappingCogit VMMaker.oscog-eem.1436 uuid: 9d2442c4-2066-4ffd-a215-e7e2b6cb8eed Aug 22 2015
VM: r3427 http://www.squeakvm.org/svn/squeak/branches/Cog Date: 2015-08-21 20:39:38 -0700
Plugins: r3415 http://squeakvm.org/svn/squeak/trunk/platforms/Cross/plugins

Loading and testing project...
/Users/dhenrich/GsDevKit_home/shared/repos/smalltalkCI/squeak/run.sh: line 223: cog_vm_flags[@]: unbound variable
nehalem:smalltalkCI $ 
```

**Comment by fniephaus** [comment]
The "unbound variable" error occurs because of `set -o nounset`. I will have a look at it now...

**Comment by dalehenrich** [comment]
okay ... not a priority, since I'm past this point ... back to running things on travis :) ... THX!

**Comment by fniephaus** [comment]
Current [`master`](https://github.com/hpi-swa/smalltalkCI/commit/4baae337e6dceae1d5f65ca6b6ef1676288c5c54) gives me:
![image](https://cloud.githubusercontent.com/assets/2368856/14234547/d7becf96-f9e5-11e5-9030-6fc7bf201e4e.png)

**Comment by dalehenrich** [comment]
I'm not sure what you are telling me here ... I thought this was a Squeak-50/osx problem, not a `Pharo-stable` thing?

**Comment by fniephaus** [comment]
Whoops, sometimes I should do more copy & paste. Now I see the error, I'll fix it tomorrow!

**Comment by dalehenrich** [comment]
Haha ... no problem ... the build was green on travis, so this appears to only be a local problem :)
