### ISSUE TITLE
#platform attribute for #testing specs

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#111]
It is likely that we will eventually need platform-specific #testing specs.

For Issue #108, I almost needed to have [different `exclusion` specs](https://github.com/dalehenrich/smalltalkCI/commit/2ec4808fb9ae5baa80cbf1a2652211ad1c0ace22#diff-bbe7f99f0fe2368a194030089288318fL10) for Pharo and Squeak ... in that case, the `STON-Tests` category was required for Squeak and _almost needed to be excluded_ for Pharo ... at the end of the day platform-specific #testing specs weren't needed, but it doesn't take a big stretch to imagine a use case where they could be needed ...

Currently, though, I do not have an explicit use case, so we might just wait until one pops up.

**Comment by fniephaus** [comment]
I guess you are right, it's just a matter of time until someone needs this.
How about we introduce a convention for all slots (`#loading`, `#testing`, ...) of a `SmalltalkCISpec`:
If a slot holds an object (e.g. Dictionary), it is valid for/compatible to every platform, if it is a list, it can contain platform-specific elements.

So for `#testing`, one could use:
```javascript
  #testing : {
    #exclude : {
      #classes : [ #SCIExcludedTests ]
    }
  }
```

or

```javascript
  #testing : [ {
    #exclude : {
      #classes : [ #SCIExcludedTests ]
    },
    #platforms : [ #squeak, #pharo, #gemstone ]
  } ]
```
and they would be equivalent.

**Comment by dalehenrich** [comment]
That seems like a nifty solution, especially since it remains backwards compatible

**Comment by fniephaus** [comment]
A more established approach to this is to use multiple ston files, which provides more flexibility in general. Let's not overcomplicate the smalltalk.ston spec.
