### ISSUE TITLE
Poor error message for Pharo-5.0 when test load error encountered

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#115]
While seeing if I can use smalltalkCI with Metacello, I created an invalid `.smalltalk.ston` file:

```ston
SmalltalkCISpec {
  #specName : 'Metacello',
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'Metacello',
      #onWarningLog;
      #load : [ 'Tests' ],
      #directory : 'repository'
    }
  ]
}
```

[Pharo-5.0 exits with an error status](https://travis-ci.org/dalehenrich/metacello-work/jobs/120732371), but fails to give a useful error message.

GemStone [produces a proper error message](https://travis-ci.org/dalehenrich/metacello-work/jobs/120732373#L1236): `GemStone Server error: a STONReaderError occurred (error 2710), : expected`.

Squeak [appears to hang](https://travis-ci.org/dalehenrich/metacello-work/jobs/120732372) ... this may be a side effect of trying to load the latest version of Metacello, but [a run with builderCI](https://travis-ci.org/dalehenrich/metacello-work/builds/120720395) loads and passes tests ... I'll make another run with the STON error fixed to find out ...

**Comment by dalehenrich** [comment]
With proper `.smalltalk.ston` file ... the [builds are green](https://travis-ci.org/dalehenrich/metacello-work/builds/120735332)

**Comment by fniephaus** [comment]
smalltalkCI doesn't handle invalid STON files well in general at the moment.
This definitely needs some work. Maybe I have some time tomorrow...

**Comment by dalehenrich** [comment]
Again, this is not a high priority, I'm submitting issues as I hit them so the information isn't lost ...

**Comment by fniephaus** [comment]
It might not be high priority for *us*, but it would certainly be a good idea to improve this this week, because we have students working with smalltalkCI as soon as next week. I'm on it...

**Comment by fniephaus** [comment]
There's still a problem with `Pharo-5.0` not showing the error at the moment, but this is apparently a bug.
Postponing the issue...

**Comment by fniephaus** [comment]
Like I mentioned before, this seems to be a Pharo-5.0 problem at the moment.
I was able to debug #134 by running smalltalkCI locally and then inspecting `PharoDebug.log`.

**Comment by dalehenrich** [comment]
Agreed that it is a Pharo5.0 problem .. but having to run a local test to debug a travis error, kind of defeats the purpose of running travis --- the fact that a workaround exists means that this isn't a high priority though ---

**Comment by estebanlm** [comment]
mmm... I will take a look

**Comment by dalehenrich** [comment]
@estebanlm I believe that the core issue is that the error stack is being dumped to the PharoDebug.log instead of stderr ... at least that's what I observed today when I needed to figure out what was causing an [error on travis](https://travis-ci.org/dalehenrich/Tugrik/builds/125293654#L1031) ... the same error occurred locally, but I was able to look at the PharoDebug.log and see the stack ...

**Comment by fniephaus** [comment]
@estebanlm do you happen to have an update on this?

**Comment by estebanlm** [comment]
ouch, I forget it… I will try it today :)

**Comment by estebanlm** [comment]
so, finally looking at this... it looks like a super weird side-effect from our integration process (how we construct the images)... in any case, this gives me the opportunity to fix a problem we have since a lot of time...

**Comment by fniephaus** [comment]
Thanks for looking into this, @estebanlm

**Comment by estebanlm** [comment]
ok, now it should be working, both for Pharo 5.0 and Pharo 6.0... @dalehenrich could you confirm this (or you @fniephaus)?

**Comment by fniephaus** [comment]
Yep! Seems to be working just fine. Awesome!

**Comment by dalehenrich** [comment]
Cool! Thanks, @estebanlm
