### ISSUE TITLE
Incomplete test results for Squeak

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#116]
Compare the end of the test results display for [Pharo-5.0](https://travis-ci.org/dalehenrich/metacello-work/jobs/120744204) and [Squeak-4.5](https://travis-ci.org/dalehenrich/metacello-work/jobs/120744205). The Squeak log is missing the all important error summary ... thre was one error during the test and I am not able to tell which test had the error with incomplete results

**Comment by dalehenrich** [comment]
[Gemstone output was truncated as well](https://travis-ci.org/dalehenrich/metacello-work/jobs/120744206) ... I do know that Metacello dumps a bunch of output to the log and for builderCI, I had split the tests in half to minimize run times ... so I'm going to guess that the log exceeded the travis maximum log length  and close this bug ...

**Comment by dalehenrich** [comment]
Yep [the raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/120744205/log.txt) has the missing information for the Squeak error --- a (random) network download error:

```
[1mMetacello.TestsMCA.MetacelloGithubIssue175TestCase[0m
[0Ktravis_fold:start:summary_error1
  [31mâœ— testIssue175[0m (0.094 seconds)
[37;1mError: file is too short[0m
[37mZipArchive class(Object)>>error:
ZipArchive class>>findEndOfCentralDirectoryFrom:
ZipArchive>>readFrom:
[] in MetacelloSqueakPlatform>>downloadZipArchive:to:
[] in MultiByteFileStream class(FileStream class)>>detectFile:do:
BlockClosure>>ensure:
MultiByteFileStream class(FileStream class)>>detectFile:do:
MultiByteFileStream class(FileStream class)>>readOnlyFileNamed:do:
UnixFileDirectory(FileDirectory)>>readOnlyFileNamed:do:
MetacelloSqueakPlatform>>downloadZipArchive:to:
MCGitHubRepository class(MCGitBasedNetworkRepository class)>>projectDirectoryFrom:version:
MCGitHubRepository(MCGitBasedNetworkRepository)>>directory
MCGitHubRepository(MCFileTreeRepository)>>allFileNames
[] in MetacelloGithubIssue175TestCase>>testIssue175
BlockClosure>>ensure:
MetacelloGithubIssue175TestCase>>testIssue175
MetacelloGithubIssue175TestCase(TestCase)>>performTest
[0m
[0Ktravis_fold:end:summary_error1
[0Ktravis_fold:end:result_summary
```

**Comment by fniephaus** [comment]
Maybe we should do something about this? AFAIK the limit is currently 10,000 lines and Metacello is quite verbose. Any ideas?

**Comment by fniephaus** [comment]
Also there are [924](https://travis-ci.org/dalehenrich/metacello-work/jobs/120744206#L9624) lines like [this](https://travis-ci.org/dalehenrich/metacello-work/jobs/120744206#L7665) that we could save if we instead print a single char without a line break.

**Comment by dalehenrich** [comment]
right, but then you risk having travis time out because of lack of output ... remember the background thread in builderCI? ... we could put a `.` out instead of test status ... what's the longest line limit for travis?

**Comment by dalehenrich** [comment]
I thought about that when I put the code in for GemStone, but I also though that meaningful output about progress would be worthwhile ... ah well , `.` it is :)

**Comment by dalehenrich** [comment]
I've gone back to usng builderCI for the near term with `metacello-work` ... my stack is getting too deep as it is ... when I get back to it I will probably go with splitting the tests up into batches (which is what I did for builderCI --- I wanted to see what would happen with smalltalkCI -- 1000 tests are a handful and I found that out ...

**Comment by fniephaus** [comment]
I actually opted for "test start" as `-` and "test end" as `>`. This way it looks like `->->->->->->`

**Comment by dalehenrich** [comment]
@fniephaus - now I am [seeing truncation in test results](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/121335708#L3075-L3098) that cannot be attributed to log overflow .. 

This *is* happening when I am running 4 tests (2 passes and 2 expected failures; one server and one client) ... currently it is on the issue_105 branch and I've just pushed it to hpi-swa if you want to fiddle ... the raw log seems complete

**Comment by dalehenrich** [comment]
the GemStone part to this will be available when fix for #105 is merged ...

**Comment by fniephaus** [comment]
I know why the results are being truncated. For the folding, I am using an undocumented Travis API which requires that all identifier for folds are unique. You are the first to create a scenario in which this can happen. But I'm working on a fix...on your branch!

**Comment by fniephaus** [comment]
@dalehenrich your issue is fixed now on `issue_105`:
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/121398710#L2216

**Comment by dalehenrich** [comment]
Excellent! I really appreciate your effort! Thx

**Comment by fniephaus** [comment]
I guess this can be closed now...
