### ISSUE TITLE
GemStone builds broken because of seaside.gemstone.com?

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#117]
See: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/120918262#L1339

**Comment by dalehenrich** [comment]
This is not a seaside.gemstone.com issue ... broken downloads occur occasionally ... restart the job and it should finish

**Comment by fniephaus** [comment]
I opened the issue because of this:
> Could not resolve: OB-Tools [OB-Tools.v3-DaleHenrichs.137] in cache http://seaside.gemstone.com/ss/GemStone

That's why I thought it was related...
Please close the issue if there's nothing we need to/can do

**Comment by dalehenrich** [comment]
The "what can you do" is to restart the build. Did the re-start work? 

Many of the older configs have a dual repository registration where both gemstone.com and gemtalksystems.com are being referenced and the attempt to load from the alternate repo is tried after failing several times, so this could be such a case .. if you note that earlier in the log ConfigurationOfGsMisc also had the exactly same signature, but did not result  in a failure...

Now that seaside.gemstone.com is back on-line I have no chance to reproduce the problem under the debugger ... I know that there are references to gemstone.com in old configs, but there are too many to edit (especially with these transitory problems) and like I said in most (if not all cases) there is a dual repository definition ...

If and when gemstone.com goes off-line permanently I'll fix any configurations that need patching:)
