### ISSUE TITLE
Speed up GemStone builds?

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#119]
[This build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/121132808) ran for 17 minutes, and the slow operations were:

- *Installing server...* with 75s
- *Creating stone...* with 430s
- *Installing server...* with 59s
- *Creating stone...* with 391s

That's a total of 955s or ~16 minutes.
Does smalltalkCI have to install a server and create a stone twice or can we reuse both from the run before? That would save ~6 minutes.
It'd be great if we could further cut down on build time for GemStone builds on OS X.

**Comment by dalehenrich** [comment]
Perhaps skipping the double build entirely on OSX is an even better 
solution? I don't think that we're likely to find any osx specific 
problems...

The osx machines are not only slow on travis (builds don't take that 
long on my laptop), but they also appear to be over-committed and it 
takes forever for the osx builds to even start ...

Dale

**Comment by fniephaus** [comment]
That's a good idea! Let me take care of that :)

**Comment by dalehenrich** [comment]
Cool, THX!

**Comment by fniephaus** [comment]
For Squeak, smalltalkCI uses prepared images that basically are stock images with metacello-work preinstalled (because that takes quite some time to load).
[It looks like something is being loaded during *Creating stone...*](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/121196048#L750) and I'm guessing that this makes up for most of the build time. Would it be useful and possible to use prepared images here as well to speed this up? Travis caching does not work for OS X for open-source projects (yet?), but we could just do this ourselves (host prepare image, download, go!).

What do you think, @dalehenrich?

**Comment by fniephaus** [comment]
Using shallow cloning, I was able to cut *Installing server...* from 75s down to [42s](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/121297844#L275).

**Comment by dalehenrich** [comment]
I think that dependency caching does the job perfectly well ... okay except for OSX and I don't really want to be in the business of maintaining prepared images ... let's revisit this in a couple of weeks as I am really swamped right now and am tired of debating this issue :)

**Comment by fniephaus** [comment]
Sure, no worries! We've already cut the build time in half on OS X, so it's not as bad anymore.
Sorry for annoying you with this so much ;)

**Comment by dalehenrich** [comment]
Haha, usually a healthy debate is worthwhile, but I am pushing things on the stack while I get the smalltalkCI client testing working and adding additional tasks to my stack is the last thing I want to see :)

**Comment by dalehenrich** [comment]
I think this one is covered
