### ISSUE TITLE
Improve caching

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#127]
By providing shared helper functions and by making the cache more consistent.

This would especially be useful for builds that require more than one image (e.g. GemStone system/client builds).

**Comment by fniephaus** [comment]
![image](https://cloud.githubusercontent.com/assets/2368856/14555902/8f57feee-02f5-11e6-8ab5-75a986b3c11e.png)
@dalehenrich this is the `_cache` directory after a `GemStone-3.3.0` build. Are the `gsDevKitCommandLine.(image|changes)` files are generated from `Pharo-3.0.(image|changes)`?
I assume the `Pharo-3.0.(image|changes)` files are untouched?

I think it would be good to have two sorts of caches: a local cache that only holds downloaded/untouched files and a cache directory that can be cached by Travis. If a job wants to cache something, it puts the content to that Travis cache directory and reuses it in the next build.

**Comment by dalehenrich** [comment]
Can we defer this convesation ... I do really want to improve the caching, but I really need to spend several days on other things .... Let's take this up next week some time?

**Comment by fniephaus** [comment]
Whoohoo: https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

**Comment by dalehenrich** [comment]
Cool ...

**Comment by fniephaus** [comment]
Closing this for now.
