### ISSUE TITLE
Large log files and `cat`ting the xml.log ....

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#131]
Is it necessary to cat the xml.log during a run?

I've got a seaside build that is running 3800+ tests and the travis output is truncated and I suspect that the cat of the xml.log is not contributed that much other than in terms of consumed bytes :)

If it's needed, it is needed ...

**Comment by fniephaus** [comment]
The XML is printed so that other tools can use it.
There's for example [AutoTDD](https://github.com/HPI-SWA-Teaching/AutoTDD) which displays Travis builds in a Squeak image.

We should make this an option, I think.

**Comment by dalehenrich** [comment]
Ah, I wondered what it was there for ... env var or option to turn on 
feature would work ... no big hurry on this ...

**Comment by fniephaus** [comment]
What would be the best default? Printing on or off?

**Comment by dalehenrich** [comment]
since we have only a limited use case for cating the files, I would say 
the default is off ... the pretty printed version is the one that you 
want to see in traivs ... unless you are using a different tool

**Comment by fniephaus** [comment]
How about we just don't print the XML files for GemStone builds? Would that work?
Otherwise, we'd need to move the printing into smalltalkCI's Smalltalk code and add an option to the config.

**Comment by dalehenrich** [comment]
That sounds fine ...

**Comment by fniephaus** [comment]
Logfiles with more than 5000 lines are not being printed, if it's a GemStone build the threshold currently is 2000 lines.
