### ISSUE TITLE
GemStone builds with DEVKIT_BRANCH=dev broken

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#133]
I've pushed https://github.com/hpi-swa/smalltalkCI/commit/52038ebff6ada9a9a7c336bab23f4f46ea0ee2d0 to allow them to fail, but @dalehenrich should have a look at this.
I'm assuming the `dev` branch is currently broken and then breaks smalltalkCI builds as well?

**Comment by dalehenrich** [comment]
the master branch of smalltalkCI should not be using the dev branch of GsDevKit_home ... that was there for work on #105 and I forgot to remove them from .travis.yml before pushing ... I'm actively developing another set of features on the dev branch and it is not unusual for that branch to be broken periodically ...

**Comment by fniephaus** [comment]
So shall I just remove all jobs that are using `dev`? 
Or do you want to keep a job with `GSCI_CLIENTS="Pharo-5.0 Pharo-4.0 Pharo-3.0"`?

**Comment by dalehenrich** [comment]
Delete the redundant dev branch jobs and keep the GS_CLIENTS job but 
remote the dev branch


Sorry about the confusion ...

Dale

**Comment by fniephaus** [comment]
Alrighty!
