### ISSUE TITLE
`EXCEPTION: a MessageNotUnderstood occurred (error 2010), a SmalltalkCICategoryTest class does not understand  #'allMethodSelectors'`

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#134]
The use of #allMethodSelectors was recently introduced ... I am making the call from a GemStone-specific method from a GsDevKit_home script that worked at the time that #105 was merged

Here's the [error log](https://travis-ci.org/GsDevKit/GsDevKit_home/jobs/123155405#L2462) .... not sure what you did to allow the other GemStone calls to pass ... i guess I need to add more test cases as well ...

I don't think GemStone is a candidate for test coverage, so perhaps the coverage code could be refactored to more effectively exclude GemStone?

**Comment by dalehenrich** [comment]
The method that is being used is amongst those that @fniephaus asked about the other day :) ... so, yes they are being used ...

**Comment by dalehenrich** [comment]
Looking at the code, I'm surprised that any GemStone SmalltalkCI tests are passing, since it looks like #runTestsWithCoverage is unconditionally called ...

**Comment by fniephaus** [comment]
> I don't think GemStone is a candidate for test coverage, so perhaps the coverage code could be refactored to more effectively exclude GemStone?

Are you saying that you don't need/want coverage testing for GemStone?

I will have a look at this issue tomorrow...

**Comment by dalehenrich** [comment]
More importantly, I don't see how GemStone functions with this new code ... I don't understand how any GemStone tests passed at this point in time since #runCI calls a method that is not implemented ...

**Comment by fniephaus** [comment]
I am guessing that `SmalltalkCICategoryTest` is not being run as part of smalltalkCI's self test?
Also, I haven't figured out how you were structuring tests (e.g. why is there a package `SmalltalkCI-AllCases-Tests.package`). I thought it would be enough to have a test package for each package.

**Comment by dalehenrich** [comment]
I did not plan on debugging SmalltalkCI problems today but if you've broken all of the GemSTone builds, I guess I will have to debug it ...

**Comment by dalehenrich** [comment]
I think it's obvious that the test coverage for SmalltalkCI is not as complete as it should be ...

**Comment by dalehenrich** [comment]
I'm eating lunch and don't have time right now to debate ... or to find out just how badly SmalltalkCI is broken for GemStone ...

**Comment by fniephaus** [comment]
@dalehenrich `runTestsWithCoverage` is implemented in `SmalltalkCI`, so it is implemented for GemStone. It's just that nothing happens in GemStone builds, because you haven't set `#coverageAgainst` (and you can't at the moment because it's not implemented)

**Comment by dalehenrich** [comment]
and it calls a method that is not implemented in GemStone ...

**Comment by fniephaus** [comment]
> I think it's obvious that the test coverage for SmalltalkCI is not as complete as it should be ...

Now that there is coverage testing for Squeak and Pharo, I am working on adding more tests. I actually wrote some today (haven't pushed them yet)...

I don't see why GemStone builds is broken, but if that's true I will fix it.

**Comment by dalehenrich** [comment]
I DON'T HAVE TIME TO DEBATE ... i HAVE A BROKEN TEST BECAUSE OF MNU AND I DON'T KNOW THE EXTENT OF THE PROBLEMS ... BECAUSE i DON'T KNOW THE EXTENT OF THE PROBLEM ... I HAVE CODE THAT HITS THE RUNcOVERAGE  SO TELLING ME THAT IT CAN'T IS NOT TRUE

**Comment by dalehenrich** [comment]
I just announced the smalltalkCI GsDevKit_home script and that is the path that is breaking in my tests so I assume that it is broken everywhere, because of this newly pushed but unused feature

**Comment by dalehenrich** [comment]
I find it ironic that a feature added to determine test coverage has exposed a gaping hole in the test coverage for smalltalkci :)

**Comment by fniephaus** [comment]
I'm really sorry that I broke something for you and your users and I obviously didn't do it on purpose.
I've reset the `master` branch to [an older commit](https://github.com/hpi-swa/smalltalkCI/commit/6ba4217c8556a9db6d215e3e96579714ca6607c6), and I hope it's working for you again. I will work on a fix tomorrow on `dev`.

Yes, SmalltalkCI isn't well-tested at the moment, and we need to change that asap.

**Comment by dalehenrich** [comment]
Thanks for taking care of this ... I am capable of figuring things out, but I don't have the time to do that ...

Okay, [the test passes now](EXCEPTION: a MessageNotUnderstood occurred (error 2010), a SmalltalkCICategoryTest class does not understand  #'allMethodSelectors') ... Thanks!

In Metacello I reached a point pretty quickly where I realized that I had to build pretty complete test coverage and that no new feature could be added with tests coverage ... Now I did that for the smalltalkCI script, but the test coverage is in the GsDevKit_home project (where I found the bug) and not in SmalltalkCI - so that is my problem --- I will have to add test coverage for the features that I depend upon into SmalltalkCI, but it's not something that I have time for over the next couple of days -- but it is high up on the list, because I **am relying** on SmalltalkCI for new features that I'm adding to GsDevKit_home, and I want SmalltalkCI to be stable...

**Comment by dalehenrich** [comment]
ON the dev branch the [build is failing](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/123166525) ... since there is no Pharo-5.0 failure information I assume that there is a failure [loading the .smalltalk.ston file](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/123166525#L1638):

```
create travisClient_Pharo5.0 image using /home/travis/build/hpi-swa/smalltalkCI/.smalltalk.ston
```

which I assume is the standard config file --- did you change the contents of the file on  the dev branch? the master branch test failed and I tried running the client tests twice and got the same failure ...

Need to fix #115

**Comment by fniephaus** [comment]
Ok, it is failing because of `MessageNotUnderstood: SCIGemStoneServerConfigSpec class>>defaultSessionName:` and I removed that method, because I didn't see where it was used and there also is `SCIGemStoneServerConfigSpec >>defaultSessionName:` and I thought that this was just a copy and paste error...

**Comment by fniephaus** [comment]
Turns out you are using it here: https://github.com/GsDevKit/GsDevKit_todeClient/search?utf8=%E2%9C%93&q=defaultSessionName

I really had no idea that you are depending on this somewhere else...

**Comment by fniephaus** [comment]
All green again: https://travis-ci.org/hpi-swa/smalltalkCI/builds/123298322
Also, I've tested `GsDevKit_home` against smalltalkCI's `dev` this time to make sure I'm not breaking your tests again: https://travis-ci.org/fniephaus/GsDevKit_home/builds/123300330

Like I said, I wasn't aware that your projects are depending this heavily on SmalltalkCI and I've learned my lesson trying to improve your code.

If you don't object, I'd like to merge `dev` into `master` again, so I can continue to improve the code coverage.

**Comment by dalehenrich** [comment]
@fniephaus as I said in another message, I really don't have the time to review and test things right now ... I really wish I had the time to devote to this, but I have other things that I need to work on now ... I should have more time available next week some time ...

**Comment by fniephaus** [comment]
If you want to review this next week, that's okay and I will wait with merging `dev`.
Sorry for bugging you with this, but we'd like to have coverage testing in place for our student projects this year and the students start next week....

**Comment by dalehenrich** [comment]
I'm not sure that https://travis-ci.org/fniephaus/GsDevKit_home/builds/123300330 is actually testing anything ... GsDevKit_home does it's own checkout of smalltalkCI and does not depend upon SMALLTALK_CI_HOME env var ... I should be able to arrange to use the dev branch of SmalltalkCI via another route ... I'll let you know how the tests pan out

**Comment by fniephaus** [comment]
Mh, that's too bad, but thanks!
BTW: @Nef10 is working on https://github.com/hpi-swa/smalltalkCI/issues/124 which might be helpful for this use case. But I guess it will take some time until this is available...

**Comment by dalehenrich** [comment]
Ah, but for the testing of GsDevKit_home, I'm not using smalltalk ci to drive the travis tests --- not testing the smalltalk part of GsDevKit_home, but the bash scripts themselves ... so the mechanisms are those used by GsDevKit_home not SmalltalkCI ... in this case SmalltalkCI is just like any other github project and is loaded into GemStone and Pharo to access the api for **nefarious** purposes :)

**Comment by fniephaus** [comment]
If it helps, I could merge `dev` into `master`, then run the tests again and if it fails I revert `master` again. It's not a good solution, but if you don't have the time to write the necessary infrastructure, this would be easy to do. And it's on a weekend :P

**Comment by dalehenrich** [comment]
The tests are running now ... https://travis-ci.org/GsDevKit/GsDevKit_home/builds/123576767 ... Had look up the name of the env var which takes a bit of research :) https://github.com/GsDevKit/GsDevKit_home/compare/313be9e4ab19...cb3692a9d3e1

**Comment by dalehenrich** [comment]
If the tests pass I'll review the code ...

**Comment by dalehenrich** [comment]
tests green ... reviewing code

**Comment by dalehenrich** [comment]
Where do you want comments ... you apparently deleted SmalltalkCI>>clientConfigurations a method that I added in support of the #configuring feature .... I am using the #configuring feature in my current development so the method needs to stay ... it is a mistake to delete methods from published/public code ... if you want to delete public protocol, you need to go through a deprecation phase ... you **have** to assume that methods that are available are being used, since it is impractical to find the senders of a method in another persons project ... 

The same thing applies to renaming (perhaps what you did) ... the old public method needs to be deprecated and then deleted after sufficient time has passed to allow folks to compensate ...

The principles in [Semantic Versioning](http://semver.org/) were invented to address these kinds of changing api issues -- where the major version is incremented when the public api is broken ... 

Removing a method breaks the public api and would require incrementing the major version number --- a good time to harvest deprecated methods ....

So when reviewing incoming code you want to look carefully at the code (which is why I pinged you to review the code that submitted when this method was added and why I tried to document the features that I was adding ... SmalltalkCI>>clientConfigurations  was part of the implementation of a new feature) once you let new public methods into the project, they won't go away without a major revision number change ...

**Comment by dalehenrich** [comment]
Starting to record issues, since I can't directly comment on the change:
  - https://github.com/hpi-swa/smalltalkCI/compare/dev?expand=1#diff-e3ee9e12e246989bc6b0980dd73b8fe8L1

**Comment by dalehenrich** [comment]
Reviewing the feature a little bit more, I see that in my current use case I'm using SmalltalkCI>>compatibleConfigurationsFor: instead of SmalltalkCI>>clientConfigurations. I also see that there a couple of missing methods: #isClientConfiguration and #isServerConfiguration ... This little area of the code is only there in anticipation of non-gemstone specs being added....

So after further review, I won't object to the removal of SmalltalkCI>>clientConfigurations and SmalltalkCI>>serverConfigurations (presumably)....

**Comment by fniephaus** [comment]
I'll revert the changes that remove those public methods. I must admin that I haven't thought about other projects that could depend on smalltalkCI and you seem to be the first to do this.
I wonder if it is good design to provide a public API that is specific to other projects or if it'd be better to have extension methods in those other projects. The methods I removed were all very generic, so they can definitely stay, but I was just thinking in general.

Thanks for review this on a Saturday, I appreciate your effort!

**Comment by dalehenrich** [comment]
This is another method that I'm using: [SmalltalkCI>>compatibleSpecs](https://github.com/hpi-swa/smalltalkCI/compare/dev?expand=1#diff-d2a05e3675531ac98508399038433e07L1) ... this one was used in the current implementation and for some reason you must have stopped using it and deleted it as well ... Another candidate for keeping ...

One of the things here is that a requirement for tests for new features would make knowing what's used and what is not a little easier ... it would also make the use cases for new features a bit more clear and revieweres would have something more than random methods to look at ...

FWIW, I was ready for push back on the new features and that I added and would have made them specific to GemStone if you'd have asked :) --- It's why I wrote volumes in for #105 so that you'd understand why I was doing what I was doing ...

> Thanks for review this on a Saturday, I appreciate your effort!

I've made better than expected progress on leveraging the new SmalltlkCI features and I don't want to get in the way of progress :)

**Comment by dalehenrich** [comment]
[#compatibleLoadSpecs is a better name than #compatibleSpecs](https://github.com/hpi-swa/smalltalkCI/compare/dev?expand=1#diff-1cf4a7700127189d1a6dbb17ca816867R3) ... perhaps if you implement #compatibleSpecs in terms of #compatibleLoadSpecs and give me some time to switch to using #compatibleLoadSpecs we can eventually delete #compatibleSpecs ...

**Comment by fniephaus** [comment]
I'll move those function to a `deprecated` protocol, so we don't forget

**Comment by dalehenrich** [comment]
sounds good

**Comment by dalehenrich** [comment]
... okay ... done with review ... other than the removed methods, I don't see anything else that would impact my usage .. I see that you added some tests :) ... lot's of cool things in there !

**Comment by fniephaus** [comment]
Thanks a lot, @dalehenrich. I'll re-add all methods as discussed before and then merge if everything still works ;)

Have a good weekend!

**Comment by dalehenrich** [comment]
You have a good weekend, too!

**Comment by fniephaus** [comment]
If [this build](https://travis-ci.org/hpi-swa/smalltalkCI/builds/123604442) does not fail, `dev` should be ready to be merged...

**Comment by dalehenrich** [comment]
Cool!

**Comment by fniephaus** [comment]
Merged, @dalehenrich feel free to restart your tests builds to make sure nothing is broken on your end.
