### ISSUE TITLE
SCISqueakTestReport sends #isTestMethod which produces DNU in Squeak 4.5

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#136]
`CompiledMethod>>isTestMethod` is not implemented in Squeak. That breaks SCISqueakTestReport>>stackTraceString:of:

**Comment by fniephaus** [comment]
https://github.com/hpi-swa/smalltalkCI/commit/b54aef4e64794866604076d5f343941addb22971 broke Squeak builds...

**Comment by theseion** [comment]
Great, thanks!

**Comment by fniephaus** [comment]
No worries. I'm afraid @marceltaeumel tricked me into this one :stuck_out_tongue_closed_eyes:
