### ISSUE TITLE
`run.sh` doesn't like custom config files that aren't named `.smalltalk.ston`

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#139]
The command `./run.sh -s GemStone-3.3.0 --gs-CLIENTS=Pharo-5.0 -v ~/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston` (when run in the smalltalkCI root directory) should be perfectly valid, but I get a `STON file at '.smalltalk_gemstone.ston' does not exist.` error even though the file does exist ... Here's the vebose output

```
dhenrich@foos-gsdevkit-1404:~/GsDevKit_home/shared/repos/smalltalkCI$ ls -altr ~/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
-rw-rw-r-- 1 dhenrich dhenrich 223 May  8 18:52 /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
dhenrich@foos-gsdevkit-1404:~/GsDevKit_home/shared/repos/smalltalkCI$ ./run.sh -s GemStone-3.3.0 --gs-CLIENTS=Pharo-5.0 -v ~/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston 
+ determine_project /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ local custom_ston=/home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ is_empty /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ local var=/home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ [[ -z /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston ]]
+ is_file /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ local file=/home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ [[ -f /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston ]]
+ [[ .ston == \.\s\t\o\n ]]
++ basename /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ config_ston=.smalltalk_gemstone.ston
++ dirname /home/dhenrich/GsDevKit_home/shared/repos/voyage/.smalltalk_gemstone.ston
+ config_project_home=/home/dhenrich/GsDevKit_home/shared/repos/voyage
+ [[ / != \/ ]]
+ is_dir /home/dhenrich/GsDevKit_home/shared/repos/voyage
+ local dir=/home/dhenrich/GsDevKit_home/shared/repos/voyage
+ [[ -d /home/dhenrich/GsDevKit_home/shared/repos/voyage ]]
+ check_clean_up
+ local user_input
+ local 'question1=Are you sure you want to clear builds and cache? (y/N): '
+ local 'question2=Continue with build progress? (y/N): '
+ [[ false = \t\r\u\e ]]
+ return 0
+ select_smalltalk
+ local 'images=Squeak-trunk Squeak-latest Squeak-5.0 Squeak-4.6 Squeak-4.5
                Pharo-stable Pharo-alpha Pharo-5.0 Pharo-4.0 Pharo-3.0
                GemStone-3.3.0 GemStone-3.2.12 GemStone-3.1.0.6'
+ is_not_empty GemStone-3.3.0
+ local var=GemStone-3.3.0
+ [[ -n GemStone-3.3.0 ]]
+ return
+ validate_configuration
+ is_empty GemStone-3.3.0
+ local var=GemStone-3.3.0
+ [[ -z GemStone-3.3.0 ]]
+ is_empty .smalltalk_gemstone.ston
+ local var=.smalltalk_gemstone.ston
+ [[ -z .smalltalk_gemstone.ston ]]
+ is_file .smalltalk_gemstone.ston
+ local file=.smalltalk_gemstone.ston
+ [[ -f .smalltalk_gemstone.ston ]]
+ print_error_and_exit 'STON file at '\''.smalltalk_gemstone.ston'\'' does not exist.'
+ print_error 'STON file at '\''.smalltalk_gemstone.ston'\'' does not exist.'
+ printf '\033[31;1m%s\033[0m\n' 'STON file at '\''.smalltalk_gemstone.ston'\'' does not exist.'
STON file at '.smalltalk_gemstone.ston' does not exist.
+ exit 1
```

it looks like `validate_config` is checking whether the file `.smalltalk_gemstone.ston` exists **in the local directory** the full path for `custom_ston` into account ...

If I create a dummy file: `touch .smalltalk_gemstone.ston`, the command executes just fine...

**Comment by fniephaus** [comment]
2994a60 should fix this issue. Please try again and reopen if the problem persists :)

**Comment by dalehenrich** [comment]
Excellent! ... I'll let you know if it pops up again

**Comment by fniephaus** [comment]
You're welcome!

**Comment by dalehenrich** [comment]
It looks like your fix for this bug broke projects that are using non-standard config files for gemstone.
19 hours ago, [this build was being run using .smalltalk_gemstone.ston](https://travis-ci.org/dalehenrich/voyage/builds/128758358#L817) and a recent build [is now using .smalltalk.ston](https://travis-ci.org/dalehenrich/voyage/jobs/128909524#L819) when it should be using .smalltalk.ston...

It is clear that the gemstone server code is not loading using .smalltalk_gemstone.ston either ...

**Comment by dalehenrich** [comment]
I suppose a test-case for using a non-standard config name is needed...

**Comment by dalehenrich** [comment]
I haven't tried a local run, like originally reported ... the travis builds are more interesting at this point

**Comment by dalehenrich** [comment]
[This is the build result that I should be able to see from .smalltalk_gemstone.ston](https://travis-ci.org/dalehenrich/voyage/builds/128991628) ... I moved the contents of .smalltalk_gemstone.ston to .smalltalk.ston and fiddled with .travis.yml

**Comment by fniephaus** [comment]
We do have a test-case for using a non-standard config file and I checked it before applying the patch:
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/128924601#L232

Again, there seems to be a difference if smalltalkCI is testing itself or if other projects are using it.
Things like this really shouldn't happen, but testing everything with multiple repositories is also quite an overhead. Fortunately, Travis will soon provide a feature for situation like this.
Anyhow, I'll try to fix this asap!

**Comment by fniephaus** [comment]
This should be fixed now, I've verified this with an external project build as well.
As always, reopen if I'm wrong :)

**Comment by dalehenrich** [comment]
It's working now ... thanks for the quick response!
