### ISSUE TITLE
Make it easier to use Travis CI for projects on SmalltalkHub

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#143]
Hi @estebanlm,
I understand you are one of the SmalltalkHub admins?

For [Fuel](https://github.com/theseion/Fuel), @theseion has set up a Jenkins job that triggers a Travis build when it detects code changes on SmalltalkHub.
I was thinking that it'd be cool to make it easy to use Travis for SmalltalkHub. Unfortunately, one will still need to use a GitHub project, but that repository does not need to contain the actual code.
For this, SmalltalkHub would need to notify Travis on push via a web hook.

How hard would it be to add support for web hooks to SmalltalkHub?

**Comment by estebanlm** [comment]
Hi Fabio,
SmalltalkHub has already support for triggering hooks on commit (if you check in settings, there is this "Commit hook"). I added it some time ago but no idea how it is working because AFAIK, nobody ever used it :)

**Comment by fniephaus** [comment]
oh nice, I didn't know! Will check out if it does what I am looking for. thanks!

**Comment by fniephaus** [comment]
@estebanlm it looks like this only supports HTTP GET requests and I need to send a POST request to [trigger a new Travis build](https://docs.travis-ci.com/user/triggering-builds).
How hard would it be to add support for POST requests?

**Comment by tinchodias** [comment]
Hi! I just "randomly" read this issue and I think it can be closed given SThub is being deprecated.

**Comment by theseion** [comment]
I agree, thanks. Closing.
