### ISSUE TITLE
Sent but not implemented and undefined symbols in common code from GemStone perspective

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#144]
In GemStone, I regulary run *sent but not implemented* and *undefined symbols* tests and today is one of those days:)

It turns out that there are a number of *sent but not implemented* and *undefined symbols* in the SmalltalkCI code base. I can make exceptions for these, but then there is the potential for masking the problem coming from other sources ....

Not a high priority, but something that should be cleaned up addressed at some point in time.

Undefined symbols:
1. SmalltalkCI>>writeCoverageReport: references StandardFileStream.
2. SmalltalkCI>>prepareCoverage references TestCoverage

Sent but not implemented:
1. #'detect:ifFound:ifNone:' sent from #'SmalltalkCI>>finishUpAfterCoverage'
2. #'searchForSelector' sent from  #'SmalltalkCI>>fileNameFor:in:'
3. #'signalInitializationError' sent from #'SCIGemStoneTestReport>>setUp'
4. #'allMethodSelectors' sent from #'SmalltalkCI>>prepareCoverage'
5. #'reportImage:' sent from #'SmalltalkCI>>reportImage'

Looks like a problem in GemStone code. The rest are in presumably "common code", but obviously platform specific or not on a code path used in GemStone.

**Comment by fniephaus** [comment]
> #'signalInitializationError' sent from #'SCIGemStoneTestReport>>setUp'
This one is interesting, everything else should be easy to fix :)

**Comment by dalehenrich** [comment]
FWIW, `#'signalInitializationError'`looks to be an artifact from the port of TestReport from Squeak? or did it originate in Pharo? Nonetheless, it looks like it should be replaces with a simple error like:

```smalltalk
self error: 'The resource ', each printString, ' is not initialized'
```

**Comment by fniephaus** [comment]
cdfa4ba should solve all these problems, could you run your tests again and reopen this if I'm wrong? :)

**Comment by dalehenrich** [comment]
[Perfect](https://travis-ci.org/dalehenrich/tode)! The 2.4.8 failure is unrelated to this issue

**Comment by fniephaus** [comment]
Sweet!
