### ISSUE TITLE
$SMALLTALK_CI_VM empty

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#145]
`$SMALLTALK_CI_VM` is empty and smalltalkCI can't change the value, because it runs in a sub-shell.

**Comment by peteruhnak** [comment]
I know (I had a workaround for the empty variable), but I need VM for every platform.
Some time ago I was downloading all of them and bundling them on Travis side ( https://github.com/dynacase/dynacase/blob/27e883846526b7409f0c3e5e6f8da66a0ec981a5/scripts/deploy.sh#L52 ) but it was slowing the build down and extra network traffic; so I moved the bundling itself to another server, that way I don't need to download the VMs every time.

**Comment by fniephaus** [comment]
I assume you are talking about VMs for different operating systems? And then you are basically aiming for an all-in-one deployment as described in #41?

**Comment by peteruhnak** [comment]
yes, but having a single zip with all VMs is way too big, so I have per-VM-bundle http://dynacase.ccmi.fit.cvut.cz/builds/all-in-one/

**Comment by fniephaus** [comment]
Ok, so you could also just have a linux and an osx build that both create a zip with the vm used by smalltalkCI. Unfortunately, this wouldn't solve the windows use case...but that could also be done in the linux build (osx builds are usually slower)

**Comment by Uko** [comment]
Is it already working on Travis, or you have to do some update?

**Comment by fniephaus** [comment]
f243374ff7437ffc46a9e42d95531988d7ac1468 has been merged into `master`, so it should already work.
Let me know if you run into any problems!
