### ISSUE TITLE
Behavior change when passing .smalltalk.ston on the CLI

### ISSUE THREAD

**Issue by zecke** [hpi-swa/smalltalkCI#147]
For some reason I executed "$SMALLTALK_CI_HOME/run.sh .smalltalk.ston" and starting from somwhere this week I end up with:

```
/home/travis/smalltalkCI-master/_builds/TravisCI.image
Pharo4.0
Latest update: #40627
Unnamed
==== Startup Error: FileDoesNotExist: File @ /home/travis/smalltalkCI-master/_builds/.smalltalk.ston
```

So somehow the path is resolved wrongly when moving to the _builds directory? I have modified my osmo-smsc travis.yml to not pass the smalltalk.json file but you might want to fix/modify the behavior change.

**Comment by fniephaus** [comment]
@zecke thanks for reporting. I just pushed a fix.
If your config file is called `.smalltalk.ston`, you don't have to provide it at all :)
