### ISSUE TITLE
Is #expectedFailures being honored?

### ISSUE THREAD

**Issue by marianopeck** [hpi-swa/smalltalkCI#149]
Hi @fniephaus 

Congrats for this nice software!!! Super easy to use and well documented. keep the good work going! 

 I am migrating some projects I have in github. I have some TestCase subclass which implements `expectedFailures` but it does not seem to be taken into account by smalltalk-ci as they are still considering as failures. Do you know if this could be the case or I may be doing something wrong?

Thanks in advance

**Comment by fniephaus** [comment]
Hi @marianopeck,
Thanks!

`expectedFailures

**Comment by fniephaus** [comment]
Hi @marianopeck,
Thanks! And yes, `expectedFailures` should work as expected 😄
There even are tests for that: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/132122045

Can you point me to a project that is broken because of this?

**Comment by marianopeck** [comment]
Hi @fniephaus 

Yes, I imagined it was supported. So I am doing something wrong.. grrr. [Here](https://travis-ci.org/marianopeck/OSSubprocess/jobs/133970891) you can see the job failing in linux and [here](https://travis-ci.org/marianopeck/OSSubprocess/jobs/133970895) on OSX. The `expectedFailures` looks  like [this](https://github.com/marianopeck/OSSubprocess/blob/dev/repository/OSSubprocess-Tests.package/OSSFileBasedUnixSubprocessTest.class/instance/expectedFailures.st) (note that this is on `dev` branch)

From the log I can only see a "Unexpected failure". The only clue I have about this is that sometimes they fail and sometimes they don't. So I suspect the test runner may complain because it was NOT a failure..but sometimes it is...grrr... 

Thoughts?

**Comment by fniephaus** [comment]
Is it working in your local test runner? I'm not sure if you can use symbols in ``expectedFailures``:
https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Excluded-Tests.package/SCIExcludedTests.class/instance/expectedFailures.st#L3

**Comment by marianopeck** [comment]
` #( testShouldFail testShouldPassUnexpectedly )` resolves to an Array of symbols... In either case, I tried with plain strings in an older commit but same results.

**Comment by marianopeck** [comment]
Yes, it does work with the Pharo TestRunner

**Comment by fniephaus** [comment]
I'm actually having problems to run the tests locally...
you can download smalltalkCI and run it locally in ``--headfull` mode to debug builds...

**Comment by fniephaus** [comment]
![image](https://cloud.githubusercontent.com/assets/2368856/15656196/f3d1e22c-26a4-11e6-9c70-fbc1f5580c7a.png)
The tests seem to freeze the image when run in headfull mode

**Comment by fniephaus** [comment]
In this very case, I wonder, why don't you perform the check in the corresponding tests and then return immediately if the platform is not supported? This way, the comment would also be in the test method rather than in the `expectedFailures` method.

**Comment by marianopeck** [comment]
Yes, indeed, you are right and I ended up doing that. Thanks and sorry for the noise. You now have a new project using smalltalkCI :) and I just made a [new release](https://github.com/marianopeck/OSSubprocess/releases/tag/v0.2.4) with it.

**Comment by fniephaus** [comment]
No worries. Feel free to look into expected failures with smalltalkCI when you have some time.
And feel free to send a PR to add your project to [this list](https://github.com/hpi-swa/smalltalkCI#projects-using-smalltalkci).

**Comment by marianopeck** [comment]
Done.
