### ISSUE TITLE
Weird errors with AQMEIO.cpp, AudioQueueObject.cpp

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#151]
I see that build has many lines like:

```
2016-06-07 18:42:34.525 Pharo[863:507] 18:42:34.524 ERROR:     [0xa116d1a8] AQMEIO.cpp:377: _FindIOUnit: error -66680
2016-06-07 18:42:34.525 Pharo[863:507] 18:42:34.525 ERROR:     [0xa116d1a8] >aq> AudioQueueObject.cpp:1590: Prime: failed (-66680); will stop (5512/0 frames)
```

Can this be resolved somehow, because they are littering the important output

**Comment by fniephaus** [comment]
I've seen that message as well and I haven't found out yet what's causing this.
Do you have a link to one of those builds?

**Comment by Uko** [comment]
for example here: https://travis-ci.org/Uko/QualityAssistant/jobs/135961674

**Comment by fniephaus** [comment]
Thanks! It looks like there's a problem with the Sound Plugin on OS X. It might be possible that sound is disabled on Travis builds and that's why the plugin fails. Unfortunately, there's no `-nosound` option like the one for Linux vms, so I guess we need to discuss this on some mailing list...

**Comment by fniephaus** [comment]
Here's the thread:
http://forum.world.st/Errors-in-AQMEIO-cpp-AudioQueueObject-cpp-on-OS-X-10-9-5-td4899728.html

**Comment by Uko** [comment]
Thanks!

**Comment by fniephaus** [comment]
Closing this in favor of https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/158.
