### ISSUE TITLE
Add spec for loading MC packages

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#152]
I have use cases where it would be nice to specify a single package (or two…) in .ston spec. Maybe there can be an `SCIMonticelloLoadSpec` that can load single packages from repositories

**Comment by fniephaus** [comment]
I assume you want to load packages without Metacello?
It should be fairly easy to add support for more loading formats such as a `SCIMonticelloLoadSpec` or even a `SCIFileTreeLoadSpec`...

**Comment by Uko** [comment]
Would it make sense to have something like

SCIGoferLoadSpec {
      #repository : 'http://…',
      #packages : [ 'Package1', 'Package2' ]
    }
 
that will translate directly into Gofer commands?

**Comment by fniephaus** [comment]
A `SCIGoferLoadSpec` sounds reasonable :)

**Comment by fniephaus** [comment]
Mh, Gofer ships with Pharo and GemStone, but not with Squeak I think.
But all images come with Monticello, so I'd prefer a `SCIMonticelloLoadSpec` if that'd work...

**Comment by fniephaus** [comment]
On second thought and since there already is a concept of platforms in smalltalkCI, we could add a `SCIGoferLoadSpec` for convenience.
