### ISSUE TITLE
odd travis failure

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#155]
I'm still debugging, but I have a [build failure](https://travis-ci.org/dalehenrich/voyage/jobs/136764680#L1854) with no obvious error printed out:

![screenshot - 06102016 - 11 58 47 am](https://cloud.githubusercontent.com/assets/623951/15975529/baab7bd2-2f02-11e6-8a8f-c33741bc8069.png)

After examining things a bit more it turns out that the failure was in the `Testing server project` section:

![screenshot - 06102016 - 12 00 34 pm](https://cloud.githubusercontent.com/assets/623951/15975571/f65555d6-2f02-11e6-910f-da59ff2cb4cc.png)

so apparently the driver is not recognizing the failure soon enough and runs the `Testing client project` section even after the the `Testing server project` tests failed ...

Reproduces locally and here's the output of the relevant sections from a verbose/debug run (whats the difference between -v and -d options?):

```
+ /export/foos1/users/dhenrich/dev/_home/bin/devKitCommandLine serverDoIt travis
[Info]: libssl-3.3.0-32.so: loaded
[06/10/2016 11:57:26.502 PDT]
  gci login: currSession 1  rpc gem processId 27748 socket 10 

========>Server Stack: 

EXCEPTION: UserDefinedError: Project 'TugrikTalk' not registered (loaded)
1. UserDefinedError(AbstractException)>>_signalWith: @6 line 25
2. UserDefinedError(AbstractException)>>signal @2 line 47
3. SmalltalkCIGemstone class(Object)>>error: @6 line 7
4. [] in String(SmalltalkCIGemstone class)>>classesToTest:fromProjects: @6 line 7
5. [] in MetacelloProjectRegistry>>registrationForClassNamed:ifAbsent: @11 line 13
6. MetacelloProjectRegistry>>registrationForExactClassNamed:ifAbsent: @7 line 8
7. MetacelloProjectRegistry>>registrationForClassNamed:ifAbsent: @3 line 3
8. MetacelloProjectRegistration class>>registrationForClassNamed:ifAbsent: @3 line 2
9. [] in SmalltalkCIGemstone class>>classesToTest:fromProjects: @3 line 6
10. Array(Collection)>>do: @6 line 10
11. SmalltalkCIGemstone class>>classesToTest:fromProjects: @3 line 3
12. [] in SmalltalkCIGemstone class>>classesToTestFrom: @3 line 6
13. Dictionary(AbstractDictionary)>>at:ifPresent: @5 line 6
14. SmalltalkCIGemstone class>>classesToTestFrom: @5 line 5
15. [] in SmalltalkCIGemstone(SmalltalkCI)>>classesToTest @4 line 10
16. Dictionary(AbstractDictionary)>>at:ifPresent: @5 line 6
17. SmalltalkCIGemstone(SmalltalkCI)>>classesToTest @10 line 9
18. SmalltalkCIGemstone>>classesToTest @5 line 11
19. SmalltalkCIGemstone>>runTests @2 line 3
20. SmalltalkCIGemstone(SmalltalkCI)>>testCI @3 line 3
21. SmalltalkCI class>>testCIFor:named: @7 line 6
22. Executed Code
23. GsNMethod class>>_gsReturnToC @1 line 1

GemStone Server error: a UserDefinedError occurred (error 2318), reason:halt, Project 'TugrikTalk' not registered (loaded)
Error on or near line 99 :: devKitCommandLine serverDoIt travis :: devKitCommandLine serverDoIt travis
+ status=1
+ timer_finish
++ timer_nanoseconds
++ local cmd=date
++ local format=+%s%N
+++ uname
++ local os=Linux
++ hash gdate
++ [[ Linux = Darwin ]]
++ date -u +%s%N
+ timer_end_time=1465585047181484757
+ local duration=1148593383
+ is_travis_build
+ [[ '' = \t\r\u\e ]]
++ echo 'scale=3;1148593383/1000000000'
++ bc
+ duration=1.148
+ printf '\e[0;34m > Time to run: %ss \033[0m\n' 1.148
 > Time to run: 1.148s 
+ travis_fold end test_server_project
+ local action=end
+ local name=test_server_project
+ local title=
+ local prefix=
+ is_travis_build
+ [[ '' = \t\r\u\e ]]
+ is_not_empty ''
+ local var=
+ [[ -n '' ]]
+ is_not_empty travisClient_Pharo5.0
+ local var=travisClient_Pharo5.0
+ [[ -n travisClient_Pharo5.0 ]]
+ for client_name in '"${DEVKIT_CLIENT_NAMES[@]}"'
+ travis_fold start test_travisClient_Pharo5.0 'Testing client project travisClient_Pharo5.0...'
+ local action=start
+ local name=test_travisClient_Pharo5.0
+ local 'title=Testing client project travisClient_Pharo5.0...'
+ local prefix=
+ is_travis_build
+ [[ '' = \t\r\u\e ]]
+ is_not_empty 'Testing client project travisClient_Pharo5.0...'
+ local 'var=Testing client project travisClient_Pharo5.0...'
+ [[ -n Testing client project travisClient_Pharo5.0... ]]
+ echo -e '\033[34;1mTesting client project travisClient_Pharo5.0...\033[0m'
Testing client project travisClient_Pharo5.0...
```

The failure `status` appears to be saved, but we're apparently continuing with run ...

I should have a fix shortly ...

**Comment by fniephaus** [comment]
Thanks! Probably unrelated, but I also had to clear the cache after merging the SCIMonticelloLoadSpec pull request to get the GemStone builds working again.

**Comment by dalehenrich** [comment]
Thanks, that may have been due to the fact that I released a new version of GsDevKit_home the other day ... this may be the first time that I had a literal error during `Testing Server project...` so I suspect a `gemstone/run.sh` logic error.

**Comment by dalehenrich** [comment]
Yep looks like there are two issues:
  1. I  pick up the failure status during the server test, but I go ahead and run the client tests
  2. I'm ignoring the return status of the client test runs altogether ...

oooh this is a bit worse than I thought ... the non-zero exit status is used to indicate test failures and load errors ...

The logic I want is to run all of the server tests and all of the client tests and then fail the build because of TEST errors ... but in my case I'm getting errors while trying to load the tests and I don't think I can differentiate between the two ... 

Perhaps I need to have a different exit status # to indicate failed tests vs. script errors?

**Comment by dalehenrich** [comment]
Ah, but the test failures don't cause a non-zero exit status so I think I'm okay ... smalltalkCI independently tests the results of all of the tests and fails ..

It's confusing that `run_build()` returns an exit status all the way back to `run()` and `main()`, yet a number of places do the `print_error_and_exit()` themselves ... I thought that the exit status of run_build() was meaningful ... I don't think the exit status for `run_build` is really meaningful anymore since a better strategy is to `print_error_and_exit()` ...

**Comment by fniephaus** [comment]
Good point, I might have to go over this. It's very much possible...

**Comment by dalehenrich** [comment]
@fniephaus it appears that when you merge a fix into the master branch that you go ahead and allow git to *fast forward* without an extra commit? I'm going to do that with my fix #155 ... [builds are green](https://travis-ci.org/hpi-swa/smalltalkCI) ... if you prefer to use a PR, then I'll do that in the future ..

**Comment by dalehenrich** [comment]
... never mind ... you're the only one that can merge without a PR:)

**Comment by fniephaus** [comment]
Even I use a PR for new features, because I can't afford to break `master`. It *needs* to work! 😉
But I didn't know that merging a PR would cause a problem like this. AFAIK, pull requests *fast forward* with an extra commit (e.g. https://github.com/hpi-swa/smalltalkCI/commit/9e77b77cdb0a7b799de913eaa5b1b6d0fcd5886e).

**Comment by dalehenrich** [comment]
issue #145 is closed and the issue/145 commit is on the [master branch with no PR commit (AFAICT)](https://github.com/hpi-swa/smalltalkCI/commit/b2fbff564770c7c7ab2c097d297c2c940f96c618) so I assumed you did a FF without a pull request (I don't see any PR associated with #145)

**Comment by dalehenrich** [comment]
There aren't that many examples that I could easily identify and #145 was the first one I came across:)

**Comment by fniephaus** [comment]
Are you saying that this broke GemStone builds? I, in fact, didn't open a PR for #145, but I probably should have...

**Comment by dalehenrich** [comment]
I didn't say that you did the merge without testing ... just that #145 looks like it was merged to master without a PR ... it's a moot point anyway, since I don't have permission to merge to master anyway:) ... which is fine by me ... I just figured I could save you some work:)

**Comment by dalehenrich** [comment]
You know pressing the merge button on a pr costs a lot of effort :)

**Comment by dalehenrich** [comment]
No nothing broke ... I just figured that this issue was a lot like #145 a simple edit on the head of the master branch with a passing travis-ci does not *require* a PR to know it's okay

**Comment by fniephaus** [comment]
I didn't open a PR, because I didn't want Travis to build everything twice (I already had [`issue/145` tested](https://travis-ci.org/hpi-swa/smalltalkCI/builds/135933058)). I'm happy to merge your branch directly, but usually we don't work at the same time.
So triggering another Travis build isn't much of a time problem and I don't have to check if the branch builds on Travis. :)

**Comment by dalehenrich** [comment]
This all started because I _thought_ I had permissions to merge to master and I when I looked it didn't seem that you were consistently opening PRs for every bugfix and figured that this bug fit into that mold: simple fix, head of master clean, no need to rerun full test suite (twie) to confirm what I already knew ..

And I asked the question **assuming** that I could merge to master ... since I can't merge to master the only way you know that I'm done is when I open a PR and the tests pass ...

I don't personally care how things get merged as long as the builds are green ... like I said **if I had master merge permissions** I would have made the same decision for this issue that you did for #145 :)

**Comment by fniephaus** [comment]
I do understand your point here and I very much appreciate that you are putting this much effort into smalltalkCI. Besides, you made me a core dev of builderCI, so it only makes sense to "return the favor".
Guess who can push to `master` now 😉

**Comment by dalehenrich** [comment]
haha ... thanks ... \rubs hands/ well let me see what I can do now:)

**Comment by fniephaus** [comment]
Just so you know: you can't force push or merge failing PRs ;)

**Comment by dalehenrich** [comment]
\ unrubs/ hands :)

**Comment by fniephaus** [comment]
Even I can't do these things, unless I change the settings :wink:
