### ISSUE TITLE
loadCI vs testCI

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#158]
I just realized when looking into #148 that GemStone builds are using `SmalltalkCI>>loadCI` and `SmalltalkCI>>testCI` rather than just `SmalltalkCI>>runCI`.

First, I wonder why `loadCI` needs to call `prepareForCI` and `finishUpAfterCI`? These functions are meant to prepare things (e.g. Author) before running the tests and then bringing the image into it's initial state.

Anyway, it does seem better to load the projects, save the image, and then run the tests. If the tests pass, we just close the image, so we might not need `finishUpAfterCI` anymore. If they fail, we save the image for debugging purposes (but we won't deploy this image, as in a stable release. however, we could still "deploy" the build artifacts for debugging purposes).

What do you think, @dalehenrich?

**Comment by dalehenrich** [comment]
Given the abstract implementations of `prepareForCI` and `finishUpAferCI` and the fact that GemStone doesn't specialize either of those messages it was pretty benign to implement `testCI` and `runCI` the way I did ...

Besides using `loadCI` for the server, I also use `loadCI` with the client Smalltalks as I use SmalltalkCI to load code into GemStone client images with no intent to actually test...

Consequently I wouldn't mind if things were refactored a bit more ...

**Comment by fniephaus** [comment]
Great! Just wanted to double check, so I don't break things :)
