### ISSUE TITLE
sent but not implemented in SCIMonticelloLoadSpec --- for GemStone

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#160]
The following methods are being sent, but are not implemented for GemStone:

```
Sent but not implemented from #'SCIMonticelloLoadSpec>>loadVersion:repository:'
	#'versionReaderForFileNamed:'
Sent but not implemented from #'SCIMonticelloLoadSpec>>extractVersionsFromPackages:'
	#'allFileNamesOrCache'
	#'ifEmpty:ifNotEmptyDo:
```

I haven't looked at the implementation yet, but unless there are overrides of SCIMonticelloLoadSpec>>loadVersion:repository: and SCIMonticelloLoadSpec>>extractVersionsFromPackages: for GemStone, SCIMonticelloLoadSpec wouldn't work for GemStone ... since Gofer is present in GemStone, perhaps these methods are used by Squeak only?

In case it matters, [sent but not implemented methods cause build failures for GemStone projects](https://travis-ci.org/dalehenrich/tode/jobs/136965697#L4064)

**Comment by dalehenrich** [comment]
When we get [platform-specific tests implemented](https://github.com/hpi-swa/smalltalkCI/issues/111), I'll be able to add [SentButNotImplementedTest and UndefinedSybolsTest](https://github.com/dalehenrich/tode/blob/master/.smalltalk.ston#L11-L15)  to the smalltalkCi tests suite and catch these earlier

**Comment by fniephaus** [comment]
Sorry @dalehenrich, this is bad. I guess we really need to add these tests, otherwise it is really hard to avoid these problems. I honestly had already forgotten about this issue again and was thinking that adding new code paths can't break things 😢

**Comment by fniephaus** [comment]
I just added `SentButNotImplementedTest` and `UndefinedSybolsTest`. No need for platform-specific `#testing` because currently, it only adds tests that actually exist in the image. But that does not mean we shouldn't add support for platform-specific `#testing`.
