### ISSUE TITLE
GemStone "hides" client startup errors

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#161]
There was a client startup error during this [build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/137268636#L1423) and GemStone hides the error: `Pharo STDOUT routed to: /home/travis/smalltalkCI-master/_builds/GsDevKit_home/dev/clients/travisClient_Pharo5.0/logs/todeClient.log` ... 

I think that this is a [GsDevKit_home issue](https://github.com/GsDevKit/GsDevKit_home/issues/127) ...

**Comment by fniephaus** [comment]
Yes, I'm still trying to figure out the source of the problem, but I don't have the infrastructure to reproduce the log file efficiently...

**Comment by dalehenrich** [comment]
I'll take a crack at this ...  wait it looks like it is a random failure ... oh well, I plan to address the "hidden" log file very soon ...

**Comment by fniephaus** [comment]
Nope, I already found and fixed it :)

**Comment by dalehenrich** [comment]
Okay ... I'll clse when I fix in GsDevKit_home...

**Comment by fniephaus** [comment]
Thanks!

**Comment by dalehenrich** [comment]
[Actually this is not a GemStone bug](https://github.com/GsDevKit/GsDevKit_home/issues/127#issuecomment-225675486): the `Pharo STDOUT routed to: /home/travis/smalltalkCI-master/_builds/GsDevKit_home/dev/clients/travisClient_Pharo5.0/logs/todeClient.log` message was misleading and stdout is not re-reouted when `startClient -t` is being used ... and that's the case here.

So this is just another instance of #115 ...
