### ISSUE TITLE
SmalltalkCI extension methods for GemStone

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#163]
Hi @dalehenrich,
I forgot to give you some context for  https://github.com/GsDevKit/GsDevKit_home/pull/128#event-692308729 and https://github.com/dalehenrich/tode/pull/273#event-692309711:

I noticed that for GemStone, you have added specialized convenience methods as extensions to `SmalltalkCI class`. I'm not sure if this is a good idea, so I've moved them to `SmalltalkCIGemStone class` instead.

I will remove the extension methods from `SmalltalkCI class` as soon as we know that everything is working for you. This time I made sure not to break compatibility, but I also don't want to keep redundant methods for too long.

**Comment by dalehenrich** [comment]
Which methods were the extension methods?

**Comment by fniephaus** [comment]
These four methods:
https://github.com/hpi-swa/smalltalkCI/tree/9bfa34e2cc24af5b8d755615b2de52e2767e1de6/repository/SmalltalkCI-GemStone.package/SmalltalkCI.extension/class

I still need to update everything in [/gsdevkit](https://github.com/hpi-swa/smalltalkCI/tree/master/gemstone/gsdevkit), but I am not quite sure how these tools are used.

**Comment by dalehenrich** [comment]
The `produceXMLLog` stuff dates back to pretty close to the beginning of my SmaltalkCI work and it was added long before [I understood that I could invoke the python pretty printer myself](https://github.com/GsDevKit/GsDevKit_home/issues/127)  ... I'm sure that it can be cleaned up at some point ...

**Comment by dalehenrich** [comment]
The [/gsdevkit](https://github.com/hpi-swa/smalltalkCI/tree/master/gemstone/gsdevkit) stuff is in the same category ... that work pre-dated the time when I could easily run smalltalkCI from the command line for GemStone ... I think that everything in that directory is obsolete ...

**Comment by fniephaus** [comment]
Can I just remove that dir then?

**Comment by dalehenrich** [comment]
Yeah go ahead
