### ISSUE TITLE
Upload a zip to bintray instead of individual files

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#165]
I didn't find if this can be customized, but can a zip of image+changes be uploaded as a zip to bintray? (for Pharo at least).

Pretty much always you want both files, so it would be easier to have a single file to point to (especially if you have something like "download" link on a website).

**Comment by fniephaus** [comment]
That's a good point. Deployments are still considered to be experimental currently which is also why I haven't added documentation for it yet. Maybe these files should always be zipped, why would someone want both files to be uploaded separately?

**Comment by peteruhnak** [comment]
Indeed, I think having just the zip is enough for bintray.

Another idea would be have a "bintray" folder (if bintray deployment is enabled), and smalltalkCI would upload everything inside the folder. By default only the zip would be in the folder, but the user could add custom files if needed (such as reports, etc.)

**Comment by fniephaus** [comment]
The only problem with that is how the user can move files into the bintray directory. Travis CI has a `before_deploy` stage for that, but that would mean that smalltalkCI needs to override the `deploy` stage. While thinking about this, it might be worth doing exactly that...please let me know if you have more deployment-related ideas!
