### ISSUE TITLE
Adding moose as a platform base

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#166]
Would it be possible to add moose (http://moosetechnology.org/) as a base in addition to Pharo?

Some projects are created on top of moose instead of plain Pharo as it provides a lot of pre-installed stuff used for data and software analysis.

This would probably mean modifying https://github.com/hpi-swa/smalltalkCI/blob/master/pharo/run.sh to download moose instead or adding a new `moose/run.sh` script (which would extend the pharo one).

The moose zip is available here https://ci.inria.fr/moose/job/moose-6.0/lastSuccessfulBuild/artifact/moose-6.0.zip

Moose 6 runs on Pharo 5

**Comment by fniephaus** [comment]
I'm not very familiar with Moose, but I'm happy to add support for it or accept a pull request.
Would you consider Moose to be a Pharo flavor or do you think it deserves it's own directory? Independent of this decision, we should call it `Moose-6.0` and add `Moose-stable`, right?

**Comment by peteruhnak** [comment]
I would consider it a Pharo flavor… it's basically Pharo to which a lot of tools were already installed (so it would save several minutes of build time and extra stuff in the project's baseline).

As for stability, Moose-X is always in Pharo-(X-1), and is released several weeks after Pharo.

Right now, Moose-5 (on Pharo-4) is stable; however soon (next week or two), Moose-6 (on Pharo-5) will be released and dev (Moose-7 on Pharo-6) will start.

We don't need to worry about Moose-5...

so maybe have just `Moose-development` until `Moose-6` is released.
Am I making sense? :)

**Comment by fniephaus** [comment]
Would it be better if we call it `Pharo-Moose-6.0`? First, it's integrated in `pharo/run.sh` and second, we would need to update our Travis integration to teach Travis that `Moose*` is a Pharo build. The latter is a simple change, but the Travis team would need to merge it...

**Comment by fniephaus** [comment]
I've opened a PR for the Travis team which makes it possible to call the Smalltalk target `Moose-*`. Once it is merged and live, I will update `issue/166` and merge it into `master`.

**Comment by peteruhnak** [comment]
Whatever is easier for you.

**Comment by fniephaus** [comment]
Done!
