### ISSUE TITLE
Moose & bintray

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#167]
I've tried to run moose together with bintray deploy, however the deploy have failed

```
Deploying to bintray.com...
Compressing and uploading image and changes files...
mv: cannot stat `/home/travis/smalltalkCI-master/_builds/TravisCI.image/': Not a directory
```

https://travis-ci.org/ObjectProfile/snabbstudio/builds/139243245#L300

I don't have test repo for bintray so I don't know if other platforms (Pharo, Squeak, ...) are also affected.

**Comment by fniephaus** [comment]
Please restart the build and try again. Thanks

**Comment by peteruhnak** [comment]
well, the error has changed

```
Deploying to bintray.com...
Compressing and uploading image and changes files...
tar: unrecognized option '--include'
Try `tar --help' or `tar --usage' for more information.
```

https://travis-ci.org/ObjectProfile/snabbstudio/builds/139243245#L300

also I can't reopen this (I guess because I didn't close it)

**Comment by fniephaus** [comment]
Well, then try again 😃

**Comment by peteruhnak** [comment]
Aah… one last thing and then I'll shut up. :)

Unziping the directory creates deep hierarchy that reflects the travis hierarchy

```
❯ unzip snabbstudio-2.1-Moose-6.0.zip
Archive:  snabbstudio-2.1-Moose-6.0.zip
  inflating: home/travis/smalltalkCI-master/_builds/snabbstudio-2.1-Moose-6.0.image
  inflating: home/travis/smalltalkCI-master/_builds/snabbstudio-2.1-Moose-6.0.changes
```

I believe there's a switch to specify the root, however the best is probably cd to the correct level.

(this is also true for the tar.gz)

The target zip should (imho) be either flat — unpacking would unpack image and changes in the current folder (this is how Pharo image zips behave), or alternatively just one folder deep; but I think flat would be better?

**Comment by fniephaus** [comment]
I've just noticed this myself. The fix is already live: https://github.com/hpi-swa/smalltalkCI/commit/43bb33057a0c6224e81bc5195a55b26ad58ccf32 :)
