### ISSUE TITLE
Add docs on how to generate coverage reports

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swa/smalltalkCI#170]
Code coverage reports and how to enable them are not currently mentioned in the README.

**Comment by fniephaus** [comment]
Coverage testing is currently still considered to be an experimental feature. I like the idea of printing coverage results into the Travis log and to make coveralls optional.
For now, coveralls is required and one needs to add `#coverage` in the `#testing`. [Here](https://github.com/hpi-swa/smalltalkCI/blob/master/.smalltalk.ston) is an example.
