### ISSUE TITLE
SCIMetacelloLoadSpec>>getClassesForMetacelloProjectRegistration:  can give wrong answers under certain circumstances

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#174]
Metacello can have *conflicting* registrations for projects with the same basename. For example there can be registrations for **BaselineOfMetacello** and **ConfigurationOfMetacello** - typically this occurs in a [bootstrapped GemStone image](https://github.com/dalehenrich/metacello-work/issues/390#issuecomment-230639317), but can happen in Squeak and Pharo as well ...

The solution is to simply use the the full className (`BaselineOf` or `ConfigurationOf`). 
We can tell the difference between a basline and configuration in the call for [`SCIMetacelloLoadSpec>>getClassesForMetacelloProjectRegistration:`](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Core.package/SCIMetacelloLoadSpec.class/instance/loadedClasses.st#L3-L6), but `SmalltalkCI class>>classesOfProjects:`  will take a little more research

**Comment by fniephaus** [comment]
Wouldn't this fix the problem then:
```javascript
...
#projects : [ 'BaselineOfMetacello' ],
...
```
Maybe we need smalltalkCI to print a good error message when there are conflicting project registrations and that the full name is required in `#projects`.

**Comment by dalehenrich** [comment]
My specific problem was coming from the following config:

```ston
SmalltalkCISpec {
  #specName : 'Metacello',
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'Metacello',
      #onWarningLog : true,
      #load : [ 'Tests' ],
      #directory : 'repository'
    }
  ]
}
```

and here, we disambiguate with the `baseline` field and this is the area where the code must change ...

Your suggestion would work if I were using the `projects` field but it does mean that I only need to fix SCIMetacelloLoadSpec>>getClassesForMetacelloProjectRegistration: ...
