### ISSUE TITLE
SCIAbstractLoadSpec should have a variable called 'name'

### ISSUE THREAD

**Issue by pinussilvestrus** [hpi-swa/smalltalkCI#180]
In order we show all LoadSpecs in a list on our UI (https://github.com/HPI-SWA-Teaching/SWT16-Project-11), it would be good if the class have a property called 'name'. This property would give every LoadSpec an alias/ reference.

**Comment by fniephaus** [comment]
I assume you want a LoadSpec>>name method that returns a string which can be used in a list like yours including details on the load spec (e.g. Baseline name etc)?
