### ISSUE TITLE
Cairo dep missing for Pharo 5.0 on Linux

### ISSUE THREAD

**Issue by SergeStinckwich** [hpi-swa/smalltalkCI#181]
Apparently Cairo libraries dependancies are missing for Pharo 5.0 VM on Linux.
For exemple, some Moose tests fail for this reason.

Search for Hismotest>>testViewEvolution2:
https://travis-ci.org/moosetechnology/Moose/jobs/147690982

Fix, maybe : apt-get install libcairo2:i386 ?

**Comment by fniephaus** [comment]
Is this a hard dependency for Pharo 5+ VMs? Or is this just for a plugin?
In the meantime, you can also add this to your `.travis.yml`:
```yml
addons:
  apt:
    packages:
      - libcairo2:i38
```

**Comment by SergeStinckwich** [comment]
Cairo is part of Pharo 5.0 standard image.
Look for CairoLibrary class.

Thank you for the tip Fabio.

**Comment by fniephaus** [comment]
You're welcome. I've opened a PR for the Travis team accordingly which adds `libcairo2:i386` as Pharo dependency.

**Comment by fniephaus** [comment]
The PR has been merged. Now it's just a matter of time until the addition reaches production.

**Comment by fniephaus** [comment]
Just confirming that this has been deployed successfully.

**Comment by SergeStinckwich** [comment]
Great ! Thank you Fabio again for the great support.
