### ISSUE TITLE
$BASELINE is not defined

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#19]
Somewhere in the last 9 days something has changed that breaks builds because of a missing baseline.

Here's an example of broken build https://travis-ci.org/dynacase/class-editor/builds/95859363
Notice that just couple of lines above the error is `export BASELINE="DCUmlClassEditor"` so I call shenanigans.

The same code with same travis configuration was passing ~9 days ago https://travis-ci.org/dynacase/class-editor/builds/95670552 (the broken build is just a rerun)

What is missing? Looking at the readme this hasn't changed.

**Comment by fniephaus** [comment]
Travis has just merged some code that allows us to define the baseline like this:
```yaml
language: smalltalk
smalltalk:
  - Pharo-stable
baseline: MyProject
...
```
Unfortunately, it seems that this change is not backwards-compatible.
Sorry about that, we didn't know that this would happen and it probably takes to long to make it compatible.

I will update the README and add a notice to the script to inform users about the change.

**Comment by peteruhnak** [comment]
Ah so just not updated readme. I like the new option :+1:
