### ISSUE TITLE
Documentation clarification needed for step 1 of "How To Enable Travis CI For Your Smalltalk Project"

### ISSUE THREAD

**Issue by bouraqadi** [hpi-swa/smalltalkCI#191]
In the "How To Enable Travis CI For Your Smalltalk Project" section, the first step is "Export your project in a compatible format." The compatible format link (https://github.com/hpi-swa/smalltalkCI#load-specs) lands in the section on "Project Loading Specifications". The word format isn't used there.

**Comment by fniephaus** [comment]
Thanks for opening the issue. I've tried to clarify this.
