### ISSUE TITLE
Folding passed tests

### ISSUE THREAD

**Issue by kursjan** [hpi-swa/smalltalkCI#192]
My projects tend to have hundred to thousands of tests and it is getting hard to find what is wrong with my test suite (see for example [this link](https://travis-ci.org/kursjan/petitparser2/jobs/155406982)).

Would it be reasonable to fold console output of classes that pass successfully?

**Comment by fniephaus** [comment]
I like the idea! Maybe we should also add the number of tests after the class title, so that one knows how many tests are folded.

**Comment by kursjan** [comment]
Even better like that :+1:
