### ISSUE TITLE
What is the default value of #directory ?

### ISSUE THREAD

**Issue by SergeStinckwich** [hpi-swa/smalltalkCI#193]
Apparently if my packages are at the root level and I put no #directory in the .smalltalk.ston file, my build break. I have to put #directory : ''
What is the default value of #directory ?

**Comment by fniephaus** [comment]
Do you have a link to an example build that fails because of that?
I'm tempted to even call this a bug. If your code is in the root directory, then you shouldn't have to use `#directory`.

**Comment by SergeStinckwich** [comment]
Yes I have an example : 
- this built is working : https://travis-ci.org/SergeStinckwich/PlayerST/builds/155759274
- this built is not working : https://travis-ci.org/SergeStinckwich/PlayerST/builds/155758816

Only difference is the directory : https://github.com/SergeStinckwich/PlayerST/commits/master/.smalltalk.ston

**Comment by fniephaus** [comment]
Thanks! This should be fixes now :) Please try again!

**Comment by SergeStinckwich** [comment]
Work now ! Thank you.
