### ISSUE TITLE
Adding MOOSE 6.1 in the list of provided images

### ISSUE THREAD

**Issue by SergeStinckwich** [hpi-swa/smalltalkCI#194]
MOOSE 6.0 image has been released and there is now a MOOSE 6.1.

**Comment by fniephaus** [comment]
Where do I find the 6.1 image? There isn't one [here](http://moosetechnology.org/res/download/).

**Comment by SergeStinckwich** [comment]
I guess on MOOSE CI: https://ci.inria.fr/moose/job/moose-6.1/

**Comment by fniephaus** [comment]
Done! :)

**Comment by SergeStinckwich** [comment]
Thank you !
