### ISSUE TITLE
Failed build for a PR in osx

### ISSUE THREAD

**Issue by npasserini** [hpi-swa/smalltalkCI#195]
Hi @fniephaus, I started using Smalltalk CI but I think there is a little bug that prevents from building PRs on osx, would you please take a look at this: https://travis-ci.org/npasserini/iceberg/jobs/157115065 ?

**Comment by fniephaus** [comment]
Hi @npasserini,
it looks like you merged the PR before Travis started to build it. Once merged, the remote reference (`refs/pull/129` in your case) becomes unavailable and therefore, Travis can't perform a merge and fails. Hope this helps! :)

**Comment by npasserini** [comment]
Ok, thank you!
