### ISSUE TITLE
Option to install latest version of Metacello before installing project

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#197]
Recently there have been several issues for projects that rely on the latest version of Metacello to load properly on all platforms:

- [Squeak/Pharo compatible class detection](https://github.com/DuneSt/MaterialDesignLite/pull/21)
- [Pin mongotalk to specific version instead of loading master](https://github.com/pharo-nosql/voyage/issues/63)

in both of those cases the proper solution was to load the latest version of Metacello, before attempting to load the project itself. Rather than forcing the developers to come up with non-optimal solutions, we should add an option for forcing a later version of Metacello to be loaded before loading the project.

Perhaps an option named: `useLatestMetacello` as part of the SCIMetacelloLoadSpec?

```ston
SmalltalkCISpec {
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'SmalltalkCI',
      #directory : 'repository',
      #load : [ 'tests' ],
      #onWarningLog : true,
      #useLatestMetacello : true,
      #platforms : [ #squeak, #pharo, #gemstone ]
    }
}
```

**Comment by fniephaus** [comment]
The only reasons we don't update to Metacello to the latest version are performance and reliability (not need to access external resource), right? An option sounds reasonable, but it also adds complexity for the user.

**Comment by dalehenrich** [comment]
yeah but an option that is only used to avoid doing [this](https://github.com/krono/MaterialDesignLite/blob/30945cd1af67f9f1806832ded8d3d566c0350bc7/src/BaselineOfMaterialDesignLite.package/BaselineOfMaterialDesignLite.class/instance/projectClass.st) is less complicated and much easier to support

**Comment by dalehenrich** [comment]
It makes sense that by default, you load using the version of Metacello that is present on the platform, you run tests to find out if the project works as expected on the vanilla target platform .. but in a few special cases it is preferable to use a version of Metacello that has a specific bugfix or feature that has not been widely distributed (for whatever reason --- old platform versions, or travis-ci image not updated) or even to find out if your project loads using the latest version of Metacello ... 

Perhaps you are concerned about a proliferation of different options?

Maybe something that looks like the following would be a better approach --- we'd still need to document options but at least they'd be corralled in one spot:

```ston
SmalltalkCISpec {
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'SmalltalkCI',
      #directory : 'repository',
      #load : [ 'tests' ],
      #platforms : [ #squeak, #pharo, #gemstone ]
      #metacelloOptions : [ 'onWarningLog', 'loadLatestMetacello' ],
    }
}
```

We could add `{ 'failLoadOn' : [ 'OCUndeclaredVariableWarning' ]}` from [this bug](https://github.com/hpi-swa/smalltalkCI/issues/64) to the list of #metacelloOptions ...  we could isolate the documentation of these options in a single spot dedicated to `advanced metacello options` and keep the top-level list as short as possible.

**Comment by fniephaus** [comment]
I was actually more curious *why* one would need to update to the latest version of Metacello, but I can see that now.
Also, I'd prefer to have separate options like in [here](https://github.com/hpi-swa/smalltalkCI/issues/197#issue-179842655) than having a `#metacelloOptions` list. First, I don't think a list makes things better to read. And second, it's much easier to explain one feature per line [in the docs](https://github.com/hpi-swa/smalltalkCI#scimetacelloloadspec).

**Comment by fniephaus** [comment]
Does this option need to load only the latest Metacello as in:
```Smalltalk
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  get.
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  load.
```

or do you also need to be able to load the `Cypress` group?

**Comment by fniephaus** [comment]
I have an implementation ready for `#useLatestMetacello`, just waiting for you now to reply to the above.

**Comment by dalehenrich** [comment]
Well I think that the latest version of Metacello is the minimal required set of functionality and I think that the Metacello `load` should explicitly load the `batch` group:

```smalltalk
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  load: #( 'batch' ).
```

The `batch` group represents the minimal functionality Metacello and was used by builderCI. I always like to be explicit when doing an an automatic update  and `batch` will guarantee that the install is refreshed for any new loading related features ...

**Comment by fniephaus** [comment]
Makes sense. But the image still has to fetch the Baseline again with `get` first, right?

**Comment by dalehenrich** [comment]
Yes ... the separate invocations is needed because the lowest common denominator version we can rely on does not allow the `get` and `load` commands to be sent in the same Metacello run, so the full invocation needs to look like this:

```smalltalk
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  get.
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://dalehenrich/metacello-work:master/repository';
  load: #( 'batch' ).
```

**Comment by fniephaus** [comment]
Check!
