### ISSUE TITLE
test title obscured by test failed button 

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#199]
see: https://travis-ci.org/dalehenrich/metacello-work/jobs/166565903#L9237

Not sure it is necessary to put the fully qualified test name in both places, expecially when it obscures the larger and more readable test name ...

**Comment by fniephaus** [comment]
The label on the right is the Travis fold identifier which needs to be unique. Any idea how to get a short but unique identifier for a TestCase? Hash it? Strip all lower-case character from the class name?

**Comment by dalehenrich** [comment]
I don't know ... perhaps the label on the left can be offset with the fold starting on a blank line after te test?

**Comment by fniephaus** [comment]
I don't think this is possible, see e.g. [here](https://travis-ci.org/dalehenrich/metacello-work/jobs/166565903#L70) how Travis is using folds. We need shorter identifiers and I think it'd make sense to use hashes for that. They're shorter and the fully qualified names are still there.

**Comment by dalehenrich** [comment]
how does travis know that the line is blank ... display test line newline add right justified fold ... but if you don't think it can work ...

**Comment by fniephaus** [comment]
Travis expects something like this for folds:
```
travis_fold:start:passing_tests_645c
40 passing Tests
...
travis_fold:end:passing_tests_645c
```
And it automatically picks the first line of the fold as the title...
