### ISSUE TITLE
Latest VMs for Squeak

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#2]
Find a better way to provide up-to-date VMs for Squeak.
Maybe show a build number?
Maybe the VMs ship with the new SqueakSSL anytime soon?

**Comment by fniephaus** [comment]
We should be able to use the vm{4,5}0 scripts from [Pharo's Zeroconf](http://get.pharo.org/) for Squeak. That should solve the problem.

**Comment by fniephaus** [comment]
http://forum.world.st/Static-link-to-latest-Coq-vms-td4868528.html

**Comment by fniephaus** [comment]
@peteruhnak and @estebanlm:
Would you prefer to use vms from get.pharo.org/vmXX for Pharo builds, or would it be ok to use a Cog VM from [mirandabanda.org/files/Cog/VM/](http://www.mirandabanda.org/files/Cog/VM/)?

I was thinking about generalising the VM setup procedure on Travis for Squeak and Pharo builds. That's why I am asking.

**Comment by peteruhnak** [comment]
Well you need Spur VM for launching  >50496 images and Cog for <50496, so I'm not sure what's the benefit of using Miranda's site over Pharo's one.

**Comment by fniephaus** [comment]
Sure, the right vm must be picked for the selected image, but there of course is a Cog Spur vm.

Here's an example for a Squeak build with Cog Spur vm.
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/99117951#L218

Also, a Cog vm seems to support a lot more options than a Pharo vm (see below), even though the Pharo one is based on Cog.
Do you know what's different between a Pharo and a vanilla Cog vm? Same bytecodes?

On the other hand, a Pharo user is most likely using a Pharo vm. If there really is a bigger difference, we might want to just keep the Pharo vm.

```
Usage: CogSpur.app/Contents/MacOS/Squeak [<option>...] [<imageName> [<argument>...]]
       CogSpur.app/Contents/MacOS/Squeak [<option>...] -- [<argument>...]

Common <option>s:
  -help                 print this help message, then exit
  -memory <size>[mk]    use fixed heap size (added to image size)
  -timephases           print start load and run times
  -breaksel selector    set breakpoint on send of selector
  -breakmnu selector    set breakpoint on MNU of selector
  -eden <size>[mk]      set eden memory to bytes
  -leakcheck num        check for leaks in the heap
  -stackpages num       use n stack pages
  -numextsems num       make the external semaphore table num in size
  -noheartbeat          disable the heartbeat for VM debugging. disables input
  -pollpip              output . on each poll for input
  -checkpluginwrites    check for writes past end of object in plugins
  -trace[=num]          enable tracing (optionally to a specific value)
  -warnpid              print pid in warnings
  -codesize <size>[mk]  set machine code memory to bytes
  -tracestores          enable store tracing (assert check stores)
  -cogmaxlits <n>       set max number of literals for methods to be compiled to machine code
  -cogminjumps <n>      set min number of backward jumps for interpreted methods to be considered for compilation to machine code
  -reportheadroom       report unused stack headroom on exit
  -maxoldspace <size>[mk]      set max size of old space memory to bytes
  -pathenc <enc>        set encoding for pathnames (default: UTF-8)
  -headless             run in headless (no window) mode (default: false)
  -headfull             run in headful (window) mode (default: true)
  -version              print version information, then exit
  -blockonerror         on error or segv block, not exit.  useful for attaching gdb
  -blockonwarn          on warning block, don't warn.  useful for attaching gdb
  -exitonwarn           treat warnings as errors, exiting on warn

Notes:
  <imageName> defaults to `squeak.image'.
  If `-memory' is not specified then the heap will grow dynamically.
  <argument>s are ignored, but are processed by the Squeak image.
  The first <argument> normally names a Squeak `script' to execute.
  Precede <arguments> by `--' to use default image.
```

**Comment by estebanlm** [comment]
we need our VMs. 
is a different setup, with different plugins (and command line options).
So... no, we cannot be ok with CogSpur (even if *in general* images will run... it will not be complete)

**Comment by fniephaus** [comment]
@estebanlm no worries! That's all I wanted to know :smiley:

**Comment by fniephaus** [comment]
Done: https://github.com/hpi-swa/smalltalkCI/issues/382.
