### ISSUE TITLE
Unnecessary and misleading stack trace when the tests fail

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#200]
see: https://travis-ci.org/dalehenrich/metacello-work/jobs/166565898#L8869

Seeing a stack trace at the end of a failed build is pretty unsightly - when the stack trace has nothing to do with the failure ... 

It's a shame you didn't give anyone an opportunity to review this before releasing into production ... 

Offhand I can't think of a good solution ... but it's released into production now so it looks as if there is a bug in how GemStone exits the tests when it is actually by design --- **your design**.

If I had known earlier that this is the result of adding this new feature I would have asked you to wait until an acceptable solution was available:(

**Comment by fniephaus** [comment]
Do you have a suggestion for how an image can communicate a failed build back to the Bash layer? Write to a status file? I know it's a bit misleading at the moment and I was hoping to find a better solution for it soon as well.

**Comment by dalehenrich** [comment]
If I had know how ugly it was going to look I would have suggested that you wait until a better solution is at hand... 

Topaz has a way to return different error codes, but any better solution requires development work for GsDevKit_home and I really don't have time to drop what I am doing right now to fix this ugly problem.

**Comment by dalehenrich** [comment]
This is not a GemStone bug ... this is a premature release problem!

**Comment by dalehenrich** [comment]
I'm surprised that you thought that the stack trace at the end of the GemStone builds was a good idea :)

**Comment by dalehenrich** [comment]
... and my Metacello test using this new feature is the first time that I have seen this ugliness...

**Comment by fniephaus** [comment]
I have sent you a few emails with all of this at the end of September and you finally said "Looking good!" when I said I was done. That's when I thought I could start merging...

**Comment by dalehenrich** [comment]
@fniephaus I looked at the build that you pointed to when I said "looking good" and I noticed three things:
1. The output does look good
2. the client tests are all passing including the pharo3 tests
3. I cannot find the failing test test ... you'll have to remind me where to find that test... If I had seen a failing test that looked like the one that I saw today (for the first time) I wouldn't have said "looking good" ... 

Did you even look at the failing tests for GemStone?

**Comment by dalehenrich** [comment]
BTW, [here's the build that I looked at and said "Looking good"](https://travis-ci.org/hpi-swa/smalltalkCI/builds/163737747)

**Comment by dalehenrich** [comment]
... it looks like you (or someone) removed the failing test case for GemStone as it looks like only pharo and squeak have the failing test case run ... 

I apologize for not noticing that the failing test run is no longer being run for GemStone ... If I had noticed I would have saved both of us a lot of time...

**Comment by dalehenrich** [comment]
[Here's the commit where you decided to no longer run the failing test for GemStone](https://github.com/hpi-swa/smalltalkCI/commit/85f2aecf33e7c67e2d988d140a45982242d6e1ca)

**Comment by dalehenrich** [comment]
Well, DUH! ... if returning an exit code isn't going to work, is there a reason why you can't just use a simple file?... if the file doesn't exist the tests failed, if the file exists the tests passed ... or put an "exit code" as the contents of a well-know file .... implementing something along these lines should be much easier than trying to revert all of the changes!
