### ISSUE TITLE
The '975 tests passed' line is misleading

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#201]
See: https://travis-ci.org/dalehenrich/metacello-work/jobs/166565898#L7644.

The `975 tests passed` shows up in bright green and draws the eye, but the line fails to mention how many failures and errors there were ... I know that the summary in blue contains this information but you have to hunt for it ... I know that the errors/failures listed is a clue that the build didn't succeed, but if there are a number of errors I have to hunt for the information ...

Perhaps a fold with errors and a fold with failures that summarizes the results would be better ... and of course the noisy stack trace at the end needs to be eliminated somehow ... when I scroll to the end of the build, I just see the stack trace and I have to scroll back up an unknown amount to see the actual results of the test ... very annoying ... perhaps putting back the python summary script is the way to go at least it gave a good summary...

**Comment by fniephaus** [comment]
This is the first result after working on https://github.com/hpi-swa/smalltalkCI/issues/192. I'm happy to iterate over it and make it better. Now that it's written in Smalltalk it's even easier to change.
Yes, the stack trace at the end needs to go away...
