### ISSUE TITLE
GemStone client tests for Pharo-3.0 failing

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#202]
see: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/166575248

Have to look at raw log to see problem ... long short: Pharo4.0, Pharo5.0 and Pharo3.0 are running identical GsdevKit scripts, but the Pharo3.0 startClient script hangs because the image create by an apparently successful createClient run is missing.

The last known [good client test build was about 12 days ago](https://travis-ci.org/hpi-swa/smalltalkCI/builds/163737747).

[There are quite a few changes in smalltalkCI since then](https://github.com/hpi-swa/smalltalkCI/compare/ad2a2862df7896800229102533fbfa4d7f591f48...master) ... but most of the changes are likely not related to this failure --- nothing obvious.

[These are the recent changes to GsDevKit_home](https://github.com/GsDevKit/GsDevKit_home/compare/aa4b2219192f43e4762f0c0c84828c00178bf5bf...master) and there are no other changes to the GsDevKit_home infrastructure.

Don't know if Pharo-3.0 itself has recently changed and that is one are to be concerned about ...

**Comment by dalehenrich** [comment]
Doing a local build, I have confirmed that pharo-3.0 has not changed recently:

```
nehalem:_cache $ ls -altr
total 43320
-rw-rw-r--   1 dhenrich  wheel  21829148 Mar 11  2015 Pharo-3.0.image
-rw-rw-r--   1 dhenrich  wheel    341483 Mar 11  2015 Pharo-3.0.changes
drwxr-xr-x  11 dhenrich  wheel       748 Oct 11 05:50 ..
drwxr-xr-x   3 dhenrich  wheel       102 Oct 11 05:51 vms
drwxr-xr-x   4 dhenrich  wheel       136 Oct 11 05:51 gemstone
-rw-r--r--   1 dhenrich  wheel      2771 Oct 11 05:52 pharo30_zeroconfig
drwxr-xr-x   4 dhenrich  wheel       238 Oct 11 05:52 .
```

vm:

```
nehalem:MacOS $ pwd
/opt/git/smalltalkCI/_cache/vms/Pharo-3.0/pharo-vm/Pharo.app/Contents/MacOS
nehalem:MacOS $ ls -altr
total 1696
drwxr-xr-x  4 dhenrich  wheel     170 May 15  2014 ..
drwxr-xr-x  2 dhenrich  wheel     952 May 15  2014 Plugins
-rwxr-xr-x  1 dhenrich  wheel  867488 May 15  2014 Pharo
drwxr-xr-x  3 dhenrich  wheel     136 May 15  2014 .
```

So we have a nice little mystery here ...

**Comment by dalehenrich** [comment]
Confirmed that in a local run, that the bug still reproduces ... client "successfully created":

```
.
./GemStone64Bit3.3.1-i386.Darwin
./GemStone64Bit3.3.1-i386.Darwin --> 3.3.1
...finished :: createPharoTodeClient -c -z /opt/git/smalltalkCI/.smalltalk.ston -s travis -v Pharo3.0 travisClient_Pharo3.0
...finished :: createClient -c -v Pharo3.0 -s travis -z /opt/git/smalltalkCI/.smalltalk.ston travisClient_Pharo3.0
...finished :: createClient -t pharo travisClient_Pharo3.0 -v Pharo3.0 -s travis -z /opt/git/smalltalkCI/.smalltalk
```

and image missing when we try to run tests:

```
The requested client image: /opt/git/smalltalkCI/_builds/2016_10_11_05_50_51/GsDevKit_home/dev/clients/travisClient_Pharo3.0/travisClient_Pharo3.0.image does not exist
Do you wish to create travisClient_Pharo3.0? [y/n]
```

and sure enough no `travisClient_Pharo3.0` in the pharo client directory:

```
nehalem:travisClient_Pharo3.0 $ pwd
/opt/git/smalltalkCI/_builds/2016_10_11_05_50_51/GsDevKit_home/dev/clients/travisClient_Pharo3.0
nehalem:travisClient_Pharo3.0 $ ls
GemTalkSystemsLogo-Medium.png	customClientLoad.st		pharo-ui
GemTalkSystemsLogo-Muted.png	deleteClient			pharo-vm
GemTalkSystemsLogo.png		github-cache			small_GemTalkSystemsLogo.png
Pharo.changes			installClientGciLibraries	startClient
Pharo.image			logs				updateClient
README.md			package-cache			updateGsDevKit
clientInfo			pharo
```

Did not run Pharo-4.0 as a control ... will do that now ...

**Comment by dalehenrich** [comment]
Here's what the client directory is supposed to look like (Pharo-4.0 run):

```
nehalem:travisClient_Pharo4.0 $ pwd
/opt/git/smalltalkCI/_builds/2016_10_11_06_09_38/GsDevKit_home/dev/clients/travisClient_Pharo4.0
nehalem:travisClient_Pharo4.0 $ ls -altr
total 100464
-rw-rw-r--  1 dhenrich  wheel  23573980 Apr 14 04:47 Pharo.image
-rw-rw-r--  1 dhenrich  wheel    377829 Apr 14 04:47 Pharo.changes
-rwxr-xr-x  1 dhenrich  wheel       867 Oct 11 06:11 updateGsDevKit
-rwxr-xr-x  1 dhenrich  wheel      1694 Oct 11 06:11 updateClient
-rwxr-xr-x  1 dhenrich  wheel      5697 Oct 11 06:11 startClient
-rw-r--r--  1 dhenrich  wheel     11906 Oct 11 06:11 small_GemTalkSystemsLogo.png
drwxr-xr-x  2 dhenrich  wheel       102 Oct 11 06:11 logs
-rwxr-xr-x  1 dhenrich  wheel       954 Oct 11 06:11 installClientGciLibraries
-rwxr-xr-x  1 dhenrich  wheel       573 Oct 11 06:11 deleteClient
-rwxr-xr-x  1 dhenrich  wheel      1442 Oct 11 06:11 clientInfo
-rw-r--r--  1 dhenrich  wheel        54 Oct 11 06:11 README.md
-rw-r--r--  1 dhenrich  wheel     45224 Oct 11 06:11 GemTalkSystemsLogo.png
-rw-r--r--  1 dhenrich  wheel     45224 Oct 11 06:11 GemTalkSystemsLogo-Muted.png
-rw-r--r--  1 dhenrich  wheel     38704 Oct 11 06:11 GemTalkSystemsLogo-Medium.png
drwxr-xr-x  3 dhenrich  wheel       136 Oct 11 06:11 pharo-vm
-rwxr-xr-x  1 dhenrich  wheel       379 Oct 11 06:11 pharo-ui
-rwxr-xr-x  1 dhenrich  wheel       390 Oct 11 06:11 pharo
-rw-r--r--  1 dhenrich  wheel      2667 Oct 11 06:11 customClientLoad.st
drwxr-xr-x  3 dhenrich  wheel       102 Oct 11 06:11 github-cache
drwxr-xr-x  2 dhenrich  wheel       102 Oct 11 06:11 package-cache
-rw-r--r--@ 1 dhenrich  wheel    919961 Oct 11 06:12 travisClient_Pharo4.0.changes
-rw-r--r--@ 1 dhenrich  wheel  26338556 Oct 11 06:12 travisClient_Pharo4.0.image
drwxr-xr-x  4 dhenrich  wheel       204 Oct 11 06:12 ..
-rw-r--r--@ 1 dhenrich  wheel      1788 Oct 11 06:13 SCIExcludedTests-testFailure.fuel
-rw-r--r--@ 1 dhenrich  wheel      1694 Oct 11 06:13 SCIExcludedTests-testError.fuel
-rw-r--r--@ 1 dhenrich  wheel      1750 Oct 11 06:13 SCIExcludedTests-testAssertError.fuel
-rw-r--r--@ 1 dhenrich  wheel      4622 Oct 11 06:13 travisClient_Pharo4.0.xml
drwxr-xr-x  6 dhenrich  wheel       952 Oct 11 06:13 .
```

**Comment by dalehenrich** [comment]
Pharo3.0 client dir from same build as pharo4.0:

```
nehalem:travisClient_Pharo3.0 $ pwd
/opt/git/smalltalkCI/_builds/2016_10_11_06_09_38/GsDevKit_home/dev/clients/travisClient_Pharo3.0
nehalem:travisClient_Pharo3.0 $ ls -altr
total 43696
-rw-rw-r--  1 dhenrich  wheel  21829148 Mar 11  2015 Pharo.image
-rw-rw-r--  1 dhenrich  wheel    341483 Mar 11  2015 Pharo.changes
-rwxr-xr-x  1 dhenrich  wheel       867 Oct 11 06:12 updateGsDevKit
-rwxr-xr-x  1 dhenrich  wheel      1694 Oct 11 06:12 updateClient
-rwxr-xr-x  1 dhenrich  wheel      5697 Oct 11 06:12 startClient
-rw-r--r--  1 dhenrich  wheel     11906 Oct 11 06:12 small_GemTalkSystemsLogo.png
drwxr-xr-x  2 dhenrich  wheel       102 Oct 11 06:12 logs
-rwxr-xr-x  1 dhenrich  wheel       954 Oct 11 06:12 installClientGciLibraries
-rwxr-xr-x  1 dhenrich  wheel       573 Oct 11 06:12 deleteClient
-rwxr-xr-x  1 dhenrich  wheel      1442 Oct 11 06:12 clientInfo
-rw-r--r--  1 dhenrich  wheel        54 Oct 11 06:12 README.md
-rw-r--r--  1 dhenrich  wheel     45224 Oct 11 06:12 GemTalkSystemsLogo.png
-rw-r--r--  1 dhenrich  wheel     45224 Oct 11 06:12 GemTalkSystemsLogo-Muted.png
-rw-r--r--  1 dhenrich  wheel     38704 Oct 11 06:12 GemTalkSystemsLogo-Medium.png
drwxr-xr-x  4 dhenrich  wheel       204 Oct 11 06:12 ..
drwxr-xr-x  4 dhenrich  wheel       170 Oct 11 06:12 pharo-vm
-rwxr-xr-x  1 dhenrich  wheel       379 Oct 11 06:12 pharo-ui
-rwxr-xr-x  1 dhenrich  wheel       390 Oct 11 06:12 pharo
-rw-r--r--  1 dhenrich  wheel      2667 Oct 11 06:12 customClientLoad.st
drwxr-xr-x  3 dhenrich  wheel       102 Oct 11 06:12 github-cache
drwxr-xr-x  2 dhenrich  wheel       102 Oct 11 06:12 package-cache
drwxr-xr-x  6 dhenrich  wheel       748 Oct 11 06:13 .
```

**Comment by dalehenrich** [comment]
Since I know that the createClient script ran successfully what happened to the `travisClient_Pharo3.0` image and changes file? The other later files are from the test run itself ... which didn't get run because of hang

**Comment by dalehenrich** [comment]
I can only include that a change to the Pharo install code has caused Pharo-3.0 to start misbehaving when SmalltalkCI is run from a GsDevKit_home createClient script ...

Have to start spelunking into the changes made to the Pharo code base...

**Comment by fniephaus** [comment]
Could you check locally if [this line](https://github.com/GsDevKit/GsDevKit_todeClient/blob/7ac62994174733e399b7c9009c582428ce74defb/bin/createPharoTodeClient#L256) is doing what it should do?

**Comment by dalehenrich** [comment]
@fniephaus ... look I am going to figure out what happened here, I don't need you to tell me what to do ... you can do any of your own investigation ... I am in the process of turning on script logging so that I can see what is actually going on obviously that line is not doing what it should be doing and that is not the interesting part ... the interesting part is why did it stop working 12 days ago for Pharo3.0 only ...

**Comment by dalehenrich** [comment]
@fniephaus if you want to help ... figure out what changed in the pharo code base for SmalltalkCI in the last 12 days that would cause a save to fail without a trace...

**Comment by dalehenrich** [comment]
... I've got other work that I should be doing so I don't know how much more I am going to be able to do today ... its 6:42 am here and my real work day is starting

**Comment by fniephaus** [comment]
Ok, I have some hours tonight again to work on this as well. Here are some image saving/Pharo related additions/changes I did recently (maybe good starting points):

https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/class/saveImage.st
https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/class/closeImageWithExitCode..st
https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Core.package/SmalltalkCI.class/instance/load.st

**Comment by dalehenrich** [comment]
I don't have time to look right now .. but perhaps you can bring up a pharo3.0 image by itself with smalltalkCI loaded and try to debug the problem, since that is obviously where the issue lies ...

**Comment by fniephaus** [comment]
No problem. A local smalltalkCI build on `Pharo-3` passes, and so does the build on Travis. Next I need to simulate what GsDevKit does....

**Comment by fniephaus** [comment]
Ok, here we go. I think I found the problem:
[This line](https://github.com/GsDevKit/GsDevKit_todeClient/blob/7ac62994174733e399b7c9009c582428ce74defb/bin/createPharoTodeClient#L255) loads smalltalkCI and also the project to test via `SmalltalkCI>>load:` or `SmalltalkCI>>load:projectDirectory:`. This is called with the VM options `--quit --save`, but smalltalkCI also [saves the image after loading](https://github.com/hpi-swa/smalltalkCI/blob/5684bbfaf3a5883a35c42bb0e26177de6ae9d8ae/repository/SmalltalkCI-Core.package/SmalltalkCI.class/instance/load.st#L12). And then, when the script tries to rename `clientTmp.image` via `clientTmp.image save $imageName`, the image immediately saves because of either the line before or smalltalkCI, but certainly not because of this very call. Just to be clear: if you run [this line](https://github.com/GsDevKit/GsDevKit_todeClient/blob/7ac62994174733e399b7c9009c582428ce74defb/bin/createPharoTodeClient#L256) twice, it'll will work because the image got past the second snapshot point.
I believe that this is only a problem with `Pharo-3` because the saving logic via the CommandLineHandler has a bug which is known, but I forgot the actual impact.

However, smalltalkCI shouldn't save and quit the image during `SmalltalkCI>>load`. I'm working on fixing this and then `Pharo-3` should be working again...

**Comment by dalehenrich** [comment]
Good detective work .... several sets of moving parts to wade through ... thanks for digging into this!
