### ISSUE TITLE
Stalled Squeak builds

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#205]
see: https://travis-ci.org/dalehenrich/smalltalkCI/builds/167130025

No output after 10 minutes ... 

Now this is a run where I am testing a new baseline of SmalltalkCI and I have refactored the GemStone packages in preparation for a port of SmalltalkCI to the GemStone base product ... and as a matter of fact this test run may depend upon the newer version of Metacello (I know that #197 is not addressed yet) than is installed in Squeak (Cypress support with the class MetacelloCypressBaselineProject),  but having the Squeak build hang instead of dump an error makes me wonder if there is something else wrong ... perhaps a loading issue ... I know that I can probably figure out the issue with a local build, but I think that I should be able to see the errors on travis and not have to do a local run to get a stack trace ...

It's also true that travis appears to be running very slowly and at this point in time only the squeak builds have run ... so there may be a real issue there ...

It's odd that the raw log ends with the following:

```
travis_fold:start:display_vm_version
[0K[1m[34mCog VM Information[0m
5.0-3427  Fri Aug 21 22:07:53 PDT 2015 gcc 4.4.7 [Production Spur ITHB VM]
CoInterpreter VMMaker.oscog-eem.1441 uuid: c41d605b-7d2e-4ecc-95e1-b295119106a7 Aug 21 2015
StackToRegisterMappingCogit VMMaker.oscog-eem.1436 uuid: 9d2442c4-2066-4ffd-a215-e7e2b6cb8eed Aug 21 2015
VM: r3427 http://www.squeakvm.org/svn/squeak/branches/Cog Date: 2015-08-21 20:39:38 -0700
Plugins: r3415 http://squeakvm.org/svn/squeak/trunk/platforms/Cross/plugins
Linux mclinux32 2.6.32-431.el6.i686 #1 SMP Fri Nov 22 00:26:36 UTC 2013 i686 i686 i386 GNU/Linux
plugin path: /home/travis/smalltalkCI-master/_cache/vms/cogspurlinux/lib/squeak/5.0-3427 [default: /home/travis/build/dalehenrich/smalltalkCI/_cache/vms/cogspurlinux/lib/squeak/5.0-3427/]
travis_fold:end:display_vm_version
[0K

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

So I can't even tell what step is being performed when the hang occurred.

**Comment by dalehenrich** [comment]
... even though travis is not reporting any problems at the moment, I am very suspicious that they are having loading issues that may be causing timeouts for builds ... and they haven't noticed yet ...

**Comment by dalehenrich** [comment]
[The pharo build is failing](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/167130048#L359-L365) and giving me the sort of stack I expected:

```
Fetched -> BaselineOfSmalltalkCI-dkh.16 --- filetree:///home/travis/smalltalkCI-master/repository [:] --- filetree:///home/travis/smalltalkCI-master/repository

BaselineOfSmalltalkCI>>projectClass (MetacelloCypressBaselineProject is Undeclared) 

Loaded -> BaselineOfSmalltalkCI-dkh.16 --- filetree:///home/travis/smalltalkCI-master/repository [:] --- filetree:///home/travis/smalltalkCI-master/repositoryMessageNotUnderstood: receiver of "new" is nil

UndefinedObject(Object)>>doesNotUnderstand: #new

BaselineOfSmalltalkCI(ConfigurationOf)>>project

BaselineOfSmalltalkCI class(ConfigurationOf class)>>project
```

I wasn't sure whether I wanted to use Cypress mode for the baseline --sorta required for loading into the GemStone base, since Monticello is not supported there --  but at this point I think I need to come up with a different approach to cypress mode ...

**Comment by fniephaus** [comment]
The first log you provided suggests that the loading of SmalltalkCI failed in Squeak. Squeak doesn't exit on error by default and I haven't had much luck with the VM option `-exitonwarn` yet. But this could be worth looking into in order to make it better.

#197 is not implemented yet, but I did #198. Not sure if this is enough for what you are trying to achieve. Why do your changes require a newer Metacello?

**Comment by fniephaus** [comment]
This is the error I see in headfull mode:
![image](https://cloud.githubusercontent.com/assets/2368856/19325283/bd0fd092-90c5-11e6-8845-4caeae00861c.png)

**Comment by dalehenrich** [comment]
When you fixed #198, did you load the Cypress group, [as I suggested](https://github.com/dalehenrich/filetree/commit/262b0288b113bca0b3aff1bee005d87916c0c1ff#commitcomment-19254136)? The missing class would have been included if you did...

My changes require a newer version of Metacello, because my baseline is using a feature that is only available in a new version of Metacello --- Cypress mode support. 

Squeak is getting the same error as Pharo, so if #197 were available I would be able to use the latest version of Metacello and not come up with alternatives to using a perfectly good feature of Metacello and SmalltalkCI would be able to test my project.

As I mention in my comment above ... I am not convinced that I need to use Cypress mode, but if I want to use travis I'll have to come up with an alternative --- something I didn't want to have to do now ... 

AGAIN, I am porting SmalltalkCI to the GemStone base (no Monticello and no compatibility code) so when I make changes along the way, I want to ensure that the changes I've made do not break Pharo and Squeak before I get to far along in the port ...

**Comment by fniephaus** [comment]
Yes, I loaded the `Cypress` group [as you suggested](https://github.com/dalehenrich/filetree/commit/262b0288b113bca0b3aff1bee005d87916c0c1ff#commitcomment-19254136).
Now that I have merged #203, I can have a look at other features and #197 is on the top of the list, because you need it. So maybe I manage to finish that tomorrow.

**Comment by dalehenrich** [comment]
Then could you look at the BaselineOfCypress class in your Squeak debugger and tell me what the projectClass method looks like, because this is what [it is supposed to look like](https://github.com/dalehenrich/smalltalkCI/blob/gs_port/repository/BaselineOfSmalltalkCI.package/BaselineOfSmalltalkCI.class/instance/projectClass.st):

```smalltalk
projectClass
^ MetacelloCypressBaselineProject
```

and you are apparently getting `nil`...

**Comment by dalehenrich** [comment]
If `MetacelloCypressBaselineProject` is not loaded, I would not be surprised it being `nil`, like in the Pharo load.

[In GemStone, I got a little bit farther](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/167130076#L1450) and in GemStone I know that  `MetacelloCypressBaselineProject` is defined, since GemStone uses the latest version of Metacello

**Comment by dalehenrich** [comment]
Regarding the original reason for submitting this bug and [this comment](https://github.com/hpi-swa/smalltalkCI/issues/205#issuecomment-253317801), it would be nice if you could figure out some way of exiting from Squeak with an informative stack, because when one does things like port to a different platform, it is convenient to get good information about mistakes that cause fatal failures in other platforms from the travis run itself ... as in this case when I see the stack I can pretty much tell exactly what I did wrong --- hanging build --- not so easy to guess.

**Comment by fniephaus** [comment]
My bad, `MetacelloCypressBaselineProject` is not present in `Squeak-5.0`, but in `Squeak-5.1`. Need to check the other Squeak images as well. I had to update the images manually and that of course is error prone. Unfortunately, it's almost midnight again and I need to get some rest. Will work on that tomorrow if that's ok. So please take `Squeak-5.1` as a reference for now.

**Comment by dalehenrich** [comment]
No problem and no hurry ... I reported this bug because the Squeak build hangs, not to complain about `MetacelloCypressBaselineProject` being missing ... I will probably just test against the various GemStone versions to start with and as I said, I don't see using Cypress modee for this as a long term solution anyway ...

**Comment by fniephaus** [comment]
Mac builds are still processing really slow at the moment, but please restart your builds when the time is right. I've once again updated the Squeak images in question...

**Comment by fniephaus** [comment]
And please reopen this issue if the problem persists.
