### ISSUE TITLE
SmalltalkCI>>headfullBreakpoint in clients should be conditional

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#207]
As I've [mentioned elsewhere](https://github.com/hpi-swa/smalltalkCI/issues/206#issuecomment-253641838), I'm using SmalltalkCI to update and construct client Smalltalk images and when I'm trying to debug a problem during the load I run using head full images and having a halt come up unconditionally is annoying at best and confusing at worst ...  

Right now I have a user that will need to run in the **debug mode** and I will have to explain to them that they need to monitor their build and be aware that an unconditional smalltalkCI halt might pop up and that for the smalltalk halt continue execution ... 

It's also possible that I run multiple head full clients and with these unconditional halts I can't just let the builds run along (taking a fairly long time) waiting for the error to pop up...

If you need to have this breakpoint it needs to be conditional ...

**Comment by fniephaus** [comment]
Actually, I wanted to move the breakpoint out of the loading/testing part of smalltalkCI as well and make the halt part of the script that calls load/test and is injected into an image. I was going to only enable the breakpoints in **debug mode**, but do you need a separate mode for your users? As in `--enable-breakpoints` or `--headfull-debug`?

**Comment by dalehenrich** [comment]
Personally I do not need anything ... I had a system that worked perfectly well for me and my client scripts using the SmalltalkCI API... I don't want an unconditional halt when SmalltalkCI is run in headfull mode ... You apparently need a breakpoint when running in headful mode --- all I ask is that you make it conditional and off by default ... you can enable it any way that you want ...

**Comment by dalehenrich** [comment]
My **debug-mode** feature simply runs the client process in headfull while while doing builds and if a debugger pops up the processing is halted and the end user can debug the problem ... if no issue occurs during the build, the headfull image exits and the driver script continues operations

**Comment by fniephaus** [comment]
Ok, so you don't seem to depend on smalltalkCI's `--debug` option here. I am using the breakpoints sometimes, so I'll move them to smalltalkCI's debug feature...
