### ISSUE TITLE
MISSING accessors for SCIGemStoneServerConfigSpec defaultSessionName 

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#208]
In trying to understand why I was getting a MNU in one of my client scripts, I discovered the the accessors for the defaultSessionName in SCIGemStoneServerConfigSpec were missing.

The commit comment for [this commit](https://github.com/hpi-swa/smalltalkCI/commit/ff7cd3830ccc80e8160d577f332d2e7cd3d8839a#diff-a7560d48175dc39519f0f9df15905877) claims to `Re-add 'SCIGemStoneServerConfigSpec class>>defaultSessionName'` but apparently the re-add was done incorrectly ... and why were these methods deleted in the first place?

**Comment by dalehenrich** [comment]
Nope ... the methods were removed in [this (more recent) commit](https://github.com/hpi-swa/smalltalkCI/commit/a1cd18d5ce4cd4747e6492331cb11ea4268d31ed#diff-a7560d48175dc39519f0f9df15905877) ... 

**You can't just remove methods from the public api of a class**

**Comment by dalehenrich** [comment]
... and the existing tests that were explicitly testing the API were removed as well ... this "cleanup" is breaking functionality that GsDevKit_home depends upon and the tests were added to make sure that this functionality was present!

**Comment by fniephaus** [comment]
I accidentally removed `SCIGemStoneServerConfigSpec class>>defaultSessionName` instead of `SCIGemStoneServerConfigSpec>>defaultSessionName` and that's also the reason why I did that. I came across `defaultSessionName` in one of your frameworks and only the class-side methods were used. I thought there must've been something wrong having identical methods on instance *and* class side.
Lastly, we also need to move them to the `public-api` protocol. Do you usually put everything in a `private` protocol to avoid others to use it? To me it's not obvious that this is public api (well of course I know it's used somewhere, but I have no idea where).
So you really need these methods on instance and class side?

**Comment by dalehenrich** [comment]
Please restore the class implementation to that as of https://github.com/hpi-swa/smalltalkCI/tree/d0850b33d1f75bdd0370b48e51392ddc3c8cc8b0/repository/SmalltalkCI-Core.package/SCIGemStoneServerConfigSpec.class

**Comment by dalehenrich** [comment]
... also restore the tests and anything that you may have changed without understanding what you are doing

**Comment by dalehenrich** [comment]
"So you really need these methods on instance and class side?" ... this a question that you should ask **BEFORE** changing any protocol whatsoever in a public project

**Comment by dalehenrich** [comment]
You have broken functionality that the users of the Tugrik and Voyage/Tugrik projects depend upon...please STOP "cleaning things up" that you do not understand --- **ASK QUESTIONS FIRST**

**Comment by fniephaus** [comment]
I will re-add them with the next push and flag them as public api.

**Comment by dalehenrich** [comment]
@fniephaus ... **PLEASE RESTORE THE FULL BEHAVIOR OF THAT CLASS AS IT EXISTED BEFORE YOU STARTED DINKING WITH IT** ... this commit has the behavior and tests that were originally written: https://github.com/hpi-swa/smalltalkCI/tree/d0850b33d1f75bdd0370b48e51392ddc3c8cc8b0/repository/SmalltalkCI-Core.package/SCIGemStoneServerConfigSpec.class

**Comment by dalehenrich** [comment]
Here is the test class that should be restored as well: https://github.com/hpi-swa/smalltalkCI/tree/95abf8199d5dff52cc2cc0e2ebe3cd242fd82422/repository/SmalltalkCI-Tests.package/SCIGemStoneServerConfigSpecTest.class

**Comment by dalehenrich** [comment]
In the future, when you are considering removing behavior from class in a public project you **MUST** solicit comment ... 

**Please Read** the [introduction for Semantic Versioning](http://semver.org/) and think about the fact that when you make an API breaking change (like deleting methods or changing behavior) you are really creating a **BRAND NEW VERSION** of the project... 

Creating a **BRAND NEW VERSION** of a project is not something that you do on a whim, over the weekend, in your free time ... you have to realize that when you delete a method or change behavior -- like introducing an unconditional `self halt` into the main-line thread of execution -- that you are very likely to be adversely affecting a number of developers who are trying to use your project ... 

If the change you are making is important enough to be made, then you have to make arrangements for developers to be able to continue to use the **OLD Version** of your project until they are ready to move to the new version of your project ...

**Comment by dalehenrich** [comment]
Finally ... I am hoping that you are scheduling your next push in the near future, because you have **BROKEN THE SMALLTALKCI API ... yet again**

**Comment by fniephaus** [comment]
Just had lunch, working on it now...

**Comment by fniephaus** [comment]
Here you go: https://github.com/hpi-swa/smalltalkCI/commit/a71902d5022ae682a595b857617c66d619ca85d0.

**Comment by dalehenrich** [comment]
The class side accessors were originally using a class variable:  `DefaultSessionName` and there is no class instance variable `defaultSessionName` ... did you look at the class in the commit that I referenced?

**Comment by fniephaus** [comment]
I did have a look, but I've missed the name mismatch. After all, I'm a human being like everyone else. Also, I never meant to release a *brand new version* and break things on your side. I came across those identical methods, started to dig into your code and was certain that the instance-side `defaultSessionName` wasn't actually in use. But of course it is used, and I should've asked you...
