### ISSUE TITLE
Poor error message in face of STON parsing errors

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#210]
See: https://travis-ci.org/GsDevKit/ston/jobs/167907755#L444.

Here's the relevant chunk of the log and note the error message: `At character 29: Cannot read STON config file for smalltalkCI`:

```
STONReaderError: At character 29: Cannot read STON config file for smalltalkCI.
[ :error | 
error messageText: 'Cannot read STON config file for smalltalkCI.'.
error signal ] in SmalltalkCIPharo>>readSTONSpec: in Block: [ :error | ...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
STONReaderError(Exception)>>signal
STONReaderError(Exception)>>signal:
STONReaderError class>>signal:streamPosition:
STONReader>>error:
STONReader>>parseMapDo:
```

If you look at STONReader>>parseMapDo:, there are two possible error messages that could apply to `character 29`, but the error handler in [SmalltalkCIPharo>>readSTONSpec:](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/instance/readSTONSpec..st) does not pick up the the STONReaderError message text so SmalltalkCI is obscuring the real cause of the error ... I don't think that there is any good reason to have a STONReaderError handler here, since the only purpose of the error handler seems to be to destroy the original error message ... it would be better to do nothing here.

[SmalltalkCISqueak>>readSTONSpec:](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Squeak-Core.package/SmalltalkCISqueak.class/instance/readSTONSpec..st) has a similar issue. In this case, though, it seems that the image is exitted ... this would be a real problem if someone were to be making a smalltalkCI run interactively from a workspace since this code is virutally undebuggable ... It is odd that other errors are passed here and perhaps that is the cause of some of the Squeak hangs ... if Error were handled here and the image exited if in headless mode (passing the exception otherwise) you might end up with a bit better behavior for Squeak when errors are encountered.

[SmalltalkCIGemStone>>readSTONSpec:](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-GemStone-Core.package/SmalltalkCIGemstone.class/instance/readSTONSpec..st) has no error handler so presumably the error is not obscured ...

**Comment by fniephaus** [comment]
These platform-specific functions haven't been touched in quite a while. I agree that we should remove the error catching in Pharo. When run in headless mode, Pharo already prints the error and quits.
In Squeak, we use `SCISqueakToolSet` during the testing stage to achieve the same behavior. However, `SCISqueakToolSet` is not used during the loading stage which is why the Squeak implementation of `readSTONSpec` does it's own error handling and exits.

What do you mean by
> It is odd that other errors are passed here...

How do you suggest to improve the Squeak method?

I'm going to remove the error catching for Pharo with the next push.

**Comment by dalehenrich** [comment]
> It is odd that other errors are passed here...

Since Squeak doesn't exit on error while running in headless mode, I think that if you are trying to exit the image on error in that method, you should catch **all** errors and exit the image ... presumably there would be fewer Squeak image hangs on travis during development (when other errors are common) if you.

So for Squeak I think that you should: a) handle all Errors, b) leave the message text of STONReaderError alone and c) arranged to dump a stack ...

**Comment by fniephaus** [comment]
What you are describing is already implemented as part of `SCISqueakToolSet`, so maybe it'd make more sense to install and finally uninstall `SCISqueakToolSet` during the loading stage, similar to what happens during the testing stage.

**Comment by dalehenrich** [comment]
I cannot comment on that, as I'm not really familiar with the ins and outs of SCISqueakToolSet ... I just noticed this while reading code :)

**Comment by fniephaus** [comment]
No worries, I try to take care of this...thanks for the feedback
