### ISSUE TITLE
Error calclulating hash in SCITestRunnerResult>>foldName

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#211]
See: https://travis-ci.org/GsDevKit/ston/jobs/168044362#L2684

Looks like the code assumes that the hex result will be 6 chacraters long and apparently there is a case where this is not true ...

**Comment by dalehenrich** [comment]
This one is a little worse than I first thought --- the error means that the tests results that may follow are not displayed and additional test results are lost ...

**Comment by fniephaus** [comment]
Yes, you are right. I've just pushed a fix to `dev`. The printing code needs to be just as solid as the testing code, otherwise we get problems like this one.

**Comment by dalehenrich** [comment]
Thx for the quick response ...
