### ISSUE TITLE
SCITestRunner class>>runClasses:named: should return something other than nil when `classes isEmpty`

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#214]
If `classes` is empty, I get a MessageNotUnderstood error:

```
 > Done in 1365.000s.Testing project...

 > Done in 14.000s.ERROR 2010 , a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'suiteName' (MessageNotUnderstood)
topaz > exec iferr 1 : stk 
==> 1 MessageNotUnderstood >> defaultAction         @3 line 3
2 MessageNotUnderstood (AbstractException) >> _signalWith: @6 line 25
3 MessageNotUnderstood (AbstractException) >> signal @2 line 47
4 UndefinedObject (Object) >> doesNotUnderstand: @10 line 10
5 UndefinedObject (Object) >> _doesNotUnderstand:args:envId:reason: @7 line 12
6 SCIGemStoneTestReporterStdout (SCITestReporterStdout) >> printStart @3 line 3
7 SCIGemStoneTestReporterStdout (SCITestReporter) >> report @2 line 2
8 SCIGemStoneTestReporterStdout class (SCITestReporter class) >> report: @5 line 6
9 SmalltalkCIGemstone >> reportResults:         @2 line 2
10 SmalltalkCIGemstone (SmalltalkCI) >> test     @5 line 15
11 SmalltalkCI class >> test:named:              @5 line 5
12 SmalltalkCI class >> test:                    @2 line 2
13 Executed Code                                 @3 line 3
14 GsNMethod class >> _gsReturnToC               @1 line 1
```

When I should get a "successful test run with 0 tests run ...."

This happened while porting SmalltalkCI to the GemStone base, but a quick glance at senders of SCITestRunner class>>runClasses:named:  shows that no one is expecting a nil result...

**Comment by dalehenrich** [comment]
I would think a `TestResult new` would be a bit more appropriate as I don't think an error of any kind is necessary here

**Comment by dalehenrich** [comment]
... looks like things are a bit more complicated than just returning `TestResult new` ... but that's okay ... an empty list of classes might be surprising, but not fatal ...

**Comment by fniephaus** [comment]
Good point, I actually don't know why `nil` is returned. Can't we just remove [these two lines](https://github.com/hpi-swa/smalltalkCI/blob/2a4a4ec5b84a3bb27b6c23ef54fdfceae74c1249/repository/SmalltalkCI-Core.package/SCITestRunner.class/class/runClasses.named..st#L8-L9)?

**Comment by dalehenrich** [comment]
Don't know ... haven't tried that ... got other things on my plate at the minute :)
