### ISSUE TITLE
After having used the new stdout test runner for a day or so --- would be nice if there were a summary of the failing test selectors at end ...

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#216]
As it is, in my shell window, the stacks included with each failing test overruns the buffer, so it is difficult to get an overview of the failing tests ... I like the the stacks being dumped so I don't want that to go away, but I would like a list of the failing/erroring tests without stacks at the very end, so that I can decide which of the failing tests I want to tackle first ...

**Comment by fniephaus** [comment]
Good point! Cool that you are also using smalltalkCI locally :)
I think smalltalkCI could print the list at the end when it's not running on Travis. AppVeyor doesn't support folds, so it would be useful there as well.
I'll take care of it :)
