### ISSUE TITLE
Inform user that no tests were executed

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#218]
For some reason this is marked as failed build https://travis-ci.org/OpenPonk/demo-editor/builds/170120791 ,
even though  Executed 0 Tests with 0 Failures and 0 Errors in 0.00s.

There's apparently an issue with tests not being loaded and executed, but build with no tests shouldn't (imho) be a failure.

**Comment by fniephaus** [comment]
Haha that's actually exactly why zero executed tests cause a build failure at the moment. Maybe we should add an option that lets smalltalkCI not fail if no tests run? Or in which situation does it make sense to not run any tests on CI?

**Comment by peteruhnak** [comment]
Hmm, maybe you are right. It would make sense if you are setting up a new project and you don't have any tests yet. But how would one know if the failure is because the loading somehow failed, or because there are no tests... or maybe more explicitly state that maybe "loading of tests may have failed"?

**Comment by dalehenrich** [comment]
Maybe a different color should be used for the summary (orange) without failing, because, well, there are not test failures or test errors...

**Comment by fniephaus** [comment]
Yes, we could change the color and explain this a little bit better to the user.
But do we agree that the build should fail by default? Or is there a good reason why it shouldn't?

**Comment by peteruhnak** [comment]
I agree that it is better to err on the side of caution (considering I publish the builds if tests pass, so I could by accident publish a broken thing).

**Comment by dalehenrich** [comment]
another case where we need tri-state logic:) ... @peteruhnak makes a good point ... you don't want to publish builds if there are no tests
