### ISSUE TITLE
Collect anonymous build statistics

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#220]
It would be cool to have some sort of a usage graph for smalltalkCI.
Obviously, I don't want to get into the business of collecting sensitive user data, but I think it would be valid to collect data that is publicly available already, so I'm only thinking about builds on TravisCI and AppVeyor. The following information might be interesting:

- Smalltalk dialect (string)
- Date of build (timestamp)
- Build environment (boolean: TravisCI or AppVeyor)
- Build status (boolean: passing/failing)
- Total build time (duration)

I wouldn't want to collect any project specifics like repository names.
The collection could be done by sending a single HTTP request via curl (this of course needs to be failsafe).

Any objections or suggestions?

/cc @dalehenrich

**Comment by dalehenrich** [comment]
Can't think of any off hand ...
