### ISSUE TITLE
self skip in tests is ignored

### ISSUE THREAD

**Issue by npasserini** [hpi-swa/smalltalkCI#234]
I have used `self skip` in one of my tests: https://github.com/npasserini/iceberg/blob/372c0f39b6caed72a87e46ed9a285c0aaabfe3ac/Iceberg-Tests.package/IceLibgitLocalRepositoryTest.class/instance/testCloneLowLevel.st but it does not seem to work in Smalltalk CI: https://travis-ci.org/npasserini/iceberg/jobs/175658089.

If I run the tests manually in my image it works correctly: 
![image](https://cloud.githubusercontent.com/assets/4633913/20261609/cc933132-aa5e-11e6-9a3d-f6fe46eef388.png)

**Comment by fniephaus** [comment]
Yes, that's currently not supported and it appears to be a Pharo-specific option.
I assume smalltalkCI needs to handle `TestSkip` and then mark a test case as skipped in Pharo?
I'll have a look as soon as I have some time...

**Comment by fniephaus** [comment]
I have it working on `dev`: https://travis-ci.org/hpi-swa/smalltalkCI/jobs/175722944#L458
Should be available as soon as https://github.com/hpi-swa/smalltalkCI/pull/235 is merged.
