### ISSUE TITLE
[Travis] Coverage is not published even if all tests pass

### ISSUE THREAD

**Issue by syrel** [hpi-swa/smalltalkCI#236]
Since around 4th-6th November coverage is not published.
9 days ago we got this error after all tests pass:
```
/home/travis/smalltalkCI-master/run.sh: line 357:  4768 Terminated  travis_jigger $! $timeout $cmd
```
and today
```
/Users/travis/smalltalkCI-master/run.sh: line 618:  2274 Terminated: 15  travis_jigger $! $timeout $cmd
```

Repo: [https://github.com/pharo-graphics/Bloc](https://github.com/pharo-graphics/Bloc)

**Comment by fniephaus** [comment]
Sorry about that. I'll have a look at it in the next few days. Thanks for reporting!

**Comment by fniephaus** [comment]
Hi @syrel,
I had a closer look at the Bloc project and it looks like someone [disabled coverage testing about 16 days ago](https://github.com/pharo-graphics/Bloc/commit/e595c28699133c8adbcb8637bdeb4009105001b2). `#testing` in the `.smalltalk.ston` must contain the key `#coverage`. [I've opened this PR](https://github.com/pharo-graphics/Bloc/pull/5) for you. Let me know if there still is a problem.

Nonetheless, I still need to add docs on coverage testing (#170), now that it is ready to use in other projects.
