### ISSUE TITLE
TransactionError while saving error stack for GemStone should not terminate test run

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#237]
See: https://travis-ci.org/dalehenrich/tode/jobs/177843319#L2204 ...

I'll fix this one in a bit ... probably after Thanksgiving holidy...

**Comment by dalehenrich** [comment]
As part of the fix stop snapping off continuations when running a travis build --- continuations are only useful when you have interactive access to the stone ... still need to bullet-proof the commit though:)

**Comment by fniephaus** [comment]
Fixed as part of https://github.com/hpi-swa/smalltalkCI/pull/247
