### ISSUE TITLE
Loading dependency of a ConfigurationOf fails, but build is marked as successful (green)

### ISSUE THREAD

**Issue by JurajKubelka** [hpi-swa/smalltalkCI#240]
[See example here on Travis](https://travis-ci.org/JurajKubelka/ExploratoryStudyInPharo/jobs/179568783#L106).

```
Loaded -> ConfigurationOfRoassal2-AlexandreBergel.91 --- http://smalltalkhub.com/mc/ObjectProfile/Roassal2/main/ --- http://smalltalkhub.com/mc/ObjectProfile/Roassal2/main/MetacelloProjectSpecLoadError: No version found for #stable of ConfigurationOfRoassal2 because: The symbolic version '1.38' is not defined in ConfigurationOfRoassal2 for the current platform. Possible symbolic version values include: #(#bleedingEdge #development #stable)
[ :ex | 
^ (MetacelloProjectSpecLoadError projectSpec: self)
	versionDoesNotExistException: ex;
	signal:
		'No version found for ' , self versionString printString , ' of '
			, self className asString , ' because: ' , ex description ] in MetacelloMCNamelessProjectSpec
```

It happens only on OS X. It informs correctly about a failure on Linux. [See Linux Travis build](https://travis-ci.org/JurajKubelka/ExploratoryStudyInPharo/jobs/179568782#L398).

The difference in the log is here (OS X):
```
The command "$SMALLTALK_CI_HOME/run.sh" exited with 0.
Done. Your build exited with 0.
```

comparing to (Linux):
```
The command "$SMALLTALK_CI_HOME/run.sh" exited with 1.
Done. Your build exited with 1.
```

**Comment by fniephaus** [comment]
Thanks for reporting this! I should have a fix ready soon. Unfortunately, I can no longer reproduce your specific case, because you seem to have fixed the corresponding `ConfigurationOf`.

**Comment by JurajKubelka** [comment]
Thanks a lot! Yes, I have reported the `ConfigurationOf` problem and it is already fixed.
