### ISSUE TITLE
Re-introduce xUnit test output

### ISSUE THREAD

**Issue by zecke** [hpi-swa/smalltalkCI#244]
In e4230acd08a42213b96e55ebdc717eae5f2da495 SCIReport is removed but the commit message does not carry any context or reasoning for it. When using Jenkins (with the smalltalkCI script) it can be handy to import the xUnit XML file into Jenkins.

Pharo has "Hudson" report generation out-of-the-box, could it be re-introduced or at least offer it as an option for Pharo?

**Comment by fniephaus** [comment]
JUnit XML exporting is still available and enabled by default, but it's now implemented as part of [`SCITestReporterXML`](https://github.com/hpi-swa/smalltalkCI/tree/c523bedb053f213be6877180381c9f205a320656/repository/SmalltalkCI-Core.package/SCITestReporterXML.class). :)

**Comment by fniephaus** [comment]
I'm curious, do you have experience with running smalltalkCI on Jenkins?

**Comment by zecke** [comment]
Sorry for the noise. I didn't search in the right place for the .xml file. Jenkins was a hypothetical example but I do use Jenkins for CI as well but right now not with smalltalkCI.

**Comment by fniephaus** [comment]
No problem! In case you are ever using smalltalkCI on Jenkins, feel free to add a section to the README.md with instructions when you have some time :)
