### ISSUE TITLE
What is the workaround for the new feature where a build fails when there are 0 tests to run?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#250]
Another change in behavior that is causing previously green builds to turn red:).

For the [GemStone-GCI project](https://github.com/GsDevKit/GemStone-GCI), I need to run a server, because the GCI tests require a server to run, but there is no need to actually run tests on the server, but due some behavior changes in SmalltalkCI, the builds are failing because 0 tests are run ... what is the approved method for not failing the build when there are 0 tests to run ... I don't really consider that a reason to fail tests.

Here's the tail of the tape --- https://travis-ci.org/GsDevKit/GemStone-GCI/jobs/185922582.

**Comment by dalehenrich** [comment]
Note that in the summary, [36 tests with 0 failures](https://travis-ci.org/GsDevKit/GemStone-GCI/jobs/185922582#L2359) and the build failed ... presumably there is a setting in the .smalltalk.ston file or .travis.yml file that I can set to not fail when there are 0 tests run (for the server).

**Comment by dalehenrich** [comment]
I guess I'm not the only person [annoyed by this new behavior](https://travis-ci.org/dalehenrich/gt4gemstone#L1549)

**Comment by fniephaus** [comment]
Hi Dale,
I'm afraid there is no option for your use-case yet.
The discussion is related to #218. I'd still argue that running no tests is in most cases a build error. But I would add an option (e.g. `allow_zero_tests`) to allow for your use-case. Do you agree and would that be sufficient? Any ideas for a better option name?
It'd be best if `allow_zero_tests` could only be enabled for the server or a certain client, but I guess for that we may need #111.

**Comment by dalehenrich** [comment]
`fail_when_zero_tests` set to true or false? ... true by default ... I don't think this should be predicated on whether or not the tests are in the gemstone/server or not - it should just be a smalltalkCI option ... occasionally the travis build is actually testing the build process and a successful build (without tests) is a success ... I think travis-ci itself does not require tests and it is a little harsh to make that a SmalltalkCI requirement ...

**Comment by fniephaus** [comment]
I'm just a little bit worried about the case when someone changes e.g. a baseline or the smalltalkCI config and then expects a failure email from Travis if things fail or doesn't look at the builds for a while. And then all builds were passing because nothing was tested and that's because a package was renamed or whatsoever.
But you also make a good point that Travis does not require tests either.
Would a red warning be enough? Would you want to disable that warning in your mentioned setup with an option? Any other ideas how to support devs? It'd be cool if smalltalkCI could keep state during multiple builds and then fail if the number of tests drops to zero, but that's not trivial.

**Comment by dalehenrich** [comment]
well if the default is to fail when then are 0 tests and someone has changed the default, then you cannot protect the developer from themselves ... if there are tests they should be run and if there are 0 tests and I don't want it to be an error then that's fine  ... 

it's perhaps more misleading to require a test that never fails to give the illusion that real tests are being run when they aren't ... 

I think the folks that want failures when there are zero tests are happy ... some of us have no tests on purpose and we want to be able to have green builds in those cases ... no need to make it more complicated ...

**Comment by fniephaus** [comment]
Ok, cool. So let's keep the current behavior and add an option `fail_when_zero_tests` which defaults to `true`. I can work on it tomorrow....

**Comment by dalehenrich** [comment]
Thanks!
