### ISSUE TITLE
Trim very long method names in Travis log

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#251]
see https://travis-ci.org/dalehenrich/gt4gemstone#L1868

**Comment by fniephaus** [comment]
Where do I have to look for the blank lines?
![image](https://cloud.githubusercontent.com/assets/2368856/21410359/3e4ae286-c7e0-11e6-973e-da1b9d8feee4.png)

**Comment by dalehenrich** [comment]
Line #1868 and #1875 are blank in my browser (FireFox):

![screenshot - 12212016 - 03 56 38 pm](https://cloud.githubusercontent.com/assets/623951/21410509/1e979a78-c796-11e6-8d86-4a55bfff8de8.png)

**Comment by fniephaus** [comment]
Ah ok, that's because the method name is too long and should be trimmed in the Travis log.

**Comment by dalehenrich** [comment]
It looks like the lines are wrapped when the test name is wider than allowed by the timing thingy on the side --- the test names show up when I reduce the magnification ... zoom out:

![screenshot - 12212016 - 04 00 06 pm](https://cloud.githubusercontent.com/assets/623951/21410602/bce2edd6-c796-11e6-8b0f-1f19d7889bdf.png)

zoom in:

![screenshot - 12212016 - 04 00 53 pm](https://cloud.githubusercontent.com/assets/623951/21410608/c41d5276-c796-11e6-9819-cc3e7ffb02d2.png)

it's still a bug ...

**Comment by fniephaus** [comment]
Yep, the titles need to be trimmed. Maybe trimmed in a clever way to be able to identify selectors, but then there is also the call stack which usually also contains the selector...

**Comment by dalehenrich** [comment]
I'd vote for ellipses at the end and then the first line inside the the 
fold should be the full untruncated name ...

why can't the title be truncated by the display code --- break at a 
character position instead of blank space ,,, the the full title can be 
maintained and when you expand the fold, the full title is visible ...

hmmm, I see that you already are listing the test class so it is 
redundant to include the class name in the title ... just a test name 
would gain some more room ...

**Comment by fniephaus** [comment]
> why can't the title be truncated by the display code --- break at a
character position instead of blank space ,,, the the full title can be
maintained and when you expand the fold, the full title is visible ...

I guess this is something you would need to discuss with the folks at Travis. Unfortunately, the folding API is not even officially supported :sweat_smile:.

And yes, the list could just contain selectors which would certainly gain some more room. Pretty sure we still need trimming at some point again :)

**Comment by dalehenrich** [comment]
On 12/21/2016 04:28 PM, Fabio Niephaus wrote:
>
>     why can't the title be truncated by the display code --- break at a
>     character position instead of blank space ,,, the the full title
>     can be
>     maintained and when you expand the fold, the full title is visible ...
>
> I guess this is something you would need to discuss with the folks at 
> Travis. Unfortunately, the folding API is not even officially 
> supported 😅.
>
> And yes, the list could just contain selectors which would certainly 
> gain some more room. Pretty sure we still need trimming at some point 
> again :)
>
Yep, but you'll have more room before things get ugly again:)
