### ISSUE TITLE
Consider including all test results in "failure summary" for testcases with errors/failures

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#254]
In this particular build, I have [9 failing tests for the TDStackFrameNewTests test case](https://travis-ci.org/dalehenrich/tode/jobs/187606619#L3659) and [3 passing tests for the TDStackFrameNewTests test case](https://travis-ci.org/dalehenrich/tode/jobs/187606619#L3633) .... 

It would be nice to see the passing tests included in the error summary so I can get a feel for progress

In this particular case, I thought for sure that there should have been at least a couple passing tests for TDStackFrameNewTests, but I had to search a bit more to verify that ...

It wouldn't hurt to include the failing tests in the successful region as well --- only when a test case has mixed results (passing and failing tests).

**Comment by dalehenrich** [comment]
... note that a count of tests in each test case would be nice as well ... I had to manually count the number of tests in each section:)

**Comment by fniephaus** [comment]
What do you mean by:
> It wouldn't hurt to include the failing tests in the successful region as well --- only when a test case has mixed results (passing and failing tests).

Show failing tests in the list of passing tests or show passing tests in the list of failing tests?

Adding a count also sounds like a good idea. How about we add # of passing tests and # of total tests to the successful region and # of failing tests plus # of total tests to the failing region

```
...
TDShellGwToObjRsyncCommandTests  (10 of 10 passing)
 ✓ #testRsyncChecksum (21ms)

...

TDStackFrameTests (4 of 10 failing)
 ✗ #testExecBlockComplexSelfBaseNodeMap (0ms)
...
```

What do you think?

**Comment by dalehenrich** [comment]
On 12/30/16 12:13 AM, Fabio Niephaus wrote:
>
> What do you mean by:
>
>     It wouldn't hurt to include the failing tests in the successful
>     region as well --- only when a test case has mixed results
>     (passing and failing tests).
>
> Show failing tests in the list of passing tests or show passing tests 
> in the list of failing tests?
>
Passing tests in the list of failing tests was definitely my first thought.
But "it wouldn't hurt" to include failing tests in the passing tests as 
well ... this one would be :extra credit" as I think the failing summary 
is the place where the combined info is the most useful
>
> Adding a count also sounds like a good idea. How about we add # of 
> passing tests and # of total tests to the successful region and # of 
> failing tests plus # of total tests to the failing region
>
> |... TDShellGwToObjRsyncCommandTests (10 of 10 passing) ✓ 
> #testRsyncChecksum (21ms) ...|

TDStackFrameNewTests(3 of 12 passing)

|...||TDStackFrameTests (4 of 10 failing) ✗ 
#testExecBlockComplexSelfBaseNodeMap (0ms) ... |

> What do you think?
>
I like the count info ... like I said, I think listing the passing tests 
as well as the failing tests in the failing region would be useful as well

**Comment by fniephaus** [comment]
I think we have improved smalltalkCI with regard to this issue, closing this for now.
