### ISSUE TITLE
Make current spec globally accessible

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#255]
When I implemented `#failOnZeroTests` as part of #250, I had to [add an inst var to `SCITestRunner` and add `SCITestRunner>>runSuite:failOnZeroTests:` and then remap `SCITestRunner>>runSuite:`](https://github.com/hpi-swa/smalltalkCI/commit/3fbe4755116a7b647c71a5c4c8b498fa07bb9499).
In some cases it's good that objects only know as much as they need. On the other hand, this makes it harder to implement features. And most features in smalltalkCI usually come with a new options, list, or some other addition to the `SmalltalkCISpec`. Some classes, such as `SmalltalkCI` itself, know the current spec already and in those cases it's easier to add features. That got me thinking that we could turn the current spec into a singleton, e.g. `SmalltalkCI currentSpec`. This would make it harder to test smalltalkCI with itself, but that certainly is a special case and I'm sure we'll find a good solution for that as well.

@dalehenrich what do you think? Have you encountered similar problems in Metacello or some other project?

**Comment by dalehenrich** [comment]
@fniephaus ... having to pass specific options to the various component classes of SmalltalkCI is definitely a pain ... on the other hand I'm not sure that a singleton is the best solution ... consider adding the `current spec` as an instance variable for each of the component classes that need to access `current spec` and when SmalltalkCI kicks off a component, the `current spec` is pass in on instance creation ... this avoids the singleton, but still allows access to the currentSpec for all of the component classes ...

**Comment by fniephaus** [comment]
Ok, that's probably a better idea :)
