### ISSUE TITLE
Add a parameter to set a proxy for the smalltalk image

### ISSUE THREAD

**Issue by VincentBlondeau** [hpi-swa/smalltalkCI#258]
In my company, they  deployed a Ci server with travis but it requires a proxy to access the outside world.

With a Pharo image, how can I set the proxy while using the run.sh?

Thanks in advance

**Comment by fniephaus** [comment]
Can you set up the proxy as part of for example [`before_script`](https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle)?
I unfortunately don't know how to set up a proxy inside a Pharo image, do you know?

**Comment by VincentBlondeau** [comment]
I have a smalltalk code to set the proxy:

> StartupPreferencesLoader default executeAtomicItems: {
> 	StartupAction 
> 		name: 'Proxy'
> 		code: [
> 			NetworkSystemSettings 
> 				useHTTPProxy: true;
> 				httpProxyPort: 3128;
> 				httpProxyServer: #'proxy'.
> 			]
> 		runOnce: true.
> }.

but I don't know if I can execute Smalltalk code directly in this before_script.

**Comment by fniephaus** [comment]
Hi @VincentBlondeau,
smalltalkCI currently does not support to run a custom script in the image at the moment.
I'll open an issue for that, but unfortunately I currently don't have much time to work on this.
Instead, I suggest you run your code as part of Metacello's `postLoadDoIt:` hook. You can guard this by checking that `SmalltalkCI` is present in the image.
Hope this helps.

**Comment by VincentBlondeau** [comment]
Ok. Thanks for your help. With the check you provide, it should work!

**Comment by fniephaus** [comment]
You're welcome. Glad this works for you. I'm closing this in favor of #259.
