### ISSUE TITLE
Add support for pre/post test/install scripts

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#259]
In some cases, it would be convenient to have the ability to run a custom script pre/post test/install.
One example is https://github.com/hpi-swa/smalltalkCI/issues/258.
This could be part of the `SmalltalkCISpec` and smalltalkCI runs the scripts accordingly.

**Comment by peteruhnak** [comment]
how travis decides when to run smalltalkCI? I guess from the language somehow, but that's opaque to me

**Comment by fniephaus** [comment]
The magic happens [here](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/smalltalk.rb). But I wouldn't want to add new keywords to the `.travis.yml` for this.
Instead, this should probably be part of the `smalltalk.ston`.
A `SmalltalkCISpec` already has `#configuring` for GemStone stuff which could be used to maybe also host these scripts, e.g. via `SCIPreInstallScriptSpec` etc.

**Comment by peteruhnak** [comment]
welll this is not necessarily for things to do inside the image, but only using the image; e.g. right now after tests has suceeded I want to run a bash script that will among other things call the image. (I could do that from inside image using OSSubProcess/ProcessWrapper, but that is not the most comfortable way)

but I will look through the code and see

**Comment by fniephaus** [comment]
ah okay, so probably we only need to check if well-named files are present in bash and execute them at the right point. for example:

```bash
if [[ is_file "${project_home}/pre_test"]; then
  chmod +x "${project_home}/pre_test" # ensure it is executable
  "${project_home}/pre_test"
fi
```

And then a user can put anything into `pre_test` and the shell would respect the shebang...makes sense?

**Comment by estebanlm** [comment]
any new on this? I'm getting to the point where I cannot longer wait ;)
what about make that part os .smalltalk.ston? (I do not like to force names, in general). At the end, you can load smalltalkci, process pre-scripts, then load project run tests, etc.

**Comment by peteruhnak** [comment]
Unfortunately not from my side, as I moved the project that need it the most to GitLab, and there the responsibility is inversed (I am executing smalltalkci at steps where I need it)

**Comment by fniephaus** [comment]
I have been thinking about this more, but still not sure what's needed to cover the most use cases.
Would something like this work for you?

```javascript
SmalltalkCISpec {
  #preLoading: 'src/myPreLoadingScript.st',
  #loading : [
    // List Of Load Specifications...
  ],
  #postLoading: 'src/myPostLoadingScript.st',
  #preTesting: 'src/myPreTestingScript.st',
  #testing : {
    // TestCase Selection...
  },
  #postTesting: 'src/myPostTestingScript.st'
}
```
And then if one or more of these scripts are set in the config, they will be executed right before/after the loading/testing stage.

Any suggestions?

**Comment by fniephaus** [comment]
In the previous example, the scripts do have to take care of platform-handling themselves.
Here's another idea which is more verbose, but would maybe make the life easier for users as well.

```javascript
SmalltalkCISpec {
  #preLoading: [
    SCICustomScript {
      path : 'src/myPreLoadingScript.st',
      #platforms : [ #squeak, #pharo ]
    },
   SCICustomScript {
      path : 'src/myPreLoadingScriptForGemstone.st',
      #platforms : [ #gemstone ]
    }
  ],
  #loading : [
    // List Of Load Specifications...
  ],
  ...
}
```

I wonder what @dalehenrich thinks about this...

**Comment by peteruhnak** [comment]
Do we really need to approach it from inside SmalltalkCI?

GitLab, and recently also Travis (although still in beta) have build
stages. So if we push everything through SCI maybe aren't we restricting
ourselves from that?

**Comment by fniephaus** [comment]
Yes, and no I guess. smalltalkCI downloads a vm and an image and exposes the path to both. So users can use this info to run stuff in the image after a test run.
A smalltalkCI config describes how to load and test a project and if a script needs to run before/after one of these stages, then that should be part of the smalltalkCI config I think.

With regard to build stages, it is currently not easy to persist vm and image from one stage to another. Allowing to run pre/post load/test scripts makes things easier for the average users, power users can still set up build stages and upload and then download what they need to S3 or some other service.

**Comment by estebanlm** [comment]
I don't know what @dalehenrich thinks about it, but I can live with it. 
With one condition: #platforms field should be optional. If not present, it means "just run it": most people does not build portable software, and the need to specify platform is just noise (btw, this applies too to all platforms in SmalltalkCISpec).

**Comment by macta** [comment]
Just a small observation on this - “not easy to persist vm/image from one stage to another” sounds like a Travis issue as GitLab does this out of the box - its an important feature. It doesn’t help with Travis - but possibly worth keeping in mind in case you assess your CI platform.

Tim

**Comment by fniephaus** [comment]
@estebanlm could you have a look at https://github.com/hpi-swa/smalltalkCI/commit/45ad2c1949063c1d7cb2f87a092cccf87daa3bac? Hope this covers your use cases.

**Comment by peteruhnak** [comment]
>  GitLab does this out of the box 
by uploading everything to S3 (or wherever the manager is pointing), which I don't know how well it scales for Pharo as you need to constantly shuffle 50-100MB images

**Comment by macta** [comment]
Hi Peter - I’m not sure if its putting it on S3 - when I look at PharoLambda its just a directive in the yml file (and it seems to preserve caches for weeks if not months).

Just mentioning this in case its useful at some point in the future for you guys.

e.g.

variables:
  VM_DIR: "pharo-vm"
  MIN_DIR: "pharo-min"
  PHARO_CACHE_DIR: "pharo-cache"
  
# add directories to cache between pipeline builds for speeding up builds
cache:
  key: "2017-08-07d" # or see: https://gitlab.msu.edu/help/ci/variables/README.md
  paths:
    - $VM_DIR
    - $MIN_DIR
    - $PHARO_CACHE_DIR

And then for a stage to share results between stages in a build I have the following directive which lets my next stage see what I generated in ./build (and also download artefacts if the build fails (due to “always”)

setup:
  stage: setup
  variables:
      GIT_STRATEGY: none # stop checkout, as just setting up environment
  script:
    - if ! ( ...
artifacts:
  paths:
    - build
  when: always
  # expire_in: 60 minutes

**Comment by peteruhnak** [comment]
Sorry, not S3, but the server where GitLab is hosted, which is usually a different machine than where the GitLab CI is running. And what is more important is that it can be changed only by the admins of the GitLab globally…
