### ISSUE TITLE
Appveyor fails with Error with status code 127 while downloading the latest 60 image

### ISSUE THREAD

**Issue by JurajKubelka** [hpi-swa/smalltalkCI#264]
I have an issue using Appveyor that it fails while downloading the latest 60 image. Now, it is configured with verbose and debug mode, see [.appveyor.yml](https://github.com/JurajKubelka/MQTTCallbackClient/blob/c50da21436241840bdc5fd166e449f6ab473c40f/.appveyor.yml).

```
Downloading the latest 60 Image:
    http://files.pharo.org/get-files/60/pharo.zip
...
Error with status code 127
```
The log is in the attachment [log.txt](https://github.com/hpi-swa/smalltalkCI/files/810609/log.txt) and [on appveyor](https://ci.appveyor.com/project/JurajKubelka/mqttcallbackclient/branch/master).

Is it a bug or a problem of my configuration?
Thanks!

**Comment by fniephaus** [comment]
Could you trigger a new build please to see if the problem is reproducible?

**Comment by JurajKubelka** [comment]
yes, it is reproducible. At least on my projects. I have configured three projects and since then all builds are like that. 

- https://ci.appveyor.com/project/JurajKubelka/mqtt/build/1.0.2/job/059e2v4u7ntlxc19 
- https://ci.appveyor.com/project/JurajKubelka/mqttchat/build/1.0.6
- https://ci.appveyor.com/project/JurajKubelka/mqttcallbackclient/build/1.0.28
- ...and lot of previous builds of those projects.

This answer says that 127 error means a command is missing: http://stackoverflow.com/questions/1763156/127-return-code-from But I did not find any missing command (rm, mv, unzip).

**Comment by fniephaus** [comment]
Thanks for confirming.
This is interesting, especially because it fails in the script provided by Pharo...

**Comment by fniephaus** [comment]
So, after looking at [`view-source:http://get.pharo.org/50`](http://get.pharo.org/50) and [running a test build](https://ci.appveyor.com/project/fniephaus/appveyor-experiments/build/job/49cs526gaiiu9lio), it seems that `unzip` has gone missing. Not sure yet why...

**Comment by JurajKubelka** [comment]
To debug it, I have `  - cmd: '%CYG_BASH% -lc "which curl wget unzip rm mv"'` in the [.appveyor.yml](https://github.com/JurajKubelka/MQTTCallbackClient/blob/c50da21436241840bdc5fd166e449f6ab473c40f/.appveyor.yml). [The log](https://ci.appveyor.com/project/JurajKubelka/mqttcallbackclient/build/1.0.28#L108) shows, that they are present:

```
%CYG_BASH% -lc "which curl wget unzip rm mv"
/usr/bin/curl
/usr/bin/wget
/usr/bin/unzip
/usr/bin/rm
/usr/bin/mv
%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; $SCI_RUN -v --debug"
```

**Comment by fniephaus** [comment]
Well, that's odd. I've opened an issue at https://github.com/appveyor/ci/issues/1356 in the meantime.

**Comment by fniephaus** [comment]
Ok, so apparently it's necessary to also do the following when installing new packages:
> -g --upgrade-also                 also upgrade installed packages

**Comment by JurajKubelka** [comment]
Thanks! I have updated the config and it works. But unfortunately, it does not run any test case. Despite the fact, that Travis does. 

[appveyor log without test cases](https://ci.appveyor.com/project/JurajKubelka/mqttcallbackclient/build/1.0.32)

```
%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; $SCI_RUN $SMALLTALK_CONFIG"
Preparing folders...
Build folder already exists at /cygdrive/c/smalltalkCI-master/_builds.
Starting Pharo build...
Downloading Pharo-6.0 image...
Downloading the latest 60 Image:
    http://files.pharo.org/get-files/60/pharo.zip
Pharo.image
 > Time to run: 5.849s 
Preparing Pharo image...
Downloading Pharo-6.0 vm...
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/60/pharo-win-stable.zip
pharo-vm/Pharo.exe
Downloading PharoV60.sources:
	http://files.pharo.org/get-files/60/sources.zip
Creating starter scripts pharo and pharo-ui
 > Time to run: 14.708s 
Build success
```

[travis log (well, currently Travis faces some outage)](https://travis-ci.org/JurajKubelka/MQTTCallbackClient/builds/206573019)

[GitHub project page](https://github.com/JurajKubelka/MQTTCallbackClient/tree/b0e55e4cd5af48ba08f82a7f54f83e9359b23e6d)

Any idea why the tests are not executed?

**Comment by fniephaus** [comment]
There's a lot of odd things going on at the moment.
For some reason, this build was flagged successful even though one job failed:
![image](https://cloud.githubusercontent.com/assets/2368856/23502294/986e0886-ff37-11e6-8f77-a3df130578ab.png)
