### ISSUE TITLE
AppVeyor builds are failing for Pharo

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#266]
The Fuel builds on AppVeyor have started failing for Pharo. I've attached the log for one of the builds (all fail for the same reason). The last successful build was on November 21, the first failing on March 5 (but I never built in between, so I can't give you a more precise date).

[log.txt](https://github.com/hpi-swa/smalltalkCI/files/853466/log.txt)

**Comment by fniephaus** [comment]
Hi @theseion,
Please make sure you use `-dgnqNO` in your `.appveyor.yml` to install `unzip` (see [here](https://github.com/hpi-swa/smalltalkCI/commit/3219ee91830bbd212735611e6fe9291655a37bb0)).
It was actually AppVeyor who changed something recently.
Unfortunately, they don't offer the same level of integration as TravisCI, so I can't update this for everyone.
Please reopen the issue if this didn't solve your problem!

**Comment by theseion** [comment]
Perfect, thanks!
