### ISSUE TITLE
add support for threaded heatbeat VM on Pharo

### ISSUE THREAD

**Issue by estebanlm** [hpi-swa/smalltalkCI#269]
I think we can benefit from:

http://get.pharo.org/vmT60
http://get.pharo.org/vmTLatest60

who were added to Pharo zeroconf. 
they are just available for now for Pharo 6.0 but they can be backported to 5.0 too :) 

Maybe a flag?

**Comment by fniephaus** [comment]
I'm not sure this is still relevant, closing this for now. Please reopen if this is still something we should work on.
