### ISSUE TITLE
Coverage should strip full file path

### ISSUE THREAD

**Issue by JurajKubelka** [hpi-swa/smalltalkCI#273]
It is not possible conveniently browse source code using Coveralls.io, because links to source code includes full file paths. For example instead of having only `src/Discord-Core.package/DSDataWebhookPost.class/instance/asDiscordJSONObject.st`, it is `/Users/travis/build/JurajKubelka/DiscordSt/src/Discord-Core.package/DSDataWebhookPost.class/instance/asDiscordJSONObject.st`. 

See example on [coveralls.io](https://coveralls.io/builds/11130281/source?filename=%2FUsers%2Ftravis%2Fbuild%2FJurajKubelka%2FDiscordSt%2Fsrc%2FDiscord-Core.package%2FDSDataWebhookPost.class%2Finstance%2FasDiscordJSONObject.st) or the following screenshot:

![captura de pantalla 2017-04-19 a la s 05 06 09](https://cloud.githubusercontent.com/assets/465505/25169678/3c795eca-24be-11e7-8383-f6c8c24dde62.png)

**Comment by fniephaus** [comment]
Whoops, that used to work correctly. Thanks for opening the issue!

**Comment by Uko** [comment]
Another issue is that the files from Linux builds have paths like

    /home/travis/build/Uko/Renraku//Renraku.package/ReAbstractCritique.class/instance/actions.st

and the ones from Mac:

     /Users/travis/build/Uko/Renraku//Renraku.package/ReAbstractCritique.class/instance/actions.st

So even if you specify the _Git repo root directory` you have duplicated files and one of each pair is not browsable

**Comment by fniephaus** [comment]
This was recently fixed.
