### ISSUE TITLE
Travis doesn't warn about missing classes / package loading issues

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#275]
I'm not 100% sure what part to blame, but normally when in Pharo I try to load package whose classes depend on classes from another package I get a warning window
![warn](https://cloud.githubusercontent.com/assets/1276328/25305885/bc1e5938-2783-11e7-9646-60f18214cb3e.png)

when running from command line, this information used to be written to stdout (or stderr), but I don't see anything of the sorts in travis log https://travis-ci.org/OpenPonk/uml-bootstrap-generator/builds/224701875 (resp. https://s3.amazonaws.com/archive.travis-ci.org/jobs/224701876/log.txt )

This is easy mistake to make but in the log there is no hint of this.
How come Travis just blasts past the issue and happily carries on? Supressing warnings? This should be imho a build-failing error (update: I was told that Moose would fail work at all if this would be error instead of warning).

**Update:**
It seems that Pharo must be running in some weird way, because normally this information is in the log

https://ci.inria.fr/moose/job/moose-6.1/696/console

```
*** Warning: Warning: This package depends on the following classes:
  RTMondrianViewBuilder
You must resolve these dependencies before you will be able to load these definitions: 
  RTMondrianViewBuilder>>#mooseFinderMondrianExamplesIn:
```

maybe (not) running it in headless mode can affect this

apparently moose has the correct output: https://travis-ci.org/moosetechnology/Moose/jobs/152646059 (line 1559)

**Update 2:**

I've made a test project https://github.com/peteruhnak/travis-load-issue where `BrokenChild` is subclass of `BrokenParent`, and each class is in their own package (of the same name).

In the `BaselineOfBrokenFamily` I load only `BrokenChild`; travis will load the project and run the test, which will fail on missing class (because BrokenParent is missing, so BrokenChild was not load), but I don't see any warning as was the case with moose earlier https://travis-ci.org/peteruhnak/travis-load-issue/builds/224713032

**Comment by dalehenrich** [comment]
There are two [metacello load spec options](https://github.com/hpi-swa/smalltalkCI#scimetacelloloadspec) that you want to look at:

```
  #onWarningLog : true,                               // Log Warning messages to Transcript
  #failOn : [ #OCUndeclaredVariableWarning ],         // Fail build on provided list of Warnings
```

If you set onWarningLog, then all Warnings will be dumped to the Transcript, which I think is dumped to stdout in a headless run ...

If you have a unique Warning class being triggered (and I think that it might be unique in this case) you can speciffy that the build fails when that warning is raised ...

**Comment by peteruhnak** [comment]
Thanks Dale! I will play around with it. (and this also solves the problem for me)
