### ISSUE TITLE
Specifying custom travis commands between smalltalkCI operations

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#278]
Is it possible to do extra stuff between smalltalkCI steps?

Specifically

* between "project being loaded via baseline" and "tests run"
* after "run completed" but before "after_success" or "after_failure" (because I want to run extra tests that could fail the build

**Comment by fniephaus** [comment]
This sounds related to #259. Something like it should exists in the foreseeable future. But I don't have time to work on this at the moment unfortunately (maybe in two months). Contributions are welcome...

**Comment by peteruhnak** [comment]
yeah, this looks like a a duplicate then; i will comment there
