### ISSUE TITLE
Pharo-stable misconfigured?

### ISSUE THREAD

**Issue by kursjan** [hpi-swa/smalltalkCI#282]
I am getting a problem with pharo-stable configuration:

```
Downloading PharoV50.sources:
	http://files.pharo.org/get-files/50/sources.zip
Creating starter scripts pharo and pharo-ui
'Pharo cannot locate the sources file named /home/travis/smalltalkCI-master/_cache/vms/Pharo-stable/pharo-vm/PharoV60.sources.

Please check that the file is named properly and is in the same directory as this image.'
```
Works fine with Pharo-5, Pharo-6, Pharo-alpha.

See this link](https://travis-ci.org/kursjan/petitparser2/jobs/239535587) for more details.

**Comment by fniephaus** [comment]
@estebanlm why is `Pharo-stable` looking for `PharoV60.sources`? Is stable now v6?

**Comment by kursjan** [comment]
indeed: [http://pharo.org/news/pharo6.0-released](http://pharo.org/news/pharo6.0-released)

**Comment by fniephaus** [comment]
I know about the release, but I wasn't sure when the links will be updated. Let's see if https://github.com/hpi-swa/smalltalkCI/commit/9f6626593f22801e21eb0d53cb54662ff83d82c9 fixes the problem...

**Comment by estebanlm** [comment]
yes, Pharo 6 is stable now, and it has new sources :P 
btw... since Pharo7 is bootstrapped, each development version will come with a brand new sources file and an empty changes (instead an empty sources and a huge changes). They will come in the distribution zip so I hope it will not be a problem for smalltalkCI?

**Comment by fniephaus** [comment]
Shouldn't be a problem. Just keep me informed and send me some links when ready :)

**Comment by fniephaus** [comment]
@kursjan could you restart your build and try again please?

**Comment by kursjan** [comment]
works fine, thanks!
