### ISSUE TITLE
Smalltalk CI fails for Pharo 6 on Mac

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#284]
Hi, I cannot figure out what is wrong, but my mac builds exit with 

```
Error with status code 56:
155 pharo::prepare_image /Users/travis/smalltalkCI-master/pharo/run.sh
282 run_build /Users/travis/smalltalkCI-master/pharo/run.sh
608 run /Users/travis/smalltalkCI-master/run.sh
638 main /Users/travis/smalltalkCI-master/run.sh
653 main /Users/travis/smalltalkCI-master/run.sh
===================================================================
config_clean=false
config_debug=false
config_headless=true
config_image=
config_smalltalk=Pharo-6.0
config_ston=/Users/travis/build/Uko/Renraku/.smalltalk.ston
config_tracking=true
config_verbose=false
config_vm=
The command "$SMALLTALK_CI_HOME/run.sh" exited with 56.
Done. Your build exited with 1.
/Users/travis/.travis/job_stages: line 152: shell_session_update: command not found
```

Is it some kind of misconfiguration or there is a bug?

**Comment by fniephaus** [comment]
Could you provide a link to the build please?

**Comment by fniephaus** [comment]
Found it at https://travis-ci.org/Uko/Renraku/jobs/247417964.
Could you restart it please? Looks like pharo.org was not responding correctly...

**Comment by Uko** [comment]
@fniephaus thanks, it worked. Sorry for bothering you, but the problem persisted for a couple of days, so I thought that it's something on the SmalltalkCI side

**Comment by Uko** [comment]
@fniephaus I'm still experiencing failures of this kind from time to time. Is this something that has to be addressed on the SmalltalkCI side, or on the pharo.org side? If it is the later one can you give me some hints of what is the problem, so I can try to fix that?

**Comment by fniephaus** [comment]
Can you provide some more links, so I can have a look?

**Comment by fniephaus** [comment]
https://github.com/hpi-swa/smalltalkCI/issues/289 might be related. Has pharo.org moved to a different server recently?

**Comment by peteruhnak** [comment]
Pharo (files.pharo.org) ran out of space (~2 weeks ago) and was moved somewhere else iirc (S3 or some other service).

**Comment by Uko** [comment]
This has not happened to me again, and I've refreshed all the failed builds. So probably we should close this issue, and in case I will have the problem again, I will keep the build.
