### ISSUE TITLE
Running SmallLint as a a part of testing

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#287]
Hi, sorry if this question should not go here, but I've read the SmalltalkCI documentation and the Travis documentation and could not find any information. I want to run some SmallLint quality rules on my code and produce a nice output. Where should I start? I suppose I need to add one more Travis step? Or should I create something in SmalltalkCI?

I'd be thankful for any pointers because I really don't know where to start.

**Comment by fniephaus** [comment]
Do Pharo images ship with SmallLint? Do you have an example of how you can run it in a workspace/playground?

**Comment by MrModder** [comment]
This should be achievable by using [custom scripts](https://github.com/hpi-swa/smalltalkCI#custom-scripts) in your .smalltalk.ston .
