### ISSUE TITLE
Pharo-alpha config seems to be broken

### ISSUE THREAD

**Issue by kursjan** [hpi-swa/smalltalkCI#289]
My `pharo-alpha` configurations seems to to be failing [because of some configuration issue](https://travis-ci.org/kursjan/petitparser2/jobs/250096029#L345).

**Comment by fniephaus** [comment]
Thanks, @kursjan. We are working on it, should be fixed within the next 24h :)

**Comment by fniephaus** [comment]
Not sure what exactly caused your problem, but currently everything seems to be working reliably. Please reopen if this happens again.
