### ISSUE TITLE
Combined GemStone/Squeak/Pharo tests?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#29]
In my tests for [GsDevKit_home](https://github.com/GsDevKit/GsDevKit_home/blob/dev/tests/basicInstallServer.sh), I expect to run both a Pharo (and someday Squeak) client and a GemStone server using this [travis.yml](https://github.com/GsDevKit/GsDevKit_home/blob/dev/.travis.yml)  .. the tests are primarily run through the pharo client, but I need to install code into both GemStone and Pharo (and someday Squeak) ...

So I'm wondering what the .travis.yml file for such a beast would look like ... the code that would be loaded into the client and server could be present in the same repository so being able to specify as much as possible in the .travis.yml file would be an advantage ... 

if not within scope then being able to run custom scripts to accomplish would be okay ... but in this case it would be nice to go through the smalltakCI api rather than have to create similar functionality from scratch ...

**Comment by fniephaus** [comment]
Interesting, so you basically need to run two different vms at the same time, right?

I'd probably just set up the server manually via `before_script:` and then run the client tests as usual.
Or are there server-side tests as well? Then you could probably also copy smalltalkCI to a different directory and run it twice at the same time, for the server and for the client.
At the moment, you could probably already use smalltalkCI with `sudo: true`, but this all should get easier once #28 is implemented. Not sure how fast we can get this done though.

**Comment by dalehenrich** [comment]
As I think about (and learn about smalltalkCI is put together) I think that I'll be able to do just fine using  [GsDevKit_home](https://github.com/GsDevKit/GsDevKit_home/blob/dev/tests/basicInstallServer.sh) ... `GsDevKit_home` itself downloads and installs Pharo into a known location ... I had thought that Pharo and Squeak and the vms themselves were built into the smalltalk container but that appears to not be the case? ... I may play with the [dependency caching](https://docs.travis-ci.com/user/migrating-from-legacy/#How-Do-I-Cache-Dependencies-and-Directories%3F) for the GemStone downloads and pharo downloads, to cut down on download times, but that optimization isn't strictly necessary ... I'll try using `sudo:true` until the shared memory is taken care of

**Comment by fniephaus** [comment]
You are right, smalltalkCI will download the corresponding vm for each build while the [`smalltalk.rb`](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/smalltalk.rb) only installs packages and sets up and runs smalltalkCI.
Dependency caching is one of the benefits of using the new infrastructure and this might be a good use-case for it.

**Comment by fniephaus** [comment]
With the new STON configuration file, it should be possible to reduce the overhead a lot.
This still needs to be a GemStone build and then you should be able to overwrite `script` in your `.travis.yml` like this:

```yml
script:
  - $SMALLTALK_CI_HOME/run.sh
  - $SMALLTALK_CI_HOME/run.sh -s Pharo-5.0
  - $SMALLTALK_CI_HOME/run.sh -s Squeak-5.0
```
You'd need to make sure that GemStone is running while the clients tests are running, but we can't test the above anyway at them moment because of #28.

**Comment by dalehenrich** [comment]
Okay ... this is starting to make sense ... hopefully this next round of fixes will let me start doing builds again:) and then I can start experimenting ...

**Comment by dalehenrich** [comment]
I don't think this issue is applicable ... right now
