### ISSUE TITLE
Headful Pharo stuck on "Preparing Pharo image..."

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#290]
I have a test failure on one of my projects Ihttps://travis-ci.org/Uko/Renraku/jobs/250298717) and when I try to reproduce this with `./run.sh -s Pharo-6.0 --headful ../Renraku/.smalltalk.ston` the build is stuck on "Preparing Pharo image..." stage and the image is open and nothing is happening

**Comment by Uko** [comment]
Update: it looks like the evaluation is not working. When I add breakpoints or do something in the `load_project` or `test_project` functions, nothing happens in the image. It is just open and nothing else happens

**Comment by Uko** [comment]
Aha, it also loads the local config. I have to take a look at that

**Comment by Uko** [comment]
Ok, I've added an option to skip loading default preferences when running Pharo scripts in pull request #292. I actually had a clash of scripts…

**Comment by fniephaus** [comment]
You could also try `./run.sh -s Pharo-6.0 --debug --headful ...`, which adds breakpoints automatically.
Also, in headful mode, the image needs to be closed manually at the moment I think, which allows you to inspect the image after smalltalkCI has run.

**Comment by Uko** [comment]
Yes, I tried that. But as I wrote, the problem was in the things that I was loading as a part of my startup process and I didn't take that into account
