### ISSUE TITLE
Smalltalk CI not loading the current version present in gitfiletree repo

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#293]
The concrete case can be experienced when running SmalltalkCI on https://github.com/Uko/Renraku/tree/forced-rules

It supposedly loads the latest version of `Renraku-Test` because the logs have this line:
    
    Loaded -> Renraku-Test-cypress.1 --- filetree:///Users/uko/Downloads/Renraku-forced-rules [:] --- cache

but when I check the changes of Renraku-Test with the `filetree:///Users/uko/Downloads/Renraku-forced-rules` repo afterwards, it finds a lot of changes, and in fact, Renraku-Test is not updated to the latest version. I tried to debug this, but everything looks fine until I reach Metacello loading mechanism, and then it gets super complicated to debug.

**Comment by Uko** [comment]
Ok, now I tried to manually load the changes from filesystem with
```
Metacello new
	repository: 'filetree://path/to/repo';
	baseline: 'Renraku';
	load
```
and I get a conflict while trying to merge. Can this be the issue? Can I force-load a package? I have no idea why there is a conflict, but maybe the metadataless format screws something up

**Comment by fniephaus** [comment]
Have you tried with `#onWarningLog : true` or `#useLatestMetacello : true`?

See: https://github.com/hpi-swa/smalltalkCI#scimetacelloloadspec

**Comment by Uko** [comment]
Yes, I've tried many options. Actually this one: https://travis-ci.org/Uko/Renraku/jobs/250653907 is with `#onWarningLog : true` and `#useLatestMetacello : true`. And I don't see any warnings in the log…

**Comment by fniephaus** [comment]
Mh, interesting..will have a look soon...

**Comment by Uko** [comment]
Looks like the packages are getting dirty during loading, and this causes problems. I'll try to change them to "unmodified" during a pro-commit hook and see if it works. But this looks like a strange MC behavior (or I used too much of a black magic somewhere).

**Comment by theseion** [comment]
I've analyzed the problem. It's a combination of unfortunate logic in Monticello and exception handling in SmalltalkCI. @fniephaus, you can mark this issue as bug and I'll provide a PR with a fix and complete description of the problem.

**Comment by theseion** [comment]
See https://github.com/pharo-project/pharo/pull/163 for the fix to Monticello.

(@fniephaus I don't have permission to alter an issue, you'll have to change the tag from "question" to "bug" yourself. Apparently, only maintainers are aloud to do that.)

**Comment by theseion** [comment]
Fixed with https://github.com/hpi-swa/smalltalkCI/pull/300/commits/3e270c37bd7db98390275f5a423206fabb270e85.

**Comment by Uko** [comment]
@theseion now I have other issues :). If you look at this job: https://travis-ci.org/Uko/Renraku/builds/253139160 only the builds for Pharo 6 are failing. But for Pharo 7 there are only 12 tests (other tests are not loaded). I.e. the project is not loaded. When I run the build manually on a local machine and execute 

    Metacello new
	repository: 'filetree://path/to/repo';
	baseline: 'Renraku';
	load

I get an error 
> MetacelloConflictingProjectError: Load Conflict between existing BaselineOfRenraku [baseline] from filetree:///Users/uko/Downloads/Renraku-development/ and BaselineOfRenraku [baseline] from filetree:///Users/uko/Downloads/Renraku-development

which happens in `MetacelloScriptOwner>>#handleConflict:`. And even if I add the `onConflictUseIncoming` option it does not crash, but does not load the new version of the packages

**Comment by theseion** [comment]
This is a different issue: https://github.com/hpi-swa/smalltalkCI/issues/305
