### ISSUE TITLE
Change to WebMessage breaks configuration loading

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#294]
> The change by Tobias (03-07-2017) to WebMessage>>getContentWithProgress: breaks loading of configurations. They are gzip encoded but that is never being considered if a converter is set. The binary stream will then be decoded as string which fails.

http://forum.world.st/Change-to-WebMessage-breaks-configuration-loading-smalltalkCI-td4953674.html

/cc @theseion

**Comment by krono** [comment]
Wait for @theseion to concur that  WebClient-Core-topa.108 fixes this

**Comment by theseion** [comment]
Yes, that fixes the problem. Thanks!
