### ISSUE TITLE
working with additional resources like images

### ISSUE THREAD

**Issue by Nef10** [hpi-swa/smalltalkCI#30]
In our project [HPI-BP2015H/squeak-parable](https://github.com/HPI-BP2015H/squeak-parable) we are using images. They need to be copied to the correct directory, so on Travis the [build](https://travis-ci.org/HPI-BP2015H/squeak-parable/jobs/100099398) is failing. 

When I copy the files to the correct directory (see [here](https://github.com/HPI-BP2015H/squeak-parable/pull/2/files)) the [build](https://travis-ci.org/HPI-BP2015H/squeak-parable/jobs/100103694) fails because I have already created the ```${SMALLTALK_CI_BUILD}``` directory.

Is there a better solution to store images or get them into the right directory or should we just check do a short check before creating the ```${SMALLTALK_CI_BUILD}``` directory?

**Comment by fniephaus** [comment]
Ah, that *is* a problem. It's probably best to set something like this up via `before_script` like you tried to.

Is it enough to let smalltalkCI not fail when the folder already exists? Can you double check locally?
Here's the line of interest:
https://github.com/hpi-swa/smalltalkCI/blob/d8d0d702b478ff4c6ddd22aa2b2d22acde65980b/run.sh#L306

**Comment by fniephaus** [comment]
Could you please restart the build and try again? If it's not working, please reopen the issue.

**Comment by Nef10** [comment]
Works, thanks :)
