### ISSUE TITLE
Pharo 7.0 changed stdout management

### ISSUE THREAD

**Issue by guillep** [hpi-swa/smalltalkCI#316]
Hi,

In Pharo 7 stdout and in particular streaming management changed a bit. Previously, cr characters were converted automatically to the platform specific new line character combination (cr, lf or crlf).

SmalltalkCI is using as stdout an old stream that does not do this conversion anymore. And because of this the output is messed up. This can be seen here:

https://travis-ci.org/guillep/OSSubprocess/jobs/283096622

The solution to this is to wrap std streams with a `ZnCrPortableWriteStream`. This is however valid only for Pharo 7 and not previous versions :).

I can do the change, but I'd like to know what is the recommended way to do it. Should I put something like

`self isPharo7 ifTrue: [ ... ] ifFalse: [ ... ]`

or there is some other way you'd like to do it?

**Comment by fniephaus** [comment]
Hi @guillep,
Thanks for the info! smalltalkCI uses `SmalltalkCI class>>stdout` for the output and the [specialized version for Pharo](https://github.com/hpi-swa/smalltalkCI/blob/25862f93367e0cb886485be68a6d173e4176cf79/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/class/stdout.st) already performs different checks. So I'd say it's reasonable to extend [`SmalltalkCIPharo class>>stdout`](https://github.com/hpi-swa/smalltalkCI/blob/25862f93367e0cb886485be68a6d173e4176cf79/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/class/stdout.st) if you agree. Feel free to extract methods if it helps readability :)

**Comment by guillep** [comment]
Sure, I saw that. My question was wether it was better to have one platform class per pharo platform or a single Pharo platform class for all of them. Or maybe I could implement SmalltalkCIPharo70 subclass of SmalltalkCIPharo, if there are no objections.
