### ISSUE TITLE
Pharo 6.1 configuration uses pharo 6.0 vm

### ISSUE THREAD

**Issue by guillep** [hpi-swa/smalltalkCI#319]
Pharo 6.1 is using a two month older vm than the one released. From the log we have:

```
Downloading the latest pharoVM:
	http://files.pharo.org/get-files/60/pharo-mac-stable.zip
```

while it should download it from http://files.pharo.org/get-files/61/pharo-mac-stable.zip

**Comment by fniephaus** [comment]
I'm not always on top of things with regard to Pharo, so this project relies on contributions like this. Happy to merge 3ebd2f09f7f84d0cf9bfe4458805e1ee7a8de8e2 if you could open a PR...thanks!
