### ISSUE TITLE
Coveralls generation support for Tonel

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#325]
Pharo has a new file format Tonel ( https://github.com/pharo-vcs/tonel , example https://github.com/estebanlm/MUDClient/blob/master/src/MUDClient-Plugin-Filter/MUDFilter.class.st ) which has file-per-class, instead of file-per-method.

So the coveralls computation will need to be adapted to that. And speaking of that, do we really want to read the actual file names? Why not consider the namespace/classname/methodname as the "file name" instead of looking at the actual disk? I do not know the other platforms (Gemstone, ...) so maybe it makes more sense there.

**Comment by fniephaus** [comment]
Yes, a new output format is required to make coverage testing work. But first, we need Tonel support in smalltalkCI and I have no idea how it is supposed to work.
I didn't understand your filename/disk access concern, but coveralls can only display the covered/uncovered lines in files correctly if the right filename is provided.

**Comment by peteruhnak** [comment]
> but coveralls can only display the covered/uncovered lines in files correctly if the right filename is provided

Oh, it links them together. Makes sense now. :)
I've created a separate issue for tonel support #326

**Comment by gcotelli** [comment]
@fniephaus I think the pull request is ready. @peteruhnak if you have some repos in Tonel format, can you test them against  gcotelli/smalltalkCI and let me know if the coverage worked?

**Comment by peteruhnak** [comment]
@gcotelli I've just tried, but the project failed to load... is the tonel support in that branch?

**Comment by gcotelli** [comment]
It should be. I branched after adding tonel support. Do you have some log
with the failure?

**Comment by gcotelli** [comment]
@peteruhnak I think you need to change
```
smalltalk_edge:
  source: gcotelli/smalltalkCI
branch: dev
```
to
```
smalltalk_edge:
  source: gcotelli/smalltalkCI
branch: master
```
because I landed the changes in the master branch of my repo

**Comment by peteruhnak** [comment]
Yeah, sorry, I don't know where I read to use dev branch.
It seems to be working well, as far as I can tell, and as far as the data source itself goes (#362 ).

This also made Coveralls much more useful, as one can now see coverage for individal classes, as well as see the classes themselves ( https://coveralls.io/builds/16419933 ), instead of a nearly-infinite 0 or 100% method list :)

Thanks a lot!

**Comment by gcotelli** [comment]
Class side methods must be working, (at least in Tonel) because I contemplated it in the code and see some examples of it in my own code. 

But extension methods are another story. I couldn't figure it out how to detect such cases  with the information available at the export time, so for now just ignored it.

**Comment by cdlm** [comment]
shouldn't this issue be closed, since it looks like @gcotelli 's PR was merged ?

**Comment by fniephaus** [comment]
I think you are right :)
