### ISSUE TITLE
Clean up support for Tonel in smalltalkCI

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#326]
(prerequisite for #325)

Tonel should be just another MCRepository, so in principle it shouldn't be too difficult.
However Tonel has to be loaded into the image before we attempt to load the project.
I don't know if it will autodetect, or if we will need to explicitly state a load strategy in the spec. @estebanlm  should know.
I will be looking at Tonel this weekend, so I will (have to) play with SmalltalkCI support too.

**Comment by fniephaus** [comment]
Support could be added by a new (loading spec](https://github.com/hpi-swa/smalltalkCI#project-loading-specifications), maybe even a subclass of `SCIMetacelloLoadSpec`.

**Comment by estebanlm** [comment]
I guess having SmalltalkCI working with Tonel is just matter of having Tonel loaded and latest metacello version? If so, probably the simplest way to do this is to add tonel as dependency for Metacello for Pharo. 
Then you use load latest metacello option.
btw, this is true just on Pharo 5 and 6 (tonel should work for Pharo 4 and 3 too but I didn't tested it... Pharo 7 already has correct metacello and tonel version and I will backport it to Pharo 6.1 next week.

**Comment by fniephaus** [comment]
That's one way to solve the problem, but then you might load Tonel even for projects that don't use it and that'd unnecessary delay builds. I believe it would be cleaner to add a `SCITonelLoadSpec` which subclasses from `SCIMetacelloLoadSpec`. It behaves the same way, but also ensures that Tonel is loaded.

**Comment by estebanlm** [comment]
> On 22 Oct 2017, at 17:56, Fabio Niephaus <notifications@github.com> wrote:
> 
> That's one way to solve the problem, but then you might load Tonel even for projects that don't use it and that'd unnecessary delay builds. I believe it would be cleaner to add a SCITonelLoadSpec which subclasses from SCIMetacelloLoadSpec. It behaves the same way, but also ensures that Tonel is loaded.
> 

tonel is super small. 
also, it would load it just for Pharo, which is probably desirable.

for me, subclassing SCIMetacelloLoadSpec is incorrect because tonel is a file format (as is filetree), its relation with metacello is just that metacello now understands “tonel” repositories, (as it understands filetree repos and mcz repos, etc.)
So I disagree is cleaner… in anycase, one could extend SCIMetacelloLoadSpec to say “load also tonel”… but in the short term tonel will be the default file format for pharo so it has sense to load it by default (it will be on newer versions anyway).

**Comment by peteruhnak** [comment]
Tonel is small, but Metacello (well, updating it) is not.

But I agree that subclassing makes little sense for the future, as it is already part of Pharo 7.

If tonel will be backported to 6.1, then I would recommend just waiting and then allowing tonel only for 6.1 and 7 -- that way no extra update/installation will be needed in SmalltalkCI.

**Comment by fniephaus** [comment]
Agreed, having to update Metacello to get Tonel support will be very expensive time-wise and you've convinced me that a subclass is not a clean solution either.
Maybe a fallback approach is good enough if compatibility to Pharo3/4/5 is needed? As in: load Tonel and retry again if loading the project has failed because the format could not be read.

**Comment by peteruhnak** [comment]
Well in that case we could add to SCI a check that this file exists and is set to tonel https://github.com/estebanlm/MUDClient/blob/master/src/.properties

**Comment by fniephaus** [comment]
@estebanlm would that be an option?

**Comment by estebanlm** [comment]
yes, that would work

**Comment by fniephaus** [comment]
Ok, cool. Well that should be relatively easy to implement by extending [`SCIMetacelloLoadSpec`](https://github.com/hpi-swa/smalltalkCI/tree/8c9f2af707941254aa661c3d5c9637405e24b9e6/repository/SmalltalkCI-Core.package/SCIMetacelloLoadSpec.class)...could you have a look at this, @peteruhnak?

**Comment by peteruhnak** [comment]
Yes, I will have a look during the weekend after Tonel is in 6.1 (so probably this weekend :)).

**Comment by peteruhnak** [comment]
So I actually cannot contribute on this, because I have no idea how to commit the change without all metadata being completely ****** up (I am using regular filetree). 😐 @estebanlm any ideas?

**Comment by peteruhnak** [comment]
Never mind, I've managed to commit the Pharo code from Squeak. 😆 But there is really something strange with metadata in Pharo.

**Comment by juliendelplanque** [comment]
Hello,

What is the state of this issue? Any progress?

I have a repository in Tonel format and I would like to set up Travis CI for it, is it possible now?

Thanks in advance,

Julien

**Comment by fniephaus** [comment]
Hi @juliendelplanque,
Sorry for the slow response. @peteruhnak, what needs to be done to support Tonel to smalltalkCI?

**Comment by fniephaus** [comment]
Hi @juliendelplanque,
Sorry for the slow response. I was hoping that @peteruhnak would comment on this.
What needs to be done to support Tonel to smalltalkCI, Peter? As in, how can Tonel be installed and used? I assume Pharo-only?

**Comment by dalehenrich** [comment]
Well this should just be a Pharo/GemStone issue ... eventually Tonel repositories should be differentiated from FileTree repos and then the loads will happen without any need for special code in SmalltalkCI ...

**Comment by peteruhnak** [comment]
I stopped working on this because I was waiting for the latest metacello/Tonel to be packported to Pharo 6.1 (and `#useLatestMetacello` wasn't working well with at  the time, so either it was working in one verseion, or the other)

But now it seems that tests are finally green on both P61 and P7 ( https://travis-ci.org/peteruhnak/pharo-changes-builder/builds/355249672 ) , so I'll send you PR today

**Comment by juliendelplanque** [comment]
Ok thank you all for your answers 😄

Thanks @peteruhnak for this PR!

**Comment by fniephaus** [comment]
If you have used smalltalkCI locally before, just do `bin/smalltalkci -s Squeak-5.1 --headful some.ston`.
Otherwise, you need the latest Metacello and then load smalltalkCI manually.

**Comment by peteruhnak** [comment]
Sorry, I meant how to load SmalltalkCI code inside Squeak (I cannot commit from Pharo, because it generates obscene amount of metadata changes).

**Comment by fniephaus** [comment]
smalltalkCI bootstraps itself before loading and testing any Squeak project. That's why you can pretend to test any of your projects, but actually working on smalltalkCI's code if that makes sense.
You could also send me a change set and I'll take care of the rest...

**Comment by peteruhnak** [comment]
Ah, I see.

Well the code is here https://github.com/peteruhnak/smalltalkCI/commit/413e6a59b30e869ab49c4b50b7eb0539f1d696a0

Since I wrote the code, the way projects are loaded has changed slightly, so `loadRepository` should instead by called `filetreeRepositoryIn:` (or something like that... maybe the name is confusing if it loads tonel instead)

Basically the code checks whether there's `.properties` file in the root of the repository, and that the file has `#format` set to `#tonel`. If true then tonel, otherwise filetree.

(`.properties` = `IceRepositoryProperties propertiesFileName`)

**Comment by peteruhnak** [comment]
You need to specify the file format, and by default you load it via `filetree://`.

In theory a new scheme (e.g. `local://`) could be introduced that would autodetect the format and transform it to `filetree://` or `tonel://` (or something else).. but that's for @dalehenrich to decide if that make sense.

Until then, we need to detect it explicitly.

**Comment by fniephaus** [comment]
Ah, right. Thanks, @peteruhnak. I'll have a look :)

**Comment by dalehenrich** [comment]
Yeah, the long term plan is that `filetree://`will check the `.properties` to determine the format and switch the proper reading ... I know that @estebanlm had plans to make the changes and it looks like only a part of the changes got made ... so far ... I haven't looked at the PR yet. but presumably that' what you (@peteruhnak) are doing? I'm a bit surprised that this code isn't just included in the Pharo release since I assume that this would be useful beyond Sm,alltalkCI ...

**Comment by peteruhnak** [comment]
@dalehenrich in Pharo the check is done by Iceberg, not Monticello (iirc), but SmalltalkCI is not using iceberg.

Nevertheless as I mentioned, I find it strange that `filetree://` would be polymorphic format considering at the moment it already means a concrete format... autodetection for `local://` makes much more sense to me.

**Comment by dalehenrich** [comment]
@peteruhnak using `filetree://` is only a backward compatibility measure. `filetree://` has always supported multiple disk formats (there were 6 or so different formats in the very beginning) and my plan was to eventually support file/class and file/package and file/project formats under the filetree name. Esteban released Tonel into the wild without a lot of discussion with me (okay no discussion), so in my mind the release was premature and I could have forecast these issues. However, what's done is done, so Esteban and I have discussed alternate schemes and something along the lines of `local://` is part of the plans ... of course neither Estaban nor I have the time to implement these new schemes (another problem that I would have forecasted), so we are stuck with the mess ...  that we have ...

With all of that said, I would suggest that the changes be made in Filetree for pharo6/7 to recognize the tonel format repos then regular developers will be able to load tonel format repos into their pahro6/7 images as well as on SmalltalkCI and then SmalltalkCI wouldn't require any special code ....

**Comment by seandenigris** [comment]
@peteruhnak: "in Pharo the check is done by Iceberg, not Monticello (iirc), but SmalltalkCI is not using iceberg."
Would it work as is if Iceberg Metacello integration was enabled?
@dalehenrich: "the long term plan is that filetree://will check the .properties to determine the format and switch the proper reading"
I assume the same would apply if the project was loaded from a remote (e.g. `github://`), correct?

**Comment by peteruhnak** [comment]
@seandenigris it might work if you enable metacello integration and force load it through iceberg... but there were other issues last time (~months ago) I've tried that

@fniephaus I think it makes sense to add the support for SmalltalkCI and remove it once it has made its way to Pharo, so the adoption of tonel is not further needlessly delayed.

**Comment by fniephaus** [comment]
@peteruhnak: @gcotelli provided https://github.com/hpi-swa/smalltalkCI/pull/363 which adds Tonel support for Pharo through smalltalkCI. Could you please give this a go and confirm that everything works as intended?

I'm reopening this issue, so we don't forget to remove this "workaround" as soon as Tonel is properly integrated into Metacello.

**Comment by peteruhnak** [comment]
@fniephaus thanks! I'm getting green tests both for Pharo 6.1 and 7.
Now #325 can be addressed.

**Comment by fniephaus** [comment]
@peteruhnak great! and sorry for the delay.

**Comment by estebanlm** [comment]
by the way, at the moment I didn't have the time (when @dalehenrich commented) but now support for tonel is integrated into metacello and using  filetree, github, etc. will work regardless the format of the repository.

**Comment by fniephaus** [comment]
> by the way, at the moment I didn't have the time (when @dalehenrich commented) but now support for tonel is integrated into metacello and using filetree, github, etc. will work regardless the format of the repository.

Does that mean #363 can be reverted or what needs to be done?

**Comment by estebanlm** [comment]
I guess so, yes. 
What does @gcotelli thinks?

**Comment by gcotelli** [comment]
If the new metacello version can figure out the project type parsing the properties file and can load tonel code using filetree:// in that case, I think we can revert the changes in #363.
As far as I understand this is what the new metacello is supposed to do, so go for reverting #363 changes.

**Comment by peteruhnak** [comment]
Isn't this only for newer Metacello that is _not_ in P6.1?

**Comment by estebanlm** [comment]
in P6.1+ you are ok I think (I do not remember)
otherwise, `useLatestMetacello` should made the trick.

**Comment by estebanlm** [comment]
in fact no.
I just realised Tonel version of P6.1 is old and I will need to backport latest :/ 
Otherwise you need to first update P6.1

**Comment by fniephaus** [comment]
Ok, let's keep the workaround for the time being. Please update this issue when the backport has happened.

**Comment by estebanlm** [comment]
I just back ported Tonel 1.0.9 to Pharo 6.1 so everything should be ok.
Version previous to 6.1 needs to update Tonel by themselves (in a preLoad)
