### ISSUE TITLE
`Pharo64-6.1` does not use Pharo-6.1 vm

### ISSUE THREAD

**Issue by jbrichau** [hpi-swa/smalltalkCI#337]
I noticed that using `Pharo64-6.1` uses the latest image but does not download the corresponding 6.1 vm. I actually hit this issue again in our builds: https://pharo.fogbugz.com/f/cases/20156/OSPlatform-current-returns-a-MacOSPlatform-instead-of-a-MacOSXPlatform-on-macOS-Sierra and changing the download script to use the 6.1 vm fixed the problem.

I also had issues (random segfaults) trying to use this Pharo version in Linux (I reverted to osx builds), but cannot confirm yet if that is also caused by the vm mismatch. However, looking at the [release statement of Pharo 6.1](https://pharo.org/news/pharo6.1-released), this might very well be the case.

@fniephaus I have a PR ready to fix this. Do you prefer PRs to go to the dev branch?

**Comment by fniephaus** [comment]
`master` branch is fine usually, I've just been working on other things and had to merge on `dev` first.

**Comment by fniephaus** [comment]
This is fixed in [v2.7.0](https://github.com/hpi-swa/smalltalkCI/releases/tag/v2.7.0).
