### ISSUE TITLE
`sw_vers: not found` during "Setting up build cache"

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#338]
[Here's a case that occurred during a passing run](https://travis-ci.org/dalehenrich/tode/jobs/303180189#L836), so I'm not thinking that this is fatal error, but it is worth pointing out, since it might indicate a bug waiting to happen

**Comment by fniephaus** [comment]
This was a Travis bug: https://github.com/travis-ci/travis-ci/issues/8714

> [The noise should no longer appear.](https://github.com/travis-ci/travis-ci/issues/8714#issuecomment-345710186)
