### ISSUE TITLE
Why two builds per platform?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#34]
In a [travis build using dalehenrich/master](https://travis-ci.org/dalehenrich/smalltalkCI/builds/100435571) - which should match hpi-swa/master - it looks like each platform has two builds:

- 33.1 Smalltalk: Squeak -trunk
- 33.2 Smalltalk:Squeak-trunk

and I am not versed enough YAML to understand why those two builds are created.

From a [build against gs_master](https://travis-ci.org/dalehenrich/smalltalkCI/builds/100443311), using this (.travis.yml file](https://github.com/dalehenrich/smalltalkCI/blob/gs_master/.travis.yml) I can tell that in the first case, the dependencies are installed and the build passes - even though the dependencies themselves appear to fail to be installed. In the second case, the dependencies are **not** installed and the build fails :

- [37.1 Smalltalk: GemStone-3.2.12](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/100443312)
- [37.2 Smalltalk: GemSTone-3-2.12](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/100443313)

The failure of (build 37.2](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/100443313#L962 appears to be due to the fact that the hostname is not set correctly ... which implies that the [`apt host travis-dev`](https://github.com/dalehenrich/smalltalkCI/blob/gs_master/.travis.yml#L29) is not being executed ...

I would have thought that there would only need to be one build done per platform (the one where dependencies get set), especially since there does not appear to be any other discernable difference in the results ...

**Comment by fniephaus** [comment]
The tests run for all supported Smalltalk dialects on all supported operating systems (Linux & OS X).
That's defined by [L4-L11](https://github.com/hpi-swa/smalltalkCI/blob/981ffbd83c84f429b658429257af852f136d8361/.travis.yml#L4-L14) and [L16-L18](https://github.com/hpi-swa/smalltalkCI/blob/981ffbd83c84f429b658429257af852f136d8361/.travis.yml#L16-L18). Basically `smalltalk` x `os` happens.
And in `matrix.include` we add a build for the bash tests and all builderCI builds.

For more general information visit:
https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

Hope this makes sense!

**Comment by fniephaus** [comment]
Also, `addon.apt.host` [does not seem to be supported](https://docs.travis-ci.com/user/apt/).
How about the following :smile: 
```yml
addons:
  hosts:
    - travis.dev
```
Source: https://docs.travis-ci.com/user/customizing-the-build/#Custom-Hostnames

**Comment by dalehenrich** [comment]
Ah of course ... I should have pulled out my magnifying glass and looked closer at those silly icons ... thanks for the explanation ... the `sudo hostnames travis.dev` clearly worked on Linux and not on osx  which explains my failure ...
Btw where do I find the information about the version of osx being used. The Worker and buid info lead be to believe that it's linux... (the icon appears to be the only place that info is present):

```
Worker information
hostname: worker-jupiter-brain:5b7a6d26-1a72-4ae0-b2d4-d917a6ff0b6c
version: v2.0.0 https://github.com/travis-ci/worker/tree/ca6cb0c5d3920912b1c3acc87c44a5da2120a971
instance: 7ef800db-942c-4db5-9a07-b7ac687d57eb:
startup: 55.430817654sBuild system information
Build language: smalltalk
Build group: stable
Build dist: precise
```

**Comment by fniephaus** [comment]
It's not obvious I'm afraid, but this tells you:
> hostname: worker-jupiter-brain:

https://blog.travis-ci.com/2015-05-29-this-week-in-travis-ci/

Also, there usually is a lot more information under `Build system information` for Linux builds.

**Comment by dalehenrich** [comment]
`sudo hostname travis.dev` still required and likely the `osx` equivalent is needed as `addons:host:travis.dev` is not sufficient on either platform ... thanks for the info 

As a side not, did you notice that the `install dependencies` is apparently failing on linux:

```
install_packages

Installing dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libc6
E: Unable to locate package libuuid1
E: Unable to locate package libfreetype6
E: Unable to locate package libssl1.0.0
E: Couldn't find any package by regex 'libssl1.0.0'
```

I recognize those from the `addon:apt:` that used to be present in one of the `.travis.yml` files - don't recall which one and seem to recall that they went away ... BTW the extra `apt` line came when I copied that section to the master `.travis.yml` file and didn't delete the `-apt` that preceded the library list (that is now gone?

**Comment by fniephaus** [comment]
The problem why apt is that your builds run on GCE and Ubuntu Trusty. I've already sent you a PR :smiley: 

`addons:host:travis.dev` modifies `/etc/hosts`, but `sudo hostname travis.dev` modifies `/etc/hostname`, right? That might be the other problem. Just use `sudo hostname travis.dev` for now, and I will find a way to get this running on the container-based infrastructure later :smiley:

**Comment by dalehenrich** [comment]
Where are the library loads coming from? I don't see them anywhere .... 

For GsDevKit_home, the installPrereqs script installs the prereqs for Squeak/Pharo using `sudo apt` and that is working ... so the fact that they are failing during `install` is okay for the time being, but I'll integrate your pul request just the same .. thx!

**Comment by fniephaus** [comment]
What do you mean by "library loads"?

Apparently, this one went through:
https://travis-ci.org/dalehenrich/smalltalkCI/jobs/100463272
