### ISSUE TITLE
Upgrade Metacello [at least in Squeak]

### ISSUE THREAD

**Issue by krono** [hpi-swa/smalltalkCI#340]
To support Squeak6 (aka current trunk), we need to upgrade Metacello to at least https://github.com/Metacello/metacello/commit/35ec6fbe32d0058e0df40c63c3e6396e2b98adbd

This is partly why https://github.com/SeasideSt/Grease/pull/58 fails.

**Comment by fniephaus** [comment]
Please "useLatestMetacello : true".
https://github.com/hpi-swa/smalltalkCI/blob/master/README.md#scimetacelloloadspec

**Comment by krono** [comment]
Ack. Sorry.
