### ISSUE TITLE
problem with deprecation of `SmalltalkCI>>test:named:`

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#341]
Here's a screen shot pre-deprecation of`SmalltalkCI>>test:named:`:
 ![screen shot 2017-11-18 at 11 16 16 am](https://user-images.githubusercontent.com/623951/32983968-0968f324-cc52-11e7-8d36-73aa7308b383.png)
and here's a screen shot post-deprecation:
![screen shot 2017-11-18 at 11 21 49 am](https://user-images.githubusercontent.com/623951/32984001-bd8104a0-cc52-11e7-823f-11c9f3c1affb.png)
Note that both tests have the same **name** and it becomes difficult to differentiate which test is which ... I believe that the reason that test names were added was to support this feature ... so deprecating custom test names is regression

**Comment by fniephaus** [comment]
Functionality should be restored once https://github.com/hpi-swa/smalltalkCI/commit/1821addf71e49656a3fe5e2c43ddd103d9b70751 hits `master`.

**Comment by dalehenrich** [comment]
excellent, Thanks!

**Comment by fniephaus** [comment]
This is fixed in [v2.7.0](https://github.com/hpi-swa/smalltalkCI/releases/tag/v2.7.0).
