### ISSUE TITLE
Test failures not resulting in a failed build

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#342]
According to travis, the job [1689.1](https://travis-ci.org/dalehenrich/tode/jobs/303862800) passed, however a look at the [test log](https://travis-ci.org/dalehenrich/tode/jobs/303862800#L4204-L5484)  shows that the travis should have failed ... here's a screenshot:
![screen shot 2017-11-18 at 11 21 49 am](https://user-images.githubusercontent.com/623951/32984049-80734aea-cc53-11e7-8e70-5b73c05f4ccb.png)

I believe that this **SERIOUS PROBLEM** was introduced when  `SmalltalkCI>>test:named:` was deprecated ... I rely upon SmalltalkCI to correctly report the status of builds I made a release based on tODE travis runs being green and now I see that I did a disservice to my users, because I made the mistake of believing the smalltalkCI results!

**Comment by dalehenrich** [comment]
BTW, the point of deprecation is to leave a feature enabled until sufficient time has passed to determine that the feature can safely be removed ... and in this case you removed the feature itself and incorrectly labeled it as a deprecation... 

You **CANNOT** arbitrarily remove functionality from a system without properly ensuring that **NO USERS ARE AFFECTED** and that was not done in the case at all... Also see #341 ... just that problem alone was enough to put the kibosh on removing this feature ... but reporting tests as passing that should have failed is **NOT ACCEPTABLE**

**Comment by dalehenrich** [comment]
Well looking back over history of the tODE builds, I've gone back a year and cannot find a case where the gemstone build failed when the client build did not fail ... so I cannot say at this point that it ever worked, the GemStone `run.sh` script hasn't changed for a long time and is not likely to be the source of the issue ... the SmalltalkCI smalltalk code is another issue, and I haven't touched that in a long time which means at this point I have no idea how it used to work or how it works now ...

**Comment by fniephaus** [comment]
I think one big design flaw we need to get rid of is the following line: https://github.com/hpi-swa/smalltalkCI/blob/d37666744186187ed71b82c642a7defe452189e0/gemstone/run.sh#L241

An image should *always* create a build status file, but I'm not sure if this would solve your problem.
I will have a closer look at this tomorrow...

**Comment by dalehenrich** [comment]
Thanks for looking!

**Comment by fniephaus** [comment]
Ok, so I spent some time on improving things. The `SmalltalkCI>>test:named:` functionality should soon be restored and I'm also improving the build status file handling.
Currently, all client tests are being executed after each other, even if they fail (the check is [here](https://github.com/hpi-swa/smalltalkCI/blob/d37666744186187ed71b82c642a7defe452189e0/gemstone/run.sh#L244)). I think it'd be better to fail immediately if a client fails, so it's easier to see what went wrong and you don't have to search the log. Agreed?
Also, I'd like to address #242 soon, but that requires to update `GsDevKit`. Would this be a good time to do this?

**Comment by dalehenrich** [comment]
I don't necessarily agree that exitting on the first failure is a good idea ... They are stacked up with multiple client tests to avoid having to build GemStone multiple times just to test the client so exiting early is not necessarily a useful thing ... there is a reason that travis ci runs multiple concurrent builds and I think it is the same thing for this feature ... knowing which clients fail and which ones pass for the same run is useful ... like I said the reason that multiple clients are run is to save having to build GemStone once for each client build ... if you aregoing to take away the utility of runnin all of the tests, you might as well take away the whole enchilada ... but the cost is more travis execution time which I thought we were trying to limit ...

**Comment by dalehenrich** [comment]
I had a little window of time over the weekend where I was going to work on the SmalltalkCI deprecation issues, but instead fiddled with this particular bug and then decided to wait until the SmalltalkCI API hits a stable point, so I don't go around chasing my tail ... so it may be a month or so before the window opens up for working on SmalltalkCI issues ... I'd like to address all of the SmalltalkCI issues at once and it is beginning to look like it will take several days worth of work --- mainly I'm going to have to study just what the heck is going on these days ... 

so I guess my overall preference is to wait until the old functionality is restored and in working order, then wait for windows of time to clean up the deprecations issues --- so all of the features that you are planning to change should be marked with deprecation warnings, so that I can tell if/when/where I am using the deprecated API (... removing the functionality and putting in a deprecation warning like you did for #341 is not the right way to do deprecation ...) and I hope you have plans to fix #341 as well, since having a unique name in the test title is a critical feature of running multiple clients

**Comment by fniephaus** [comment]
That's why I asked and I get your point. I will keep the behavior untouched then...

**Comment by dalehenrich** [comment]
sounds good:)

**Comment by fniephaus** [comment]
I'm currently hardening the build status reporting and already found a bug in the old code. I haven't verified if this caused your issue though, but it's likely.
Is there an "easy" way to test all code depending on smalltalkCI against the `dev` branch, or do I have to merge into `master` first and hope things don't break?

**Comment by dalehenrich** [comment]
Isn't that a function of how SmalltalkCI installs iitself ... I guess the question is, "is there a way for a project to use an alternate branch of SmalltalkCI?" If so then I can arrange to fire off builds on separate project branches for you to debug with ... hmmm is that what https://github.com/hpi-swa/smalltalkCI#using-a-different-smalltalkci-branch-or-fork is for?

If it is let me know and I'll fire of a tode build ... although there _are_ smalltalkCI tests for GemStone that use multiple clients as well ...

**Comment by fniephaus** [comment]
Yes, you should be able to set `smalltalk_edge` to use the `dev` branch instead. I wasn't sure if your script manually clone smalltalkCI...

**Comment by dalehenrich** [comment]
Let me know when I should fire off a tode build to test your changes ...

**Comment by fniephaus** [comment]
Feel free to do it now, the behavior with regard to multi-client testing should be restored...

**Comment by fniephaus** [comment]
Just found another bug, please restart if your builds are already running...

**Comment by dalehenrich** [comment]
just launched [the build](https://travis-ci.org/dalehenrich/tode/builds/304914460)

**Comment by fniephaus** [comment]
ok, let's wait and see...

**Comment by dalehenrich** [comment]
... no errors or failures but the build is failing ... did I get the wrong version of smalltalkCI (too soon after your update) or is there another issue?

**Comment by dalehenrich** [comment]
... see same mysterious problem in the [smalltalkci build](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/304913936)

**Comment by fniephaus** [comment]
yes, there's another issue..new [smalltalkCI build](https://travis-ci.org/hpi-swa/smalltalkCI/builds/304924042). Please restart yours...

**Comment by dalehenrich** [comment]
next time I'll wait for the smalltalkCI builds to be breen before relauching tode ... got my hopes up:) ... also the labels for the tests appear to be wrong ... there should be a unique label for each test ..

**Comment by fniephaus** [comment]
True, I should have had a look at the deprecation warnings...I need to get some dinner and will ping you then...

**Comment by fniephaus** [comment]
Mh, `test:named` should work, but clients are still using another API to inject a custom suite name (`SmalltalkCIPharo>>suiteName:`). A fix is on `dev`, restart your builds when [this](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/304931851) passes.

**Comment by dalehenrich** [comment]
K

**Comment by fniephaus** [comment]
The Pharo file server is a massive pain :(

**Comment by estebanlm** [comment]
we know :( 
this happens since latest "update". We are working to solve it, I hope we will have an answer soon(™)

**Comment by fniephaus** [comment]
@estebanlm well I know, hopefully it's getting fixed soon

**Comment by fniephaus** [comment]
@dalehenrich time to restart your builds :)

**Comment by dalehenrich** [comment]
okay ... so the build that is supposed to test failures is failing even though the tests did fail correctly:) ... restarted ... I'm headed to the dentist in about 10 minutes so will be offline for 2-3 hours ...

**Comment by fniephaus** [comment]
yes, I'm already trying to figure out why this is happening...at least I didn't break anything in the other code path

**Comment by fniephaus** [comment]
Ok, so please restart your builds one more time. In the meantime, I will get some rest and will follow up tomorrow morning...

**Comment by dalehenrich** [comment]
okay restart [build](https://travis-ci.org/dalehenrich/tode/builds/304914460)

**Comment by fniephaus** [comment]
Two builds failed due to network errors, and a third because of failing tests. Can you restart the first two failed builds?

**Comment by fniephaus** [comment]
Please restart all builds...

**Comment by dalehenrich** [comment]
done

**Comment by fniephaus** [comment]
And, is [this](https://travis-ci.org/dalehenrich/tode/builds/304914460) your expected result?

**Comment by fniephaus** [comment]
BTW: I'm checking expected failures in smalltalkCI with [this](https://github.com/hpi-swa/smalltalkCI/blob/d37666744186187ed71b82c642a7defe452189e0/.travis.yml#L18) (inverting the result).

**Comment by dalehenrich** [comment]
You mean the test failures for 2.4.8? Yes ... I have been on the fence with how much longer I will "support" tODE on 2.4.8 ... it's never really been functional (there are some base bugs that will not be fixed) and these base bugs get in the way of making it easy to fix the bugs ... I've left the allowe failures as a constant reminder that I need to eventually drop support for 2.4.8 ... so I guess I could turn it into a green result? ... the other test looks like it is there inadvertantly since it appears to be a duplicate of a test that fails ... I may have put it there to some pre-release testing on 3.4.0 and forgot to take it out ...

**Comment by dalehenrich** [comment]
Oh wait that is the OSX build ... for OSX I can get a rash of API RATE LIMIT errors again ... because of the unreliability of OSX builds for GemStone on travis, I don't usually include OSX in the mix ...again it;s wishful thinking that someday I won't have to worry about the APR RATE LIMIT errors ... I **am** making an overhaul to the GemStone build process that will greatly speed up the build process and eliminate rate limiting errors (entire build done from git checkouts) --- it's what I am supposed to be doing over the next couple of weeks --- so the wishes may be granted in the not too distant future ... of course this will only apply to the newer versions of GemStone ...

**Comment by fniephaus** [comment]
Sounds good! Am I under the right impression that the current dev is better than master and fixes this issue? If so, I will merge into master once Travis is happy.

**Comment by dalehenrich** [comment]
Yes the labels are back and if things are failing correctly we are good

**Comment by fniephaus** [comment]
Perfect!

**Comment by dalehenrich** [comment]
Thanks a ton for your effort ... it is really appreciated!

**Comment by fniephaus** [comment]
This is fixed in [v2.7.0](https://github.com/hpi-swa/smalltalkCI/releases/tag/v2.7.0).
