### ISSUE TITLE
Build matrix to test packages in concurrent jobs

### ISSUE THREAD

**Issue by jbrichau** [hpi-swa/smalltalkCI#343]
We have a build for which running the entire test suite exceeds the maximum job time imposed by Travis-CI. I am exploring how I can define a matrix to run a job per test package.

I guess SmalltalkCI currently does not have a built-in possibility for this? Do you think this is possible to achieve?

**Comment by jbrichau** [comment]
Browsing through the existing issues, it sounds like I need https://github.com/hpi-swa/smalltalkCI/issues/106 to work?

**Comment by fniephaus** [comment]
Hi @jbrichau,
[Metacello](https://github.com/Metacello/metacello) uses multiple `SmalltalkCISpec`s to separate tests into different builds (see `.smalltalkA.ston`, `.smalltalkB.ston`, etc). I assume this is what you are looking for?

**Comment by jbrichau** [comment]
Hi @fniephaus 

Yes, it would seem so but I think it's still not working as I read here: https://github.com/hpi-swa/smalltalkCI/issues/185 
Looking at the Metacello builds, it seems they are not being used.

**Comment by fniephaus** [comment]
Right, there's a weird Travis bug going on that we haven't figured out yet.
In the meantime, this should work:
```javascript
...
jobs:
  include:
    - smalltalk_config: .smalltalkAston
    - smalltalk_config: .smalltalkB.ston
...
```

**Comment by jbrichau** [comment]
Thanks for that workaround! Works as advertised.

I guess that, in the future, I would actually want to use the env variables for that, similar to how it's done for other languages (https://docs.travis-ci.com/user/speeding-up-the-build/). Will be diving into that as we go along.

**Comment by fniephaus** [comment]
We try to minimize the amount of env vars used in smalltalkCI. Why would you prefer to use them over the `smalltalk_config` option (if matrix expand worked as well)?

BTW: you should already be able to use env vars like this:

```yml
...
env:
  - SMALLTALK_CONF=.smalltalkA.ston
  - SMALLTALK_CONF=.smalltalkB.ston
script: smalltalkci $SMALLTALK_CONF

```

**Comment by jbrichau** [comment]
Thanks again for that pointer. I'm definitely not yet on-par with all Travis-CI possibilities....

The reason I prefer the env variable is that the values are more clearly distinguishable in the travis-ci build job screen. This makes it easier to see which smalltalk config is run in which job. I know it's in the job name, but that's just less easy to see at a glance.

**Comment by fniephaus** [comment]
Ok, that makes sense. smalltalkCI tries not to "pollute" the env column too much, so users can do other things in there too. But most of the functionality can be replicated with env vars out of the box.
