### ISSUE TITLE
How to debug SentButNotImplementedTest

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#346]
What's the best way to debug a failing `SentButNotImplementedTest`? The error message on Travis does not give any hints as to which messages are causing the problem which is unfortunate.

**Comment by dalehenrich** [comment]
the SentButNotImplementedTest dumps the list of unimplemented messages and the sender of the message into the log while the test is running ... I don't recall the exact string, but if you have a specific travis test failure log I can easily find the long entry and point you to it for future refence ...

**Comment by fniephaus** [comment]
Perfect thanks! ([example](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/305915876#L2872))
