### ISSUE TITLE
Travis-CI gets stuck with Pharo-5.0

### ISSUE THREAD

**Issue by JurajKubelka** [hpi-swa/smalltalkCI#347]
Hi!

For couple of days my Travis-CI configuration does not work. I have checked my code, even if I do local testing using `smalltalkCI.sh --headfull -s Pharo-5.0` it does not work. At the moment of running test cases, the Pharo window is black and not responsive (on macOS 10.13.1), CPU is about 100%.

On Travis, it says:

```
Testing project...
Running suite "Pharo-5.0 on Travis CI (181.1)" with 22 tests.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

By checking [Travis build history](https://travis-ci.org/JurajKubelka/GTEventRecorderServer/builds), it used to work, [the last green build is 174](https://travis-ci.org/JurajKubelka/GTEventRecorderServer/builds/305704620). I have not changed any code since then. 

By executing the test cases manually it works well. Any idea why it happens?

Steps to reproduce:

```Bash
git clone git@github.com:JurajKubelka/GTEventRecorderServer.git
cd GTEventRecorderServer
smalltalkCI.sh --headfull -s Pharo-5.0
```

The output shows a failing error:
```
$ smalltalkCI.sh --headfull -s Pharo-5.0
Preparing folders...
Starting Pharo build...
Downloading Pharo-5.0 image...
Downloading the latest 50 Image:
    http://files.pharo.org/get-files/50/pharo.zip
Pharo.image
 > Time to run: 20.000s 
Preparing Pharo image...
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
Image Information
Image
-----
/Users/jura/SourceCode/pharo/hpi-swa/smalltalkCI/_builds/2017_11_29_09_46_09/TravisCI.image
Pharo5.0
Latest update: #50772
Unnamed


 > Done in 1.000s.
Loading project...

 > Done in 16462.000s.
nil
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
Testing project...
Running suite "Pharo-5.0" with 22 tests.
E
```

**Comment by fniephaus** [comment]
It appears to be a problem with the new code coverage testing...I'll look into this when I have some time.

**Comment by fniephaus** [comment]
A quick looks revealed that this has something to do with the [`valueUnpreemptively`](https://github.com/hpi-swa/smalltalkCI/blob/4b6909db3623d2dd9642fefe91e0f99326724968/repository/SmalltalkCI-Coverage-Core.package/SCICodeCoverage.class/instance/run.spec..st#L6) and your code attempts to establish network connections etc.
Therefore, I assume you cannot coverage test manually as well?

**Comment by JurajKubelka** [comment]
How can I try "coverage test manually"?

**Comment by fniephaus** [comment]
`TestRunner` > "Run Coverage" and then select your package.
Your test code must be spawning high-priority processes (maybe for a network connection?) which causes the image to freeze.
I'm trying to fully understand why `valueUnpreemtively` is used. I think it's a requirement for a correct coverage result and a clean system, and I would like to keep it to ensure smalltalkCI behaves in the same way as the original `TestRunner`.

**Comment by JurajKubelka** [comment]
You are right. `TestRunner > "Run Coverage"` does not work. Yes, I use `ZnServer` and `ZnClient`

**Comment by fniephaus** [comment]
Mh, that's unfortunate. It used to "work" before, but the result could've been manipulated by any high-priority process executing code in the code path.
I'm not sure yet what would be the right thing to do here, need to read more (code) about code coverage first...

**Comment by JurajKubelka** [comment]
OK. Thank you for the effort.
