### ISSUE TITLE
Travis WebLint (http://lint.travis-ci.org)doesn't recognize `smalltalk` as a language

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#35]
An attempt to [validate](http://lint.travis-ci.org) the .travis.yml for [Object Explorer](https://github.com/dalehenrich/obex/blob/master/.travis.yml) resulted in the following errors:

- in language section: illegal value smalltalk, defaulting to ruby
- unexpected key smalltalk, dropping
- your repository must be feature flagged for the os setting to be used

Perhaps it is just a matter of time before smalltalk is migrated to Travis WebLint?

BTW, I had a different error (tab on the last line) that was causing the [failure](https://travis-ci.org/dalehenrich/obex/builds/100843007

**Comment by fniephaus** [comment]
[travis-lint](https://github.com/travis-ci/travis-lint) seems to be lagging behind quite a bit.

This might be something @bahnfahren, @chistopher, @jchromik, and @Nef10 could work on, since it isn't time-critical.

**Comment by Nef10** [comment]
since our PR is merged this should work now

**Comment by fniephaus** [comment]
Oh nice! Thanks a lot! :smiley:
