### ISSUE TITLE
Squeak 5.1 image is not up to date wrt source.squeak.org MC repository

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [hpi-swa/smalltalkCI#350]
The tests for squeak 5.1 launched from opensmalltalk-vm are stalling on linux VM.
https://github.com/OpenSmalltalk/opensmalltalk-vm/tree/Cog/tests)

The problem has been reported and identified in squeak vm-dev thread "Stalled travis_tests in linux32x86".
http://lists.squeakfoundation.org/pipermail/vm-dev/2017-December/026046.html

A workaround has been published in Monticello repository for squeak 5.1 on source.squeak.org
http://source.squeak.org/squeak51/Files-nice.163.diff

Note that there's another similar workaround not yet integrated
http://source.squeak.org/squeak51/Files-ul.162.diff

It now remains to update the squeak 5.1 image
(maybe both official image and the smalltalkCI copy from which the image is downloaded)

**Comment by fniephaus** [comment]
Thanks for looking into this, I actually have seen similar problems and I think this should fix it.
I will update all Squeak images tomorrow...

**Comment by fniephaus** [comment]
5.1 image should be updated, also updated Metacello in all other Squeak images.
