### ISSUE TITLE
defaultTimeout for tests can be supported too

### ISSUE THREAD

**Issue by dionisiydk** [hpi-swa/smalltalkCI#354]
Starting from Pharo 6 there is timeout for tests.
But the message is different from Squeak. It is named #defaultTimeLimit which accepts a duration instance:
```Smaltalk
TestCase defaultTimeLimit: 2 minutes
```
And there is version with seconds number argument:
```Smaltalk
TestCase defaultTimeLimitSecs: 30
```

**Comment by fniephaus** [comment]
Thanks for suggestion, should work now

**Comment by dionisiydk** [comment]
Cool.
Thanks.

2018-02-05 13:35 GMT+01:00 Fabio Niephaus <notifications@github.com>:
