### ISSUE TITLE
Broken coveralls testing?

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#356]
Is coveralls testing broken?

I've created several repos in the past two weeks, and none of them are properly uploading anything to coveralls. Normally I just copy configuration from an existing working project and tweak it. But it seems that coveralls simply isn't uploaded and I have no idea why. And likewise I have no idea how can I even debug this.

Here are two example repos:

github: https://github.com/peteruhnak/pharo-sentry/blob/master/.smalltalk.ston
coveralls: https://coveralls.io/github/peteruhnak/pharo-sentry
travis: https://travis-ci.org/peteruhnak/pharo-sentry/jobs/341797270#L744

github: https://github.com/peteruhnak/onigmo/blob/master/.smalltalk.ston
coveralls: https://coveralls.io/github/peteruhnak/onigmo
travis: https://travis-ci.org/peteruhnak/onigmo/jobs/341799762#L695

**Comment by fniephaus** [comment]
Thanks for bringing this up. I will have a look in the next couple of days.

**Comment by peteruhnak** [comment]
Uh... this is strange.

Apparently coveralls data is uploaded for the build, but it was never aggregated. So I don't know if this is SmalltalkCI issue or if Coveralls is bugged

onigmo/8: https://coveralls.io/builds/15536492
onigmo: https://coveralls.io/github/peteruhnak/onigmo

**Comment by fniephaus** [comment]
This might be a Coveralls issue. [smalltalkCI's Coveralls page](https://coveralls.io/github/hpi-swa/smalltalkCI) displays wrong data:
![image](https://user-images.githubusercontent.com/2368856/36489316-03e361d6-1726-11e8-8323-4b0918aaa6d0.png)
I don't think there's this much Go code in this repository :(

**Comment by gcotelli** [comment]
I don't know if it's related but when the upload to coveralls times out the build don't fail. 

I'm seeing a lot of 
```
[1m[34mUploading coverage results to Coveralls...[0m
/home/travis/smalltalkCI-master/helpers.sh: line 368:  4261 Terminated              travis_jigger $! $timeout $cmd

`travis_time:end:0713e836:start=1522930990442491002,finish=1522932445172749768,duration=1454730258766`
```
in a project running 48.000 tests (so probably a huge JSON file). 
Take a look for example at: https://api.travis-ci.org/v3/job/362599725/log.txt
The API docs states that you can upload the json file gzipped (https://docs.coveralls.io/api-introduction). Maybe this can help with the timeouts?

I'm not a bash expert but probably adapting `upload_coveralls_results` to do something like:
```bash 
gzip "${coverage_results}"
curl -s -F 'json_file=@"${coverage_results}".gz;type=gzip/json' "${COVERALLS_API}"
```
can work.

Probably it's a good idea to notice this failure in some way.

**Comment by fniephaus** [comment]
I didn't know you can upload `gzip` files, interesting! Could you try this out locally and share your learnings?

But to be fair, enabling coverage testing for a project with 48.000 tests and probably thousands of classes doesn't sound like a good idea. Just because you can doesn't mean you should ;) I don't know how well smalltalkCI and Coveralls can handle something like this anyway...

**Comment by peteruhnak** [comment]
Well... I think we can agree that has been (and still is for some of my repos) a coveralls issue, and SmalltalkCI cannot really do anything about it... so I'm closing this, sorry about the noise. :)

**Comment by fniephaus** [comment]
@peteruhnak I'm reopening this, because smalltalkCI's coverage currently supports coveralls and it used to work. Have you tried their API out manually to reproduce the problem? Aren't other projects (written in other languages) having similar issues? Are there any related bug reports or issues?

**Comment by peteruhnak** [comment]
SmalltalkCI's upload seems to be just fine,
e.g. the data was clearly uploaded a processed https://coveralls.io/builds/16363670
but the aggregation/general overview remains empty https://coveralls.io/github/peteruhnak/pharo-sentry

strangely for other projects, such as this one it works correctly https://coveralls.io/github/peteruhnak/pharo-travis-pipeline

so I think it's coveralls' fault

**Comment by fniephaus** [comment]
Have you verified that the JSON that smalltalkCI produced is correct? It'd be great to know how to reproduce the problem...

**Comment by peteruhnak** [comment]
It seems that this was a temporary failure on coveralls-side that was eventually resolved.
As far as I can tell this issue is no longer present.

**Comment by fniephaus** [comment]
@peteruhnak thanks for the update!
