### ISSUE TITLE
Pharo-alpha builds don't work on Windows

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#357]
32 bit and 64 bit builds produce slightly different output:
- 32: https://ci.appveyor.com/project/theseion/fuel/build/1.0.108/job/iowiad0svnhba9qj
- 63: https://ci.appveyor.com/project/theseion/fuel/build/1.0.108/job/5agld0c917639191

**Comment by fniephaus** [comment]
> Creating starter scripts pharo and pharo-ui

It looks like the zeroconf script is broken? @estebanlm?

**Comment by theseion** [comment]
Appears to be resolved.

**Comment by fniephaus** [comment]
Great news!
