### ISSUE TITLE
Coverage not wotking on Pharo 7

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#359]
I'm getting the following error on travis for Pharo 7:

```smalltalk
Testing project...
KeyNotFound: key #TestCoverage not found in SystemDictionary
SystemDictionary(Dictionary)>>errorKeyNotFound:
[ self errorKeyNotFound: key ] in SystemDictionary(Dictionary)>>at: in Block: [ self errorKeyNotFound: key ]
SystemDictionary(Dictionary)>>at:ifAbsent:
SystemDictionary(Dictionary)>>at:
SmalltalkImage>>at:
[ :each | (Smalltalk at: #TestCoverage) on: each ] in SCIPharoCodeCoverage(SCICodeCoverage)>>startUp in Block: [ :each | (Smalltalk at: #TestCoverage) on: each ]...etc...
OrderedCollection>>collect:
SCIPharoCodeCoverage(SCICodeCoverage)>>startUp
SCIPharoCodeCoverage(SCICodeCoverage)>>run:
SCIPharoCodeCoverage class(SCICodeCoverage class)>>run:spec:in:
[ self prepareForTesting.
self executionClass
	run: [ runner := self runTests ]
	spec: self spec
	in: self projectDirectory.
self finishUpAfterTesting ] in SmalltalkCIPharo7(SmalltalkCI)>>basicTest in Block: [ self prepareForTesting....
BlockClosure>>ensure:
SmalltalkCIPharo7 class(SmalltalkCI class)>>travisTime:foldName:on:block:
[ self
	travisTime: aTitle
	foldName: anID
	on: aStream
	block: aBlock ] in SmalltalkCIPharo7 class(SmalltalkCI class)>>travisFold:id:on:block: in Block: [ self...
BlockClosure>>ensure:
SmalltalkCIPharo7 class(SmalltalkCI class)>>travisFold:id:on:block:
SmalltalkCIPharo7 class(SmalltalkCI class)>>travisFold:id:block:
SmalltalkCIPharo7 class(SmalltalkCI class)>>stage:id:block:
```
Full log on: https://travis-ci.org/ba-st/Buoy/jobs/353483653

**Comment by fniephaus** [comment]
Looks like the `TestCoverage` class has been removed from Pharo. That's a pity...I wonder why?

**Comment by peteruhnak** [comment]
TestCoverage was removed here https://github.com/pharo-project/pharo/pull/975/commits

I asked Marcus

> MarcusDenker - Today at 12:06 PM
> There is still HDTestCoverage which is for the CI
> Jenkins in this case
> The problem is that TestCoverage is installed as a method, this is not an API to use but the deep deep > implementation artefact

the collector should probably be disabled for P7 then until it is fixed... so builds are at least not failing.

(On the other hand coveralls have stopped working properly for some time now without any public response :-/, so it's not like fixing it immediately will bear fruit...)

**Comment by fniephaus** [comment]
https://github.com/hpi-swa/smalltalkCI/commit/61e2f3c00314c68757f93673373bb814b8a5f5de fixes this in smalltalkCI, not sure if coveralls has fixed their problems.
