### ISSUE TITLE
Loading a project with tonel dependencies don't work

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#365]
It seems that loading a project whose dependencies are in tonel format don't work:
See discussion here:
http://forum.world.st/SmalltalkCI-loading-tonel-dependencies-td5073542.html

I think it's probably related to disabling Iceberg metacello integration during the load phase. @fniephaus: did you remember the reason why Iceberg metacello integration is disabled in smalltalkCI?

**Comment by fniephaus** [comment]
Unfortunately, I can't remember and I'm also not using Iceberg. Maybe this is related to @dalehenrich's comment at https://github.com/hpi-swa/smalltalkCI/issues/326#issuecomment-374735048 and really a Metacello issue?

**Comment by estebanlm** [comment]
this is still not solved in metacello level (which is where it should be). 
in Pharo, you need to have

```Smalltalk
Iceberg enableMetacelloIntegration: true
```

to be able to load tonel dependencies.

**Comment by gcotelli** [comment]
Maybe we can try enabling Iceberg-Metacello integration? If you're Ok I can prepare a pull request so we can test against it.

**Comment by fniephaus** [comment]
Would there be any drawbacks if smalltalkCI always calls `Iceberg enableMetacelloIntegration: true` in all Pharo images that come with Iceberg (as a workaround of course)?

**Comment by gcotelli** [comment]
The corresponding Pharo images already have iceberg-metacello integration enabled. 
Probably we just need to remove the users of `disableIcebergDuring:`
