### ISSUE TITLE
SmalltalkCI missing dependencies

### ISSUE THREAD

**Issue by BjoernDaase** [hpi-swa/smalltalkCI#375]
Using an Ubuntu 16.04 64 Bit running smalltalkCI will result in missing dependencies. If you run the follwong piece of code, that should help:

`sudo dpkg --add-architecture i386`
`sudo apt upate`
`sudo apt install libglu1-mesa:i386 libsm6:i386 libc6:i386 libuuid1:i386 libssl1.0.0:i386 -y`

**Comment by fniephaus** [comment]
The dependencies depend purely on the VM in use and differ across dialects. Closing this as those are not actually smalltalkCI's dependencies
