### ISSUE TITLE
Builds failing due to ss3.gemstone.com unavailable

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#376]
Today some builds for Pharo 7 started failing because smalltalkCI couldn't be loaded. It fails trying to load STON because the configuration in use points to ss3.gemstone.com that is deprecated. It should point to http://ss3.gemtalksystems.com/ as confirmed by @jgfoster. 

This is the failing log:

```
 Fetched -> BaselineOfSmalltalkCI-fn.16 --- filetree:///home/travis/smalltalkCI-master/repository [:] --- filetree:///home/travis/smalltalkCI-master/repository
Loaded -> BaselineOfSmalltalkCI-fn.16 --- filetree:///home/travis/smalltalkCI-master/repository [:] --- filetree:///home/travis/smalltalkCI-master/repository
Loading baseline of BaselineOfSmalltalkCI...
 Fetched -> ConfigurationOfSton-SvenVanCaekenberghe.29 --- http://smalltalkhub.com/mc/SvenVanCaekenberghe/STON/main/ --- http://smalltalkhub.com/mc/SvenVanCaekenberghe/STON/main/
Loaded -> ConfigurationOfSton-SvenVanCaekenberghe.29 --- http://smalltalkhub.com/mc/SvenVanCaekenberghe/STON/main/ --- http://smalltalkhub.com/mc/SvenVanCaekenberghe/STON/main/
Project: Ston stable [0.24]
...RETRY->STON-Core-SvenVanCaekenberghe.87
...RETRY->STON-Core-SvenVanCaekenberghe.87
gofer repository error: 'GoferRepositoryError: Could not access http://ss3.gemstone.com/ss/STON: ZnHttpUnsuccessful: 500 Internal Server Error'...ignoring
...FAILED->STON-Core-SvenVanCaekenberghe.87Could not resolve: STON-Core [STON-Core-SvenVanCaekenberghe.87] in /home/travis/smalltalkCI-master/_builds/pharo-local/package-cache http://ss3.gemstone.com/ss/STON ERROR: 'GoferRepositoryError: Could not access http://ss3.gemstone.com/ss/STON: ZnHttpUnsuccessful: 500 Internal Server Error'
```

**Comment by gcotelli** [comment]
The full travis log in case is useful
https://travis-ci.org/ba-st/Mole/jobs/396078509

**Comment by fniephaus** [comment]
This does affect smalltalkCI builds, but it's actually [a STON bug](https://github.com/hpi-swa/smalltalkCI/blob/cb59b92d7c08ee92151884bafb5bdb6ed9efbadd/repository/BaselineOfSmalltalkCI.package/BaselineOfSmalltalkCI.class/instance/baseline..st#L54) which @svenvc needs to fix.

**Comment by svenvc** [comment]
I don't understand, what do I have to fix ?
AFAIC remember I did not write the BaselineOf

**Comment by fniephaus** [comment]
`ss3.gemstone.com` is referenced multiple times in [`ConfigurationOfSton-SvenVanCaekenberghe.29`](http://smalltalkhub.com/mc/SvenVanCaekenberghe/STON/main/ConfigurationOfSton-SvenVanCaekenberghe.29.mcz). Side comment: I'm still confused by the different STON repositories. Which one is the primary one? SmalltalkHub or GemtalkSystem's SS3? I was hoping it would be the one on Github at some point.

**Comment by svenvc** [comment]
I still don't see the 'bug'.

From ConfigurationOfSton it is clear that ss3.gemstone.com is the primary repository. StHub is a fully synced copy, GitHub is an occasional copy.

That is the current situation. It could change one day, but not now.

**Comment by jgfoster** [comment]
Sven,

There situation changed some years ago. You should replace references to ss3.gemstone.com with ss3.gemtalksystems.com.

James Foster

**Comment by fniephaus** [comment]
@svenvc the baseline0*N* methods of `ConfigurationOfSton`, for example, contain references to `ss3.gemstone.com` which should be replaced with `ss3.gemtalksystems.com`.

**Comment by svenvc** [comment]
Ah OK, will do and let you know.

**Comment by svenvc** [comment]
Name: ConfigurationOfSton-SvenVanCaekenberghe.30
Author: SvenVanCaekenberghe
Time: 22 July 2018, 2:54:47.480293 pm
UUID: f9a64bc5-f72d-0d00-849b-a30608524610
Ancestors: ConfigurationOfSton-SvenVanCaekenberghe.29

changed host ss3.gemstone.com to ss3.gemtalksystems.com in all existing baselines

**Comment by fniephaus** [comment]
Thanks! I'm closing this issue for now...
