### ISSUE TITLE
GemStone builds currently broken

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#38]
GemStone builds are currently broken due to a syntax error I didn't see when updating the `smalltalk.rb`.
I will try to fix that with Travis asap.

/cc @dalehenrich

**Comment by fniephaus** [comment]
A fix has been sent to Travis: https://github.com/travis-ci/travis-build/pull/596

**Comment by dalehenrich** [comment]
Hmmm, the patch was merged 2 hours ago, but I'm still getting a [syntax error](https://travis-ci.org/dalehenrich/obex/jobs/102476586) ... any idea what the lag time is between the merge and it actually showing up?

**Comment by fniephaus** [comment]
Just because it is merged doesn't mean it is in production. But it will be with the next release I guess.

However, I already noticed a different problem: https://github.com/docker/docker/issues/8902
I'm afraid this could mean that we aren't able to set the hostname in container-based builds.
Can you think of a way to use the random hostname that is provided by Travis?

**Comment by dalehenrich** [comment]
well the problem is that `hostname` returns the "wrong answer" --- it is 
not in `/etc/hosts` ... so I suppose the workaround would be to add the 
result of `hostname` to the `/etc/hosts`... for gemstone to function the 
result of `hostname` needs to be in `/etc/hosts`

--- we cannot make those kinds of changes to the older versions of the 
product and it isn't likely that we'll change a future version of the 
product just so that we'll work on travis ---

**Comment by fniephaus** [comment]
So, adding the hostname to the `/etc/hosts` is still a workaround and requires a product change?
Correct?
It does work fine for OS X, because they don't run on the container-based infrastructure, but it'd still be nice to get this working somehow.

BTW: it seems that the patch still hasn't been deployed yet.

**Comment by dalehenrich** [comment]
On 1/15/16 2:06 AM, Fabio Niephaus wrote:
>
> So, adding the hostname to the |/etc/hosts| is still a workaround and 
> requires a product change?
> Correct?
>
No. If smalltalkCI.rb adds the result of `hostname` to /etc/hosts and 
travis-ci does not blow it's lunch then there is no need for a GemStone 
product change ...

Again. GemStone expects the host name answered by the `/bin/hostname` to 
be present in `/etc/hosts`. If you look at an un-modified travis 
container(?), the result of `/bin/hostname` is not present in `/etc/hosts`.

The original workaround was to a) add `travis.dev` to /etc/hosts and 
then b) arrange to change the host name to `travis-dev`.

The next thing to try is to take the result of `/bin/hostname` and add 
it to /etc/hosts ... if travis will let you do that then GemStone should 
run fine...


> It does work fine for OS X, because they don't run on the 
> container-based infrastructure, but it'd still be nice to get this 
> working somehow.
>
Agreed.

**Comment by fniephaus** [comment]
The patch has been deployed but it still isn't enough to get GemStone tests running. A new one is on the way...I'm closing this in favor of #28.
