### ISSUE TITLE
Cannot load Gemstone project due to API limitations

### ISSUE THREAD

**Issue by jecisc** [hpi-swa/smalltalkCI#380]
I tried to enable GemStone in the CI of DuneSt/MaterialDesignLite but the build is failing because of API limitations.

Here is the error:

```
 receiver a UserDefinedError occurred (error 2318), reason:halt, Error during download: 'UserDefinedError: API rate limit exceeded for 207.254.16.35. (But here''s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)'
```

Do you have any idea how to bypass this problem?

**Comment by fniephaus** [comment]
It's unfortunately a common issue, but it's not triggered by smalltalkCI. It might be Metacello problem...closing this here.
