### ISSUE TITLE
Segmentation fault during project loading

### ISSUE THREAD

**Issue by mschroederi** [hpi-swa/smalltalkCI#381]
Here are the last lines of Travis' log:
```
basicReplaceFrom:to:with:startingAt:
basicNew:
basicNew:
basicReplaceFrom:to:with:startingAt:
basicNew:
basicNew:
basicReplaceFrom:to:with:startingAt:
finalizeValues
finalizeValues
primitiveGarbageCollect
**FullGC**
handleFailingFailingBasicNew:
basicAt:
basicAt:put:
stack page bytes 4096 available headroom 2788 minimum unused headroom 0
	(Segmentation fault)
/home/travis/smalltalkCI-master/_builds/vm: line 1:  3776 Aborted                 (core dumped) /home/travis/smalltalkCI-master/_cache/vms/cogspurlinux/squeak "$@"
Error with status code 134:
506 travis_wait /home/travis/smalltalkCI-master/helpers.sh
```

**Comment by fniephaus** [comment]
Could you provide a link to the corresponding Travis log? Is this reproducible or just a flaky build?

**Comment by mschroederi** [comment]
Because I restarted the job on Travis I cannot provide a link to the log above, but I found a [job](https://travis-ci.org/hpi-swa-teaching/SWT18-Project-13/jobs/396783693) that wasn't restarted yet but also crashed.
Usually one of 4 jobs crashes no matter what Squeak version or OS, but restarting that one helps getting Travis run through.

**Comment by fniephaus** [comment]
Ok, so it's flaky. Is coverage testing enabled?

**Comment by mschroederi** [comment]
Yes, Coveralls is enabled.

**Comment by fniephaus** [comment]
This appears to be a bug in the vm, I've closed this here and opened a new bug at https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/272.
