### ISSUE TITLE
Headless for Linux no set

### ISSUE THREAD

**Issue by LukasBudach** [hpi-swa/smalltalkCI#383]
As I included a isHeadless check in my postLoad code I noticed, that TravisCI seems to not set the isHeadless property while launching Squeak5.1 on Linux.
On Mac everything works fine in 27 seconds.

**Comment by fniephaus** [comment]
https://github.com/hpi-swa/smalltalkCI/commit/144b4b6b0cc8e884837234f49a0d698a7f7f38a8 should fix this issue once merged into `master`. Also, I've pushed [`System-fn.1039`](http://forum.world.st/The-Trunk-System-fn-1039-mcz-td5082542.html) to correctly detect `-nodisplay` in future releases of Squeak.
