### ISSUE TITLE
No coverage data with Pharo 7

### ISSUE THREAD

**Issue by cdlm** [hpi-swa/smalltalkCI#386]
I recently disabled Pharo 6.1 builds for [Clap](https://github.com/cdlm/clap-st) on Travis, and do not get coverage updates anymore. In fact looking back on the latest builds, we can see that [coveralls only received data for builds x.3, x.4, x.7, and x.8](https://coveralls.io/builds/18160551) which correspond to the 6.1 builds. So it seems that none of my 7.0 builds ever uploaded coverage…

**Comment by gcotelli** [comment]
For the log it seems no coveralls data is being generated:
```
Running suite "Clap" with 47 tests.
...............................................Finished running suite: Clap
Coveralls data is not available. Skipping coverage testing... 
```
Maybe you changed something in `.smalltalk.ston` and now it's not running the coverage?

**Comment by gcotelli** [comment]
I've checked some of our builds and we get the same message for Pharo 7 jobs, but works for Pharo 6.1 jobs in the same build. So it looks like some problem in smalltalkCI with Pharo 7.

**Comment by fniephaus** [comment]
The TestCoverage class was removed in Pharo 7, don't know from the top of my hat if that's why it's not working. Will look into this soon!

**Comment by fniephaus** [comment]
Fixed via https://github.com/hpi-swa/smalltalkCI/commit/61e2f3c00314c68757f93673373bb814b8a5f5de.
