### ISSUE TITLE
Travis ulimit problem even with sudo enabled

### ISSUE THREAD

**Issue by cdlm** [hpi-swa/smalltalkCI#388]
See https://github.com/travis-ci/travis-ci/issues/6815

Here's an instance of the VM complaining in one of my builds: https://travis-ci.org/cdlm/clap-st/jobs/413185194#L785

**Comment by fniephaus** [comment]
[`pthread_setschedparam failed: Operation not permitted`](https://travis-ci.org/cdlm/clap-st/jobs/413185194#L653) suggests that your build did not run on a sudo-enabled container. Could you try again with `sudo: true`?

**Comment by cdlm** [comment]
Right… I must have force-pushed over previous attempts… just pushed `sudo: true`

**Comment by fniephaus** [comment]
Interesting..even though [the newer build ran on GCE which is sudo-enabled](https://travis-ci.org/cdlm/clap-st/jobs/413594096#L13), raising rtprio failed. I'll have a look in the next couple of days.

On the other hand, maybe we should hide these instructions in the VM somehow. AFAIK, no one has encountered any weird problems if rtprio is not raised.

**Comment by cdlm** [comment]
TBH I'm mostly annoyed by the noise in stderr; if there was a way to silence VM diagnostics or to separate them from what the image sends to stdout/err, for instance by setting a different logger, I wouldn't care that much about this…

**Comment by fniephaus** [comment]
@cdlm sorry for the issue ping pong, but maybe open another issue for discussing the removal of this note at https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/new?

**Comment by fniephaus** [comment]
Considering the possible problems of incorrectly using threaded VMs (see https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/275#issuecomment-411569935), maybe it would be better to use itimer VMs across all smalltalkCI builds. What do you think, @estebanlm?

**Comment by estebanlm** [comment]
No, there is a reason why we use the threaded VM instead the iTime. There are several cases, but as example: The iTimer heartbeat will break the usage of SSH2 channels and with that any usage of libgit2 hence Iceberg.
While I would want a solution for the usage of the threaded heartbeat, not using it is not an option for us now (I'd like an idle VM, instead a heartbeat, I think that's the correct way to go... but is a lot of work and is not happening soon :( )

**Comment by fniephaus** [comment]
@estebanlm thanks! That's good to know.
Does Iceberg work correctly when running on a threaded VM without rtprio being raised?
And what would you do about the rtprio warning OSVMs print all the time on Travis and such?

**Comment by fniephaus** [comment]
@cdlm please restart your sudo-enabled builds, should work now :)
