### ISSUE TITLE
Coverage fails on Tonel format if a Trait is present

### ISSUE THREAD

**Issue by JurajKubelka** [hpi-swa/smalltalkCI#390]
The reason is that a `*.class.st` file is expected instead of `*.trait.st` file. Here is a proposed change:

```Smalltalk
SCIPharoCodeCoverage class >> tonelFilePathFor: class in: aDirectoryName
	| packageName packagePath |
	packageName := self packageNameForClass: class.
	packagePath := aDirectoryName , SmalltalkCI pathNameDelimiter , packageName.
	^ (SmalltalkCI fileExists: packagePath)
		ifTrue: [ packagePath , SmalltalkCI pathNameDelimiter , class theNonMetaClass name , 
			(class isTrait ifTrue: [ '.trait.st' ] ifFalse: [ '.class.st' ]) ]
		ifFalse: [ "This can be an extension. Currently not supported" SCIError signal: 'Extensions are unsupported in coverage' ]
```

I am not sure if it should be `class theNonMetaClass isTrait`.

**Comment by JurajKubelka** [comment]
A failing example is here: https://travis-ci.org/pharo-graphics/Bloc/jobs/420368576#L1897

**Comment by gcotelli** [comment]
As far as I remember the code coverage reporter is not prepared to work
with traits, so even if the file name don't fail I think the coverage
reported wouldn't be correct. Because the trait methods are never executed
in the context of the trait but in the class using the trait, so you need
to implement this detection.

I think it's better to ignore the traits by now ( so it never reaches the
problematic part) , and open a new issue to implement the coverage
reporting for traits.

I will take a look later when I have access to my computer.

**Comment by fniephaus** [comment]
Thanks for opening this issue, @JurajKubelka, and @gcotelli for looking into this. I've added both of you as collaborators of smalltalkCI. :)
Coverage testing is quite hard, especially in such a dynamic system. Happy to review and merge a PR with support for traits.

**Comment by gcotelli** [comment]
@JurajKubelka can you try including
```
smalltalk_edge:
  source: gcotelli/smalltalkCI
  branch: master
```
in your travis config?

If the build passes I will propose a proper PR, and open a new issue to consider the coverage support for traits. But at least you can have your build working again.

**Comment by gcotelli** [comment]
PR is on the way. I've forked the problematic project and changed it to use my branch for testing. See https://travis-ci.org/gcotelli/Bloc/jobs/420503067.

**Comment by gcotelli** [comment]
@fniephaus I think the PR is ready to be reviewed and merged.

**Comment by fniephaus** [comment]
As mentioned by @gcotelli, please open a new issue for adding code coverage support for traits. Until then, traits are excluded from coverage testing (see #391).

**Comment by JurajKubelka** [comment]
Thank you! I was not available today.
