### ISSUE TITLE
Issues using `non-closing-test` branch with GsDevKit_home

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#392]
Currently in GsDevKit_home, I have written code that looks like the following:
```smalltalk
ci := projectPath isEmpty
	ifTrue: [ (Smalltalk at: #SmalltalkCI) load: '/home/dhenrich/rogue/_homes/rogue/_devkit/shared/repos/GemStone-GCI/.smalltalk.ston' ]
	ifFalse: [ 
		(Smalltalk at: #SmalltalkCI)
			load: '/home/dhenrich/rogue/_homes/rogue/_devkit/shared/repos/GemStone-GCI/.smalltalk.ston'
			projectDirectory: projectPath ] 
```
Where I'm expecting an instance of SmalltalkCI to be returned (the current behavior on the `master` branch), however with the code on the `non-closing-test` branch, I get back a **Boolean** and I am curious if that is intentional or not.

I've tracked the change in behavior of the 'master' branch versus the  `non-closing-test` branch to a change to the SmalltalkCI>>load method. Here's the `master` branch implementation:
```smalltalk
load
  self class withBuildStatusReportingDo: [ self basicLoad ]
```
and here's the  `non-closing-test` branch implementation:
```smalltalk
load
  ^ self class withBuildStatusReportingDo: [ self basicLoad ]
```
If the change is intentional, then I will have to find another way to get the SmalltalkCI instance ... In this particular instance I am sending the message #compatibleConfigurationsFor: to the returned object (formerly a SmalltalkCI instance):
```smalltalk
 (ci compatibleConfigurationsFor: #gemstoneClient) do: [:configSpec |
            configSpec defaultSessionName ifNotNil: [:sessName |  sessionName := sessName ]]
```
to pull the defaulSesionName from the configuration spec...

**Comment by fniephaus** [comment]
Hi Dale,
I changed the return value on purpose and was hoping nobody replies on it, but I do understand why you need. Let's put this on hold until the beginning of next month, hope you don't mind.

**Comment by dalehenrich** [comment]
Sounds like a plan ... I’ll be at ESUG for the next 2 weeks, so this works well for me

**Comment by fniephaus** [comment]
Perfect and enjoy ESUG! :)

**Comment by dalehenrich** [comment]
I think it is safe to close this issue at this point in time
