### ISSUE TITLE
Weird issue when running a build

### ISSUE THREAD

**Issue by bergel** [hpi-swa/smalltalkCI#394]
I have the following error:

<img width="899" alt="screenshot 2018-09-14 10 57 41" src="https://user-images.githubusercontent.com/393742/45540626-32baf900-b80d-11e8-817c-179bb9d637b2.png">
Any idea what's going on?

My `.travis.yml` is
```
➜  Roassal2 git:(master) ✗ cat .travis.yml
language: smalltalk

os:
  - osx
  - linux

smalltalk:
  - Pharo-stable
  - Pharo-6.1
  - Pharo(64)-6.0
  - Pharo(64)-6.1
  - Pharo(64)-7.0
```

**Comment by fniephaus** [comment]
Oh, the image identifiers should not contain round brackets. They are meant to be interpreted as some sort of regex, so "Pharo(64)-..." stands for "Pharo-..." *or* "Pharo64-...". Maybe it's better to list all possible identifiers explicitly in the README.md. Feel free to open a PR for that.
