### ISSUE TITLE
Release test testAllClassInstanceVariablesStartLowercase fails because of SmalltalkCI

### ISSUE THREAD

**Issue by pavel-krivanek** [hpi-swa/smalltalkCI#395]
The release test ProperlyImplementedClassesTest>>#testAllClassInstanceVariablesStartLowercase on Pharo that checks that class instance variable names must start with a lowercase letter fails because of the SmalltalkCI. It is because of these variables:

SmalltalkCI class->#PlatformClass 
SmalltalkCI class->#TravisID 
SmalltalkCI class->#DeprecationWarnings 
SCIGemStoneServerConfigSpec class->#DefaultSessionName 
SCICustomScript class->#PlatformClass 
SCIMetacelloLoadSpec class->#PlatformClass 
SCIMonticelloLoadSpec class->#PlatformClass

**Comment by fniephaus** [comment]
Thanks for raising this issue, @pavel-krivanek. What is this test case for and when is it usually being run? Feel free to provide a PR, the fix should be relatively straightforward.

**Comment by pavel-krivanek** [comment]
Hi, for the Moose, I'm trying to run all tests in the image.

**Comment by fniephaus** [comment]
Ok, I can't work on this at the moment. Probably best to just exclude the corresponding TestCase in your .smalltalk.ston until this has been resolved.

**Comment by fniephaus** [comment]
@pavel-krivanek could you please try again and let me know if `testAllClassInstanceVariablesStartLowercase ` now passes for you? Thanks!

**Comment by pavel-krivanek** [comment]
It seems to be fixed now. Thank you very much!

**Comment by fniephaus** [comment]
Perfect, thanks for checking!
