### ISSUE TITLE
The method ClassDescription>>#theMetaClass was deprecated

### ISSUE THREAD

**Issue by syrel** [hpi-swa/smalltalkCI#402]
Hi

Looks like the following methods are deprecated in Pharo 7. What could be the solution?

> The method ClassDescription>>#theMetaClass called from SCICodeCoverage>>#allPackagesUnderTestOf: has been deprecated.
> Please use #classSide instead

> The method ClassDescription>>#theNonMetaClass called from SCICodeCoverage>>#classesAndMetaclassesOf: has been deprecated.
> Please use #instanceSide instead

Thanks

**Comment by fniephaus** [comment]
Hi @syrel,
Looks like we need to override these methods in [`SCIPharoCodeCoverage`](https://github.com/hpi-swa/smalltalkCI/tree/master/repository/SmalltalkCI-Pharo-Core.package/SCIPharoCodeCoverage.class), probably using `respondsTo:` to provide compatibility.
Would you be able to work on this?

**Comment by fniephaus** [comment]
Thanks!

**Comment by gcotelli** [comment]
I've just got bitten by that. One of my jobs (https://api.travis-ci.org/v3/job/496164772/log.txt) is failing because this deprecation warnings are making the log file to exceed the maximum supported length.
`
The job exceeded the maximum log length, and has been terminated.`
