### ISSUE TITLE
Pharo 7 downloads are not working

### ISSUE THREAD

**Issue by pavel-krivanek** [hpi-swa/smalltalkCI#404]
Pharo 7 changed the image name schema. Now it is like `Pharo7.0-SNAPSHOT-64bit-12a3a9f.image`.

**Comment by pavel-krivanek** [comment]
The issue is directly in zeroconf

**Comment by fniephaus** [comment]
Could you please provide some links to failing builds on TravisCI, etc?

**Comment by fniephaus** [comment]
@estebanlm could you please comment on this?

**Comment by pavel-krivanek** [comment]
It is fixed. Esteban reverted his changes in the build process for now. Sorry for the noise. From the perspective of the SmalltalkCI, nothing should change as soon as it will be properly merged again because SmalltalkCI uses the ZeroConf that should hide such changes.

**Comment by fniephaus** [comment]
Ok, great. Thanks for the update!
