### ISSUE TITLE
Newest change on environment variable accessing under Pharo break Smalltalk CI.

### ISSUE THREAD

**Issue by juliendelplanque** [hpi-swa/smalltalkCI#406]
On Pharo 7.0

See this build: https://travis-ci.org/moosetechnology/PetitParser/jobs/471005156

Because of this PR: https://github.com/pharo-project/pharo/pull/1980

**Comment by jecisc** [comment]
Thank you @fniephaus !

**Comment by juliendelplanque** [comment]
Thank you a lot!
