### ISSUE TITLE
Exclude one test

### ISSUE THREAD

**Issue by badetitou** [hpi-swa/smalltalkCI#413]
I did not find in the documentation if it's possible to exclude only one specific test ?

**Comment by fniephaus** [comment]
Hi @badetitou,
You can only exclude entire classes in the smalltalkCI config, but you can mark tests as excludedFailures ([example](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Excluded-Tests.package/SCIExcludedTests.class/instance/expectedFailures.st)) in the same way you would mark them in your image. Does this solve your problem?

**Comment by badetitou** [comment]
Hi @fniephaus,

Thanks for the answer. 
It does not solve my problem because I do not want to modify my image and want to only exclude two tests. 
If it's not possible, I will find another way... 

Thanks !

**Comment by fniephaus** [comment]
Mh, I'm not sure smalltalkCI should allow excluding single tests cases, you can always use and exclude a dedicated class if you really need that ability. What you probably want to do is to skip/ignore the test, it could either be an expected failure or you could ensure it's not fully executed when running on CI. Closing this for now
