### ISSUE TITLE
CI support for Pharo 6/7 is broken with the overlap of include, exclude directives due to Tag names

### ISSUE THREAD

**Issue by macta** [hpi-swa/smalltalkCI#417]
I am seeing strange results when trying to run a subset of my tests - I have 3 packages with sub tags
Exercism, ExercismDev, ExercismTools

ExercismDev has a composite TestCase called AllExercismTests, and it seems to be run even though its in the exclude list - making me wonder what the overlap of include / exclude is. Also - do I have to explicity set #allTestCases to false (it doesn't default to true does it? The docs aren't clear).

I specify the following:
```
 #testing : {
    #include : {
      #packages : [ 'Exercism', 'ExercismDev', 'ExercismTools' ]
    },
    #exclude : {
      #classes : [ #AllExercismTests, #ExercismSubmitTest, #ExercismDownloadTest ],
      #packages : [ 'ExercismWIP']
    }
  }
```

**Comment by macta** [comment]
It also seems to run all my tests twice - is this a consequence of not setting #allTestCases?

**Comment by macta** [comment]
Testing with #allTestCases : false makes no difference (so that works like I expect).

Is it possible that having packages with sub-tags causes an issue? In Pharo , I have exercises tagged underneath Exercism (e.g. Exercism-HelloWorld) and these are all running 2x as well.

Exclude by class doesn't seem to do anything - so maybe its broken?

**Comment by macta** [comment]
You can view my results here (if it helps) : https://github.com/exercism/pharo-smalltalk/pull/155

**Comment by macta** [comment]
Is it possible that #include('Exercism') also matches 'ExercismWIP' and 'ExercismTools'? It appears this way as I've added a new test to ExercismTools that is environmental specific and for now is not supposed to run on my CI, and it has started to run on Travis?

I think this might be a bug?

**Comment by fniephaus** [comment]
Hi @macta,
Sorry for the slow response. I'm not too familiar with Pharo packages, but in Squeak, `Exercism` would be the parent category including `ExercismWIP` and `ExercismTools` because it's a prefix. What happens when you save the `Exercism` package, does it include the two sub packages as well or are they separate? If the latter is true, this might be a bug in smalltalkCI.

**Comment by macta** [comment]
These are separate packages. My Exercism package does have different sub-packages (called tags) and they appear as Exercism-Acronym, Exercism-Anagram etc. Equally ExercismWIP has tags like ExercismWIP-Triangle, ExercismWIP-Words.

So yes, I think it’s a bug. The top level package does answers all the classes in itself and sub tags, so possibly it’s just a name March thing.

**Comment by macta** [comment]
Thinking a bit more - apart from this mismatching - the fact that I got duplicate runs of the same class would indicate you dont use a Set to avoid duplicates?

**Comment by fniephaus** [comment]
[`SmalltalkCI class>>classesWithPackageNames:`](https://github.com/hpi-swa/smalltalkCI/blob/5f28f7cfac13ac2465d9718c84726a19d63e4528/repository/SmalltalkCI-Core.package/SmalltalkCI.class/class/classesWithPackageNames..st) is using a set, but maybe at a later stage, smalltalkCI might be using something else. Some of the logic is Pharo-specific, see [`SmalltalkCIPharo class>>classesInPackage:`](https://github.com/hpi-swa/smalltalkCI/blob/5f28f7cfac13ac2465d9718c84726a19d63e4528/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/class/classesInPackage..st) for example. Maybe insert a `self halt` somewhere in that code and debug it in `--headful` mode. I currently don't have any free cycles to work on this, but I'm happy to answer any questions and to review PRs ;)

**Comment by macta** [comment]
I'm in the thick of something else now - but will have to come back to this and see if I can propose a fix. Your hint should get me started. thanks.
