### ISSUE TITLE
Pharo 8 build does not show test results

### ISSUE THREAD

**Issue by jecisc** [hpi-swa/smalltalkCI#420]
When I have builds on Pharo 8, the Travis view seems to bug and do not display anything after the "Loading" phase. If I want to see the test results, I need to check the raw logs. 

It seems to happen only on Pharo 8 builds.

**Comment by fniephaus** [comment]
Oh, I'm guessing that there's yet another encoding issue... could you please provide a link to one of your Pharo 8 builds?

**Comment by jecisc** [comment]
I have this one for example: https://travis-ci.org/pharo-spec/Spec/jobs/521764506

**Comment by fniephaus** [comment]
According to the [raw log file](https://api.travis-ci.org/v3/job/521764506/log.txt), there are lots of deprecation warnings and they are being highlighted as well (`[0m[0m` and `[31m[33m`). Is this new behavior introduced in Pharo 8? I'm guessing your problems goes away as soon as you fix all Pharo 8 deprecating warnings. Nonetheless, we need to find a fix for this for smalltalkCI. Is there any way to disable colorful output in Pharo 8?

```
...
travis_time:end:load_project_timer_8cd0:start=4204000000,finish=53365000000,duration=49161000000
[0Ktravis_fold:end:load_project_8cd0
[0Ktravis_fold:start:test_project_8cd0
[0Ktravis_time:start:test_project_timer_8cd0
[0K[1m[34mTesting project...[0m
Running suite "Pharo64-8.0 on Travis CI (606.2)" with 1126 tests.
The method TextPresenter>>#aboutToStyle: called from MethodBrowser>>#initializeWidgets has been deprecated.
This has been moved to specific presenters
[31m[33m
*** Warning: Deprecation: The method TextPresenter>>#aboutToStyle: called from MethodBrowser>>#initializeWidgets has been deprecated.
This has been moved to specific presenters
[0m[0mThe method TextPresenter>>#aboutToStyle: called from MethodBrowser>>#initializeWidgets has been deprecated.
This has been moved to specific presenters
[31m[33m
*** Warning: Deprecation: The method TextPresenter>>#aboutToStyle: called from MethodBrowser>>#initializeWidgets has been deprecated.
This has been moved to specific presenters
[0m[0mThe method TextPresenter>>#aboutToStyle: called from MethodBrowser>>#initializeWidgets has been deprecated.
This has been moved to specific presenters
...
```

**Comment by jecisc** [comment]
I thought it was not the problem because I have also deprecation warning on Pharo 7, but maybe I have more in Pharo 8. I'll need to check.

I don't know for the color output.

**Comment by fniephaus** [comment]
Maybe Pharo 7 does not support colorful stdout and that's why everything works fine? smalltalkCI also adds ASCII commands for TravisCI log folds, colors, etc...

**Comment by jecisc** [comment]
If color is managed via `[0m�[0m` and `[31m�[33m` , it seems it also happen on Pharo 7:

https://api.travis-ci.org/v3/job/522179969/log.txt

**Comment by fniephaus** [comment]
I noticed that there are some deprecation warnings in the Pharo 8 logs (see below). I fixed this with https://github.com/hpi-swa/smalltalkCI/commit/757e7d1cec488e14285f2838cb899c79ec5eab89. Could you please restart one of your Pharo 8 builds and check whether this has also fixed your issue?


### Pharo 8
```
...
Loaded -> SmalltalkCI-Pharo-Core-GabrielOmarCotelli.1524038808 --- filetree:///home/travis/smalltalkCI-master/repository [:] --- cache
...finished baselineThe method OSEnvironment class>>#default called from SmalltalkCIPharo class>>#getEnv: has been deprecated.
Please use #current instead
The method OSEnvironment>>#getEnv: called from SmalltalkCIPharo class>>#getEnv: has been deprecated.
Use #at:ifAbsent: instead
travis_fold:start:image_info_032d
[0Ktravis_time:start:image_info_timer_032d
[0K[1m[34mImage Information[0m
Image
-----
...
```

### Pharo 7
```
...
Loaded -> SmalltalkCI-Pharo-Core-GabrielOmarCotelli.1524038808 --- filetree:///home/travis/smalltalkCI-master/repository [:] --- cache
...finished baselinetravis_fold:start:image_info_481b
[0Ktravis_time:start:image_info_timer_481b
[0K[1m[34mImage Information[0m
Image
-----
...
```

**Comment by jecisc** [comment]
It works. Thank you very much! :)

**Comment by fniephaus** [comment]
Great, thanks for confirming!
