### ISSUE TITLE
smalltalkCI Breaks on Windows For Pharo6.1 on AppVeyor

### ISSUE THREAD

**Issue by hemalvarambhia** [hpi-swa/smalltalkCI#421]
As you are aware we use smalltalkCI for continuous integration for the PolyMath project. Currently I am working on an [issue](https://github.com/PolyMathOrg/PolyMath/issues/100) where on AppVeyor the Pharo6.1 Windows build is failing:  https://ci.appveyor.com/project/SergeStinckwich/polymath-88bea/builds/24063518

The [config](https://github.com/PolyMathOrg/DataFrame/blob/master/appveyor.yml) we are using is the same as the DataFrame project but whereas the same build there is green, it is red for PolyMath.

We are unable to get to the root cause of this at all, so your help and advice on this would be greatly appreciated. If you have any questions, please feel free to contact me or @SergeStinckwich.

**Comment by fniephaus** [comment]
That's an odd issue, thanks for filing. We need to debug this locally, but I don't have access to a Windows machine at the moment. I might have some time to have a look at this tomorrow, will keep you posted.

**Comment by fniephaus** [comment]
![image](https://user-images.githubusercontent.com/2368856/57108659-bc372100-6d33-11e9-9dc6-ab83bcfa538f.png)

@estebanlm the VM for Pharo 6.1 has problems to print to `stderr` (`PharoConsole.exe`).

**Comment by fniephaus** [comment]
`Pharo64-8.0` seems to work fine, `Pharo64-6.0` has the same problem.

`Pharo32-6.0` throws a different error:
![image](https://user-images.githubusercontent.com/2368856/57109236-33b98000-6d35-11e9-89c7-008850a3309e.png)

**Comment by fniephaus** [comment]
This is something smalltalkCI cannot fix. Assigning the issue to @estebanlm.

**Comment by SergeStinckwich** [comment]
Thank you Fabio for your investigation ! What is strange for me is that the build works for project like DataFrame: https://ci.appveyor.com/project/olekscode/dataframe/build/job/uvuxv98exk485oah not for PolyMath ...

**Comment by SergeStinckwich** [comment]
What is written on stdout ?

**Comment by fniephaus** [comment]
I'll have another look. smalltalkCI outputs all build log info through stdout. So without that, we wouldn't see anything.

**Comment by SergeStinckwich** [comment]
This is not related to the fact that some tests print things on Transcript ?

**Comment by SergeStinckwich** [comment]
Ok I remove all Transcript show in tests, and still the same error.

**Comment by fniephaus** [comment]
> What is strange for me is that the build works for project like DataFrame: https://ci.appveyor.com/project/olekscode/dataframe/build/job/uvuxv98exk485oah not for PolyMath ...

Interesting observation...is there any way PolyMath interacts with FileStream and invalidates stdio file handles for some reason?

**Comment by fniephaus** [comment]
also, [this](https://ci.appveyor.com/project/olekscode/dataframe/build/job/uvuxv98exk485oah) ran 21 days ago. Maybe @estebanlm updated the Windows VMs in the meantime?

**Comment by SergeStinckwich** [comment]
Yes might be the problem.

**Comment by fniephaus** [comment]
@SergeStinckwich what might be the problem? That the VM has changed or that PolyMath is closing `stdout`?

**Comment by SergeStinckwich** [comment]
the VM changed.

**Comment by fniephaus** [comment]
Has this been fixed in the meantime?

**Comment by hemalvarambhia** [comment]
We haven't tested yet. I will try it tonight and report back, @fniephaus.

**Comment by hemalvarambhia** [comment]
Just to report back, @fniephaus, we're noticing on the PolyMath project that smalltalkCI is [failing](https://travis-ci.org/PolyMathOrg/PolyMath/jobs/550208680)

I ran my tests locally and they're still green.

**Comment by hemalvarambhia** [comment]
We can close this now as, at least for PolyMath, it's not as pressing now that we're using Github Actions

**Comment by fniephaus** [comment]
Thanks for the update, @hemalvarambhia. This doesn't seem to be something we can fix from within smalltalkCI anyway, so I am going to close this for now.
