### ISSUE TITLE
SCIPharoCodeCoverageTest>>testMethodReferenceForSelector fails on Pharo 8

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#434]
[Example build failure](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/565996310#L631).

Could someone from the Pharo community (maybe @jecisc) have a look at this please?

**Comment by jecisc** [comment]
I tried to check the problem and apparently the Ring #name method changes of implementation in Pharo 8. 

If you want to get the selector of the method I think the best way is to use #selector instead of #name.

**Comment by jecisc** [comment]
Reading the code of SmalltalkCI I have the impression that the real code is already using #selector instead of #name. I guess we can just update the test.
