### ISSUE TITLE
Smalltalk-ci builds on Travis still run on Ubuntu Trusty

### ISSUE THREAD

**Issue by jbrichau** [hpi-swa/smalltalkCI#438]
I contacted Travis-CI support because all builds using Smalltalk-CI on Travis default to Ubuntu Trusty instead of Xenial.

They acknowledged the issue as specific to `language:smalltalk` builds.

Any idea if this requires a community effort to update base boxes for Smalltalk builds? I'm reaching out via this issue to see if we can be of help, or should we just wait for Travis support to handle the issue?

**Comment by fniephaus** [comment]
Could you please try again, @jbrichau?

**Comment by jbrichau** [comment]
Hi @fniephaus 
Right. I forgot about having reported that issue here but it has been fixed a month or two ago :)
I noticed our builds are now using Xenial.

**Comment by fniephaus** [comment]
Thanks for the update, glad it's working now!
