### ISSUE TITLE
Segmentation fault during error printing

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/smalltalkCI#440]
Now it also happens in Squeak 5.2 images. Might be a problem with the VM? The crash seems to be flaky in that it has varying symptoms. One is a reported segmentation fault, the other is an exit status code of 133, and the trunk images seem to mostly just quit silently as reported in #439.

The segfault, if any, happens here:
```
Smalltalk stack dump:
    0x7ffc37e3a2f8 M Context(Object)>copy 0x50e1690: a(n) Context
    0x7ffc37e3a340 M Context>copyTo: 0x1843430: a(n) Context
    0x7ffc37e3a398 I SCISqueakTestRunner>serializeError:of: 0x50cb070: a(n) SCISqueakTestRunner
    0x7ffc37e3a3e8 M [] in SCISqueakTestRunner(SCITestRunner)>runCase: 0x50cb070: a(n) SCISqueakTestRunner
```
https://travis-ci.org/hpi-swa/Squot/jobs/588685170#L364 (this is on Mac OS X, but also already happened on Linux already).

On Mac with Squeak-Trunk 32 Bits it printed this, but don't know if it gives a clue or is unrelated: 
```
/Users/travis/smalltalkCI-master/_builds/vm: line 1:  2347 Trace/BPT trap: 5       /Users/travis/smalltalkCI-master/_cache/vms/Squeak32-trunk/Squeak.app/Contents/MacOS/Squeak "$@"
Error with status code 133:
519 travis_wait /Users/travis/smalltalkCI-master/helpers.sh
271 squeak::run_script /Users/travis/smalltalkCI-master/squeak/run.sh
312 squeak::test_project /Users/travis/smalltalkCI-master/squeak/run.sh
```
https://travis-ci.org/hpi-swa/Squot/jobs/588685168#L367
I got similar output on a subsequent rebuild on Linux Squeak-5.2 64 Bits: https://travis-ci.org/hpi-swa/Squot/jobs/588685165#L771

In that same build, Mac Squeak-5.2 64 Bits and Linux Squeak-5.2 32 Bits finished as expected.

**Comment by j4yk** [comment]
Here is an instance where Linux Squeak-32-5.2 failed, so this particular VM is not "clean" either.
https://travis-ci.org/hpi-swa/Squot/jobs/588957676#L838

Actually, it is the only build in this particular set (503) that ended abnormally... all 64 bit builds are red due to a test failure, the other 32 bit builds are green.

**Comment by fniephaus** [comment]
Since we haven't updated the VM in a while, I suspect an image-side change to be responsible for the crashes. This might still be a VM bug and anyway this needs to be fixed. Let's try to debug this together on Thursday?

**Comment by j4yk** [comment]
We can try, sure. Hopefully we get enough "bad" builds to look at during that time. ;-)

**Comment by fniephaus** [comment]
I found the corresponding issues against OpenSmalltalk VM, which I filed more than a year ago: https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/265
