### ISSUE TITLE
SmalltalkCI suddenly doesn't know #failOnZeroTests any more

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#444]
My builds suddenly fail because I use `#failOnZeroTests`. `StonReader` bails because `SmalltalkCISpec` has no instance variable `failOnZeroTests`. I haven't been able to figure out what changed.

**Comment by theseion** [comment]
I put the instruction in the wrong context... 🤦‍♂

**Comment by fniephaus** [comment]
No worries, glad it's still working :)
