### ISSUE TITLE
smalltalk_config is suddenly always interpreted as array

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#448]
Travis appears to suddenly always treat `smaltlalk_config` as an array of strings. The `run.sh` script, however, assumes that it's always a simple string. This leads to the following error: 

> STON configuration could not be found at '/home/travis/build/theseion/Fuel/[.default.ston]'.

For me this started happening with this build https://travis-ci.org/theseion/Fuel/builds/647985949 from February 9.

AFAICT the problem lies with Travis (although it would be good to updated `run.sh`).

**Comment by fniephaus** [comment]
Well, that's annoying :( Could you propose a workaround in `run.sh`? Happy to review it.

**Comment by theseion** [comment]
Sure. Unfortunately, I couldn't find any information on how Travis injects array variables. Do you know whether they are injected as strings like `[1,2,3]` or as bash variables?

**Comment by fniephaus** [comment]
[Here's](https://github.com/travis-ci/travis-build/blob/0afb532b33b76d11c0ec308639f935dd458c596f/lib/travis/build/script/smalltalk.rb#L45) where the values are being exported. I'm guessing it's just a string?

**Comment by theseion** [comment]
Yes, it's a string I think. The fix simply extracts the first element since I don't think we support multiple STON files for a single configuration.

**Comment by fniephaus** [comment]
Please re-open if this does not work correctly. Should we also file a bug against TravisCI?

**Comment by theseion** [comment]
Looks like it works, thanks. I'll see if I can dig up anything that would have caused this on the Travis side.

**Comment by theseion** [comment]
Well, I tried to find something but couldn't. Nothing has been changed in the Smalltalk schema definition of the YAML but they have been working on travis-yml quite heavily lately, so maybe they messed up something. Do you want to open the issue? You know them already.
