### ISSUE TITLE
Folding issue if image preparation fails, missing line feed in log

### ISSUE THREAD

**Issue by j4yk** [hpi-swa/smalltalkCI#450]
In this build, you can see that you cannot see what is in "Preparing Squeak64-trunk image for CI..." if you unfold it. https://travis-ci.org/hpi-swa/Squot/jobs/659875039

Looking at the [raw log](https://api.travis-ci.org/v3/job/659875039/log.txt) you can see that there is no newline after the failure during the preparation. Does this cause the folding issue? If yes, can you force a line feed before the end of the duration end marker?

```
[0Ktravis_fold:start:prepare_image
[0Ktravis_time:start:18fc27b8
[0K[1m[34mPreparing Squeak32-trunk image for CI...[0m
...............................................Error: vmParameterAt:put: failedtravis_time:end:18fc27b8:start=1583786631092909388,finish=1583786864249902311,duration=233156992923
[0Ktravis_fold:end:prepare_image
```

EDIT: thou shallst not press rebuild after you posted a link...

Curiously during the rebuild, it went further and produced one dot more. Then the folding works.

```
[0Ktravis_time:start:14452cf7
[0K[1m[34mPreparing Squeak64-trunk image for CI...[0m
...........................Error: vmParameterAt:put: failed.travis_time:end:14452cf7:start=1583866370193496681,finish=1583866505807795397,duration=135614298716
[0Ktravis_fold:end:prepare_image
```

https://travis-ci.org/hpi-swa/Squot/jobs/659875037

EDIT 2: And right after I posted the first EDIT, the folding no longer works even with the additional dot. I'm puzzled.

**Comment by fniephaus** [comment]
Travis folds are an undocumented feature, and they likely trigger bugs if used by third parties like us.
We could force a new line, but I am not sure this fixes the problem. My rule of thumb is: folds are not allowed to break if the build succeeded.

**Comment by fniephaus** [comment]
It's hard to reproduce problems like this...closing this for now
