### ISSUE TITLE
Travis Build Fails Due To Error While Generating Build Script

### ISSUE THREAD

**Issue by hemalvarambhia** [hpi-swa/smalltalkCI#451]
**Project:** PolyMath.

Here is [an example of the error](
https://travis-ci.org/github/PolyMathOrg/PolyMath/jobs/665499216?utm_medium=notification&utm_source=email) for the push travis build. The environment the tests were run on is a 32-bit Pharo 7.0 image for MacOSX. What's interesting is that: 

- the [push build](https://travis-ci.org/github/PolyMathOrg/PolyMath/jobs/665499212?utm_medium=notification) for the linux version of that build is green

- the [PR build is green](https://travis-ci.org/github/PolyMathOrg/PolyMath/builds/665499226?utm_source=github_status&utm_medium=notification). 

Would a colleague be able to assist here?

**Comment by fniephaus** [comment]
Thanks for filing this issue, @hemalvarambhia.

It looks like this is due to the Travis CI outage: https://www.traviscistatus.com/incidents/7mbxh26jk3sl

Please re-open if the issue persists.
