### ISSUE TITLE
Upgrade Squeak stable Images for WebClient Fix

### ISSUE THREAD

**Issue by tom95** [hpi-swa/smalltalkCI#457]
A fix to WebClient has been backported to 5.3, 5.2, and 5.1: http://forum.world.st/The-Trunk-WebClient-Core-tobe-121-mcz-td5116242.html

I am currently in the process of fixing Squeak builds for Metacello https://travis-ci.org/github/Metacello/metacello/builds/684719345 and depend on these backports for some tests to pass, in particular these three: https://travis-ci.org/github/Metacello/metacello/jobs/684719372

**Comment by fniephaus** [comment]
This is how the new images were generated:

```smalltalk
| monitor |
FileStream startUp: true. "Reload stdio file handles"
Utilities setAuthorInitials: 'smalltalkCI'.
TranscriptStream redirectToStdOut: true.

"Avoid showing system progress bar and using graphical tools."
Project current instVarNamed: #uiManager put: DummyUIManager new.
ToolSet default: (Smalltalk at: #CommandLineToolSet).

monitor := [ [
	FileStream stdout nextPutAll: '.'.
	(Delay forMilliseconds: 5000) wait] repeat ] forkAt: 75.

[[[[

Transcript show: 'Updating...'.
MCMcmUpdater default doUpdate: false.
Transcript show: 'finished.'; cr; showln: SystemVersion current printString.

] on: ProgressNotification do: [:p | p resume]
] on: Warning do: [:warning | warning resume]
] on: MCNoChangesException do: [:ex | ex resume]
] on: MCMergeResolutionRequest do: [:mrr |
	mrr merger conflicts do: [:conflict |
		conflict chooseRemote].
	mrr resume: true].

monitor terminate.
monitor := nil.

Smalltalk at: #Metacello ifPresent: [ :m | m new "load metacello" ].
Smalltalk at: #Metacello ifAbsent: [ "///////////////////"
"Get the Metacello configuration (for Squeak users)"
Installer gemsource
    project: 'metacello';
    addPackage: 'ConfigurationOfMetacello';
    install.

"Bootstrap Metacello Preview, using mcz files (#'previewBootstrap' symbolic version"
((Smalltalk at: #ConfigurationOfMetacello) project 
  version: #'previewBootstrap') load.

"Load the Preview version of Metacello from GitHub"
(Smalltalk at: #Metacello) new
  configuration: 'MetacelloPreview';
  version: #stable;
  repository: 'github://Metacello/metacello:configuration';
  load.

"Now load latest version of Metacello"
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://Metacello/metacello:master/repository';
  get.
(Smalltalk at: #Metacello) new
  baseline: 'Metacello';
  repository: 'github://Metacello/metacello:master/repository';
  load.
"/////////////////////////////" ].

Transcript showln: 'Reverting update-specific changes...'.
TranscriptStream redirectToStdOut: false.
TranscriptStream forceUpdate: true.
ToolSet default: (Smalltalk at: #StandardToolSet).
Project current instVarNamed: #uiManager put: MorphicUIManager new.

"Close all windows"
ReleaseBuilder deleteAllWindows.
Project current world removeAllMorphs.
Project current removeMainDockingBar.
TheWorldMainDockingBar updateInstances.

"Only keep the latest changes"
Smalltalk condenseChanges.

Smalltalk snapshot: true andQuit: true.
```

**Comment by tom95** [comment]
Sadly, the fix appears to not have made its way to Squeak5.2 yet (https://travis-ci.org/github/Metacello/metacello/jobs/687125170) and I received an error while trying to fetch the 5.1 image (https://travis-ci.org/github/Metacello/metacello/jobs/687125169). 5.3 however appears to run fine now though! :)

I confirmed locally that pulling the 5.2 smalltalkCI image and running updates again will install the fix.

**Comment by fniephaus** [comment]
Ok, upgrading the images has uncovered a new issue: Metacello appears to be still depending on the old repository WebClient was hosted in before it was merged into Squeak. Therefore, the backported changes were basically reverted after Metacello was loaded. Loading Metacello before updating seems to avoid this, but is not necessarily a good long-term fix.

/cc @dalehenrich @krono

**Comment by fniephaus** [comment]
Apparently, @krono already fixed this with `ConfigurationOfMetacello-topa.803` on http://seaside.gemtalksystems.com/ss/metacello. However, [the config](https://github.com/Metacello/metacello/tree/configuration/ConfigurationOfMetacelloPreview.package/ConfigurationOfMetacelloPreview.class) used when following the Metacello instructions is notoriously out of date.

**Comment by fniephaus** [comment]
The updated 5.1 images uncovered another issue: Metacello does no longer work correctly on 5.1, due to https://github.com/Metacello/metacello/commit/bcd5d2f39be94703b9643ea89470524cb9c2d9c6. I'm going to pin Metacello in 5.1 to https://github.com/Metacello/metacello/commit/51e7b0fecadd1531513a8903113675cdc72e3ed8, the commit right before compatibility was broken.

**Comment by tom95** [comment]
Instead of pinning, another option might be to backport the `#setAuthorIntials:` to `#authorInitials:` rename to 5.1. Might be easier to keep tracking of things that way. I think I would only go with pinning if we decide to also drop 5.1 checks for Metacello on travis.

**Comment by fniephaus** [comment]
It's actually the other way around (`#authorInitials` is not present in 5.1). I'm going to manually backport it for smalltalkCI images. Will update the used script in the comment above accordingly.

**Comment by fniephaus** [comment]
@tom95 all images should now be functional. Please verify on your side.

**Comment by tom95** [comment]
Looking good! Travis failed for 5.2 with the same error, but it work with a local smalltalkCI, so I'll assume it was a random occurrence, maybe like a cache kicking in. If another run, when I pushed more changes, turns out to fail I'll report back.
