### ISSUE TITLE
Errors running SmalltalkCI tests against GemStone 3.5.1 and above (apparently)

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#459]
GemStone builds of Grease began failing for GemStone 3.5.1 several weeks ago (https://travis-ci.org/github/GsDevKit/Grease/jobs/696955030) and appears to e failing during a the `SCIGemStoneMetacelloLoadSpec class (SCIMetacelloLoadSpec class) >> updateMetacello @11 line 9` call (https://travis-ci.org/github/GsDevKit/Grease/jobs/702843448#L2003-L2080).... 

I don't think G/S 3.5.1 has been added to the lineup yet, so I will need to dig deeper.

**Comment by dalehenrich** [comment]
ping ... @jbrichau, I willbe digging deeper later this afternoon

**Comment by dalehenrich** [comment]
In debugging the error, I see that `useLatestMetacello` is true in `SCIMetacelloLoadSpec >> useLatestMetacello` and for GemStone it should be false, as GemStone comes loaded with the latest Metacello. On top of that `:SCIMetacelloLoadSpec class >> updateMetacello` is trying to load force a load of Metacello from the `Metacello/metacello` repository instead of `dalehenrich/metacello-work` which is being used by GemStone at the moment:
```Smalltalk
   updateMetacello
           (Smalltalk at: #Metacello) new
                   baseline: 'Metacello';
                   repository: 'github://Metacello/metacello:master/repository';
                   get.
           (Smalltalk at: #Metacello) new
                   baseline: 'Metacello';
                   repository: 'github://Metacello/metacello:master/repository';
                   load: #( 'batch' )
```
Part of the reason that is that during the SmalltalkCI loads in GemStone, I am disallowing locks --- a technique that has been working for a very long time ... until about 30 days or so ago? 

Anyway, I'm not sure which change caused the builds to start failing (my 3.5.0 test build is also failing with `Security violatio` error, which doesn't seem to be happening in the wild), so a little more digging will be needed ...

**Comment by dalehenrich** [comment]
It seems that the difference between a passing travis and a failing travis is that the following line shows up when failing:
```
--transcript--'Fetched -> Metacello-MC-tobe.738 --- github://Metacello/metacello:master/repository [348ac29:master] --- github://Metacello/metacello:master/repository'
```
A look at the Metacello travis runs, shows that the [3.5.0 build](https://travis-ci.org/github/Metacello/metacello/jobs/701468202#L1774) was failing with the same problem as seen elsewhere. I approved the release with failing GemStone builds, because I did not realize that smalltalkCI was `unconditionally` updating Metacello in GemStone builds ... The [expected failures in GemStone were expected to be some failing json tests](https://travis-ci.org/github/dalehenrich/metacello-work/jobs/695548452#L4303).

... at this point, I think I'm included to have the default value of `SCIMetacelloLoadSpec >> useLatestMetacello` for GemStone be false, since there is no value in getting the latest version, since GemStone builds always should be using the latest Metacello versions ... by definition ... this will then decouple Metacello/metacello from use in GemStone until a fix to the Metacello/metacello builds can be made.

**Comment by dalehenrich** [comment]
From looking at code, it seems that `SCIMetacelloLoadSpec >> useLatestMetacello` must be set to true, but the standard default value for useLatestMetacello is `false` and I cannot find where the code that sets updateMetacello to true and causes `SCIMetacelloLoadSpec class >> updateMetacello` to be called...

**Comment by dalehenrich** [comment]
Ahhhhhh, finally tracked the `problem` down to the fact that [Grease explicitly sets `useLatestMetacello` to true](https://github.com/GsDevKit/Grease/blob/master/.smalltalk.ston#L7) ... and now I believe that GemStone should ignore that setting, because it shouldn't apply to GemStone builds as Metacello is always the `latest` for GemStone ...

**Comment by dalehenrich** [comment]
Now that SeasideSt/Grease#105 has been resolved, we can close this issue ... [no modifications required (see comments starting here for more details)](https://github.com/SeasideSt/Grease/issues/105#issuecomment-651444990)

**Comment by fniephaus** [comment]
Thanks Dale!
