### ISSUE TITLE
any insight as to why this build is erroring out?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#460]
(This build](https://travis-ci.org/github/dalehenrich/metacello-work/builds/705615804) has massive failures, while the [PR](https://travis-ci.org/github/dalehenrich/metacello-work/builds/704519011) and [previous master](https://travis-ci.org/github/dalehenrich/metacello-work/builds/704534645) builds succeeded.
Here's the error (from https://travis-ci.org/github/dalehenrich/metacello-work/jobs/705615809):
![image](https://user-images.githubusercontent.com/623951/86814048-be7ec480-c035-11ea-91a2-a5ec4626cacc.png)
Other project do not seem to be affected ... I think that I cleared the caches before rerunning the above build ... ... the heroku failure is a complete mystery...

**Comment by dalehenrich** [comment]
I see that it is running [Ubuntu 20.04](https://travis-ci.org/github/dalehenrich/metacello-work/jobs/705615809#L18), while a `linux` run started a few minutes later is running 16.04?

**Comment by dalehenrich** [comment]
No information on the [Travis page](https://docs.travis-ci.com/user/reference/overview/) and it still claims that 16.04 is the default environemtn ... how can I get 16.04 back?

**Comment by gcotelli** [comment]
The build log states that it must be using Xenial (16.04) 
```
Build language: smalltalk
Build dist: xenial
```
But later it reports is running Focal Fossa (20.04), so it's probably a Travis problem. You can try reaching it's support. I've tried in the past with not so much success :man_shrugging: (by the time they responded the build was fixed without any change from my side), but maybe you have better luck.

**Comment by dalehenrich** [comment]
@gcotelli, thanks for the quick response ... I've looked around and I haven't found information about how to "contact support" ... what's odd is that concurrent builds are not exhibiting the problem, while the problem build refuses to behave... I guess I'll just try again every couple of hours and see if my builds self heal:)

**Comment by gcotelli** [comment]
support@travis-ci.com , it's hidden in a tiny link at the bottom of the page. This talks about how much care it receives :facepalm:

**Comment by dalehenrich** [comment]
thx

**Comment by dalehenrich** [comment]
sent my mail to support@travis and will see where this gets me:)

**Comment by dalehenrich** [comment]
Looks like [SeasideSt/Parasol jobs are failing with same problem as Metacello](https://travis-ci.org/github/SeasideSt/Parasol/jobs/706005511) ... sent mail to travis-ci support yesterday and not a peep from them ...

**Comment by jbrichau** [comment]
So, last time this happened (see https://github.com/hpi-swa/smalltalkCI/issues/438), the travis-ci support guys told me that it's the combination of 'smalltalk' with 'xenial' that was running into the problem.

It appears it's not such a high-profile problem for them (even though we use a commercial license) as they said: 'we will look into it, you will see when it gets fixed' and it took them 3-4 months to fix.

**Comment by jbrichau** [comment]
Mind that it seems many builds are failing because of issues on 'Focal': https://travis-ci.org/github/SeasideSt/Seaside/builds/706509827

**Comment by fniephaus** [comment]
This is unfortunate, hopefully it'll soon be fixed on Travis' side. BTW: Has anyone managed to run OpenSmalltalkVM on Focal yet?

**Comment by dalehenrich** [comment]
In the support request that I opened, they gave me the same line about smalltalk being a community supported project. Are we certain, that this isn't really a smalltalk-only problem? In my case the issue first occurred during a CRON run, so I had not touched the .travis.yml, since then I have added an explicit request for `dist: Xenial` to my .travis.yml, and the support person pointed out that i spelled `Xenial` wrong, but I had also usd `xenial` as well ... 

If it is only occurring in the smalltalk builds, then there might be something that can be done in self defense, even if it is a travis problem at the core?

**Comment by jbrichau** [comment]
Just to keep you in the loop, the response I got from Travis-CI support is: 
>Thanks for writing in and sorry for this issue.
> I have raised this with our Engineering team and will follow up with you once I get feedback.
It _is_ the same start as last time, but give that I referenced the issue from last year, maybe there is some hope...

**Comment by dalehenrich** [comment]
And I just got this email fro support:
>Thanks for writing back in and sorry about this issue.
>
>I found a previously resolved ticket from last year with a slightly similar issue. I have raised this with our Engineering team and will provide updates as soon as they get back.
>
>Once again, sorry about this issue.
The engineering team must not be in the building today:)

**Comment by jbrichau** [comment]
ROFLOL

**Comment by jbrichau** [comment]
Hurray! It got fixed!
@dalehenrich

**Comment by jbrichau** [comment]
Seaside build has a nice green color again: https://travis-ci.org/github/SeasideSt/Seaside/builds/706633463

**Comment by dalehenrich** [comment]
haha, just saw mail from support where they said they'd fixed the issue! Yay!

**Comment by dalehenrich** [comment]
reopening so that other users know that [the problem has resurfaced](https://travis-ci.org/github/Metacello/metacello/builds/707633473) ... I've mailed travis-ci support, so we'll see ...

**Comment by fvozzi** [comment]
I have a similar issue, maybe related or maybe not. But it starts to happend today:

![image](https://user-images.githubusercontent.com/9647240/87337868-8e925e00-c51a-11ea-8ef3-208a74bbe2cb.png)

**Comment by dalehenrich** [comment]
@fvozzi If your `build dist is `xenial` and the `Description` is `20.04`, then you are _are_ seeing the same problem:
![image](https://user-images.githubusercontent.com/623951/87340828-7a8c3380-c4fd-11ea-9d54-de6cd74a4530.png)

**Comment by fvozzi** [comment]
@dalehenrich It's working again now. Is your build working now?

**Comment by dalehenrich** [comment]
@fvozzi thanks for the ping ... restarted failing builds and they are passing again ...
