### ISSUE TITLE
CodeCoverage via Github Actions is not uploaded to Coveralls

### ISSUE THREAD

**Issue by Lasklu** [hpi-swa/smalltalkCI#461]
I try to integrate Coveralls in our [project](https://github.com/hpi-swa-teaching/TelegramClient) via Github Actions. After passing the CI I receive the confirmation that codecoverage will be uploaded (`Uploading coverage results to Coveralls...`) , but I cannot see the result in [coveralls](https://coveralls.io/github/hpi-swa-teaching/TelegramClient?branch=bugfix/GH-199).
As far as I know this works in travisCI but not in GHA.

What could be a possible solution?

Related files:
* [.smalltalk.ston](https://github.com/hpi-swa-teaching/TelegramClient/blob/bugfix/GH-199/.smalltalk.ston)
* [main.yml](https://github.com/hpi-swa-teaching/TelegramClient/blob/bugfix/GH-199/.github/workflows/main.yml)
* [workflow](https://github.com/hpi-swa-teaching/TelegramClient/pull/200/checks?check_run_id=931998225#step:4:47313)

**Comment by fniephaus** [comment]
Fixed via https://github.com/hpi-swa-teaching/TelegramClient/commit/dc15c7f6835089accc4f32bdc356252140a6f7f5.
