### ISSUE TITLE
smalltalkCI Assets

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#467]
This issue is used to collect assets (e.g. screenshots), so that they can be used in the `README.md` and in smalltalkCI's documentation.

**Comment by fniephaus** [comment]
#### ESUG logo
![logo](https://user-images.githubusercontent.com/2368856/91981051-88ee1300-ed28-11ea-8eb1-3f1ef5d07c4a.png)

#### ESUG badge (small)
![2016_64x64](https://user-images.githubusercontent.com/2368856/91981067-8f7c8a80-ed28-11ea-8fab-db2e96a28b8c.png)

#### ESUG badge (large)
![2016_512x512](https://user-images.githubusercontent.com/2368856/91981109-a15e2d80-ed28-11ea-88bb-36b5f0b0ab95.png)

**Comment by fniephaus** [comment]
## Gemstone screenshots

#### localClientServerTestResults
![localClientServerTestResults](https://user-images.githubusercontent.com/2368856/91981189-bc30a200-ed28-11ea-8c3a-5a738beb8373.png)

#### todeTestFailureMessage
![todeTestFailureMessage](https://user-images.githubusercontent.com/2368856/91981194-bd61cf00-ed28-11ea-88db-b4501e61a7eb.png)

#### travisErrorStack
![travisErrorStack](https://user-images.githubusercontent.com/2368856/91981196-bdfa6580-ed28-11ea-9603-a02e0b28920c.png)

#### travisOlView
![travisOlView](https://user-images.githubusercontent.com/2368856/91981202-bf2b9280-ed28-11ea-81aa-a7b84b5a355a.png)

**Comment by MrModder** [comment]
**LCOV example report**
![lcov-example](https://user-images.githubusercontent.com/1346493/91981290-e2eed880-ed28-11ea-9abf-3d3323af5d84.png)

**Comment by fniephaus** [comment]
From #498:
<img width="497" alt="gitlab-ci-coverage-line" src="https://user-images.githubusercontent.com/2368856/106434811-52046080-6472-11eb-858c-fdeca4c942cc.png">
<img width="968" alt="gitlab-ci-coverage-percent" src="https://user-images.githubusercontent.com/2368856/106434814-53358d80-6472-11eb-9c8f-27069cebd1b6.png">
