### ISSUE TITLE
Custom download location

### ISSUE THREAD

**Issue by badetitou** [hpi-swa/smalltalkCI#488]
Is it possible to have a parameter that allows us to specify a custom location for our project?

For example, I'm using a custom version of Moose at my company.
Should I select the Moose image, and install my company each time ? 
Or do you think it is possible to specify a custom location to download the zip file with the Moose Image (maybe two parameters, one for the image, one for the VM)

**Comment by fniephaus** [comment]
Hi @badetitou,
For such use cases, smalltalkCI provides `--image` and `--vm` as [command-line options](https://github.com/hpi-swa/smalltalkCI#command-line-options). Just download the VM and image combination you need and pass in their paths.

Please feel free to re-open this and let me know if you have any further questions.

Cheers,
Fabio
