### ISSUE TITLE
Gemstone setup script for smalltalkCI assumes OSprereqs installed, which is not the case when running in github actions

### ISSUE THREAD

**Issue by jbrichau** [hpi-swa/smalltalkCI#489]
I'm currently giving smalltalkCI via github actions a try for running the Seaside builds. One of the essential build platforms is GemStone64. 

A first hurdle seems to be cause by this line in the smalltalkCI run script, which asserts that the OSpreqs were already installed.
https://github.com/hpi-swa/smalltalkCI/blob/e2b46d3a159cedc5f9920c6608e2099a899d64da/gemstone/run.sh#L35

Is this line necessary, given that the `installOsPreqs` script checks and touches the file itself when run? Or what is the rationale for this step so we can skip it in github actions builds where the ospreqs are not installed? If I traced this back correctly, it seems @dalehenrich added this steps and might be able to comment?

There might be more hurdles on the way to use GemStone builds on github actions, but it seems this is at least a first required step and manually installing some of the prereqs already is removing the errors I get) https://github.com/SeasideSt/Seaside/actions?query=workflow%3AsmalltalkCI

**Comment by jbrichau** [comment]
Small update: it appears it is the only fix required for successful usage of smalltalkCI on github-actions for Gemstone builds:
https://github.com/SeasideSt/Seaside/runs/1503209045?check_suite_focus=true

**Comment by fniephaus** [comment]
Cool stuff! Now that you know what needs to be done, feel free to fill in the blanks 😉:
https://github.com/hpi-swa/setup-smalltalkCI/blob/a271ee530f18ecf947856f3f163c4687101ec6b6/index.js#L49

(so far, no one tried to run GemStone in a GitHub action 😅)

**Comment by fniephaus** [comment]
BTW, [this is](https://github.com/travis-ci/travis-build/blob/b18908e74e650b02495552d8a5c866830905e7b9/lib/travis/build/script/smalltalk.rb#L26-L40) was we do on Travis CI to set up a Gemstone environment. Maybe some of this still applies and should be integrated into the setup-smalltalkCI action? @dalehenrich would know...

**Comment by jbrichau** [comment]
@fniephaus oh, thanks for the pointers. Yes, that looks exactly like what needs to be done. 
I’ll get to it....

**Comment by fniephaus** [comment]
Turns out [this](https://github.com/hpi-swa/smalltalkCI/commit/0ee367311a0e9880485d555ec3a05af7161e60c8) is all we have to do to make things even easier. Some Travis CI environments do not allow `sudo`, so `installOsPrereqs` failed to install OS dependencies. GitHub runners do not have this limitation, so smalltalkCI can just run the `installOsPrereqs` as part of the build process. I've also added a GemStone build job to the smalltalkCI workflow, which just [passed successfully](https://github.com/hpi-swa/smalltalkCI/runs/1688508434).

/cc @dalehenrich

**Comment by jbrichau** [comment]
@fniephaus thx, I had forgotten this a little ;-)
Indeed, that's all that is needed!

**Comment by dalehenrich** [comment]
@fniephaus, many thanks for getting GemStone working with github actions!

**Comment by dalehenrich** [comment]
@jbrichau thanks for your work as well !
