### ISSUE TITLE
TestFailure: Block raised NotFound: Object is not in the collection

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#49]
While working on porting SmalltalkCI to GemStone, I accidentally used the following `.smalltalk.ston`:

```ston
SmalltalkCISpec {
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'SmalltalkCITests',
      #directory : 'tests',
      #platforms : [ #squeak, #pharo, #gemstone ]
    }
  ],
  #testing : {
    #exclude : {
      #classes : [ #Object]
    }
  }
}
```

and it hit an [error that is present for all dialects](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/107343587#L280). I've [fixed the bug for GemStone](https://github.com/dalehenrich/smalltalkCI/commit/61f1591d86835dbffce39ba73b771b5ef1153cb8) and will be including the GemStone fix as well as a test for the bug in the pull request addressing Issue #48.

**Comment by dalehenrich** [comment]
I've added the fix to the `SmalltalkCI-Core.st file, but apparently that file is not used by Squeak ... the [Pharo builds are green](https://travis-ci.org/dalehenrich/smalltalkCI/builds/107356054)...

**Comment by fniephaus** [comment]
Thanks for fixing this! Squeak builds fail, because I need to update the images first. SmalltalkCI and Metacello are preinstalled in these images to speed up builds

**Comment by fniephaus** [comment]
Has this been fixed now?

**Comment by dalehenrich** [comment]
Yes, [this code was in my recent PR](https://github.com/dalehenrich/smalltalkCI/commit/ef5b7d2a854c39d79d8f234b367df908330bb8de) ... Of course the test may not be running as the tests for this are in the [dead code](https://github.com/hpi-swa/smalltalkCI/issues/69)
