### ISSUE TITLE
Getting random "cp: target '/home/travis/smalltalkCI-master/_cache/gemstone/pharo/' is not a directory" running smalltalkCI

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#490]
I'm seeing a whole bunch of failures in the [Metacello/metacello cron job](https://travis-ci.org/github/Metacello/metacello/builds/748450055) that [weren't failing a week ago](https://travis-ci.org/github/Metacello/metacello/builds/747100087) ... It looks like every single GemStone job is failing with the same error ...

I haven't looked at all of the failures, but the first one I have looked is failing with [`cp: target '/home/travis/smalltalkCI-master/_cache/gemstone/pharo/' is not a directory`](https://travis-ci.org/github/Metacello/metacello/jobs/748450056#L1909) which seems to be in the run script for SmalltalkCI, since I haven't change the script myself, I'm wondering ifd anything has changed in SmalltalkCI in the last week that would cause these massive failures....

[24 hours ago the GsDevKit_home jobs ran clean](https://travis-ci.org/github/GsDevKit/GsDevKit_home) ...

**Comment by dalehenrich** [comment]
AFAICT, the last [smalltalkCI travis job was run two weeks ago](https://travis-ci.com/github/hpi-swa/smalltalkCI/builds),
so I'm curious what changed to cause all of the GemStone jobs to start failing in the last 24 hours?

**Comment by fniephaus** [comment]
Hi @dalehenrich,
As you might have seen already, smalltalkCI hasn't changed in the last 14 days. Since the error mentions `_cache`, it may have something to do with caching on your CI infrastructure? It may also be a smalltalkCI bug that manifested after a cache refresh?

**Comment by dalehenrich** [comment]
Since Travis is so slow these days, I figured it was easier to ask, than to start ramdomly retrying (and getting the same result) ...

clearing the cache is a good idea ... If I had thought of it I **would** have tried that before submitting a bug ... Also I remembered seeing a smalltalkCI message that I had skimmed where something to the effect of "applications should no longer depend upon the directory structure" so I was suspicious that I had missed an important memo ...

I do see that other travis tests for other projects are passing so I will rerun and clear caches ...

@fniephaus thanks for the quick response!

**Comment by fniephaus** [comment]
It seems that Travis wants the open source community to move their projects from travis-ci.org to travis-ci.com.
Also, I saw [this](https://news.ycombinator.com/item?id=25338983) yesterday. 😢

**Comment by gcotelli** [comment]
Sad, but I see it coming since the last acquisition of the company. We
switched some time ago all of our builds to use GitHub actions, so thank
you for providing that infrastructure.

**Comment by dalehenrich** [comment]
I'm still getting jobs run albeit very slowly ... now is not a good time for me to rewrite the tests for all of my repos to use github actions --- but it sure is nice to know that there are options

**Comment by fniephaus** [comment]
FYI @dalehenrich: @jbrichau got GemStone builds working on GitHub action (see https://github.com/hpi-swa/smalltalkCI/issues/489#issuecomment-739202969)

**Comment by dalehenrich** [comment]
THX @fniephaus, @jbrichau already turned me onto that ... I just have to find the time :)

**Comment by dalehenrich** [comment]
BTW, clearing cache and rerunning resulted in successful travis runs and haven't seen failures ... thanks for the help
