### ISSUE TITLE
SmallTalkCi does not work in Pharo9

### ISSUE THREAD

**Issue by badetitou** [hpi-swa/smalltalkCI#491]
SmalltalkCIPharo78 used a deprecated version of FileStream in Pharo.
However, the FileStream class has been removed in Pharo9.

So, I believe that SmallTalkCi should be updated to work with the last version of Pharo.

The problem is in `SmalltalkCIPharo class>>#forceNewFileNamed: aFile do: aBlock`

Maybe we should replace the method by:

```smalltalk
forceNewFileNamed: aFile do: aBlock
	aFile asFileReference writeStreamDo: [ :aStream | aBlock value: aStream ] 
```

**Comment by fniephaus** [comment]
`#forceNewFileNamed:do:` is defined in `SmalltalkCIPharo class` and could be overridden in `SmalltalkCIPharo78 class`. Is your version compatible with Pharo 7, 8, and 9?

**Comment by badetitou** [comment]
Some tests of SmalltalkCi-Tests are yellow with my fix, but they are also yellow without it...
in P7, P8, P9

I do not know how to test it.
Maybe creating a new branch and running the tests of a project with the fix?

**Comment by badetitou** [comment]
My fix comes from the comment of the FileStream class of P7

"

What you should remember:
- use file references as entry points to file streams 
- DO NOT USE FileStream class
- 'file.txt' asFileReference readStream and similar methods now return an instance of ZnCharacterReadStream instead of MultiByteFileStream
- 'file.txt' asFileReference writeStream and similar methods now return an instance of ZnCharacterWriteStream instead of MultiByteFileStream
- the new API has a clearer separation between binary and text files

"
