### ISSUE TITLE
GitLab CI, a test using LibGit results in error: SSL certificate invalid

### ISSUE THREAD

**Issue by TiredFalcon** [hpi-swa/smalltalkCI#494]
Hello, in my project I use LibGit to clone and parse git repositories for analysis.  
In my tests, a call to `LGitRepository clone` results in the following error:
`LGit_GIT_ECERTIFICATE: The SSL certificate is invalid`

The tests work perfectly fine in my local image.  
If I [run SmalltalkCI locally](https://github.com/hpi-swa/smalltalkCI#how-to-test-your-smalltalk-project-locally) the tests _do not_ fail.  
If I run SmalltalkCI from inside the [docker image](https://hub.docker.com/r/hpiswa/smalltalkci), the tests _fail_ in the same way as on GitLab CI.

I suspect that the problem is that the [docker image](https://hub.docker.com/r/hpiswa/smalltalkci) has not been updated since 3 years. However, I am not sure that this is the image being used by GitLab CI.

---
Some info follows

Example of a failed test:
```smalltalk
 ✗ #testCommits (311ms)
LGit_GIT_ECERTIFICATE: The SSL certificate is invalid
LGitReturnCodeEnum>>handleLGitReturnCode
LGitRepository(LGitExternalObject)>>withReturnHandlerDo:
LGitRepository>>clone:options:to:
LGitRepository>>clone:options:
LGitRepository>>clone:
[ git clone: self url ] in Repository>>initializeGit
...
```

Contents of `.gitlab-ci.yml`:
```yml
image: hpiswa/smalltalkci

Pharo64 8.0:
  stage: test
  script:
    - cd pharo
    - smalltalkci -s "Pharo64-8.0"
  only:
    changes:
      - pharo/**/*
```

And my `.smalltalk.ston` is very basic:
```ston
SmalltalkCISpec {
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'Narrator',
      #directory : 'src'
    }
  ],  
  #testing : {
    #coverage : {
      #packages : [ 'Narrator' ]
    }
  }
}
```

**Comment by fniephaus** [comment]
smalltalkCI doesn't have many GitLab users so far. That's one reason the docker image hasn't been updated so far. We'll renew the image tomorrow. Maybe that'll already fix this issue.

Are your GitLab project and builds public? If yes, some links might be helpful.

**Comment by TiredFalcon** [comment]
Thank you! I'll let you know if that solves my issue.

> Are your GitLab project and builds public? If yes, some links might be helpful.

Sadly, no, the project is private and on a self hosted GitLab instance.

**Comment by fniephaus** [comment]
I've upgraded the docker image. It's now using [ubuntu:18.04](https://github.com/hpi-swa/smalltalkCI/commit/c87968c4f34469cd009bef289db462793e2a084a). Please let me know if that fixes this issue.

**Comment by TiredFalcon** [comment]
Thanks! I tried and unfortunately it still fails with the same error.

I created a small repository with a minimal example of the failing tests: https://gitlab.com/aron.fiechter/smalltalkci-test.  
The failing CI tests can be seen here: https://gitlab.com/aron.fiechter/smalltalkci-test/-/jobs/915953469.

**Comment by fniephaus** [comment]
Thanks for the reproducer, that makes things much easier!
I've found a way to fix the error by setting `SSL_CERT_FILE` (see https://github.com/hpi-swa/smalltalkCI/commit/e5bab9dfb03771fa9d1f0d8d04f1387c650966a5). Could you please restart your build and see whether it's now fixed?

**Comment by TiredFalcon** [comment]
Now everything works as expected! Thank you very much :)

**Comment by fniephaus** [comment]
Excellent, thanks for confirming!
