### ISSUE TITLE
Logicalfont>>asFreeTypeFont errors on CI but not on local machine

### ISSUE THREAD

**Issue by TiredFalcon** [hpi-swa/smalltalkCI#499]
Hello, I recently found the following problem in my CI: a test runs smoothly and succeeds on my local machine on a fresh Pharo8 64 image, but it errors on smalltalkCI.

Example code to reproduce:

```smalltalk
testLogicalFont
	| font cairoFont |
	font := StandardFonts defaultFont.
	self assert: font familyName equals: 'Source Sans Pro'.
	cairoFont := CairoScaledFont fromFreetypeFont: font asFreetypeFont.
	
	self assert: cairoFont class equals: CairoScaledFont.
	self assert: cairoFont status isZero
```

Example of CI pipeline where this test fails: https://gitlab.com/aron.fiechter/smalltalkci-test/-/jobs/1010640307.

Specifically, I found this when running a test that made use of a Roassal3 canvas with the interaction `RSCanvasController`, which needs to build fonts.

**Comment by fniephaus** [comment]
It sounds like a dependency is missing in smalltalkCI's [Dockerfile](https://github.com/hpi-swa/smalltalkCI/blob/docker/Dockerfile). Do you happen to know which one it is? Otherwise, it'd be great if you could get in touch with the Pharo folks to figure this one out. I'm not up-to-date with the dependencies of Pharo to be honest.

**Comment by StephanEggermont** [comment]
https://pharo.org/gnu-linux-installation says: 

 sudo dpkg --add-architecture i386 
 sudo apt-get update 
 sudo apt-get install libx11-6:i386 
 sudo apt-get install libgl1-mesa-glx:i386 
 sudo apt-get install libfontconfig1:i386 
 sudo apt-get install libssl1.0.0:i386 

which is incorrect for Ubuntu 20, but might help

**Comment by fniephaus** [comment]
It turned out that libcairo2, libgl1-mesa-glx, and libfontconfig1 were missing in the docker image. I've just pushed a fix... please re-run your build @TiredFalcon and re-open this issue if the test still fails on your end.

**Comment by TiredFalcon** [comment]
> please re-run your build @TiredFalcon

I did and [it works](https://gitlab.com/aron.fiechter/smalltalkci-test/-/pipelines/255035177)! Thanks for the help :)

**Comment by fniephaus** [comment]
Excellent, thanks for confirming!
