### ISSUE TITLE
Summary of test failures by failed test in travis output - useful

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#50]
I have several packages with 1000+ tests and I'm afraid that it will be like trying to find a needle in the haystack when trying to determine the list of tests that have failed ... collecting and listing the failed tests at the end of the output would be very useful in these cases ....

**Comment by dalehenrich** [comment]
[Here's an example of the utility of such a summary](https://travis-ci.org/dalehenrich/tode/builds/107594163#L3957)

**Comment by fniephaus** [comment]
That's right, if there are a lot of tests, the current output might not be very user friendly.
There already is [a summary at the end](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/107610773#L129), but we could just add another Travis fold that contains all failure/error messages once more.
Let's get GemStone builds running first and then I will work on this :)

**Comment by dalehenrich** [comment]
sounds like a plan ...
