### ISSUE TITLE
smalltalkCI setup is failing for Pharo 7 32 bits on GitHub actions

### ISSUE THREAD

**Issue by gcotelli** [hpi-swa/smalltalkCI#500]
Since yesterday the builds are failing due to 
```
Reading package lists...
/usr/bin/sudo apt-get install -qq --no-install-recommends libc6-i386 libuuid1:i386 libssl1.0.0:i386 libcairo2:i386
E: Package 'libssl1.0.0:i386' has no installation candidate
Error: The process '/usr/bin/sudo' failed with exit code 100
```
when running the `hpi-swa/setup-smalltalkCI` step.
It will probably happen with other 32 bits versions trying to install this package.

For example:
https://github.com/ba-st/Willow/pull/197/checks?check_run_id=1868137185

Here are the complete logs in case they are useful: [logs_265.zip](https://github.com/hpi-swa/smalltalkCI/files/5957395/logs_265.zip)

**Comment by fniephaus** [comment]
Looks like the job ran on Ubuntu 20.04.2, while older ones ran on 18.04.5.
You should be able to fix this on your end by pinning the version of Ubuntu (instead of `ubuntu-latest` use `ubuntu-18.04`.

However, we need to fix this in [hpi-swa/setup-smalltalkCI](https://github.com/hpi-swa/setup-smalltalkCI). Do you happen to know which 32bit libssl package works under Ubuntu 20.04?

Context: https://github.com/actions/virtual-environments/issues/1816

**Comment by gcotelli** [comment]
Apparently libssl1.0 is no longer available for Ubuntu > 18.04 , it looks like we need to try a newer version like `libssl1.1`

https://askubuntu.com/questions/1173587/e-package-libssl1-0-0-has-no-installation-candidate#1173621

**Comment by gcotelli** [comment]
`sudo apt-get install libssl1.1:i386` seems to work for Ubuntu 20.04.2

**Comment by fniephaus** [comment]
Yes, `libssl1.1:i386` seems to work, just pushed https://github.com/hpi-swa/setup-smalltalkCI/commit/573f65db766bd7a0d509533164bb9f18972dd907. Could you please restart your build?

**Comment by gcotelli** [comment]
E: Unable to locate package libuuid1:i386libssl1.1:i386
E: Couldn't find any package by glob 'libuuid1:i386libssl1.1'
E: Couldn't find any package by regex 'libuuid1:i386libssl1.1'

**Comment by gcotelli** [comment]
Looks like a missing space

**Comment by fniephaus** [comment]
whoops, fixed...please try again 😅

**Comment by gcotelli** [comment]
Now its running. Thank you @fniephaus

**Comment by fniephaus** [comment]
Sweet! Thanks for the report and for verifying the fix :)
