### ISSUE TITLE
Lcov file not found

### ISSUE THREAD

**Issue by hernanmd** [hpi-swa/smalltalkCI#501]
I have this [CI matrix](https://github.com/pharo-ai/Datasets/blob/master/.github/workflows/cimatrix.yml) with the corresponding [STON file](https://github.com/pharo-ai/Datasets/blob/master/.smalltalk.ston) targeting Pharo images. There is only one test class, and [this is the build error](https://github.com/pharo-ai/Datasets/runs/1939897859).

For some reason, the lcov file is not generated for my setup.

Following [this issue](https://github.com/hpi-swa/smalltalkCI/issues/454) it seems to be not necessary to specify auto-upload when using coveralls. 

I ran out of ideas, is this something missing in my configuration or just a problem with smalltalkCI and coveralls?

**Comment by gcotelli** [comment]
Maybe you're missing the format: #lcov directive in the .smalltalk.ston .
Take a look at
https://github.com/ba-st/Buoy/blob/release-candidate/.smalltalk.ston . We
re using codecov action instead of coveralls, but maybe this helps.

**Comment by hernanmd** [comment]
Interesting, didn't knew about that directive, thanks.
The jobs were ran again and for now only windows fails with Error: Lcov file not found.
Will keep investigating.

**Comment by fniephaus** [comment]
We also have dedicated documentation for coverage:

https://github.com/hpi-swa/smalltalkCI/blob/master/docs/COVERAGE.md#coverage-testing

Let us know if that doesn't help you set everything up!

**Comment by hernanmd** [comment]
Thank you @gcotelli and @fniephaus I checked carefully and the problem was the #coverage directive was missing in the .ston file.
