### ISSUE TITLE
[sporadic] Unable to parse Coveralls build data (invalid escape character \i)

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#504]
I have seen this issue in two builds for my repository so far, but it does not occur always. It could be a server-side issue because I have a matrix of two jobs, and in both cases, the coveralls upload failed for both job instances at the same time.

Error message:

```
Unable to parse Coveralls build data from /home/runner/.smalltalkCI/_builds/coveralls_build_data.json:
STONReaderError: At character 464/465: 'invalid escape character \i'
```

Example builds:

- https://github.com/hpi-swa-lab/SqueakByExample-english/runs/2141953375?check_suite_focus=true#step:4:155
- https://github.com/hpi-swa-lab/SqueakByExample-english/runs/2141953404?check_suite_focus=true#step:4:153
- https://github.com/hpi-swa-lab/SqueakByExample-english/runs/2133734034?check_suite_focus=true#step:4:156
- https://github.com/hpi-swa-lab/SqueakByExample-english/runs/2133734061?check_suite_focus=true#step:4:154

Because the issue occurs sporadically only, I have not yet been able to grab a broken version of `coveralls_build_data.json`. I will send any updates if I find out more about this issue.

**Comment by cmfcmf** [comment]
I have the same issue with this build: https://github.com/cmfcmf/ReactS/runs/2264098469
It is reproducible locally. I think it is caused because I got over-excited in the commit message which reads `Add support for keys \o/`. STON treats the backslash as an escape character.
You will see that @LinqLover's failed commits also all include a backslash.

Full reproduction steps:
```
git clone git@github.com:cmfcmf/ReactS.git
cd ReactS
git reset --hard 6bf3abfbbde09d949aa991e725928a6510b1a9a5
smalltalkCI/bin/smalltalkci .smalltalk.ston --smalltalk "Squeak64-5.3"
```

**Comment by fniephaus** [comment]
Thanks for identifying the issue, @cmfcmf. The bug is fixed :)
