### ISSUE TITLE
Squeak trunk builds are broken

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#513]
According to @marceltaeumel, the preparation process for Squeak trunk builds freezes because author initials are requested with a UI. He's working on a fix, maybe that requires some changes in smalltalkCI.

/cc @LinqLover.

**Comment by marceltaeumel** [comment]
I just changed the Trunk to use `Utilities changeStampPerSe` for the critical path. No need to adjust smalltalkCI (or its Trunk base image) for now.

**Comment by fniephaus** [comment]
Thanks!
