### ISSUE TITLE
GemStone fails on GitHub Actions

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#514]
For some reason, GemStone builds have started to fail on GitHub Actions (see [here](https://github.com/hpi-swa/smalltalkCI/runs/2390812991?check_suite_focus=true#step:4:1356) for example). Not sure what is going on, maybe `3.5.0` is broken somehow? Maybe @dalehenrich can make sense of the error?
It seems that #512 does not introduce the error, so that PR is no longer blocked on this particular error.

Assigning to @dalehenrich for now.

<details>
<summary>Here's the relevant log:</summary>

```
=================
1349
   GsDevKit script: startStone -b travis
1350
              path: /home/runner/work/smalltalkCI/smalltalkCI/_builds/GsDevKit_home/bin/startStone
1351
=================
1352
/home/runner/work/smalltalkCI/smalltalkCI/_builds/GsDevKit_home/server/stones/travis/product/bin/waitstone[Info]: GemStone version '3.5.0'
1353
Network service !#dir:/home/runner/work/smalltalkCI/smalltalkCI/_builds/GsDevKit_home/server/stones/travis/logs#log:%N%P.log#server!travis is ready.
1354
stone travis already running, to restart use -r option :: startStone -b travis
1355
Install tODE on stone: travis
1356
Error: Unable to create a session, check netldi and gem log files.
1357
 For further information about login failures, check the gem log file
1358
TDTopezGemStoneClient>>loginUsing:
1359
TDTopezGemStoneClient>>installTodeBlock: in Block: installTodeBlock: installBlock...
1360
BlockClosure>>on:do:
1361
TDTopezGemStoneClient>>installTodeBlock:
1362
TDTopezGemStoneClient>>installTode:
1363
TDShell>>executeLoadServer: in Block: [ ^ self topezClient installTode: options ]
1364
Dictionary>>at:ifPresent:ifAbsent:
1365
Dictionary>>at:ifAbsent:ifPresent:
1366
TDShell>>executeLoadServer:
1367
TDShell>>executeBuiltIn:
1368
TDShell>>evaluateCommand:batchMode:
1369
TDShell>>evaluate:batchMode: in Block: [ :command | result := self evaluateCommand: comma...etc...
1370
TDCommandLine class>>line:forEachCommand: in Block: [ :isolated | ...
1371
OrderedCollection>>do:
1372
TDCommandLine class>>line:forEachCommand:
1373
TDCommandLine class>>fromStream:selectLine:forEachCommand: in Block: [ :cmdLine | ...
1374
OrderedCollection>>do:
1375
TDCommandLine class>>fromStream:selectLine:forEachCommand:
1376
TDShell>>evaluate:batchMode: in Block: evaluate: aString batchMode: aBool...
1377
BlockClosure>>on:do:
1378
TDShell>>evaluate:batchMode:
1379
TDShell>>evaluate:
1380
TDShell>>executeScript: in Block: [ ^ self evaluate: commands ]
1381
Dictionary>>at:ifPresent:ifAbsent:
1382
TDShell>>executeScript: in Block: [ ...
1383
Dictionary>>at:ifPresent:ifAbsent: in Block: [ :v | ^ oneArgBlock value: v ]
1384
BlockClosure>>cull:
1385
Dictionary>>at:ifPresent:
1386
Dictionary>>at:ifPresent:ifAbsent:
1387
TDShell>>executeScript: in Block: [ ...
1388
Error on or near line 99 :: devKitCommandLine loadTode travis :: devKitCommandLine loadTode travis
1389
Error on or near line 55 :: todeLoad travis :: todeLoad travis
1390
Error on or near line 220 :: createStone travis 3.5.0 :: createStone travis 3.5.0
```
</details>

**Comment by dalehenrich** [comment]
@jbrichau saw this problem in the Seaside github actions and this is [the patch](https://github.com/SeasideSt/Grease/commit/c575154a1f54f8c8581805746cb46d91f483ed36#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR25) that he applied to get things working again. You may remember that we had a similar problem with the `/etc/hosts` file back in the early days of travis-ci ...

**Comment by fniephaus** [comment]
Thanks for the hint! Trying to fix that with https://github.com/hpi-swa/setup-smalltalkCI/commit/9ebd52512a27973c958c149d678acc25afb9c671. A quick note from @jbrichau would've been helpful, but glad we figured it out.

**Comment by jbrichau** [comment]
@fniephaus well, it should actually have been fixed on monday (yesterday) by github itself (https://github.com/actions/virtual-environments/issues/3185#issuecomment-821758343). I discovered the problem myself on saturday and tried the patch on sunday to confirm this was the issue I was seeing. I have not had time to verify since if the patch was still required, but it seems to be... 

I'm not sure if the workaround should be a permanent addition that might cause other issues...

**Comment by fniephaus** [comment]
Oh, that's very good to know. Thanks, @jbrichau!
Looks like others also rely on reverse name lookup, so we don't have to change anything on our end. I'll monitor the issue that @jbrichau linked and close this once the issue has been resolved by the GitHub Actions team.

**Comment by fniephaus** [comment]
The issue has been resolved by the GitHub team. Builds are green again!
