### ISSUE TITLE
Vm crash dump should appear in travis log

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [hpi-swa/smalltalkCI#515]
It would be very usefull to see the contents of crash dump files emitted upon VM crash.

**Comment by nicolas-cellier-aka-nice** [comment]
An example of report currently is this: https://travis-ci.com/github/OpenSmalltalk/opensmalltalk-vm/jobs/500599180

```
$ ./scripts/ci/travis_test.sh
Starting SUnit testing...
Please consider explicitly specifying image architecture
(Example: use `Squeak64-trunk` instead of `Squeak-trunk`).
Preparing folders...
Build folder already exists at /Users/travis/build/OpenSmalltalk/opensmalltalk-vm/smalltalkCI-master/_builds.
Starting Squeak build...
download_image
0.88sDownloading 'Squeak32-5.1-16555.tar.gz' testing image...
Extracting image...
/Users/travis/build/OpenSmalltalk/opensmalltalk-vm/smalltalkCI-master/helpers.sh: line 643: 10169 Segmentation fault: 11  $cmd
Error with status code 139:
643 travis_wait /Users/travis/build/OpenSmalltalk/opensmalltalk-vm/smalltalkCI-master/helpers.sh
302 squeak::run_script /Users/travis/build/OpenSmalltalk/opensmalltalk-vm/smalltalkCI-master/squeak/run.sh
323 squeak::load_project /Users/travis/build/OpenSmalltalk/opensmalltalk-vm/smalltalkCI-master/squeak/run.sh
367 run_build /Users/travis/build/OpenSmalltalk/opensmalltalk-vm/smalltalkCI-master/squeak/run.sh
499 run ./run.sh
532 main ./run.sh
538 main ./run.sh
===================================================================
config_clean=false
config_colorful=true
config_debug=false
config_first_arg_or_empty=/Users/travis/build/OpenSmalltalk/opensmalltalk-vm/tests/smalltalk.ston
config_headless=true
config_image=
config_smalltalk=Squeak-5.1
config_ston=/Users/travis/build/OpenSmalltalk/opensmalltalk-vm/tests/smalltalk.ston
config_tracking=true
config_verbose=false
config_vm=/Users/travis/build/OpenSmalltalk/opensmalltalk-vm/products/Squeak.app/Contents/MacOS/Squeak
config_vm_dir=/Users/travis/build/OpenSmalltalk/opensmalltalk-vm/smalltalkCI-master/_cache/vms/Squeak-5.1
The command "./scripts/ci/travis_test.sh" exited with 139.
```

**Comment by fniephaus** [comment]
Do these crash dumps always have the same name across dialects or do they differ? How would you print those, @nicolas-cellier-aka-nice ? Just cat the dump file if it exists?

**Comment by hernanmd** [comment]
@fniephaus  AFAIK historically the crash file name was always the same: crash.dmp

These are the references for the pharo-vm

https://github.com/pharo-project/pharo-vm/blob/5e8e842fad07c79c64a353f588a2b608d43b60d5/opensmalltalk-vm/platforms/iOS/vm/Common/Classes/sqSqueakMainApp.m#L288
https://github.com/pharo-project/pharo-vm/blob/5e8e842fad07c79c64a353f588a2b608d43b60d5/opensmalltalk-vm/platforms/unix/vm/sqUnixMain.c#L1032
https://github.com/pharo-project/pharo-vm/blob/5e8e842fad07c79c64a353f588a2b608d43b60d5/opensmalltalk-vm/platforms/Mac%20OS/vm/sqMacMain.c#L321

**Comment by fniephaus** [comment]
Would it be enough to just check for a file called `crash.dmp` in the directory of the image and if it exists, print that right before the trace? Here's the logic that prints the stack trace:
https://github.com/hpi-swa/smalltalkCI/blob/51d0cfb50908150a9d7bdb08ef6d4fabd2eee28d/run.sh#L90-L103
