### ISSUE TITLE
curl: (28) Operation timed out, failed to download Squeak Trunk image

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#516]
While debugging smalltalkCI locally, I received the following error multiple times:

```
curl: (28) Operation timed out after 29979 milliseconds with 26840721 out of 29105923 bytes received
curl failed to download https://github.com/hpi-swa/smalltalkCI/releases/download/v2.9.6/Squeak64-trunk-20447.tar.gz to '/path/to/smalltalkCI/_builds/2021_04_26_18_03_43/Squeak64-trunk-20447.tar.gz'.
```

Since the download was already completed by 91% in this case, would you agree to increase the timeout?

**Comment by fniephaus** [comment]
Yes, that'd make builds like that less flaky. But let's not bump it too high, I'd say 60s tops.

**Comment by LinqLover** [comment]
Please see #517. When will this timeout be useful indeed? Usually, the server will close the connection immediately if there is any concrete error, won't it?

Imagining a (low, but realistic) internet speed of ~1 MBps, the download of the current Trunk image would take around 3 minutes - with a rising tendency as the image is getting larger over time. I don't see why we should hinder Squeakers sitting in an airplane from using smalltalkCI locally. ;-)

**Comment by fniephaus** [comment]
Sure, thanks! But please don't try to reproduce your CI builds on an airplane, take selfies instead:
![image](https://user-images.githubusercontent.com/2368856/116128198-f93b1180-a6c8-11eb-9f45-e931bfd1e1c3.png)

**Comment by LinqLover** [comment]
Great, thanks for the fast feedback!

**Comment by LinqLover** [comment]
(And this is the reason why mining useful data from software repositories is such a hard discipline ^^)
