### ISSUE TITLE
Unable to invoke smalltalkCI with option `--clean` if `.smalltalk.ston` is absent

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#519]
- Steps to reproduce: `cd smalltalkCI/bin && ./smalltalkci --clean`
- Expected behavior: Clean up works as usual
- Actual behavior: `No STON file named '.smalltalk.ston'`

The problem appears to be that in the `run.sh`, `ensure_ston_config_exists` is called before `check_clean_up`:

https://github.com/hpi-swa/smalltalkCI/blob/cac96a5fd62f38b04dfacf774baec2fa946f0f97/run.sh#L525-L529

Intuitively, I would have swapped the two last statements, but to support continuation after the `--clean` option, `check_clean_up` depends on `config_ston` which is initialized in `ensure_ston_config_exists` only:

https://github.com/hpi-swa/smalltalkCI/blob/cac96a5fd62f38b04dfacf774baec2fa946f0f97/run.sh#L442-L446

Would it be okay to check for `config_first_arg_or_empty` instead to eliminate this dependency?

**Comment by fniephaus** [comment]
> Would it be okay to check for config_first_arg_or_empty instead to eliminate this dependency?

Sure, please draft a PR and I'll take a look.

**Comment by LinqLover** [comment]
Done in #520, ready for review! :-)
