### ISSUE TITLE
Customize the `reproduce` message for GemStone

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#52]
[This message](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/107610773#L135) would *work* for GemStone, but since run.sh does a full install of GsDevKit_home it is overkill for someone who may already have a GsDevKit_home installation ...

**Comment by fniephaus** [comment]
If we make sure that smalltalkCI does nothing if GemStone is already installed, then there is nothing to do I guess.
The message is automatically generated: https://github.com/hpi-swa/smalltalkCI/blob/add3c7fd5f64473fdd45fe921c5b30ad1d6da3af/helpers.sh#L66-L75

**Comment by dalehenrich** [comment]
That's a very good point ... duh!

**Comment by dalehenrich** [comment]
please assign this to me and I will work on that ...

**Comment by fniephaus** [comment]
This is now the case:
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/112107806#L4022

However, I don't really feel comfortable showing steps to reproduce for a GemStone build, because it requires some OS prerequisites and it does way more than just downloading a vm and an image.
What do you think, @dalehenrich?

**Comment by dalehenrich** [comment]
@fniephaus it might turn out that the "solution" might be custom GemStone options passed in at the ./run.sh command ... isn't their a "posix style" for specifying options to an underlying command? Such an *escape clause* would make it possible to simply add custom options to the gemstone/run.sh command, allowing for the re-use of existing checkout or ???

**Comment by fniephaus** [comment]
I think for now, the good ol' Smalltalk approach should be sufficient: namespace all the GemStone options with ```--gs-``` (e.g. ```--gs-custom-option```). :smile: What do you think?

**Comment by dalehenrich** [comment]
@fniephaus ... but then that would require that we keep run.sh options and gemstone/run.sh options in synch ... rather than a pass-through option ...

**Comment by fniephaus** [comment]
The gemstone/run.sh is being sourced rather than called in a subshell. That means, smalltalkCI just needs to "accept" --gs-* (it fails if it doesn't know an option) and then there could be a second round of argument passing in the gemstone/run.sh. This way, nothing needs to be kept in sync and you are free to add custom options for GemStone. Sounds good? If yes, I could start working on this next week :)

**Comment by dalehenrich** [comment]
I was thinking of the [`-Wlxxx` and `-Xlinker xxx` option style used by `gcc` for passing options through to `ld`](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html):

> -Xlinker option
    Pass option as an option to the linker. You can use this to supply system-specific linker options that GCC does not recognize.
>
>    If you want to pass an option that takes a separate argument, you must use -Xlinker twice, once for the option and once for the argument. For example, to pass -assert definitions, you must write -Xlinker -assert -Xlinker definitions. It does not work to write -Xlinker "-assert definitions", because this passes the entire string as a single argument, which is not what the linker expects.
>
>    When using the GNU linker, it is usually more convenient to pass arguments to linker options using the option=value syntax than as separate arguments. For example, you can specify -Xlinker -Map=output.map rather than -Xlinker -Map -Xlinker output.map. Other linkers may not support this syntax for command-line options.
>
> -Wl,option
>    Pass option as an option to the linker. If option contains commas, it is split into multiple options at the commas. You can use this syntax to pass an argument to the option. For example, > -Wl,-Map,output.map passes -Map output.map to the linker. When using the GNU linker, you can also get the same effect with -Wl,-Map=output.map.

`-Wg, option`, `-Wp,option`, and `-Ws,option` could be used for passing platform specific options, but your approach may be easier to write in bash:)

**Comment by fniephaus** [comment]
Mh, I guess this would be possible, but might be harder to implement as you said.
I will look into this next week and try to find something reasonable. I hope this is not super urgent...

**Comment by dalehenrich** [comment]
Not urgent at all ... I still need to figure out what the set of 
(running local) options might be:

   - create stone in an existing GsDevKit_home checkout rather than 
build a fresh one
   - run the tests interactively using an existing tODE client
   - create a tODE client and run interactively
   - optionally produce xml log
   - use an alternate _cache directory structure
   - create stone using a named extent file as starting point
   - run tests in an existing stone without loading anything ....

and then find the time to implement the GemStone functionality (some of 
these options may take tODE and/or GsDevKit_home changes:)

**Comment by fniephaus** [comment]
That is quite a list of options. :smile: 
Would it make sense to use or even reuse some sort of config file for GemStone builds?

**Comment by dalehenrich** [comment]
The cut point here is to differentiate between things that apply equally to local and travis runs --- a file of some sort makes sense --- The command line option would be used for things that apply only to the local builds ... forcing a user to create a config file for a "one-off" local run does not make sense --- that is what command line options are for:) 

I have several projects that currently use builderCI that are not easily ported to smalltalkCI so I'm still exploring what those needs are as well as looking at expanding my use of smalltalkCI beyond testing just github projects ... so the actual final requirements are pretty fluid right now  --- as as I said, this is not critical at the moment ...

I hope to be able to fulfull the travis requirements by extending the contents of the .smalltalkCI.ston file ...

**Comment by dalehenrich** [comment]
@fniephaus you might get you wish for "gemstone configuration options" [sooner rather than later](http://forum.world.st/Seaside-Smalltalk-CI-build-for-Gemstone-runs-out-of-temp-object-space-tp4886891p4887007.html) :) ... have a use case for setting size of GEM_TEMPOBJ_CACHE_SIZE for test gem that falls squarely in the travis/local box .... 

I'm proposing the following to the list:

```ston
SmalltalkCISpec {
  #gemstone: 
    SCIGemStoneConfiguration {
      #gemConfPath : 'tests/gemstone/gem.conf',
      #stoneCofPath : 'tests/gemstone/system.conf'
    },
  #loading : ['...']
}
```

Perhaps something like the following would be more general:

```json
SmalltalkCISpec {
  #configuration: 
    SCISystemConfiguration {
      #gemConfPath : 'tests/gemstone/gem.conf',
      #stoneCofPath : 'tests/gemstone/system.conf',
      #platforms : [ #gemstone ]    },
  #loading : ['...']
```

Will wait to see the responses on the list before opening a separate issue.

**Comment by fniephaus** [comment]
What do you think about bc072cce2ca7b1657d5b320bc07faa04360af4da?
I will have a look at the above tomorrow...

**Comment by dalehenrich** [comment]
Passing the args through to `gemstone/run.sh` looks good. I'd like to take the actual gemstone options to be implemented under advisement as I'm not ready to commit to which options make sense as command-lines, etc.... Ideally I will take a long close look at several different use cases before committing to an approach ... like setting gemstone-specific env vars, probably should be part of the .travis.yml instead of command line args --- if travis is part of the equations ...

`GS_STONE_NAME` might have two use cases, for example. One could be to create a new stone using that name and another may mean to use an existing stone of that name ... both are possibilities and I need to explore the options before making up my mind
 
I will also want to reserve the GS_* env vars for use by GsDevKit+home itself :)

So I think passing the `--gs-*` options through to gemstone/run.sh is a very good start and we'll leave the rest for later ...

The above came from an actual user of smalltalkCI for GemStone, so I will want to solve that use case (which will apply equally to travis and local runs) first ...

**Comment by dalehenrich** [comment]
@pdebruic suggested that it would be useful to set the timezone for the stone --- something that needs to be done as SystemUser, so not easy to do from within a test suite --- so the a #timezone field might be added as well ...

**Comment by dalehenrich** [comment]
@fniephaus I'm fixing to submit a PR with [this implementation of gemstone-specific args](https://github.com/dalehenrich/smalltalkCI/commit/811e5e832c924ac16a01d188bc50bf620d0748f8) ... I want to test my `--clean` fix a bit more, but you can preview the changes otherwise

**Comment by fniephaus** [comment]
Ops, I [just pushed an update](https://github.com/hpi-swa/smalltalkCI/blob/6452b9b7109a46832570813b7931def4ba52178e/run.sh#L262-L279) for `--clean` :grin:

**Comment by dalehenrich** [comment]
The `--clean` fix is specific to GemStone ... also I see that you actually pushed the gemstone args with args that I didn't actually want to support (yet) ... I didn't realize that I *approved* them ...

Also have you actually tested your implementation? When I tried to use your implementation, `$@` is empty by the time that gemstone gets the args, so I had to use a slightly different approach... I'll work through all of the commit conflicts and test my solution along with the gemstone-specific `--clean` fix --- with this PR I'm not planning on supporting any gemstone-specific args (just the infrastructure), since I am working through the permutations and priorities for what I want to actually support ...

**Comment by dalehenrich** [comment]
Here are the [diffs between the edits I made to get `--gs-` args to actually work](https://github.com/hpi-swa/smalltalkCI/compare/master...dalehenrich:gemstone_args?expand=1) ... I'm now going to test my changes to make sure that the are still working

**Comment by fniephaus** [comment]
Sorry, I had a few other fixes on `dev` that I wanted to be merged and I might have acted a little prematurely (next time I cherry pick...).
And yes, you did not approve any of those, so I am happy to take your lead. I actually just implemented them as an example for you :satisfied:

**Comment by dalehenrich** [comment]
I appreciated the pointers in getting them to work and I started with your basic edits so at the end of the day all is good!

I'm waiting for travis to pass judgement on my edits :)

**Comment by fniephaus** [comment]
Can this be closed?

**Comment by dalehenrich** [comment]
It would still be nice to have an example script that would actually reproduce the build ... proper `-s` etc. but now that the scripts run correctly for GemStone and the help message is pretty good I suppose it's not that big of a deal

**Comment by fniephaus** [comment]
Thanks! A user would still get the [generic notice how to reproduce the build](https://github.com/hpi-swa/smalltalkCI/blob/master/helpers.sh#L124-L133), right?

**Comment by dalehenrich** [comment]
my comment was aimed at the changing the *generic notice* to be a little less **generic** :)

**Comment by fniephaus** [comment]
Noted!
