### ISSUE TITLE
Error: Instances of Character are not indexable (while reporting error)

### ISSUE THREAD

**Issue by hernanmd** [hpi-swa/smalltalkCI#521]
Testing locally with a project using Travis and Coveralls causes an error in an error reporting method.

![Error Instances of Character are not indexable](https://user-images.githubusercontent.com/4825959/118316776-88349000-b4f7-11eb-9d78-25103d71431d.png)

The quick fix could be as easy as converting Characters to String for concatenation in #coverallsBuildData and #failAndQuit: methods

´´´smalltalk
coverallsBuildData

	SmalltalkCI readOnlyFileNamed: self coverallsBuildDataFilename
		do: [ :stream | 
			[^ STON fromStream: stream] 
				on: STONReaderError
				do: [:error | 
					SmalltalkCI failAndQuit: 
						'Unable to parse Coveralls build data from ', self coverallsBuildDataFilename, ':', Character cr asString,
						error asString, Character cr asString ,
						'This is a smalltalkCI internal error. If the problem persists, please open an issue at https://github.com/hpi-swa/smalltalkCI/issues/new .'. ]]
´´´

and this method:

´´´smalltalk
failAndQuit: aString
	"Prints and persists an internal failure for debugging purposes"
	| message |
	message := aString , Character cr asString , Character cr asString , 'To inspect this error, open the image in the "', self platformClass imagePath, '" directory.'.
	self
		printErrorToStdout: message;
		saveAndQuitImage;
		halt
´´´

**Comment by fniephaus** [comment]
Thanks for the report! What Pharo version were you using and how can I reproduce the issue (e.g. which project did you try to test)?

**Comment by hernanmd** [comment]
Sure, this is how I got the error:

```bash
git clone https://github.com/hpi-swa/smalltalkCI.git
git clone https://github.com/hernanmd/ProjectFramework.git
smalltalkCI/bin/smalltalkci --headful ProjectFramework/.smalltalk.ston
```

Select 15 (Pharo 8 - 64 bit)

Then in the image click in Proceed in the dialog box.

Let me know if you need further info.

**Comment by fniephaus** [comment]
I've just pushed a fix. I chose to use `String cr` instead of `Character cr asString` 😉. Note that the error was only hit if there's an issue with your coverage setup (only error handling code paths contained `Character cr`).
