### ISSUE TITLE
`SmalltalkCI-*` used in package pattern for Pharo does not match any packages - it should

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#53]
As pointed out in [Issue #51](https://github.com/hpi-swa/smalltalkCI/pull/51#issuecomment-181138208), Pharo interprets `SmalltalkCI-*` as a regex expression and returns an  empty set of matches ...

The only reason that this is interesting is that  `SmalltalkCI-*` is a legal category pattern that does return a proper result set of classes .. 

For GemStone I intend to support the package class spec, but I think this issue needs to be resolved one way or the other first ...

**Comment by fniephaus** [comment]
I'm a little confused here. Is this a smalltalkCI bug or a Pharo problem?

**Comment by dalehenrich** [comment]
Well, the bug is in the behavior of SmalltalkCI ... a pattern that is used for category matching (`Smaltalk-*`) by SmalltalkCI gives a different result when used to match packages in the Pharo/GemStone #package extension for SmalltalkCI ... and the fix will most likely be made in [SmalltalkCI-Pharo.st](https://github.com/hpi-swa/smalltalkCI/blob/master/src/SmalltalkCI-Pharo.st#L23) so technically this is a SmalltalkCI bug ... 

At the end of the day `Smaltalk-*` interpreted as regex (which is what Pharo currently does for packages) does not give the same result as [SmalltalkCIclassesInCategoryPrefix:](https://github.com/hpi-swa/smalltalkCI/blob/master/src/SmalltalkCI-Core.st#L300) (which is what is used by Squeak, Pharo and GemStone for categories) ....

**Comment by dalehenrich** [comment]
This bug is illustrated by these two expected failure conditions:

```Smalltalk
expectedFailures
  SmalltalkCI platformSymbol = #'pharo'
    ifTrue: [ ^ #(#'testGemStonePharoClassesTestPackages2') ].
  SmalltalkCI platformSymbol = #'gemstone'
    ifTrue: [ ^ #(#'testGemStonePharoClassesTestPackages3') ].
  ^ #()
```

The test code will be present on the master branch once PR #74 is merged

**Comment by dalehenrich** [comment]
Once the merge is complete @estebanlm and I can discuss alternatives, as I think the behavior should be consistent

**Comment by estebanlm** [comment]
sorry for not having time recently to look at this :( 
but yes, the "*" pattern should match for pharo (also, the regex ".*" should do it)...

**Comment by fniephaus** [comment]
We have unified this across all dialects with 5073e620d008b0c1c2066aec60a9ada9d3db9448. [Here is an example](https://github.com/hpi-swa/smalltalkCI/blob/5073e620d008b0c1c2066aec60a9ada9d3db9448/repository/SmalltalkCI-Tests.package/SmalltalkCITest.class/instance/testClassesForPackages.st).
