### ISSUE TITLE
Pharo64-6.0 fails on Windows

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#534]
because http://files.pharo.org/get-files/60/pharo64-win-stable.zip does not exist. Is this an oversight or expected? @theseion @estebanlm

**Comment by gcotelli** [comment]
I don't think there is a 64 version of the Pharo 6 image. AFAIR the first
64 bits version landed for Pharo 7.

**Comment by theseion** [comment]
Sounds about right. But @estebanlm should know.

**Comment by estebanlm** [comment]
yes, this is right... P6 had 64bit versions for linux and mac, not windows (we were working on it at the time)

**Comment by fniephaus** [comment]
Thanks all! I've excluded that particular build on Windows.
