### ISSUE TITLE
`Pharo64-10` builds fail due to `OSEnvironment` not understanding #default

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#539]
> Instance of OSEnvironment class did not understand #default

See https://github.com/hpi-swa/smalltalkCI/runs/3124912619?check_suite_focus=true

Please advise, @estebanlm.

**Comment by estebanlm** [comment]
uhm... weird, `OSEnvironment` does not understand default in Pharo 9 either.

**Comment by fniephaus** [comment]
There are dedicated classes for Pharo 9 (see [isPlatformCompatible.st](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo9.class/class/isPlatformCompatible.st#L4)). Looks like we may need to introduce  `SmalltalkCIPharo10.class`?

**Comment by estebanlm** [comment]
mmm, ok, I can do a PR but we will have our eternal problem with properties file. 
can I just give you the two classes I added as .st?
(also, how do I test this locally?)

**Comment by fniephaus** [comment]
> can I just give you the two classes I added as .st?

Sure, I can add them for you.

> (also, how do I test this locally?)
Just run `bin/smalltalkci -s Pharo64-10 --self-test` in smalltalkCI's root directory.

**Comment by estebanlm** [comment]
[p10.zip](https://github.com/hpi-swa/smalltalkCI/files/6861035/p10.zip)

voilà :)
(local tests are passing)

**Comment by fniephaus** [comment]
Done, I removed your `imageInfo` override and instead let `SmalltalkCIPharo10` inherit from `SmalltalkCIPharo9`.
