### ISSUE TITLE
Need to be able to specify GsDevKit_home branch for GemStone builds ... 

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#54]
Probably a GemStone-specific env var set in .travis.yml ... @fniephaus - please assign to me and I will work on this ...

**Comment by fniephaus** [comment]
Unfortunately, I can't assign this to you, because you are not (yet) an official contributor of this repo. And I can't add you to [hpi-swa](https://github.com/hpi-swa), but I will ask someone tomorrow who can.

Why do you need to be able to specify the GsDevKit_home branch?
There are two ways to do this: either via an env var as you suggested, or as an [argument of `run.sh`](https://github.com/hpi-swa/smalltalkCI/blob/add3c7fd5f64473fdd45fe921c5b30ad1d6da3af/run.sh#L95). An argument can then be used like [this](https://github.com/hpi-swa/smalltalkCI/blob/add3c7fd5f64473fdd45fe921c5b30ad1d6da3af/.travis.yml#L30).

**Comment by dalehenrich** [comment]
... haha, I don't **need** the bug assigned to me, but I do intend to 
fix the bug ... Yes I can easily add that to the GemStone scripts and I 
can do the work, but I am using this issue as a placeholder to remind 
myself to do the work, since I intend to leave SmalltalkCI as is (i.e., 
working AFAICT for GemStone) until the container issues are resolved...

As an example, tODE is dependent upon the structure in GsDevKit_home, 
if/when the structure changes, in GsDevKit_home and I make corrsponding 
changes to tODE, tODE needs to use a particular branch of GsDevKit_home 
for it's tests ... I also have cases where I want to test tODE against 
both branches of GsDevKit_home to ensure that structural dependencies 
have not snuck in ...

I've already done this on my jury-rigged use of smalltalkCI and tODE[1] 
and found it very useful ..

Dale

[1] https://github.com/dalehenrich/tode/blob/dev/.travis.yml

**Comment by fniephaus** [comment]
Is there a reason for [cloning the entire Git repository](https://github.com/hpi-swa/smalltalkCI/blob/master/gemstone/run.sh#L19-L21)?
Couldn't we just use a single download link?
It's probably best if a user can just override that default download link by setting an env variable.

**Comment by dalehenrich** [comment]
You mean a zip file instead of a clone? 

GsDevKit is designed to be used as a clone ... doing a pull request is how a new version of GsDevKit_home is delivered --- so switching branches is how it is documented to use GsDevKit_home ... that's why I talk about switching branches ...

For the purposes of optimizing the operation of smalltalkCI, we could download a zip file of the target commitish , but this optimization would be a separate issue from needing to provide the end user with the ability to switch versions ... I've notthing against doing that ... Of course, I'll ask you to not look too closely at GsDevKit_home itself, because there are a number of projects that get cloned as part of the "normal operation" of GsDevKit_home and it starts to defeat the purpose of using GsDevKit_home, if I start rewriting chunks of the system just for travis:)

**Comment by fniephaus** [comment]
Would `git clone --depth=1 <remote-url>` work? See [git-clone](http://git-scm.com/docs/git-clone).

**Comment by dalehenrich** [comment]
Does that get me the tip of each branch? If so then that would be fine ...

**Comment by fniephaus** [comment]
Yep, it does.
So a user would need to specify a repository and a branch? Would you want to use the Metacello format `<repo url>:<branch>` and if no `<branch>` is defined, it defaults to `master`?

**Comment by dalehenrich** [comment]
At the moment I am think that a set of environment variables will be used to control the GsDevKit_home options I have a couple of different use cases right now with different projects and I need to sort through things ...

I could also add a GsDevKit_home spec to the smalltalk.ston file ... GsDevKit_home uses a pharo image to implement some of the more complicated logic and I could employ that same technique to this particular problem.

Keep in mind that I want to use smalltalkCI (which uses GsDevKit_home) to actually test GsDevKit_home ....

**Comment by fniephaus** [comment]
I'd like to minimize the things that need to be configured via `.travis.yml` and instead use the STON file. If this works for you, I am happy to extend the STON config with GemStone specific options. Same counts for Pharo and Squeak.
It'd be cool to have a Gemfile/package.json/requirements.txt equivalent in Smalltalk :)

**Comment by dalehenrich** [comment]
addressed in #105
