### ISSUE TITLE
[Pharo] The tested repository does not register itself with Iceberg

### ISSUE THREAD

**Issue by hogoww** [hpi-swa/smalltalkCI#552]
The image created for Pharo testing does not register the repository on Iceberg.
Because of that, Iceberg features cannot be used.

Particularly, I generally rely on Iceberg to tell me where the repository is in the file system.
Which allows me to use external resources.
(Maybe there's a portable equivalent, but I only use iceberg :/).

I don't have time to investigate it myself, I fixed it in another way for my project.

Pierre

**Comment by fniephaus** [comment]
Not sure what smalltalkCI would need to do. Could an Iceberg user comment on this? Maybe @gcotelli or @estebanlm?

**Comment by fniephaus** [comment]
While we wait for someone knowledgeable, I'd like to point out that smalltalkCI supports [custom scripts](https://github.com/hpi-swa/smalltalkCI#custom-scripts), which you could use as a temporary workaround.

**Comment by fniephaus** [comment]
Fixed with #580.
