### ISSUE TITLE
Image closes when using ‘--headful’ with ‘Pharo64-9.0’

### ISSUE THREAD

**Issue by Rinzwind** [hpi-swa/smalltalkCI#561]
When using ‘Pharo64-9.0’ with option ‘--headful’, the image doesn’t stay open as expected:

```
./bin/smalltalkci --headful --smalltalk Pharo64-9.0
```

It does stay open when using ‘Pharo64-8.0’:

```
./bin/smalltalkci --headful --smalltalk Pharo64-8.0
```

The following outputs ‘isHeadless: true’ for the Pharo 9 build, and ‘isHeadless: false’ for the Pharo 8 build:

```
for b in _builds/*; do (cd "$b"; ./vm TravisCI.image eval "Stdio stdout nextPutAll: 'isHeadless: ' , SmalltalkCI isHeadless asString; lf. Smalltalk snapshot: false andQuit: true"); done
```

**Comment by fniephaus** [comment]
`isHeadless` uses [`Smalltalk isHeadless` in Pharo](https://github.com/hpi-swa/smalltalkCI/blob/master/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/class/isHeadless.st#L3). Not sure what is happening here and what has changed. @estebanlm?

**Comment by Rinzwind** [comment]
Seems related to this: https://github.com/pharo-project/pharo/issues/10727

**Comment by Rinzwind** [comment]
Just a note: to avoid this issue, we’ve patched smalltalk-CI with an extra method `SmalltalkCIPharo9 class>>#isHeadless` implemented as returning the value of `Smalltalk isInteractiveGraphic not`.

**Comment by jvalteren** [comment]
@Rinzwind Thanks for the suggestion. I've committed it to our fork of the repo. Are you planning to create a pull request or shall I?

**Comment by Rinzwind** [comment]
Forgot about this, sorry, please do create the pull request.

**Comment by jvalteren** [comment]
Hi @Rinzwind, this is now resolved as per your suggested change to SmalltalkCIPharo9, thanks! Also thank you @fniephaus for accepting the PR so quickly!
