### ISSUE TITLE
Fix or remove AppVeyor builds for this repo

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#573]
These failing builds from AppVeyor are permanently taking the joy of a green bar from us and make it harder (at least for me) to determine whether a build actually failed on any relevant platform:

![image](https://user-images.githubusercontent.com/38782922/193127572-acda1b25-860f-4741-a857-3c7819680e14.png)

Since to my knowledge, AppVeyor is not used any longer in this project and is dealing with some very weird McAffee signature problems, disabling it would probably be the best option.

I'd be happy to offer to help with this as well as I can, but likely this requires admin access to the repo. Is it possible for you to disable AppVeyor anywhere on its homepage or to remove it from the [webhooks page](https://github.com/hpi-swa/smalltalkCI/settings/hooks) of the repository, from the [installations page](https://github.com/hpi-swa/smalltalkCI/settings/installations) of the repository, or from your [user-wide applications page](https://github.com/settings/installations)?

See also https://github.com/keaven/gsDesign/issues/26, https://github.com/pypa/setuptools/issues/2499, or https://github.com/appveyor/ci/issues/3585.

**Comment by fniephaus** [comment]
I have disabled AppVeyor builds. Technically, it should still be possible to run smalltalkCI builds on it, but their setup has changed and I don't have the capacity to update things. If someone is willing to work on it, please feel free to get in touch or open a PR. But for now, let's focus on GHA.

**Comment by LinqLover** [comment]
Thank you, it looks so beautiful now! :D

![image](https://user-images.githubusercontent.com/38782922/195999932-21cea912-0542-45d4-ab1d-4ad1b24bb4ea.png)

**Comment by fniephaus** [comment]
Thanks for helping clean that up! 🙂
