### ISSUE TITLE
What is the purpose of #include section in #testing?

### ISSUE THREAD

**Issue by peteruhnak** [hpi-swa/smalltalkCI#58]
What is the purpose of the `#include` section?

```ston
    #categories : [ 'MyProject-*' ],                          // Define categories to test explicitly
    #classes : [ #MyProjectTestCase ],                        // Define classes to test explicitly
    #packages : [ 'MyProject.*' ]                             // Define Pharo packages to test
    #include : {
        #categories : [ 'AnotherProject-Tests' ],               // Include categories to test
        #classes : [ #AnotherProjectTestCase ],                 // Include classes to test
        #packages : [ 'AnotherProject.*' ]                      // Include Pharo packages to test
    },
```

Isn't it equal to having it directly in the array?

```ston
    #categories : [ 'MyProject-*', 'AnotherProject-Tests' ],                          // Define categories to test explicitly
    #classes : [ #MyProjectTestCase, #AnotherProjectTestCase ],                        // Define classes to test explicitly
    #packages : [ 'MyProject.*', 'AnotherProject.*' ]                             // Define Pharo packages to test
```

**Comment by peteruhnak** [comment]
Nevermind, apparently the second variant doesn't work (even though the array syntax would suggest otherwise.)

**Comment by fniephaus** [comment]
The `#testing` section currently works as follows:


1. If not set, determine tests to run automatically (just like builderCI)
2. If `#classes` or `#categories` are set, use these for testing and ignore everything else
3. If `#include` or `#exclude` are set, determine tests to run automatically and add or remove tests accordingly. Note that 2. should not be the case (`#classes` and `#categories` should not be set).

I hope the above makes sense.

**Comment by fniephaus** [comment]
If you have an idea how to improve the doc, please send a PR :smiley:

**Comment by peteruhnak** [comment]
My point was different:

if I have
```ston
#packages : [ 'Foo.*' ]
```

then Foo is tested as expected ( https://travis-ci.org/peteruhnak/ci-foo/builds/109091321 )

however if I have
```ston
#packages : [ 'Foo.*', 'Bar.*' ]
```

then only Foo is tested, and not Bar ( https://travis-ci.org/peteruhnak/ci-foo/builds/109091408 )

So I have to do
```ston
#packages : [ 'Foo.*' ]
#include: {
  #packages : [ 'Bar.*' ]
}
```

to have them tested both ( https://travis-ci.org/peteruhnak/ci-foo/builds/109091536 )

So my question is: why does the second variant not work?

My impression is that the first `#packages` is based on LoadSpecs and ignores what I actually write there (because it will test also tests from different packages that are part of the project but do not match the regex).

**Comment by peteruhnak** [comment]
Just to confirm, are my observations about the default `package:` not really having effect correct? (i.e. that they will use LoadSpecs regardless of what I put there.)

**Comment by fniephaus** [comment]
Sorry for leaving this unanswered for so long.
I understand that
```javascript
#packages : [ 'Foo.*', 'Bar.*' ]
```
only causes `Foo` to be tested and not `Bar`? Is this the current behavior? If so, it's a bug.

**Comment by peteruhnak** [comment]
That was the case as you can see in the linked travis builds.

I seem to have deleted the github repos, but it should be easy to setup again…

**Comment by fniephaus** [comment]
That's my bad I guess. But yes, shouldn't be to hard :) I'll look into it in the next few days.

**Comment by fniephaus** [comment]
@peteruhnak you were absolutely right, explicit `#packages` have been disregarded completely. A fix should be very simple...
