### ISSUE TITLE
GemStone build fails due to missing `#ZnInvalidUTF8`

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#588]
Hi @dalehenrich,

Could you take a look at this failure please?

> .........'Undefined Symbol:#''ZnInvalidUTF8'''
> ...
> UndefinedSymbolsTest
 ✗ #testUndefinedSymbols (6ms)
a TestFailure occurred (error 2751), Assertion failed

https://github.com/hpi-swa/smalltalkCI/actions/runs/4241931741/jobs/7381820254#step:4:2523

**Comment by dalehenrich** [comment]
It looks like this isn't an issue any more? GemStone is running in recent builds...
