### ISSUE TITLE
smalltalkCI builds on GCE are broken

### ISSUE THREAD

**Issue by zecke** [hpi-swa/smalltalkCI#59]
I have no idea how the "language: smalltalk" is implemented by travis-ci but it looks like somehow it is issuing both "dpkg --add-architecture" and "apt-get". If the docker service is enabled the apt-get is issued without a '-y'.

Where can I find the scripts that implement "language: smalltalk" or could they be fixed to work with docker?

**Comment by fniephaus** [comment]
Hi @zecke,
You are looking for [this](https://github.com/travis-ci/travis-build/blob/9561e7ddc523ef51487b23b41549c11ee93a04f6/lib/travis/build/script/smalltalk.rb#L103).
It's probably better, if you send a PR to https://github.com/fniephaus/travis-build, so I can add your change to the next `smalltalk.rb` update that I'm going to send the Travis team. I try not to bomb the folks at Travis with smalltalkCI PRs.

Also have a look at https://github.com/travis-ci/travis-build/commit/592f87448bdc31ab943e0ad97dc796a8cf6c1656. Maybe it's sufficient to just revert that commit.

Thanks,
Fabio

**Comment by fniephaus** [comment]
@zecke can you restart one of your failing builds? The fix is merged, but I'm not sure if it's already deployed.

**Comment by fniephaus** [comment]
I just restarted an older GCE build and it seems to be working again. Thanks, @zecke.
