### ISSUE TITLE
update GemStone builds to run on Ubuntu 20.04 and macos-latest

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#591]
As of this [dalehenrich/smalltalkCI build](https://github.com/dalehenrich/smalltalkCI/actions/runs/4654610817), I've got the GemStone builds to pass for 20.04 and moacos, however, when I add the full pharo/squeakmosse lineup  I'm seeing [/d/a/smalltalkCI/smalltalkCI/helpers.sh: line 558: config_smalltalk: unbound variable ERROS](https://github.com/dalehenrich/smalltalkCI/actions/runs/4654561318/jobs/8236430802#step:4:265) and it is not obvious to me how to fix this issue ... I ran into the issue in GemStone builds and fixed it by using the following :
```bash
-  if [[ "${config_tracking}" != "true" ]]; then
-    return 0
+  if [ "${config_tracking+set}" ] then
+  	if [[ "${config_tracking}" != "true" ]]; then
+    	return 0
+ fi
```
but the solution is not as obvious on line 558:
```bash
  curl -s --header "X-BUILD-DURATION: ${duration}" \
          --header "X-BUILD-ENV: ${env_name}" \
          --header "X-BUILD-SMALLTALK: ${config_smalltalk}" \
          --header "X-BUILD-STATUS: ${build_status}" \
            "https://smalltalkci.fniephaus.com/api/" > /dev/null || true
```
Some guidance in this area would be appreciated.

**Comment by fniephaus** [comment]
Hi Dale, good question... I didn't see anything obviously wrong (apart from that you seem to be [mixing branches](https://github.com/dalehenrich/smalltalkCI/blob/9dd42e127227e259ec691f868fffba5f3cb8d085/.github/workflows/main.yml#L82)).
All of these vars should be defined when coverage is supposed to be reported. I can take a closer look in the next few days if you don't work out what's wrong.

**Comment by fniephaus** [comment]
Oh, maybe it's because you're pushing your commits to your fork and for that, you don't have coveralls enabled? Yes, the build shouldn't fail neither because of that nor because it can't do the tracking thing. To confirm my suspicion, maybe push your branch to this repo?

**Comment by dalehenrich** [comment]
[reproduced the failure on local issue_591 branch](https://github.com/hpi-swa/smalltalkCI/actions/runs/4659104604/jobs/8245600763#step:4:247)

**Comment by fniephaus** [comment]
I think I've fixed this with https://github.com/hpi-swa/smalltalkCI/commit/a84db3fce21126997392a9be2fe6cbae91c166a0. There seems to be a problem with the Windows VMs, which leads to corrupted JSON files, which then fail to be uploaded with curl to coveralls, which fails the subshell, which does not have access to `config_smalltalk` etc.

**Comment by dalehenrich** [comment]
... merged changes ... but [GToolKit looks to be segfaulting on mac?](https://github.com/hpi-swa/smalltalkCI/actions/runs/4669157354/jobs/8267230790#step:4:1696) ... will restart without GToolKist and try to get a GemStone run ...

**Comment by dalehenrich** [comment]
[a different kind of GToolKit failure after merging to master; running without GToolKit; failing with GToolKit](https://github.com/hpi-swa/smalltalkCI/actions/runs/4672363679/jobs/8274476329)

**Comment by fniephaus** [comment]
Feel free to open a PR now. We probably need to mark the GToolkit builds as allowed failures if they are too flaky.
