### ISSUE TITLE
Update GitHub action

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#608]
@fniephaus I think we need to update the GH action for my latest fix to work there. I've never done this. Do I just merge `main` into `action`? Or rebase?

**Comment by fniephaus** [comment]
Why do we need to do this? Because we switched `Pharo-stable` and `Pharo-alpha` to 64 bits? setup-smalltalkci uses the javascript template and they document how do change and update these types of actions [here](https://github.com/actions/javascript-action#initial-setup).

**Comment by theseion** [comment]
No, because
1. we fixed the VM selection for the stable Pharo versions
2. we fixed deprecations for Pharo 12 (that lead to failed runs)

I'll try to open a PR.

**Comment by theseion** [comment]
Oh, I see now that the action uses the master branch... Weird. Well, back to investigating then...
