### ISSUE TITLE
Please release upgraded Squeak Trunk images to resolve conflict in update stream

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/smalltalkCI#616]
I updated the Squeak Trunk images for smalltalkCI because they could not update any longer. The reason was that an empty system category (`Etoys-Squeakland-Network-MIME`) in the images (at least in the 64-bit one) had been removed, causing a Monticello conflict when updating the image. Since we could not reproduce the issue in other old images, we suspect that this clean-up had been performed by accident during the manual preparation of the previous images.

I created the new images using the same script that was used for the previous ones:

```smalltalk
PreferenceWizardMorph allInstancesDo: [:ea | ea abandon].
"Ensure Metacello is loaded."
Metacello new.
"Ensure Tonel is loaded."
[ (Smalltalk classNamed: #MCTonelMissing) signal ] valueSupplyingAnswer: true.
"Clean up and save the image."
ReleaseBuilder deleteAllWindows.
Smalltalk garbageCollect.
Smalltalk condenseChanges.
Smalltalk snapshot: true andQuit: true.
```

- [Squeak6.1alpha-22854-32bit.zip](https://github.com/hpi-swa/smalltalkCI/files/13460786/Squeak6.1alpha-22854-32bit.zip)
- [Squeak6.1alpha-22854-64bit.zip](https://github.com/hpi-swa/smalltalkCI/files/13460791/Squeak6.1alpha-22854-64bit.zip)

@fniephaus Please excuse the redundant message, Marcel said you no longer seem to have access to our Slack. :-)

**Comment by fniephaus** [comment]
Done, see v3.0.4
