### ISSUE TITLE
[Bug] Error when load in new image on Windows: curl failed to download get.pharo.org/64/vm110

### ISSUE THREAD

**Issue by labordep** [hpi-swa/smalltalkCI#617]
Hi,

Since a lot of days we have one error before launch tests on Windows.

![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/91d2515a-fa88-4479-bac5-fbc10b0dca07)

This error appears at the first launch of the Job, if I restart manually the job it's ok (sometimes).

The error is : `curl failed to download get.pharo.org/64/vm110 to '/c/Users/runneradmin/.smalltalkCI/_cache/vms/Pharo64-11/zeroconfig'.`
You can see the problem here : https://github.com/OpenSmock/GeoView/actions/runs/7118087629/job/19380226905

This is for Pharo 11 or Pharo 12 on Windows.

Thanks.

**Comment by labordep** [comment]
Similar problem on MacOS (I think):

![image](https://github.com/hpi-swa/smalltalkCI/assets/49183340/3702150f-1d78-4c85-b6dc-819e2ee21085)

When restarting this is ok!

**Comment by fniephaus** [comment]
I'm not sure what is going on, especially on Windows. Are there any known connectivity issues? @estebanlm @theseion?

**Comment by labordep** [comment]
We have these issues across several of our GitHub projects, all quite diverse. Curious that no one else has reported this problem.

For examples:
https://github.com/plantec/Toplo/actions/runs/7147253815/job/19466439389
https://github.com/OpenSmock/Molecule/actions/runs/7151366799/job/19475629372
https://github.com/OpenSmock/Pyramid/actions/runs/6920390669/job/18824841350
etc.

May be we are using CI not correctly?

**Comment by fniephaus** [comment]
The exit code always seems to be 56 and comes from curl. According to [the docs](https://everything.curl.dev/usingcurl/returns), it means:

> Failure in receiving network data. Receiving data over the network is a crucial part of most curl operations and when curl gets an error from the lowest networking layers that the receiving of data failed, this exit status gets returned. To pinpoint why this happens, some serious digging is usually required. Start with enabling verbose mode, do tracing and if possible check the network traffic with a tool like Wireshark or similar.

So this indeed sounds like the Pharo servers are having some issues.

**Comment by theseion** [comment]
Nothing we can do really... The only option I see is to add some fallback logic.

**Comment by fniephaus** [comment]
I guess the best we can do is retry the download, which I have just enabled with https://github.com/hpi-swa/smalltalkCI/commit/3f608f002763495be31a10f7563060668ba045a6.

**Comment by labordep** [comment]
Thanks, we haven't seen this problem since your update 👍

**Comment by fniephaus** [comment]
Perfect, thanks for the update!
