### ISSUE TITLE
Metacello broken again for Pharo 12

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#622]
See https://github.com/pharo-project/pharo/issues/15929

**Comment by guillep** [comment]
I'm working on it, it will be fixed during the day ;)

**Comment by guillep** [comment]
Hi guys this is solved in https://github.com/pharo-project/pharo/pull/15937.
I've already seen some smalltalkci projects in the nature working ;)

Please contact me if there is another issue!

**Comment by fniephaus** [comment]
Thank you, @guillep!

**Comment by theseion** [comment]
Thanks @guillep!
