### ISSUE TITLE
Pharo12 builds fail because they removed Time>>millisecondsToRun:

### ISSUE THREAD

**Issue by jbrichau** [hpi-swa/smalltalkCI#623]
The builds using Pharo12 fail because they removed the `Time>>millisecondsToRun:` method:

`Instance of Time class did not understand #millisecondsToRun:`

For example: https://github.com/SeasideSt/Seaside/actions/runs/7512588387/job/20453435450

**Comment by jbrichau** [comment]
I fixed the mistake in the baseline for Pharo 3 that made builds fail after the class package change. I do wonder if these old versions should still be supported in the future though.

**Comment by theseion** [comment]
This issue can be closed, right?

**Comment by jbrichau** [comment]
Yes, thanks @theseion and @fniephaus !
