### ISSUE TITLE
Github actions warning: node16 actions are deprecated

### ISSUE THREAD

**Issue by jbrichau** [hpi-swa/smalltalkCI#627]
The following appears when running smalltalkCI on github actions:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: hpi-swa/setup-smalltalkCI@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by LinqLover** [comment]
This needs to be changed here: https://github.com/hpi-swa/setup-smalltalkCI/blob/fbba7557dea7bd79a8780cf5e3b5e7dd27c5cedb/action.yml#L25 But no idea whether node20 has breaking changes for the use cases of this action.
