### ISSUE TITLE
[Question] Is it sensible to rely on SmalltalkCI code for an asdf plugin?

### ISSUE THREAD

**Issue by smarr** [hpi-swa/smalltalkCI#628]
This might be a little unusual question for the SmalltalkCI maintainers:

Would it be totally unreasonable to rely on the SmalltalkCI project as a source of "machine-readable" version information and installation/download code for Squeak?

I would like to add Squeak to [smarr/asdf-awfy](https://github.com/smarr/asdf-awfy), a plugin for [asdf](https://asdf-vm.com/), a Runtime Version Manager, which I started setting up for the AreWeFastYet project.

I am currently thinking of parsing [README.md](https://github.com/hpi-swa/smalltalkCI/blob/master/README.md) for the supported Squeak image versions, and possibly just download the latest version of [squeak/run.sh](https://github.com/hpi-swa/smalltalkCI/blob/master/squeak/run.sh) for having the code of extracting/installing the VM/image.

Would that be vaguely reasonable? Or might there be other options I am not aware of?

**Comment by LinqLover** [comment]
If your goal is to automate the download & preparation of the latest Squeak bundles, could [create-image](https://github.com/LinqLover/create-image) maybe help you?

**Comment by smarr** [comment]
@fniephaus yeah, parsing listings on `files.squeak.org` is another option. In the end, I am just looking for a "good enough" 80% solution, that's only needs a bit of maintaining every 5 years or so... :) 

For Pharo, I indeed parse `files.pharo.org`: https://github.com/smarr/asdf-awfy/blob/main/lib/utils.bash#L48-L54

**Comment by fniephaus** [comment]
> only needs a bit of maintaining every 5 years or so

There are not too many Squeak releases, and parsing listings on `files.squeak.org` is probably better than smalltalkCI's README.md.

**Comment by smarr** [comment]
Alright, it's not exactly pretty, but will work for now. Thanks.

https://github.com/smarr/asdf-awfy/blob/main/lib/utils.bash#L65-L92
