### ISSUE TITLE
Deprecate builderCI fallback

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#63]
The builderCI fallback seems broken again at the moment and this might be a good time to deprecate it.
Initially, I have added builderCI fallback support to provide support for Pharo and GemStone. Pharo has been fully supported for quite a while now and I hope that we have GemStone running very soon (#51).
There's no need to maintain something (builderCI fallback in smalltalkCI) that nobody is using anymore, anyway.

**Comment by fniephaus** [comment]
@dalehenrich are you ok with this?

**Comment by dalehenrich** [comment]
absolutely ... smalltalkCI as configured now supports all GemStone versions from 2.4.4.1 through 3.3.0, so there is no need to do a fallback at all ...
