### ISSUE TITLE
Compatibility package for Pharo

### ISSUE THREAD

**Issue by sebastianconcept** [hpi-swa/smalltalkCI#632]
After seeing https://github.com/hpi-swa/smalltalkCI/issues/631 which affects more than one Pharo version, a compatibility package is the recommendation to isolate its changing public API.

As its first feature, this compatibility package  needs to return a boolean for this:

https://github.com/hpi-swa/smalltalkCI/blob/f163c906638fc4be54e340ae801833137ff14394/repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo.class/class/saveImage.st#L3

**Comment by fniephaus** [comment]
See https://github.com/hpi-swa/smalltalkCI/issues/631#issuecomment-1946409055
