### ISSUE TITLE
Test that smalltalkCI builds can fail

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#65]
At the moment, the smalltalkCI self-test checks if the smalltalkCI tests pass.
It'd be good to also test if smalltalkCI builds can actually fail.
There are already [excluded tests](https://github.com/hpi-swa/smalltalkCI/tree/99e03d360a50dc65c45290d9a77a1b1c699275c1/repository/SmalltalkCI-Excluded-Tests.package) that we can use for this.
Also, it would be handy to be able to specify a custom `.ston` file for a build. Then we could do both, executing the normal tests and tests that are expected to fail in one build by running smalltalkCI twice.

**Comment by dalehenrich** [comment]
See the comment [here](https://github.com/hpi-swa/smalltalkCI/pull/51#issuecomment-188057056) of a [build failure](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/111388569#L2995) that is not a failed test, but a failure that indicates another problem ... probably need to reopen and fix for GemStone
