### ISSUE TITLE
lcov file is empty

### ISSUE THREAD

**Issue by Trevizoalejandro15** [hpi-swa/smalltalkCI#653]
im running smalltalkCI locally in my windows PC and for some reason if i run the next lines the tests run but my lcov file is empty

bin/smalltalkci -s "Pharo64-10" --image /c/Users/luisp/locationOfImage.image /c/Users/locationOfSmalltalkSton/.smalltalk.ston

and this is my SmalltalkCISpec

SmalltalkCISpec {
  #testing : {
    #include : {
      #packages : [ 'MyTests' ]
    },
    #coverage : {
      #packages : [ 'MyPackage to get  coverage' ],
      #format : #lcov
    }
  }
}

**Comment by fniephaus** [comment]
Could you provide a reproducer please? I can't tell what the problem is. You can try debug it with the debug option.

**Comment by Trevizoalejandro15** [comment]
yeah sure

![image](https://github.com/user-attachments/assets/fca0c585-5a17-47b9-9eb4-4976b01edbc7)

**Comment by Trevizoalejandro15** [comment]
just i ran it in linux, it dont works well in windows
