### ISSUE TITLE
Make sure smalltalkCI fails if any subcommand fails

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#66]
`set -e` isn't enough: https://github.com/hpi-swa/smalltalkCI/pull/51#issuecomment-187491814.

**Comment by fniephaus** [comment]
@dalehenrich I have not been able to reproduce the problem you mentioned in https://github.com/hpi-swa/smalltalkCI/pull/51#issuecomment-185924243.
Regardless, I have enabled a few more safety switches to make sure smalltalkCI fails as soon as something unexpected happens.

**Comment by fniephaus** [comment]
@dalehenrich Do you think it's necessary to keep [these `exit 1`s](https://github.com/hpi-swa/smalltalkCI/blob/cec5905a1ff45d2c86f7fa1721795cca33229882/gemstone/run.sh#L53) or [the `print_error_and_exit`s](https://github.com/hpi-swa/smalltalkCI/blob/cec5905a1ff45d2c86f7fa1721795cca33229882/gemstone/run.sh#L101)?

**Comment by dalehenrich** [comment]
I think that those `exit 1`s were created before I knew that `print-error_and_exit` existed :)

**Comment by dalehenrich** [comment]
I see that you've assigned this bug to me ... what do you want done in relation to this ... change the `exit 1`s or something else?

**Comment by fniephaus** [comment]
I had a look at this again.
Looks like that this [`|| status=$?`](https://github.com/hpi-swa/smalltalkCI/blob/d4b1bbf11c210b995f81b6f69367bb3488498fc1/run.sh#L568) causes the problems. Basically `set -e` is ignored for some reason when a subfunction is called like that. I'm cleaning up the code a little bit and I'll make sure checks like this are only used when absolutely necessary.
