### ISSUE TITLE
Test resources are set up multiple times

### ISSUE THREAD

**Issue by Rinzwind** [hpi-swa/smalltalkCI#661]
Given a TestResource subclass DummyTestResource with `#setUp` implemented as showing 'Setting up DummyTestResource' on the transcript, after adding DummyTestResource to the resources for SCIAbstractLoadSpecTest, the message is shown five times, rather than just once, when running the smalltalkCI tests using Pharo64-13.

Reverting the change made to `#runClasses:spec:` for SCIPharoTestRunner in commit 7fed37997820de11 causes the message to only be shown once as expected (but also causes the test `#testCustomTestSuite` introduced in the same commit to fail).

**Comment by fniephaus** [comment]
Thanks for filing this issue. Could one of you take a look please, @mattonem and @theseion?

**Comment by theseion** [comment]
@Rinzwind Why is your expectation that the message is only shown once? Resources are set up and torn down for every test suite and Dr. Test constructs one suite per test class. Ergo, you should see the message as many times as there are test classes that use the resource.

**Comment by Rinzwind** [comment]
Because I expected it to use a single suite like `#runClasses:named:` for HDTestReport does do (at least in Pharo 13 build 225). That ignores overrides of `#suiteClass` though. In `#runClasses:spec:` for SCIPharoTestRunner the resources could be combined so that they only need to be set up once, while still keeping each class’s `#suiteClass` into account, by replacing the ‘do’ over the classes with the following:

```smalltalk
resources := OrderedCollection new.
classes do: [ :class |
	| classSuite |
	classSuite := class suite.
	resources addAll: (classSuite resources reject: [ :resource | resources includes: resource ]).
	classSuite resources: #().
	suite addTest: classSuite ].
suite resources: resources.
```

**Comment by theseion** [comment]
That will prevent overrides of `#suiteClass` from working. I don't feel that this is an issue with SmalltalkCI but with SUnit in Pharo. `TestSuite>>#tearDown` sends `#resetResources` to `TestResource`, which resets all the resources of the suite. This completely defeats the idea that suites can be nested. IMO, nested suites must know that they are nested and leave tear down to the outer suite (this already works for `#setUp`, because `TestResource>>#isAvailable` returns true after the outer suite has run initialization).

**Comment by Rinzwind** [comment]
I don’t quite follow how it would prevent overrides of `#suiteClass` from working. I tried replacing the ‘do’ in `#runClasses:spec:` for SCIPharoTestRunner. That allowed `#testCustomTestSuite` to still pass while causing the message of the test resource in my example to be shown only once instead of five times. I do agree though the framework should probably better take into account that suites can be composed when it comes to resources.

**Comment by theseion** [comment]
You're right, it does work with the code you posted, sorry. I had simply patched the code to mimic what `HDTestReport` does, which is to construct a single suite. I'll look into patching SmalltalkCI. Would you mind raising the issue with Pharo? Or would you rather I do that?

**Comment by Rinzwind** [comment]
I opened [Pharo issue #17113](https://github.com/pharo-project/pharo/issues/17113) about it.

**Comment by theseion** [comment]
I've opened a PR (#662). I'd appreciate your feedback @Rinzwind.

**Comment by Rinzwind** [comment]
I added my feedback to the pull request.
