### ISSUE TITLE
No reason of failure given

### ISSUE THREAD

**Issue by Uko** [hpi-swa/smalltalkCI#67]
Hi, I end up with this log:

```
Loading and testing project...
3.00s2016-02-23 08:41:17.139 Pharo[517:507] 08:41:17.137 ERROR:     [0xa116d1a8] AQMEIO.cpp:377: _FindIOUnit: error -66680
2016-02-23 08:41:17.139 Pharo[517:507] 08:41:17.139 ERROR:     [0xa116d1a8] >aq> AudioQueueObject.cpp:1590: Prime: failed (-66680); will stop (5512/0 frames)
2016-02-23 08:41:17.140 Pharo[517:507] 08:41:17.140 ERROR:     [0xa116d1a8] AQMEIO.cpp:377: _FindIOUnit: error -66680
2016-02-23 08:41:17.142 Pharo[517:507] 08:41:17.142 ERROR:     [0xa116d1a8] >aq> AudioQueueObject.cpp:1590: Prime: failed (-66680); will stop (33075/0 frames)
Fetched -> BaselineOfSmalltalkCI-fn.5 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- filetree:///Users/travis/smalltalkCI-master/repository
Loaded -> BaselineOfSmalltalkCI-fn.5 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- filetree:///Users/travis/smalltalkCI-master/repository
Loading baseline of BaselineOfSmalltalkCI...
Fetched -> STON-Core-fn.59 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- filetree:///Users/travis/smalltalkCI-master/repository
Fetched -> SmalltalkCI-Core-fn.2 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- filetree:///Users/travis/smalltalkCI-master/repository
Fetched -> SmalltalkCI-Pharo-fn.2 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- filetree:///Users/travis/smalltalkCI-master/repository
Loaded -> STON-Core-fn.59 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- cache
Loaded -> SmalltalkCI-Core-fn.2 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- cache
Loaded -> SmalltalkCI-Pharo-fn.2 --- filetree:///Users/travis/smalltalkCI-master/repository [:] --- cache
...finished baseline
Failed to load and test project.
The command "$SMALLTALK_CI_HOME/run.sh" exited with 1.
Done. Your build exited with 1.
```

And if you look at it you have no idea what happened because it says `...finished baseline` and then immediately `Failed to load and test project.`

**Comment by Uko** [comment]
This happens if `#directory : ` is missing from configuration STON.

First of all it would be nice to tell people if they are missing something.

Secondly, how about making `#directory` setting optional, and make it point to the root of the project by default?

**Comment by fniephaus** [comment]
Thanks for reporting, @Uko. This is definitely a problem and I like your suggestion.
It actually reminds me of the fact that I should add more tests to SmalltalkCI and it's platform-specific packages.

**Comment by peteruhnak** [comment]
I'm having the same issue, and it's not `#directory` related as far as I can tell; all my builds are failing because of this.

`.smalltalk.ston`: https://github.com/dynacase/dynacase-model/blob/90146e44c497972ca8a81d3032068cc952705ad2/.smalltalk.ston

failing build: https://travis-ci.org/dynacase/dynacase-model/builds/111426018#L244

**Comment by fniephaus** [comment]
Mh, this is bad news. I just run the dynacase build locally and it passes without any problems, so it's probably a Travis thing. Could you enable debugging output by overriding `script` in your `.travis.yml`:
```yml
script: $SMALLTALK_CI_HOME/run.sh --debug --verbose
```

**Comment by fniephaus** [comment]
It's even worse: your tests seem to be passing now on Travis :see_no_evil: 
What happens if you restart your older failing build?

**Comment by peteruhnak** [comment]
and now it's failing again… so verbose/debug is setting something wrong?

**Comment by fniephaus** [comment]
`--verbose` is only used [here](https://github.com/hpi-swa/smalltalkCI/blob/c7008543c8e6ec37cf31bd64abb98cf4e47a6bf6/run.sh#L331), and `--debug` [here](https://github.com/hpi-swa/smalltalkCI/blob/c7008543c8e6ec37cf31bd64abb98cf4e47a6bf6/run.sh#L301-L307). They are not used at all in `pharo/run.sh`.
So I really don't see why this is happening :(

**Comment by fniephaus** [comment]
@peteruhnak and I have been able to identify and fix the problem.

Things I still need to do:
- [ ] Display meaningful error when `SmalltalkCI runCIFor:` is invoke with a non-STON file
- [ ] Make sure custom file is a STON file

**Comment by dalehenrich** [comment]
I have a related problem with a slightly different error condition for [a pharo build](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/112153953#L275-L285) where I see the following in the travis log where there is absolutely no information about why the load failed:

```
Loaded -> SmalltalkCI-Tests-dkh.21 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
Loaded -> SmalltalkCI-Package-Tests-dkh.1 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
Loaded -> SmalltalkCI-Package-Pharo-Tests-dkh.1 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
Loaded -> SmalltalkCI-Excluded-Tests-fn.1 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
Loaded -> STON-Tests-fn.54 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
Failed to load and test project.
The command "$SMALLTALK_CI_HOME/run.sh --debug && $SMALLTALK_CI_HOME/tests/fail_test.sh" exited with 1.
Done. Your build exited with 1.
```

Fortunately, the [squeak build is failing in the same spot](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/112153943#L252-L289) and presumably has the same error:

```
Loaded -> SmalltalkCI-Tests-dkh.21 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
Loaded -> SmalltalkCI-Excluded-Tests-fn.1 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
(ZnBufferedReadStream is Undeclared) 
(ZnBufferedWriteStream is Undeclared) 
Loaded -> STON-Tests-fn.54 --- filetree:///home/travis/build/dalehenrich/smalltalkCI/repository [:] --- cache
...finished baselineSmalltalkCICategoryTest class>>sunitName
isAbstract
	"Override to true if a TestCase subclass is Abstract and should not
	have TestCase instances built from it"
	^ self sunitName = #SmalltalkCIAbstractTest
SmalltalkCICategoryTest class(Object)>>doesNotUnderstand: #sunitName
SmalltalkCICategoryTest class(SmalltalkCIAbstractTest class)>>isAbstract
[] in SCITestReport class>>runClasses:named:
[] in Set>>select:
Set>>do:
Set>>select:
SCITestReport class>>runClasses:named:
SmalltalkCISqueak>>runTests
```

So it appears that pharo is not properly dumping the stack trace to the travis log ...

BTW, I can open a separate issue if you want ... the solution is probably different than this particular case

**Comment by fniephaus** [comment]
I would usually run smalltalkCI locally with `--headfull` mode enabled. This will most likely show you a Pharo image with an open debugger. I'll have a look next week.

And feel free to open another issue if you think it's unrelated. :)

**Comment by fniephaus** [comment]
Closed in favor of https://github.com/hpi-swa/smalltalkCI/issues/115.
