### ISSUE TITLE
SmalltalkCI-Tests remains in ./tests

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#69]
What do we do with these tests?
https://github.com/hpi-swa/smalltalkCI/tree/ee4070f14b153fd85d6ad7f65a150a18efd7d4ae/tests/SmalltalkCI-Tests.package/SmalltalkCITest.class/instance

**Comment by dalehenrich** [comment]
Ah ... these tests are supposed to be run ... and they were passing for all three platforms in my checkout  .... I see that they are not being run now so I will look into what is happening ...

**Comment by dalehenrich** [comment]
Aha ... the tests repo got move from `.tests` to `.repository` and I didn't notice --- no conflicts --- and my new tests were not merged .... I'll take care of that soonish

**Comment by dalehenrich** [comment]
action has moved to PR #74
