### ISSUE TITLE
last line of jUnit XML is not shown

### ISSUE THREAD

**Issue by Nef10** [hpi-swa/smalltalkCI#70]
Have a look at [this build](https://travis-ci.org/HPI-BP2015H/squeak-parable/jobs/111706297#L270), there is no `</testsuite>` in line 318.
But if you get the raw log from travis you can find the line `</testsuite>travis_fold:end:junit_xml`

We think is is because there is no newline before the `travis_fold:end`.

**Comment by fniephaus** [comment]
Opps, yes that's a problem. Can you send a PR?
