### ISSUE TITLE
GemStone should use `master` branch of GsDevKit_home

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#72]
For PR #51, changes were required to GsDevKit_home and those changes were made on the `dev` branch. Now that the PR #51 work is done, I will merge the needed changes into the `master` branch  with GsDevKit/GsDevKit_home#75 and once that's done, I will need to switch back to using the `master` branch of GsDevKit_home ...

**Comment by fniephaus** [comment]
I think this relates to #54, right? And why would I want to switch the branch?

**Comment by dalehenrich** [comment]
Yes, and I may not fix Issue #54 right now ... 

I will want to switch the branch of GsDevKit_home that is being used if there is a bugfix in a branch that needs to be tested (as was the case here --- smalltalkCI green tests were dependent upon using the dev branch of GsDevKit_home, until the code in the dev branch could be merged to master ...

IN the general case, this well extend to specifying a different GsDevKit_home fork to be used with smalltalkCI ...

And of course I have yet to figure out how I will test GsDevKitHome itself using smalltalkCI, but it will involve "changing the version of GsDevKit_home that is being used to bootstrap things"

**Comment by fniephaus** [comment]
f0fcfbb6f2ee0e8198b247bb80a97fd3243e6489
