### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#77]
Travis is [working on Windows support](https://github.com/travis-ci/travis-ci/issues/2104) and in the meantime, one could use [appveyor](http://AppVeyor.com) for Windows builds.

Since I haven't been working with Win in the last few years, it'd be great if someone else could work on this.

**Comment by fniephaus** [comment]
Maybe Microsoft is faster supporting bash:
http://blog.dustinkirkland.com/2016/03/ubuntu-on-windows.html

:smile:

**Comment by dalehenrich** [comment]
`Github for Windows` supports a git and a bash shell for Windows ... I use it for the GsDevKit_home Windows client support ... so smalltalkCI could run locally in that environment .... GemStone only supports windows clients and the formula for downloading and starting a Paro/Squeak vms might be different, but presumably the run.sh scripts should run (almost) without changes...

**Comment by fniephaus** [comment]
Windows/AppVeyor support available since 5073e620d008b0c1c2066aec60a9ada9d3db9448.
