### ISSUE TITLE
List of projects using smalltalkCI

### ISSUE THREAD

**Issue by SergeStinckwich** [hpi-swa/smalltalkCI#78]
You should start a list of projects that use SmalltalkCI. For example PlayerST: https://github.com/SergeStinckwich/PlayerST

**Comment by fniephaus** [comment]
I like the idea. Shall we add this to the end of the `README.md` or do you have a better suggestion?

**Comment by SergeStinckwich** [comment]
Yes at the end of README.md or put the list on the Wiki.

**Comment by fniephaus** [comment]
20+ projects are already using smalltalkCI, nice! :)
