### ISSUE TITLE
Should exception handling be configurable?

### ISSUE THREAD

**Issue by theseion** [hpi-swa/smalltalkCI#80]
See pull request #79 and issue #64.

For reference:

> > Are you sure that this only needs to be done in Pharo?
> 
> For Fuel yes. In general I expect that MC will issue a Warning instead of the more specific MCMergeOrLoadWarning.
> 
> > A handler for just the "load or merge Warning" is pretty specific and won't mask other Warnings that might be more interesting
> 
> True. However, MCMergeOrLoadWarning expects true when resuming, which is not the default resumption value. So this warning needs special handling.
> 
> > Perhaps it would be useful to log the fact that the exception was handled before resuming?
> 
> Yes. I had to guess my way to fixing the problem because nothing was visible in the log. It would be nice to see warnings and exceptions, even if they are then being handled.
> 
> > There's an outside chance that it might be desirable to break the build as discussed in Issue #64.
> 
> I think such a setting is be a good idea (and maybe should be the default). However, for Fuel specifically I must be able to force the load, and there's no way to disable the warnings (unless I patch MC in a #preLoadDoIt...)
> 
> > For the long term perhaps we could add a list of Warnings to be handled and resumed in addition to the fail load on list and deprecate the #onWarningLog attribute.
> 
> While that sounds like a good idea, as I state above I fear that MC in Squeak will issue a Warning. So handling of that specific case would entail the same handling for all warnings.
> In addition, we would need an option to specify the handling behaviour, as MCMergeOrLoadWarning expects a specific value when resumed.

**Comment by dalehenrich** [comment]
On 3/5/16 9:50 AM, Max Leske wrote:
>
> See pull request #79 <https://github.com/hpi-swa/smalltalkCI/pull/79> 
> and issue #64 <https://github.com/hpi-swa/smalltalkCI/issues/64>.
>
> For reference:
>
>         Are you sure that this only needs to be done in Pharo?
>
>     For Fuel yes. In general I expect that MC will issue a Warning
>     instead of the more specific MCMergeOrLoadWarning.
>
MCMergeOrLoadWarning is specific to Pharo ... both GemStone and Squeak 
issue a simple Warning...

Metacello has two Notifications: MetacelloIgnorePackageLoaded , 
MetacelloSkipDirtyPackageLoad that can be used to control Metacello's 
behavior in this area ... if you go ahead and load over a dirty package, 
then you are exposed to the platform behavior in this regard...
>
>         A handler for just the "load or merge Warning" is pretty
>         specific and won't mask other Warnings that might be more
>         interesting
>
>     True. However, MCMergeOrLoadWarning expects true when resuming,
>     which is not the default resumption value. So this warning needs
>     special handling.
>
Oh that's right ... it should not be a subclass of Warning since it 
doesn't behave like a Warning --- don't know why it was created as a 
subclass of Warning ...
>
>         Perhaps it would be useful to log the fact that the exception
>         was handled before resuming?
>
>     Yes. I had to guess my way to fixing the problem because nothing
>     was visible in the log. It would be nice to see warnings and
>     exceptions, even if they are then being handled.
>
That's what onWarningLog does ...
>
>         There's an outside chance that it might be desirable to break
>         the build as discussed in Issue #64
>         <https://github.com/hpi-swa/smalltalkCI/issues/64>.
>
>     I think such a setting is be a good idea (and maybe should be the
>     default). However, for Fuel specifically I must be able to force
>     the load, and there's no way to disable the warnings (unless I
>     patch MC in a #preLoadDoIt...)
>
I guess I don't quite understand what is special about Fuel ... is there 
a reason it ends up with dirty packages on load ... perhaps the Fuel 
configuration should be using #atomic loadType ... this is the classic 
cause of getting dirty package Warnings when moving a method between 
packages ...
>
>         For the long term perhaps we could add a list of Warnings to
>         be handled and resumed in addition to the fail load on list
>         and deprecate the #onWarningLog attribute.
>
>     While that sounds like a good idea, as I state above I fear that
>     MC in Squeak will issue a Warning. So handling of that specific
>     case would entail the same handling for all warnings.
>     In addition, we would need an option to specify the handling
>     behaviour, as MCMergeOrLoadWarning expects a specific value when
>     resumed.
>
>
Well it turns out that Warnings work just fine if you do a `resume: 
true`, since the return value is ignored ... this is a pattern I have 
used a lot (which is why I thought that onWarningLog would work --- the 
non-warning Warning has been a pain for many years) and could be applied 
in this case ... if not special cases can be buried in the handling code:)

Dale

**Comment by theseion** [comment]
> On 05 Mar 2016, at 19:15, Dale Henrichs <notifications@github.com> wrote:
> 
> 
> 
> On 3/5/16 9:50 AM, Max Leske wrote:
> >
> > See pull request #79 <https://github.com/hpi-swa/smalltalkCI/pull/79> 
> > and issue #64 <https://github.com/hpi-swa/smalltalkCI/issues/64>.
> >
> > For reference:
> >
> > Are you sure that this only needs to be done in Pharo?
> >
> > For Fuel yes. In general I expect that MC will issue a Warning
> > instead of the more specific MCMergeOrLoadWarning.
> >
> MCMergeOrLoadWarning is specific to Pharo ... both GemStone and Squeak 
> issue a simple Warning...
> 
> Metacello has two Notifications: MetacelloIgnorePackageLoaded , 
> MetacelloSkipDirtyPackageLoad that can be used to control Metacello's 
> behavior in this area ... if you go ahead and load over a dirty package, 
> then you are exposed to the platform behavior in this regard...
> >
> > A handler for just the "load or merge Warning" is pretty
> > specific and won't mask other Warnings that might be more
> > interesting
> >
> > True. However, MCMergeOrLoadWarning expects true when resuming,
> > which is not the default resumption value. So this warning needs
> > special handling.
> >
> Oh that's right ... it should not be a subclass of Warning since it 
> doesn't behave like a Warning --- don't know why it was created as a 
> subclass of Warning ...
> >
> > Perhaps it would be useful to log the fact that the exception
> > was handled before resuming?
> >
> > Yes. I had to guess my way to fixing the problem because nothing
> > was visible in the log. It would be nice to see warnings and
> > exceptions, even if they are then being handled.
> >
> That's what onWarningLog does …

Good to know for the future :)

> >
> > There's an outside chance that it might be desirable to break
> > the build as discussed in Issue #64
> > <https://github.com/hpi-swa/smalltalkCI/issues/64>.
> >
> > I think such a setting is be a good idea (and maybe should be the
> > default). However, for Fuel specifically I must be able to force
> > the load, and there's no way to disable the warnings (unless I
> > patch MC in a #preLoadDoIt...)
> >
> I guess I don't quite understand what is special about Fuel ... is there 
> a reason it ends up with dirty packages on load ... perhaps the Fuel 
> configuration should be using #atomic loadType ... this is the classic 
> cause of getting dirty package Warnings when moving a method between 
> packages …

Your remark made me curious. It turns out, that MC does something funky when treating method changes. After a method has been modified it will send #methodModified: to MCWorkingCopy class, where #managersForCategory:do: tries to figure out which working copy is responsible for the method (in my case the method is an extension method on SocketStream in the category *Fuel). This is how MC tries to figure this out:

```self registry do: [:mgr | 
		(mgr packageSet packages anySatisfy:[:p | p name beginsWith: aSystemCategory])	ifTrue: [
			aBlock value: mgr.
			foundOne := true.
		]
	].```

`aSystemCategory` is ‘Fuel’. Ergo the first matching working copy will be set to modified, and that happens to be FuelCommandLineHandler, which has absolutely nothing to do with the modification.

Hence I get multiple modified packages about which MC complains when it tries to load another extension method.

> >
> > For the long term perhaps we could add a list of Warnings to
> > be handled and resumed in addition to the fail load on list
> > and deprecate the #onWarningLog attribute.
> >
> > While that sounds like a good idea, as I state above I fear that
> > MC in Squeak will issue a Warning. So handling of that specific
> > case would entail the same handling for all warnings.
> > In addition, we would need an option to specify the handling
> > behaviour, as MCMergeOrLoadWarning expects a specific value when
> > resumed.
> >
> >
> Well it turns out that Warnings work just fine if you do a `resume: 
> true`, since the return value is ignored ... this is a pattern I have 
> used a lot (which is why I thought that onWarningLog would work --- the 
> non-warning Warning has been a pain for many years) and could be applied 
> in this case ... if not special cases can be buried in the handling code:)

Ok. So my work around should be integrated into the general warning handling.

> 
> Dale
> —
> Reply to this email directly or view it on GitHub <https://github.com/hpi-swa/smalltalkCI/issues/80#issuecomment-192700757>.
>

**Comment by fniephaus** [comment]
The `#onWarningLog` option for `SCIMetacelloLoadSpec`s was implemented a while ago.
Can this be closed?

**Comment by dalehenrich** [comment]
I think this bug remains open because the `onWarningLog` feature in SmalltalkCI does not do a `resume: true` for the Warning, thus @theseion is seeing Warnings when load Fuel even when using `onWarningLog` ... the fix would be to change SCIMetacelloLoadSpec>>basicLoadProjectOn: to either use `resume: true` or explicitly use the #onWarningLog for Metacello ... I assume the comment about `older versions of Metacello` refers to the fact that older versions of Pharo (including Pharo4.0 which wasn't old at the time) did not have a recent version of Metacello installed by default that included the #onWarningLog feature ... so that means we stil need to change the code to do a `resume: true` ...

**Comment by fniephaus** [comment]
Mh I though that's exactly what is already happening. [This](https://github.com/hpi-swa/smalltalkCI/blob/d4b1bbf11c210b995f81b6f69367bb3488498fc1/repository/SmalltalkCI-Core.package/SCIMetacelloLoadSpec.class/instance/basicLoadProjectOn..st#L23) looks very much the same as [this](https://github.com/dalehenrich/metacello-work/blob/cec4d0cf222c8f438ea68a99c65cb9efc8f74452/repository/Metacello-Base.package/Metacello.class/instance/onWarningLog.st#L8), right?

**Comment by fniephaus** [comment]
I thought the option already does the same as Metacello's option. [This](https://github.com/hpi-swa/smalltalkCI/blob/d4b1bbf11c210b995f81b6f69367bb3488498fc1/repository/SmalltalkCI-Core.package/SCIMetacelloLoadSpec.class/instance/basicLoadProjectOn..st#L23) looks very much the same as [this](https://github.com/dalehenrich/metacello-work/blob/cec4d0cf222c8f438ea68a99c65cb9efc8f74452/repository/Metacello-Base.package/Metacello.class/instance/onWarningLog.st#L8), right?
But if you say it needs to be `resume: true` instead, I'm happy to update `basicLoadProjectOn:`.

**Comment by fniephaus** [comment]
I wonder, since `MCMergeOrLoadWarning` is Pharo-specific, what would be the best way to deal with this. A Pharo-specific subclass and overwrite the method? I don't think it's save to use `resume: true` for all Warnings, even the ones on Squeak and GS, right?

**Comment by dalehenrich** [comment]
Good point ... Sorry ... every time this comes up I end up with the following comment (which I missed when refreshing my memory about this bug):

>this is a pattern I have used a lot (which is why I thought that onWarningLog would work --- the non-warning Warning has been a pain for many years) and could be applied in this case 

Metacello has a **MetacelloSkipDirtyPackageLoad** which is implemented correctly (not a subclass of Warning) and behaves similarly to Pharo's **MCMergeOrLoadWarning** ... and I have an [open issue to add an onDirty: handler for Metacello](https://github.com/dalehenrich/metacello-work/issues/231) ...

Sooo long story short ...  I do not plan on changing onWarningLog and eventually I will get around to adding [an `onDirtyLog` feature to Metacello ](https://github.com/dalehenrich/metacello-work/issues/231) at which time SmalltalkCI can add a similar feature --- which is actually more useful in the end ...

I'm inclined to want onWarningLog to track Metacello's implementation which it does and perhaps the Pharo folks should fix their bug:)

**Comment by dalehenrich** [comment]
It's safe to use `resume:` but it isn't really **correct** thus my reluctance to change Metacello or SmalltalkCI ... 

I use the `resume:` pattern when I write scripts where I want to suppress the MCMergeOrLoadWarning ... but only when I am working with Pharo ...

**Comment by fniephaus** [comment]
Ok, so we leave `SCIMetacelloLoadSpec>>basicLoadProjectOn:` as is to keep the implementations aligned and add `onDirtyLog` when it's available. Can we close this issue then and maybe add a comment to https://github.com/dalehenrich/metacello-work/issues/231 so we don't forget to add it to smalltalkCI?

**Comment by dalehenrich** [comment]
closing this issue is @theseion call.. this bug could be renamed to be an onDirty something or other and it can stay open until metacello adds the feature ...

**Comment by dalehenrich** [comment]
on second thought I think that the pharo folks need some kind of relief for loading their projects ( original reason for @theseion to submit bug ) ... onWarningLog seems wrong but perhaps onMCMergeOrLoadWarningLoad would be a Pharo-only option to handle these Warnings ... I don't recall offhand what the default action for MCMergeOrLoadWarningLoad is, but it is likely to be wrong for use in SmalltalkCI :(

**Comment by theseion** [comment]
I'll review this on the weekend and let you know what I think.

**Comment by theseion** [comment]
The default action for `MCMergeOrLoadWarning` is to cancel the operation (`nil`). `true` will force the load and `false` will produce a merge.

I think `MCMergeOrLoadWarning` should be changed, so that the default is to force the load. That would make a lot of things easier, wouldn't it? What's your opinion?

I can open another issue in addition as a reminder for the `onDirtyLog` implementation.

**Comment by fniephaus** [comment]
I think it's weird that there's is an action for `nil` which is also the default. It'd certainly make things easier if the default is to force the load, otherwise user interaction is required, right?
Please feel free to open a dedicated issue for `onDirtyLog` if this is something you'd need for your use-cases :)

**Comment by dalehenrich** [comment]
@theseion perhaps an explicit onDirtyLog issue is called for ...

**Comment by theseion** [comment]
I've opened an issue to change the behaviour of `MCMergeOrLoadWarning` in Pharo: https://pharo.fogbugz.com/f/cases/19280/The-default-operation-of-MCMergeOrLoadWarning-should-be-to-perform-the-load-not-cancel-the-operation
