### ISSUE TITLE
Cache bootstrapped version of GemStone by GemStone version number

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#83]
The bootstrapped version of GemStone changes relatively infrequently and if the `--clean` option does what I think it does, a developer can clean their cache whenever they are interested in picking up the latest bootstrapped build ...

**Comment by fniephaus** [comment]
Where does the bootstrapped version of GemStone live? `_builds/GsDevKit_home`?
It is very easy to [cache a directory](https://docs.travis-ci.com/user/caching/#Arbitrary-directories). Maybe try caching `$SMALLTALK_CI_BUILD/GsDevKit_home`?

**Comment by fniephaus** [comment]
> There is one cache per branch and language version/ compiler version/ JDK version/ Gemfile location/ etc.

See https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches

**Comment by dalehenrich** [comment]
Right now it seems to make the most sense to simply cache the extent file produced by the initial createStone ... Also the gsDevKitCommandLine pharo image/changes files are also worth caching ... Finally, since the pharo vm, image and chages files are being cached, I will cache those as well (if they haven't already been cached) ....

**Comment by dalehenrich** [comment]
So smalltalkCI itself is not using the `_cache` directory as a dependency cache?

**Comment by fniephaus** [comment]
Nope, not yet. It is fairly easy to enable this, but I haven't had the time to check how caching could speed up GemStone builds. Apparently, you were able to speed it up quite a bit!
For Squeak and Pharo, I don't think that caching would help much, because almost everything is just downloaded and that's it. Directory caching works the same way (Downloads everything and then extracts it).

**Comment by dalehenrich** [comment]
Yeah, if the travis timings are to be believed, [the non-cached timings](https://travis-ci.org/dalehenrich/smalltalkCI/builds/116756215) vs [cached timings](https://travis-ci.org/dalehenrich/smalltalkCI/builds/116736746) are actually faster (up to 2x slower for  some Squeak and Pharo builds).

I'm guessing that those differences are showing up because changes were found in the cache for those builds ... not sure why, but I was only concerned with whether or not the non-GemStone builds were passing not why they were running slower ... the cache upload time is pretty slow ...

**Comment by fniephaus** [comment]
I've enable caching for GemStone builds on Linux, but oddly enough the cache size is 0?
![image](https://cloud.githubusercontent.com/assets/2368856/13876963/ae09ae8e-ecff-11e5-96d3-33ed624b72df.png)

**Comment by dalehenrich** [comment]
Yes, I noticed that you changed the cache path from `$TRAVIS_BUILD_DIR/_cache` to `$SMALLTALK_CI_HOME/_cache`, but at the time that the caches defined, `$SMALLTALK_CI_HOME` is not defined correctly - the cache definition runs before the [install step](https://github.com/hpi-swa/smalltalkCI/blob/master/.travis.yml#L22). Either the download step needs to be changed to set `$SMALLTALK_CI_HOME` correctly or we have to use `$TRAVIS_BUILD_DIR/_cache` in the smalltalkCI `.travis.yml' file ... presumably `$SMALLTALK_CI_HOME/_cache` will be correct for users of smalltalkCI

**Comment by fniephaus** [comment]
Are you sure? It seems to be set, but also it *could not download cache*:
https://travis-ci.org/hpi-swa/smalltalkCI/jobs/116877289#L378

**Comment by fniephaus** [comment]
The install step you mentioned does run after the cache definition, but the cache definition runs after [this](https://github.com/travis-ci/travis-build/blob/bbe7c12b6f2c8bdc6cd9a7d3e839a729048648ae/lib/travis/build/script/smalltalk.rb#L66).

**Comment by dalehenrich** [comment]
Well, all I can say is that when I used SMALLTALK_CI_HOME it was set to the *wrong* value and that at the time that the cache is defined, TRAVIS_BUILD_DIR has the **correct** value ... The first travis run for  https://github.com/dalehenrich/smalltalkCI/commit/acbffadc35d6152f8dc420b2b82e6c09da9ceb03 just finished and the cache is being used ... the [second run is in progress](https://travis-ci.org/dalehenrich/smalltalkCI/builds/116927068) and I'm waiting to verify that GemStone is using the cache

**Comment by dalehenrich** [comment]
I don't doubt that you think that it should be working (by reading code),  but `/home/travis/smalltalkCI-master/_cache` from [here](https://travis-ci.org/hpi-swa/smalltalkCI/jobs/116877289#L378) is not the proper path ... compare that to the value of SMALLTALK_CI_HOME after the install step and you'll see what I'm talking about ... 

I don't know **WHY** this is going on, but I do know that it **IS** going on ... believe me I tried several different combos before I discovered that TRAVIS_BUILD_DIR ... presumably if you set SMALLTALK_CI_HOME to TRAVIS_BUILD_DIR in you env script, you'll get the right answer and everyone can be happy:)

**Comment by dalehenrich** [comment]
From [this build where caching is functional](https://travis-ci.org/dalehenrich/smalltalkCI/jobs/116927088), the path being used is `/home/travis/build/dalehenrich/smalltalkCI/_cache` which is completely different from `/home/travis/smalltalkCI-master/_cache` ... go figure

**Comment by fniephaus** [comment]
I just remembered why: when running smalltalkCI self-tests, [this line](https://github.com/hpi-swa/smalltalkCI/blob/ca5646599c3d402ed2a45be835ad862ade09abfa/.travis.yml#L22) forces the build to use the smalltalkCI from that very branch which is a different one that has been installed via `smalltalk.rb`. Having said that, using `$SMALLTALK_CI_HOME` should work for any project using smalltalkCI, but not for smalltalkCI itself :D

**Comment by fniephaus** [comment]
If the smalltalkCI directory that is created by `smalltalk.rb` is instead replaced but the directory from the current branch, than this should work just fine. I might change that when I have the time.

**Comment by dalehenrich** [comment]
I'm queuing up a pull request that will restore TRAVIS_BUILD_DIR and in the process of [testing whether or not a project using smalltalkCI](https://github.com/dalehenrich/obex) can get away with using `$SMALLTALK_CI_HOME` ....[tests are in progress\(https://travis-ci.org/dalehenrich/obex), so far I have confirmed that the cache was created and filled, now I need to confirm that the cache is used.

Interesting that `/home/travis/smalltalkCI-master/_cache` [appears to work for obex](https://travis-ci.org/dalehenrich/obex#L374) ... must be something special about smalltalkCI when testing itself ...

**Comment by fniephaus** [comment]
Check this out: https://github.com/hpi-swa/smalltalkCI/commit/b9c8c2ffb5da5457121f38d0af41923fd56252c2

**Comment by dalehenrich** [comment]
I see that you now understand ... I'll submit the PR with the patch when I the tests finish

**Comment by dalehenrich** [comment]
I only saw changes to .travis.yml, what am I supposed to see there?

**Comment by dalehenrich** [comment]
I would say that using TRAVIS_BUILD_DIR in the smalltalkCI .travis.yml is not a travesty, especially since SMALLTALK_CI_HOME works in user projects ...

**Comment by fniephaus** [comment]
I just pushed an update to `master` which let's us use `$SMALLTALK_CI_HOME` for caching during self-tests :)

**Comment by dalehenrich** [comment]
Sounds like a plan:)
