### ISSUE TITLE
`fatal: Couldn't find remote ref refs/pull/12/merge` error for my PR build of smalltalkCI ... why?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#84]
https://travis-ci.org/dalehenrich/smalltalkCI/jobs/116525556#L197

```
$ git clone --depth=50 https://github.com/dalehenrich/smalltalkCI.git dalehenrich/smalltalkCI
Cloning into 'dalehenrich/smalltalkCI'...
remote: Counting objects: 1988, done.
remote: Compressing objects: 100% (1034/1034), done.
remote: Total 1988 (delta 806), reused 1924 (delta 774), pack-reused 0
Receiving objects: 100% (1988/1988), 312.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (806/806), done.
Checking connectivity... done.
$ cd dalehenrich/smalltalkCI
3.41s$ git fetch origin +refs/pull/12/merge:
fatal: Couldn't find remote ref refs/pull/12/merge
Unexpected end of command stream
```

**Comment by fniephaus** [comment]
Mh, I guess this one has failed, because you merged it before the builds were done?

**Comment by dalehenrich** [comment]
which builds?

**Comment by fniephaus** [comment]
For each PR, Travis also initiates builds. If the PR is merged before those builds have run, then the builds fail, because they can't find the PR. Makes sense?

**Comment by dalehenrich** [comment]
Okay ... that makes sense ...

**Comment by Yoochard** [comment]
Hi, may I ask how to solve this problem? Because all the PRs behind will give the same error

**Comment by fniephaus** [comment]
Hi @Yoochard, there's not really a fix for this. Maybe you can try to restore the branch that was merged. The builds that were failing here, were the ones building the target branch *after* merging. Hope this helps

**Comment by Yoochard** [comment]
@fniephaus Yeap the clarification really helps a lot, thanks! :D
