### ISSUE TITLE
builds are twice as slow using containers?

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#85]
Comparing a tODE build from a month ago (https://travis-ci.org/dalehenrich/tode/jobs/107937673) to a containuer-based build done today (https://travis-ci.org/dalehenrich/tode/jobs/116525067) and it is taking 20 minutes instead of 10 minutes ...

The old build was basically a simulation of using SmalltalkCI ... GsDevKit_home downloaded, installed, stone created, tODE loaded and tests run ... so the difference is most likely due to something with travis ... are the containers that much slower/loaded?

**Comment by fniephaus** [comment]
Maybe this is still because of #68? Under Linux, shmall is still not set up correctly.
Referring to [this](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), builds on containers have more RAM and better CPU. Not sure yet why this is happening...

**Comment by dalehenrich** [comment]
#68 has nothing to do with a performance problem ... if shmall was not adequate GemStone would fail to start ... GemStone hasn't changed nor has GsDevKit_home changed during that time ...

**Comment by dalehenrich** [comment]
I'm suspicious that the tODE tests might be disk intensive rather than RAM or CPU intensive ... need to do some profiling and gather more data ... perhaps it was just a slow container day ...

**Comment by dalehenrich** [comment]
I just finished a test run on my local workstation of the tODE tests and it took 18 minutes:

```
Executed 1044 tests, with 0 failures and 0 errors in 1081.942 seconds.
```

which is comparable to the container timings ... 

So at this point in time I am less inclined to point a finger at the container being the cause ...
