### ISSUE TITLE
hard to get `-h` or `--help` for run.sh ... running manually

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#86]
```
foos:smalltalkCI>./run.sh -h
No valid STON provided and not running on Travis.
foos:smalltalkCI>./run.sh --help
No valid STON provided and not running on Travis.
foos:smalltalkCI>
```

**Comment by peteruhnak** [comment]
as a workaround you can just run `./run.sh` without any parameters to get the help, or provide path to the .ston `./run.sh -h .smalltalk.ston`

**Comment by dalehenrich** [comment]
A similar error happens if you try a clean with specifying anything else on the command line: 

```
foos:smalltalkCI>./run.sh --clean
Smalltalk image is not defined.
foos:smalltalkCI>
```

I know these are nitpicks, but it seems that both --help and --clean shouldn't require additional arguments --- there may be more :)

With that said, I know that parsing command line arguments in bash is a complete mess.

**Comment by fniephaus** [comment]
I will look into this tomorrow. I tried to follow best practices, but unfortunately that's not enough :S
