### ISSUE TITLE
GemStone Server error: Load Conflict between existing BaselineOfTode --- while loading Tode for testing

### ISSUE THREAD

**Issue by dalehenrich** [hpi-swa/smalltalkCI#88]
`onWarningLog` should have taken care of this, but tODE is a somewhat special case, since it is already present in the image and I'm loading a newer version of tODE on top of it ... 

I had started debugging this problem, running smalltalkCI locally and have discovered (possibly incidental) issues in the base SCIMetacelloLoadSpec implementation that should be fixed as they could be issues for other platforms ...

assign to me

**Comment by fniephaus** [comment]
So cf4b9ede358e06aa92f306aa41c1358f113c40bb is a fix and not a workaround? I'm just asking because of [this](https://github.com/dalehenrich/smalltalkCI/commit/cf4b9ede358e06aa92f306aa41c1358f113c40bb#diff-df1d7d367d0662c6dd79e0177b241458R13).

**Comment by dalehenrich** [comment]
.. and what makes you think that is a workaround? Pharo and possibly Squeak is not guaranteed to be using a recent version of Metacello and the copy is necessary to compensate for older versions of Metacello ... the fix is to do the `get` ... by hook or by crook :)

**Comment by fniephaus** [comment]
I wasn't quite sure what `metacello copy get.` is doing, but all good! Thanks!
