### ISSUE TITLE
Documentation on how to run this locally

### ISSUE THREAD

**Issue by pdebruic** [hpi-swa/smalltalkCI#92]
Dale mentioned that you don't need travis at all.  

It would be good to describe how to do it in the docs

**Comment by fniephaus** [comment]
Hi @pdebruic,
Thanks for opening this and yes, it sure is possible to run smalltalkCI without Travis! I for example run it locally whenever someone encounters a weird problem that'd take ages to debug using Travis builds.
I was hoping that [this](https://github.com/hpi-swa/smalltalkCI#further-configuration) covers it. Any suggestions how we could make it better?

**Comment by peteruhnak** [comment]
Apparently I don't know how commit tags work…  this PR should address this https://github.com/hpi-swa/smalltalkCI/pull/95

**Comment by pdebruic** [comment]
Hi Fabio & Peter,

Sure that's great.   I think you should mention that it can run locally in the first line of the readme.md file so that people don't have to read/scan 85% of the documentation before getting to the instructions.

**Comment by peteruhnak** [comment]
The readme.md is quite long… maybe add a TOC at the beginning? (Or move it
to wiki, but that's less discoverability.)

**Comment by fniephaus** [comment]
Thanks for the suggestion, @pdebruic. SmalltalkCI runs on Linux and OS X, it just happens to provide Smalltalk support on Travis CI as well ;) I will work on the wording as soon as I have more time! But sure, it can be used as a local CI system or on Jenkins or any other system!

Isn't it the other way around, @peteruhnak? Shouldn't #95 address this issue? ;)

**Comment by pdebruic** [comment]
Or just change the first sentence of the read me from 


Community-supported framework for building Smalltalk projects on Travis CI (continuous integration) infrastructure.




to



Community-supported framework for building Smalltalk projects in Linux & OS X environments as well as Travis CI (continuous integration) infrastructure.

**Comment by fniephaus** [comment]
How do you like the new description and [this](https://github.com/hpi-swa/smalltalkCI#running-smalltalkci-locally)? A TOC as suggested by @peteruhnak might still be a good idea though...

**Comment by peteruhnak** [comment]
This is certainly better as it should cover the mentioned use cases.

Regarding the TOC, if you want to keep everything in a single README then it would be better. It's way to easy to skim past some sections. :)

**Comment by fniephaus** [comment]
Mh, I think it still makes sense to keep everything in a single README file for the time being. I don't think it's enough content yet to set up a wiki or a GitHub page. Let's go with a TOC for now and reiterate when we add more content next time :)
