### ISSUE TITLE
User interface for smalltalkCI

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#94]
It'd be cool to have some sort of UI to smalltalkCI-ify a new project and to manage existing ones. This could be a simple tool that helps managing smalltalkCI configurations, but it could also do the following:
- Run CI builds locally against multiple _dialects_ x _versions_
- Create new GitHub repository for project
- Export a project via Filetree and create a Baseline
- Push code to GitHub
- Enable Travis CI for repository
- Display build information from Travis CI
- Cross-platform compatibility

This is just a very vague idea, but maybe something for SWT, @krono?

**Comment by krono** [comment]
k
