### ISSUE TITLE
Safety check for GemStone

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/smalltalkCI#97]
Ask user for confirmation that he has prepared his OS for GemStone before running GemStone builds locally.

**Comment by dalehenrich** [comment]
GemStone does the prereq installation as part of it's installation step 
so there is no need to ask whether or not they've prepared their system 
... I _have_ created GsDevKit/GsDevKit_home#87, for adding prompts to 
the install script to make sure that user wants to allow GemSTone to 
install the prereqs automatically ...

It's only the the travis containers with their weird host names and lack 
of sudo access that confound that standard installation scripts :)

**Comment by fniephaus** [comment]
The installation step would only run once if I understood correctly, so that's great.
I still think a confirmation would be good, because the script calls sudo and it's usually good practise to inform a user beforehand. But if you are planning to add prompts, we may not need to do it in smalltalkCI. I didn't know about that :)

**Comment by fniephaus** [comment]
Closed in favor of https://github.com/GsDevKit/GsDevKit_home/issues/87.
